### ISSUE TITLE
Auto-update not working, downloaded file can't be found

### ISSUE THREAD

**Issue by andy5995** [tutao/tutanota#1032]
- OS:Debian Stretch

**Describe the bug**
This is what appears in my terminal. The existing .AppImage file (that I downloaded 2 weeks ago) is in my home directory with executable permissions (not running as root).

```
autoUpdater info: Checking for update
autoUpdater info: Found version 3.45.2 (url: tutanota-desktop-linux.AppImage)
autoUpdater info: Signature verification successful, downloading update
autoUpdater info: Downloading update from tutanota-desktop-linux.AppImage
autoUpdater info: No cached update info available
autoUpdater info: File has 2565 changed blocks
autoUpdater info: Full: 79,172.49 KB, To download: 52,621.94 KB (66%)
autoUpdater info: New version 3.45.2 has been downloaded to /home/andy/.cache/tutanota-desktop-updater/pending/tutanota-desktop-linux.AppImage
autoUpdater error: Error: Error: ENOENT: no such file or directory, chmod '/home/andy/.cache/tutanota-desktop-updater/pending/temp-tutanota-desktop-linux.AppImage'
    at Object.<anonymous> (/tmp/.mount_tutanoR0gtoz/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:65:15)
From previous event:
    at Object.task (/tmp/.mount_tutanoR0gtoz/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:37:11)
    at /tmp/.mount_tutanoR0gtoz/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:610:25
From previous event:
    at AppImageUpdater.executeDownload (/tmp/.mount_tutanoR0gtoz/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:545:68)
    at AppImageUpdater.executeDownload (/tmp/.mount_tutanoR0gtoz/resources/app.asar/node_modules/electron-updater/src/BaseUpdater.ts:27:18)
    at AppImageUpdater.doDownloadUpdate (/tmp/.mount_tutanoR0gtoz/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:33:17)
    at AppImageUpdater.downloadUpdate (/tmp/.mount_tutanoR0gtoz/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:420:19)
    at AppImageUpdater.ElectronUpdater._verifySignature (/tmp/.mount_tutanoR0gtoz/resources/app.asar/src/desktop/ElectronUpdater.js:67:5)
    at AppImageUpdater.emit (events.js:182:13)
    at AppImageUpdater.onUpdateAvailable (/tmp/.mount_tutanoR0gtoz/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:389:10)
    at /tmp/.mount_tutanoR0gtoz/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:375:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/tmp/.mount_tutanoR0gtoz/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at AppImageUpdater.checkForUpdates (/tmp/.mount_tutanoR0gtoz/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at Timeout._onTimeout (/tmp/.mount_tutanoR0gtoz/resources/app.asar/src/desktop/ElectronUpdater.js:124:6)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
autoUpdater error: Update Download failed, ENOENT: no such file or directory, chmod '/home/andy/.cache/tutanota-desktop-updater/pending/temp-tutanota-desktop-linux.AppImage'
```
I manually checked `~/.cache/tutanota-desktop-updater/pending/` and there are no files in that directory.

**Comment by ganthern** [comment]
The updater cleans up if the update fails, that's why the directory is empty.

The odd thing I see is that the updater is trying to chmod `temp-tutanota-desktop-linux.AppImage`, which, after download and before the chmod, should have been renamed to `tutanota-desktop-linux.AppImage` by electron-updater (which would explain why the chmod fails).

**Comment by ganthern** [comment]
Turns out my theory is correct, this should be fixed in the next release.
