### ISSUE TITLE
TypeError in Chrome 37

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1037]
Many Android users still have Chrome 37 as their WebView (they should update it and we should communicate it but it should still work there at least for some time).
They all experience the same error (perhaps some function is not polyfilled):

```
Client: android app
Tutanota version: 3.44.4
User agent: 
Mozilla/5.0 (Linux; Android 5.0; Beeline Smart 4 Build/LRX21M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Mobile Safari/537.36

Error message: 
undefined is not a function

Stacktrace: 
TypeError: undefined is not a function
at IndexerCore._createClass.value (file:///android_asset/tutanota/dist/worker.js:1:283583)
at file:///android_asset/tutanota/dist/worker.js:1:280575
at a (file:///android_asset/tutanota/dist/libs.js:26:73165)
at F._settlePromiseFromHandler (file:///android_asset/tutanota/dist/libs.js:26:46542)
at F._settlePromise (file:///android_asset/tutanota/dist/libs.js:26:47342)
at F._settlePromise0 (file:///android_asset/tutanota/dist/libs.js:26:48041)
at F._settlePromises (file:///android_asset/tutanota/dist/libs.js:26:49393)
at h (file:///android_asset/tutanota/dist/libs.js:26:1646)
at p (file:///android_asset/tutanota/dist/libs.js:26:1585)
at a._drainQueues (file:///android_asset/tutanota/dist/libs.js:26:3078)
at drainQueues (file:///android_asset/tutanota/dist/libs.js:26:1327)
```

**Comment by charlag** [comment]
Still receive reports from Chrome 37-38 about `performance.mark()`

```
Client: Browser
Tutanota version: 3.47.3
User agent:
Mozilla/5.0 (Linux; Android 4.4.2; Optima 7.07 3G TT7007MG Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 YaBrowser/14.12.2125.9740.01 Safari/537.36

Error message:
undefined is not a function

Stacktrace:
TypeError: undefined is not a function
at https://mail.tutanota.com/worker.js:1:397635
at a (https://mail.tutanota.com/libs.js:26:73165)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46542)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromiseCtx (https://mail.tutanota.com/libs.js:26:47848)
at h (https://mail.tutanota.com/libs.js:26:1699)
at p (https://mail.tutanota.com/libs.js:26:1585)
at a._drainQueues (https://mail.tutanota.com/libs.js:26:3078)
at drainQueues (https://mail.tutanota.com/libs.js:26:1327)
```

**Comment by charlag** [comment]
Duplicate of #703
