### ISSUE TITLE
Attach desktop client to push notifications

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#1047]
- [x] connect desktop client to sse
- [x] manage identifier storage
- [x] keep record of shown & confirmed notifications per user
- [x] add capability for push identifier display name

**Comment by armhub** [comment]
When loggin in:
error TypeError: Cannot read property 'list' of null
    at PushServiceApp.value (PushServiceApp.js:94)
    at PushServiceApp.js:40
    at a (libs.js:26)
    at F._settlePromiseFromHandler (libs.js:26)
    at F._settlePromise (libs.js:26)
    at F._settlePromise0 (libs.js:26)
    at F._settlePromises (libs.js:26)
    at F._fulfill (libs.js:26)
    at Object.main8 (libs.js:26)
    at Queue.value (WorkerProtocol.js:115)
    at Worker.Queue._transport._transport.onmessage (WorkerProtocol.js:97)

**Comment by armhub** [comment]
On Windows the sse connection is stopped often:

starting sse connection, identifier htC userIds [ 'JjZyrKD----0', 'LThX2nB----0', 'LNzNznm----0', 'JjdJzYr----0' ]
sse response closed
scheduling to reconnect sse in 60 seconds
sse error: { Error: socket hang up
    at createHangUpError (_http_client.js:322:15)
    at TLSSocket.socketCloseListener (_http_client.js:363:25)
    at TLSSocket.emit (events.js:187:15)
    at _handle.close (net.js:606:12)
    at TCP.done (_tls_wrap.js:386:7) code: 'ECONNRESET' }

**Comment by ganthern** [comment]
> On Windows the sse connection is stopped often

this seems to be a quirk of our test server, it's also affecting all other sse clients.
