### ISSUE TITLE
Failed to add to autostart: missing directory

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1083]
> An error occurred in Ubuntu desktop client when attempting to choose 'Yes' for 'Run on startup'. This is on a fresh install of Ubuntu 18.10 

```
Client: linux
Tutanota version: 3.46.2
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.46.2 Chrome/69.0.3497.106 Electron/4.0.2 Safari/537.36

Error message: 
ENOENT: no such file or directory, open '/home/<username>/.config/autostart/tutanota-desktop.desktop'

Stacktrace: 
Error: ENOENT: no such file or directory, open '/home/<username>/.config/autostart/tutanota-desktop.desktop'
at Object.openSync (../../../../home/<username>/Downloads/fs.js:436:3)
at Object.module.(../../../../home/<username>/Downloads/anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)
at Object.writeFileSync (../../../../home/<username>/Downloads/fs.js:1168:35)
at /tmp/.mount_tutanoQV09js/resources/app.asar/src/desktop/autolaunch/AutoLauncherLinux.js:36:1129
```

**Comment by mpfau** [comment]
the option always resets to "No"
