### ISSUE TITLE
createAsyncDropdown fails on Edge

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1110]
`buttonRect=e.currentTarget.getBoundingClientRect()`

```
Client: Browser
Tutanota version: 3.47.3
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763

Error message: 
Object doesn't support property or method 'getBoundingClientRect'

Stacktrace: 
TypeError: Object doesn't support property or method 'getBoundingClientRect'
at Anonymous function (https://mail.tutanota.com/main.js:1:992150)
at a (https://mail.tutanota.com/libs.js:26:73149)
at F.prototype._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46383)
at F.prototype._settlePromise (https://mail.tutanota.com/libs.js:26:47337)
at F.prototype._settlePromiseCtx (https://mail.tutanota.com/libs.js:26:47843)
at h (https://mail.tutanota.com/libs.js:26:1697)
at p (https://mail.tutanota.com/libs.js:26:1585)
at a.prototype._drainQueues (https://mail.tutanota.com/libs.js:26:3078)
at drainQueues (https://mail.tutanota.com/libs.js:26:1325)
```

**Comment by charlag** [comment]
> the problem exist only with IE when wanted to see or set a recovry password

(they mean Edge)
