### ISSUE TITLE
TypeError: cannot read property mailGroup of undefined

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1112]
Multiple reports

```
Client: Browser
Tutanota version: 3.47.3
User agent:
Mozilla/5.0 (Linux; Android 6.0.1; SM-A300FU) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36

Error message: 
Cannot read property 'mailGroup' of undefined

Stacktrace: 
TypeError: Cannot read property 'mailGroup' of undefined
at isUserMailbox (https://mail.tutanota.com/main.js:1:902494)
at getEnabledMailAddresses (https://mail.tutanota.com/main.js:1:902326)
at new MailEditor (https://mail.tutanota.com/main.js:1:231627)
at ContactViewer.value (https://mail.tutanota.com/main.js:1:269284)
at Button.clickHandler (https://mail.tutanota.com/main.js:1:265025)
at Button.value (https://mail.tutanota.com/main-boot.js:1:182206)
at HTMLButtonElement.onclick (https://mail.tutanota.com/main-boot.js:1:178046)
at EventDict.handleEvent (https://mail.tutanota.com/main-boot.js:1:234789)
```

**Comment by charlag** [comment]
Still on 3.38.1:

```
Error message: 
Cannot read property 'mailGroup' of undefined

Stacktrace: 
TypeError: Cannot read property 'mailGroup' of undefined
at isUserMailbox (https://mail.tutanota.com/main.js:1:896164)
at getEnabledMailAddresses (https://mail.tutanota.com/main.js:1:895996)
at new MailEditor (https://mail.tutanota.com/main.js:1:230101)
at ContactViewer.value (https://mail.tutanota.com/main.js:1:267707)
at Button.textField._injectionsRight [as clickHandler] (https://mail.tutanota.com/main.js:1:263448)
at Button.value (https://mail.tutanota.com/main-boot.js:1:114965)
at HTMLButtonElement.onclick (https://mail.tutanota.com/main-boot.js:1:110805)
at EventDict.handleEvent (https://mail.tutanota.com/main-boot.js:1:239626)
```
