### ISSUE TITLE
Object has been destoyed

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1116]
```
logging on


Client: win32
Tutanota version: 3.47.3
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.47.3 Chrome/69.0.3497.106 Electron/4.0.2 Safari/537.36

Error message: 
Object has been destroyed

Stacktrace: 
Error: Object has been destroyed
at C:\Users\nshin\AppData\Local\Programs\tutanota-desktop\Tutanota Desktop\resources\app.asar\src\desktop\ApplicationWindow.js:153:105
at try..\..\Catcher (C:\Users\nshin\AppData\Local\Programs\tutanota-desktop\Tutanota Desktop\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
at Promise._settlePromiseFromHandler (..\..\C:\Users\nshin\AppData\Local\Programs\tutanota-desktop\Tutanota Desktop\resources\app.asar\node_modules\bluebird\js\release\promise.js:512:31)
at Promise._settlePromise (..\..\C:\Users\nshin\AppData\Local\Programs\tutanota-desktop\Tutanota Desktop\resources\app.asar\node_modules\bluebird\js\release\promise.js:569:18)
at Promise._fulfillPromises (..\..\C:\Users\nshin\AppData\Local\Programs\tutanota-desktop\Tutanota Desktop\resources\app.asar\node_modules\bluebird\js\release\promise.js:669:14)
at Promise._settlePromises (..\..\C:\Users\nshin\AppData\Local\Programs\tutanota-desktop\Tutanota Desktop\resources\app.asar\node_modules\bluebird\js\release\promise.js:695:18)
at _drainQueueStep (..\..\C:\Users\nshin\AppData\Local\Programs\tutanota-desktop\Tutanota Desktop\resources\app.asar\node_modules\bluebird\js\release\async.js:138:12)
at _drainQueue (..\..\C:\Users\nshin\AppData\Local\Programs\tutanota-desktop\Tutanota Desktop\resources\app.asar\node_modules\bluebird\js\release\async.js:131:9)
at Async._drainQueues (..\..\C:\Users\nshin\AppData\Local\Programs\tutanota-desktop\Tutanota Desktop\resources\app.asar\node_modules\bluebird\js\release\async.js:147:5)
at Immediate.Async.drainQueues [as _onImmediate] (..\..\C:\Users\nshin\AppData\Local\Programs\tutanota-desktop\Tutanota Desktop\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
at runCallback (..\..\timers.js:694:18)
at tryOnImmediate (..\..\timers.js:665:5)
at processImmediate (..\..\timers.js:647:5)
```

**Comment by vladimiry** [comment]
Please see [this](https://github.com/tutao/tutanota/commit/95056ddb725be28d71b0f52a7ebddced69f0a6d2#r32411373) comment.

**Comment by armhub** [comment]
Not testable here.

**Comment by vladimiry** [comment]
Such errors normally occur when the sender has already been destroyed but the main process still responds to it. User triggers some event sending from a renderer process (`webContents` is a sender here) then quickly closes/kills the window (kills the sender) and so `Object has been destroyed` occurs.

**Comment by armhub** [comment]
Thanks for the explanation. We will check if we still receive error reports for this when the fix is released because we can not reproduce it here.
