### ISSUE TITLE
TypeError when changing notification email

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1156]
>trying to change my notification email

```
Client: Browser
Tutanota version: 3.48.1
Timestamp (UTC): Tue, 05 Mar 2019 05:02:34 GMT
User agent:
Mozilla/5.0 (Linux; Android 8.1.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.105 Mobile Safari/537.36

Error message: 
Cannot read property 'group' of undefined

Stacktrace: 
TypeError: Cannot read property 'group' of undefined
at addNotificationEmailAddressOkAction (https://mail.tutanota.com/main.js:1:770882)
at Object.doAction [as click] (https://mail.tutanota.com/main.js:1:1273076)
at _Button.value (https://mail.tutanota.com/main-boot.js:1:167947)
at HTMLButtonElement.onclick (https://mail.tutanota.com/main-boot.js:1:164302)
at EventDict.handleEvent (https://mail.tutanota.com/main-boot.js:1:239626)
```

**Comment by charlag** [comment]
There's an empty header with "email settings" left
