### ISSUE TITLE
TypeError: Cannot read property 'update' of undefined in submitGroupedNotification

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1175]
Client: win32
Tutanota version: 3.48.3
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.48.3 Chrome/69.0.3497.128 Electron/4.0.8 Safari/537.36

Error message: 
Cannot read property 'update' of undefined

Stacktrace: 
TypeError: Cannot read property 'update' of undefined
at DesktopNotifier.submitGroupedNotification (..\..\C:\Users\USERNAME\AppData\Local\Programs\Tutanota Desktop\resources\app.asar\src\desktop\DesktopNotifier.js:71:15)
at C:\Users\USERNAME\AppData\Local\Programs\Tutanota Desktop\resources\app.asar\src\desktop\DesktopSseClient.js:185:23
at Array.forEach ()
at C:\Users\USERNAME\AppData\Local\Programs\Tutanota Desktop\resources\app.asar\src\desktop\DesktopSseClient.js:179:64
at Array.map ()
at DesktopSse..\..\Client._processSseData (C:\Users\USERNAME\AppData\Local\Programs\Tutanota Desktop\resources\app.asar\src\desktop\DesktopSseClient.js:179:17)
at IncomingMessage. (..\..\C:\Users\USERNAME\AppData\Local\Programs\Tutanota Desktop\resources\app.asar\src\desktop\DesktopSseClient.js:128:48)
at IncomingMessage.emit (..\..\events.js:182:13)
at addChunk (..\..\_stream_readable.js:283:12)
at readableAddChunk (..\..\_stream_readable.js:260:13)
at IncomingMessage.Readable.push (..\..\_stream_readable.js:219:10)
at HTTPParser.parserOnBody (..\..\_http_common.js:122:22)
at TLSSocket.socketOnData (..\..\_http_client.js:441:20)
at TLSSocket.emit (..\..\events.js:182:13)
at addChunk (..\..\_stream_readable.js:283:12)
at readableAddChunk (..\..\_stream_readable.js:264:11)

**Comment by charlag** [comment]
It seems like `DesktopSseClient` is created before `DesktopMain#main()` kicks in

**Comment by ganthern** [comment]
fb68f4d1e8d7a419ec16992a4929becd040ed9d1
