### ISSUE TITLE
TransactionTimeout in _putEncryptedEntity

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1235]
v3.50.3
Mostly Safari, occasionally older Chrome
times out in `IndexerCore#_getOrCreateSearchIndexMeta()`

Example of a stacktrace:
```
Error message: 
IDB could not get data os:SearchIndexMeta key:2Q23NhgMe3ry8aoDxI39oA==: TransactionInactiveError, Failed to execute 'get' on 'IDBIndex': The transaction is not active.> Error: Failed to execute 'get' on 'IDBIndex': The transaction is not active.
at Error (native)
at https://mail.tutanota.com/worker.js:1:524161
at a (https://mail.tutanota.com/libs.js:26:73165)
at Function.F.fromNode.F.fromCallback (https://mail.tutanota.com/libs.js:26:41328)
at IndexedDbTransaction._createClass.value (https://mail.tutanota.com/worker.js:1:524020)
at IndexerCore._createClass.value (https://mail.tutanota.com/worker.js:1:370361)
at IndexerCore._createClass.value (https://mail.tutanota.com/worker.js:1:362678)
at result._promiseMapCompat.concurrency (https://mail.tutanota.com/worker.js:1:362251)
at _mapInCallContext (https://mail.tutanota.com/worker.js:1:533404)
at IndexerCore.mapInCallContext [as _promiseMapCompat] (https://mail.tutanota.com/worker.js:1:533258)
at IndexerCore._createClass.value (https://mail.tutanota.com/worker.js:1:362116)
at https://mail.tutanota.com/worker.js:1:357916
at a (https://mail.tutanota.com/libs.js:26:73165)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46542)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromise0 (https://mail.tutanota.com/libs.js:26:48041)
```

**Comment by charlag** [comment]
Happens still in 3.50.4 in Safari, there were still some `Promise.resolve()`s
