### ISSUE TITLE
Feedback new client - NotAuthorizedError (permission on mail body is missing)

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#124]

**Comment by mpfau** [comment]
Stacktrace: 
NotAuthorizedError: 403: KvU94ff----0 | GET /rest/tutanota/mailbody/<id>
at handleRestError (https://mail.tutanota.com/main-boot.js:1:203836)
at XMLHttpRequest.xhr.onload (https://mail.tutanota.com/worker.js:1:444566)
