### ISSUE TITLE
[android] App crashes on starting

### ISSUE THREAD

**Issue by SNMetamorph** [tutao/tutanota#1286]
**Smartphone**
 - Device: Xiaomi Redmi 6A
 - OS: Android 8.1
 - App version: 3.52.1

**Additional context**
Crash happens on both builds from GitHub and from Google Play.

**Crash dump**
> java.lang.RuntimeException: Unable to start activity ComponentInfo{de.tutao.tutanota/de.tutao.tutanota.MainActivity}: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to find donor package: com.android.chrome
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2843)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2921)
 at android.app.ActivityThread.-wrap11(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1639)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:176)
 at android.app.ActivityThread.main(ActivityThread.java:6662)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to find donor package: com.android.chrome
 at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:456)
 at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:192)
 at android.webkit.WebView.getFactory(WebView.java:2536)
 at android.webkit.WebView.ensureProviderCreated(WebView.java:2531)
 at android.webkit.WebView.setOverScrollMode(WebView.java:2596)
 at android.view.View.<init>(View.java:4582)
 at android.view.View.<init>(View.java:4716)
 at android.view.ViewGroup.<init>(ViewGroup.java:598)
 at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
 at android.webkit.WebView.<init>(WebView.java:643)
 at android.webkit.WebView.<init>(WebView.java:588)
 at android.webkit.WebView.<init>(WebView.java:571)
 at android.webkit.WebView.<init>(WebView.java:558)
 at android.webkit.WebView.<init>(WebView.java:548)
 at de.tutao.tutanota.MainActivity.onCreate(Unknown Source:23)
 at android.app.Activity.performCreate(Activity.java:7074)
 at android.app.Activity.performCreate(Activity.java:7065)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2796)
 ... 9 more
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to find donor package: com.android.chrome
 at android.webkit.WebViewFactory.fixupStubApplicationInfo(WebViewFactory.java:290)
 at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:389)
 at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:416)
 ... 27 more

**Comment by charlag** [comment]
Hi, thanks for reporting.
We've seen this before, it should be an easy fix.
Do you have an idea on how to reproduce it?

**Comment by SNMetamorph** [comment]
I just uninstalled vendor pre-installed Google Chrome browser, and it started to happen.
But when I recovered uninstalled app, crash stopped happening. 
It's so strange when 3-rd party applications depends on Google Chrome.

**Comment by charlag** [comment]
We depend on WebView only, not on Chrome directly. It shouldn't be that you don't have any WebView provider but I recommend you to check FAQ and HOWTO
https://tutanota.com/faq/#webview
https://tutanota.com/howto#webview
