### ISSUE TITLE
Support Encrypted Calendar Alarms reminders

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#1365]

**Comment by charlag** [comment]
Now in the master

**Comment by charlag** [comment]
Didn't work on Windows
```
[2019-11-08T09:29:26.930Z] failed to schedule alarm! Error: could not resolve pushIdentifierSessionKey
    at C:\Users\flops\AppData\Local\Programs\test Tutanota Desktop\resources\app.asar\src\desktop\sse\DesktopAlarmStorage.js:128:11
    at tryCatcher (C:\Users\flops\AppData\Local\Programs\test Tutanota Desktop\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\flops\AppData\Local\Programs\test Tutanota Desktop\resources\app.asar\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\flops\AppData\Local\Programs\test Tutanota Desktop\resources\app.asar\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromiseCtx (C:\Users\flops\AppData\Local\Programs\test Tutanota Desktop\resources\app.asar\node_modules\bluebird\js\release\promise.js:606:10)
    at _drainQueueStep (C:\Users\flops\AppData\Local\Programs\test Tutanota Desktop\resources\app.asar\node_modules\bluebird\js\release\async.js:142:12)
    at _drainQueue (C:\Users\flops\AppData\Local\Programs\test Tutanota Desktop\resources\app.asar\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\flops\AppData\Local\Programs\test Tutanota Desktop\resources\app.asar\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\flops\AppData\Local\Programs\test Tutanota Desktop\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate (internal/timers.js:439:21)
```

**Comment by charlag** [comment]
This was tested with incorrect version, it seems to work.

**Comment by charlag** [comment]
When downloading missed notifications response parsing may fail, because the data is too big to fit in one chunk. The failing example was bigger than 130kb.

**Comment by nikolayhg** [comment]
not working on Ubuntu 18, as described in #1439
