### ISSUE TITLE
TypeError applySafeAreaInsetMarginLR

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1436]
```
Client: android
Tutanota version: 3.57.6

Error message: 
Cannot read property 'style' of undefined

Stacktrace: 
TypeError: Cannot read property 'style' of undefined
at applySafeAreaInsetMarginLR (file:///android_asset/tutanota/dist/main.js:1:965450)
at file:///android_asset/tutanota/dist/main.js:1:730074
at Array.forEach ()
at ListSwipeHandler.value (file:///android_asset/tutanota/dist/main.js:1:730048)
at file:///android_asset/tutanota/dist/main.js:1:702121
```

**Comment by armhub** [comment]
not reproducible here, so can not be tested
