### ISSUE TITLE
[android]  SecurityException: !@Too many alarms (500) registered

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1495]
User complains that their don't receive alarms anymore. In the log they sent to us there's a following message:

```
java.lang.SecurityException: !@Too many alarms (500) registered from uid 15010309
	at android.os.Parcel.createException(Parcel.java:1966)
	at android.os.Parcel.readException(Parcel.java:1934)
	at android.os.Parcel.readException(Parcel.java:1884)
	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:240)
	at android.app.AlarmManager.setImpl(AlarmManager.java:722)
	at android.app.AlarmManager.setExactAndAllowWhileIdle(AlarmManager.java:927)
	at de.tutao.tutanota.alarms.AlarmNotificationsManager.scheduleAlarmOccurrenceWithSystem(AlarmNotificationsManager.java:157)
	at de.tutao.tutanota.alarms.AlarmNotificationsManager.schedule(AlarmNotificationsManager.java:138)
	at de.tutao.tutanota.alarms.AlarmNotificationsManager.scheduleNewAlarms(AlarmNotificationsManager.java:88)
	at de.tutao.tutanota.push.PushNotificationService.handleAlarmNotifications(PushNotificationService.java:415)
	at de.tutao.tutanota.push.PushNotificationService.handlePushNotification(PushNotificationService.java:410)
	at de.tutao.tutanota.push.PushNotificationService.connect(PushNotificationService.java:315)
	at de.tutao.tutanota.push.PushNotificationService.lambda$zI_bEoF5N5v3gV3WFF_AxH42pl8(Unknown Source:0)
	at de.tutao.tutanota.push.-$$Lambda$PushNotificationService$zI_bEoF5N5v3gV3WFF_AxH42pl8.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at de.tutao.tutanota.push.LooperThread.run(PushNotificationService.java:660)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.SamsungAlarmManagerService.checkMaliciousAppLocked(SamsungAlarmManagerService.java:333)
	at com.android.server.AlarmManagerService.setImpl(AlarmManagerService.java:1739)
	at com.android.server.AlarmManagerService$2.set(AlarmManagerService.java:2081)
	at android.app.IAlarmManager$Stub.onTransact(IAlarmManager.java:92)
	at android.os.Binder.execTransact(Binder.java:739)
```

This StackOverflow answer says that this is due to the use of `FLAG_UPDATE_CURRENT`/`FLAG_CANCEL_CURRENT` and that it is Samsung specific.

https://stackoverflow.com/questions/29344971/java-lang-securityexception-too-many-alarms-500-registered-from-pid-10790-u

**Comment by charlag** [comment]
Not receiving any alarms on Android currently even though they are scheduled
