### ISSUE TITLE
TypeError, null is not an object (evaluating 'db.transaction')> 

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1527]
We've added `createTransactionSync` and we expect database to be there when we invoke it but seems like we don't for it.

```
Client: ios
Tutanota version: 3.59.17
User agent:
Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148DbError
Error message: could not create transaction: TypeError, null is not an object (evaluating 'db.transaction')> value@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/worker.js:1:473347
value@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/worker.js:1:345595
value@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/worker.js:1:346465
value@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/worker.js:1:382002
visibilityChange@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/worker.js:1:328753
value@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/common.js:1:253542
Stacktrace: 
DbError. could not create transaction: TypeError, null is not an object (evaluating 'db.transaction')> value@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/worker.js:1:473347
value@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/worker.js:1:345595
value@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/worker.js:1:346465
value@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/worker.js:1:382002
visibilityChange@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/worker.js:1:328753
value@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/common.js:1:253542
DbError@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/common.js:1:245617
value@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/worker.js:1:473659
value@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/worker.js:1:345595
value@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/worker.js:1:346465
value@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/worker.js:1:382002
visibilityChange@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/worker.js:1:328753
value@file:///var/containers/Bundle/Application/B623D8BD-20A1-4C01-A524-F8B6AEDEDF39/tutanota.app/build/dist/common.js:1:253542
```

```
Didn't do anything . Just clicked on the open Tutanota window and got this message .

Client: Browser
Tutanota version: 3.59.17
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36 OPR/63.0.3368.94DbError
Error message: could not create transaction: TypeError, Cannot read property 'transaction' of null> TypeError: Cannot read property 'transaction' of null
at DbFacade.value (https://mail.tutanota.com/worker.js:1:473348)
at Object.transactionFactory (https://mail.tutanota.com/worker.js:1:344446)
at IndexerCore.value (https://mail.tutanota.com/worker.js:1:345577)
at IndexerCore.value (https://mail.tutanota.com/worker.js:1:344354)
at IndexerCore.value (https://mail.tutanota.com/worker.js:1:344122)
at https://mail.tutanota.com/worker.js:1:391647
at a (https://mail.tutanota.com/libs.js:26:73165)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46542)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromise0 (https://mail.tutanota.com/libs.js:26:48041)
at F._settlePromises (https://mail.tutanota.com/libs.js:26:49393)
at h (https://mail.tutanota.com/libs.js:26:1646)
at p (https://mail.tutanota.com/libs.js:26:1585)
at a._drainQueues (https://mail.tutanota.com/libs.js:26:3078)
at drainQueues (https://mail.tutanota.com/libs.js:26:1327)
Stacktrace: 
DbError: could not create transaction: TypeError, Cannot read property 'transaction' of null> TypeError: Cannot read property 'transaction' of null
at DbFacade.value (https://mail.tutanota.com/worker.js:1:473348)
at Object.transactionFactory (https://mail.tutanota.com/worker.js:1:344446)
at IndexerCore.value (https://mail.tutanota.com/worker.js:1:345577)
at IndexerCore.value (https://mail.tutanota.com/worker.js:1:344354)
at IndexerCore.value (https://mail.tutanota.com/worker.js:1:344122)
at https://mail.tutanota.com/worker.js:1:391647
at a (https://mail.tutanota.com/libs.js:26:73165)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46542)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromise0 (https://mail.tutanota.com/libs.js:26:48041)
at F._settlePromises (https://mail.tutanota.com/libs.js:26:49393)
at h (https://mail.tutanota.com/libs.js:26:1646)
at p (https://mail.tutanota.com/libs.js:26:1585)
at a._drainQueues (https://mail.tutanota.com/libs.js:26:3078)
at drainQueues (https://mail.tutanota.com/libs.js:26:1327)
at DbFacade.value (https://mail.tutanota.com/worker.js:1:473648)
at Object.transactionFactory (https://mail.tutanota.com/worker.js:1:344446)
at IndexerCore.value (https://mail.tutanota.com/worker.js:1:345577)
at IndexerCore.value (https://mail.tutanota.com/worker.js:1:344354)
at IndexerCore.value (https://mail.tutanota.com/worker.js:1:344122)
at https://mail.tutanota.com/worker.js:1:391647
at a (https://mail.tutanota.com/libs.js:26:73165)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46542)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromise0 (https://mail.tutanota.com/libs.js:26:48041)
at F._settlePromises (https://mail.tutanota.com/libs.js:26:49393)
at h (https://mail.tutanota.com/libs.js:26:1646)
at p (https://mail.tutanota.com/libs.js:26:1585)
at a._drainQueues (https://mail.tutanota.com/libs.js:26:3078)
at drainQueues (https://mail.tutanota.com/libs.js:26:1327)
```

When we optimized

**Comment by charlag** [comment]
Fixed by 6bc323449fb8edf965167eec3adfcabf8897245b
