### ISSUE TITLE
Include Public Key for signature verification in client

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#1601]
The client should not request the public key from github or other third parties.

**Comment by bedhub** [comment]
update from version 3.60.9 to 3.60.13 failed on Mac OSX


> [2019-11-07T14:15:34.755Z] autoUpdater info: 
trying to retrieve public key from https://raw.githubusercontent.com/tutao/tutanota/master/tutao-pub-test.pem
[2019-11-07T14:15:34.763Z] autoUpdater info:
 found public key
[2019-11-07T14:15:34.764Z] autoUpdater info:
 checking-for-update
[2019-11-07T14:15:35.023Z] autoUpdater info:
 update not available: {
  version: '3.60.13',
  files: [
    {
      url: 'tutanota-desktop-test-mac.zip',
      sha512: 'Ux5CYNfu8FaY1LaTZaPFs0MLMVe/wZc5t9RmLnbQz0S89w5Fh7d0A8+EcbrrUE2pfwYOm55oLyzWze6CPVqmfQ==',
      size: 67611303,
      blockMapSize: 72562
    },
    {
      url: 'tutanota-desktop-test-mac.dmg',
      sha512: 'eaquHwZXvMOLSrqLzCrkfHWIMGqZ7EXawgneqO9Qo04AHRzmYWoXHpJ2zSbR2H8vH7f2+dO72+UC4YB+KmjYWw==',
      size: 69796941
    }
  ],
  path: 'tutanota-desktop-test-mac.zip',
  sha512: 'Ux5CYNfu8FaY1LaTZaPFs0MLMVe/wZc5t9RmLnbQz0S89w5Fh7d0A8+EcbrrUE2pfwYOm55oLyzWze6CPVqmfQ==',
  releaseDate: '2019-11-07T12:52:20.329Z',
  signature: 'Z4AdwNhZ42WaY7XQqxCNhJ3XwuE7rfPuHKljkMIePL/OQ03acNaQXrSIk/rGcSC8TP6Ws+iVKiExtI45v+YMZf8nQak92VHt3PBBpqUZ4AJzAUXuMDaLjMRTJDHL4UpuFxUmikFFC9cvlsMHO4bnYdk7F6EWPvuCIHFQMDuqFFbbUQWPnS5tYWwWr0FXVbfrI4Lx5fKPxcNFusvhdVErtdM0sGuErdxsi9tgLyA7qbsiQ5jnvC2r7X2buv8XG+BvF4nXX/nd6rR+y/biScNFfYymKrKZU3EHAbn8DTTMeD1/C6Lm2uXrCUkZuRvjaa2JZFXYMwVEOfTDdGehvNMZlg=='
}

**Comment by bedhub** [comment]
Starting the version 3.60.13 fails on OSX

```` 
Uncaught Exception:
Error: dlopen(/var/folders/_9/tpfwz85950g992wd3w7k4gxm0000gn/T/.de.tutao.tutanota-test.cbY7YO, 1): no suitable image found.  Did find:
/var/folders/_9/tpfwz85950g992wd3w7k4gxm0000gn/T/.de.tutao.tutanota-test.cbY7YO: code signature in (/var/folders/_9/tpfwz85950g992wd3w7k4gxm0000gn/T/.de.tutao.tutanota-test.cbY7YO) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
/var/folders/_9/tpfwz85950g992wd3w7k4gxm0000gn/T/.de.tutao.tutanota-test.cbY7YO: stat() failed with errno=17
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Applications/test Tutanota Desktop.app/Contents/Resources/app.asar/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
````
