### ISSUE TITLE
[iOS] Error message: Failed to execute 'abort' on 'IDBTransaction': The transaction is inactive or finished.

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1603]
Happens periodically.
In `IndexerCore#onVisibilityChanged` we try to abort the transaction but it happens too late for some reason. We should probably ignore any errors that happen because of the abort.
Mostly happens to iOS 12 but it's not going away anytime soon.

```
Client: ios
Tutanota version: 3.60.6
User agent:
Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148InvalidStateError
Error message: Failed to execute 'abort' on 'IDBTransaction': The transaction is inactive or finished.
Stacktrace: 
abort@[native code]
value@file:///var/containers/Bundle/Application/8918E7BD-EEE1-4BAB-8A29-9D0C5FBB0835/tutanota.app/build/dist/worker.js:1:476361
value@file:///var/containers/Bundle/Application/8918E7BD-EEE1-4BAB-8A29-9D0C5FBB0835/tutanota.app/build/dist/worker.js:1:346244
value@file:///var/containers/Bundle/Application/8918E7BD-EEE1-4BAB-8A29-9D0C5FBB0835/tutanota.app/build/dist/worker.js:1:381945
visibilityChange@file:///var/containers/Bundle/Application/8918E7BD-EEE1-4BAB-8A29-9D0C5FBB0835/tutanota.app/build/dist/worker.js:1:328753
value@file:///var/containers/Bundle/Application/8918E7BD-EEE1-4BAB-8A29-9D0C5FBB0835/tutanota.app/build/dist/common.js:1:254893
```

**Comment by charlag** [comment]
v3.67.6 (ios, restored):

```
abort@[native code]
  at value abort (../../src/api/worker/search/DbFacade.js:330:2)
  at value neverNull (../../src/api/worker/search/IndexerCore.js:313:3)
  at value visible (../../src/api/worker/search/Indexer.js:214:2)
  at visibilityChange _locator$indexer (../../src/api/worker/WorkerImpl.js:310:4)
  at value command (../../src/api/common/WorkerProtocol.js:126:4)
```
visibility change triggers `abort()` and it leaks somewhere. Probably throws synchronously if we can get this stacktrace. We should just wrap this `abort()` in try/catch.

**Comment by charlag** [comment]
Seems to be fixed now
