### ISSUE TITLE
Desktop app tries to register as mailto handler in web part and it fails

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1643]
After using few shortcuts in the mail editor the app tries to register the protocol handler. It seems like it's not the desktop-specific mechanism but rather the render part.

Could reproduce it on Windows with 3.64.0 staging

Seems like it's here:
https://github.com/tutao/tutanota/blob/master/src/app.js#L80

<details>
<summary>
Stacktrace:
</summary>

```
Failed to register a mailto: protocol handler  DOMException: Failed to execute 'registerProtocolHandler' on 'Navigator': The scheme of the url provided must be the 'http' or 'https'.
    at Object.execute (file:///C%3A/Users/flops/AppData/Local/Programs/test%20Tutanota%20Desktop/resources/app.asar/main-boot.js:1:355396)
    at C (file:///C%3A/Users/flops/AppData/Local/Programs/test%20Tutanota%20Desktop/resources/app.asar/libs.js:27:10905)
    at e (file:///C%3A/Users/flops/AppData/Local/Programs/test%20Tutanota%20Desktop/resources/app.asar/libs.js:27:7574)
    at M (file:///C%3A/Users/flops/AppData/Local/Programs/test%20Tutanota%20Desktop/resources/app.asar/libs.js:27:8611)
    at file:///C%3A/Users/flops/AppData/Local/Programs/test%20Tutanota%20Desktop/resources/app.asar/libs.js:27:10367
    at a (file:///C%3A/Users/flops/AppData/Local/Programs/test%20Tutanota%20Desktop/resources/app.asar/libs.js:26:73165)
    at F._settlePromiseFromHandler (file:///C%3A/Users/flops/AppData/Local/Programs/test%20Tutanota%20Desktop/resources/app.asar/libs.js:26:46542)
    at F._settlePromise (file:///C%3A/Users/flops/AppData/Local/Programs/test%20Tutanota%20Desktop/resources/app.asar/libs.js:26:47342)
    at F._settlePromise0 (file:///C%3A/Users/flops/AppData/Local/Programs/test%20Tutanota%20Desktop/resources/app.asar/libs.js:26:48041)
    at F._settlePromises (file:///C%3A/Users/flops/AppData/Local/Programs/test%20Tutanota%20Desktop/resources/app.asar/libs.js:26:49393)
    at h (file:///C%3A/Users/flops/AppData/Local/Programs/test%20Tutanota%20Desktop/resources/app.asar/libs.js:26:1646)
    at p (file:///C%3A/Users/flops/AppData/Local/Programs/test%20Tutanota%20Desktop/resources/app.asar/libs.js:26:1585)
    at a._drainQueues (file:///C%3A/Users/flops/AppData/Local/Programs/test%20Tutanota%20Desktop/resources/app.asar/libs.js:26:3078)
    at drainQueues (file:///C%3A/Users/flops/AppData/Local/Programs/test%20Tutanota%20Desktop/resources/app.asar/libs.js:26:1327)​
```

</details>

**Comment by charlag** [comment]
I mistook it for another error, it' actually #1645
