### ISSUE TITLE
Cannot read property 'moreResults' of null

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1733]
From report, not sure when it happens: 

Client: Browser
Tutanota version: 3.66.5

```
TypeError
Error message: Cannot read property 'moreResults' of null
Stacktrace:
TypeError: Cannot read property 'moreResults' of null
at hasMoreResults (https://mail.tutanota.com/main.js:1:1771283)
at https://mail.tutanota.com/main.js:1:322191
at a (https://mail.tutanota.com/libs.js:26:73165)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46542)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromise0 (https://mail.tutanota.com/libs.js:26:48041)
at F._settlePromises (https://mail.tutanota.com/libs.js:26:49393)
at F._fulfill (https://mail.tutanota.com/libs.js:26:48411)
at F._resolveCallback (https://mail.tutanota.com/libs.js:26:45290)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46696)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromise0 (https://mail.tutanota.com/libs.js:26:48041)
at F._settlePromises (https://mail.tutanota.com/libs.js:26:49393)
at F._fulfill (https://mail.tutanota.com/libs.js:26:48411)
at u. (https://mail.tutanota.com/libs.js:26:52825)
at u._promiseFulfilled (https://mail.tutanota.com/libs.js:26:35031)
```

**Comment by charlag** [comment]
Not reported anymore
