### ISSUE TITLE
TypeError: mailboxDetails is undefined

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1748]
```
Client: Browser
Tutanota version: 3.59.17 - 3.66.7
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
TypeError
Error message: mailboxDetails is undefined
Stacktrace:
isUserMailbox@https://mail.tutanota.com/main.js:1:1332870
getEnabledMailAddresses@https://mail.tutanota.com/main.js:1:1332730
MailEditor@https://mail.tutanota.com/main.js:1:995736
newMail/<@https://mail.tutanota.com/main.js:1:985352
a@https://mail.tutanota.com/libs.js:26:73165
[22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][20]value@https://mail.tutanota.com/common.js:1:269305
Queue/this._transport.onmessage@https://mail.tutanota.com/common.js:1:268921
```

Alternative messages:
`Cannot read property 'mailGroup' of undefined`
`undefined is not an object (evaluating 'mailboxDetails.mailGroup')`

**Comment by bedhub** [comment]
Open desktop client with mailto now leads to unexpected error:

```
[2020-01-31T14:43:45.570Z] unexpected error: OperationalError [TypeError]: Cannot read property 'user' of undefined
    at isUserMailbox (file:///tmp/.mount_tutanodXdLK6/resources/app.asar/main.js:1:1338744)
    at getEnabledMailAddresses (file:///tmp/.mount_tutanodXdLK6/resources/app.asar/main.js:1:1338566)
    at new MailEditor (file:///tmp/.mount_tutanodXdLK6/resources/app.asar/main.js:1:1000375)
    at file:///tmp/.mount_tutanodXdLK6/resources/app.asar/common.js:1:222497
    at a (file:///tmp/.mount_tutanodXdLK6/resources/app.asar/libs.js:26:74251)
    at R._settlePromiseFromHandler (file:///tmp/.mount_tutanodXdLK6/resources/app.asar/libs.js:26:47148)
    at R._settlePromise (file:///tmp/.mount_tutanodXdLK6/resources/app.asar/libs.js:26:48048)
    at R._settlePromiseCtx (file:///tmp/.mount_tutanodXdLK6/resources/app.asar/libs.js:26:48554)
    at c (file:///tmp/.mount_tutanodXdLK6/resources/app.asar/libs.js:26:1466)
    at a (file:///tmp/.mount_tutanodXdLK6/resources/app.asar/libs.js:26:1352)
    at s._drainQueues (file:///tmp/.mount_tutanodXdLK6/resources/app.asar/libs.js:26:2474)
```
