### ISSUE TITLE
[Android] FileNotFoundException on reading/writing file in temp directory

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1789]
It's an old issue

One case when trying to decrypt temp file:

```
Client: android
Tutanota version: 3.66.5
User agent:
Mozilla/5.0 (Linux; Android 9; Mi A1 Build/PKQ1.180917.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/79.0.3945.136 Mobile Safari/537.36
java.io.FileNotFoundException
Error message: /data/user/0/de.tutao.tutanota/files/temp/encrypted/IMG_20200124_110556.jpg (No such file or directory)
Stacktrace:
java.io.FileNotFoundException: /data/user/0/de.tutao.tutanota/files/temp/encrypted/IMG_20200124_110556.jpg (No such file or directory)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:231)
at java.io.FileInputStream.(FileInputStream.java:165)
at java.io.FileInputStream.(FileInputStream.java:112)
at android.content.ContentResolver.openInputStream(ContentResolver.java:1015)
at de.tutao.tutanota.Crypto.aesDecryptFile(Crypto.java:292)
at de.tutao.tutanota.Native.invokeMethod(Native.java:184)
at de.tutao.tutanota.Native.lambda$invoke$2$Native(Native.java:78)
at de.tutao.tutanota.-$$Lambda$Native$8fBIKwro4kS4gvJJ99lRbXtVm5g.run(Unknown Source:4)
at java.lang.Thread.run(Thread.java:764)
```

Another case when copying decrypted file:

```
Client: android
Tutanota version: 3.66.5
User agent:
Mozilla/5.0 (Linux; Android 9; VTR-L09 Build/HUAWEIVTR-L09; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/79.0.3945.136 Mobile Safari/537.36
java.io.FileNotFoundException
Error message: /data/user/0/de.tutao.tutanota/files/temp/decrypted/IMG_20181219_122332.jpg (No such file or directory)
Stacktrace:
java.io.FileNotFoundException: /data/user/0/de.tutao.tutanota/files/temp/decrypted/IMG_20181219_122332.jpg (No such file or directory)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:231)
at java.io.FileInputStream.(FileInputStream.java:165)
at java.io.FileInputStream.(FileInputStream.java:112)
at android.content.ContentResolver.openInputStream(ContentResolver.java:1031)
at de.tutao.tutanota.FileUtil.addFileToDownloads(FileUtil.java:178)
at de.tutao.tutanota.FileUtil.lambda$putToDownloadFolder$2$FileUtil(FileUtil.java:156)
at de.tutao.tutanota.-$$Lambda$FileUtil$8S6F8DzO9t7kbDuaYsfHQZs0Pdc.run(Unknown Source:6)
at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:784)
```

The cause is probably the same. There are no additional info from users except that their download/upload a file.

**Comment by charlag** [comment]
Got some more info:

>Just happened to try to download more than one file at a time from the same email.

Not sure how they manage it yet

**Comment by charlag** [comment]
I don't think this is happening anymore
