### ISSUE TITLE
undefined is not an object (evaluating 'this._mailFolderSelection.selectedValue')

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1790]
```
Client: Browser
Tutanota version: 3.67.3
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36
TypeError
Error message: Cannot read property 'selectedValue' of undefined
Stacktrace:
TypeError: Cannot read property 'selectedValue' of undefined
at SearchView.value (https://mail.tutanota.com/main.js:1:200705)
at https://mail.tutanota.com/main-boot.js:1:362073
at a (https://mail.tutanota.com/libs.js:26:74251)
at R._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:47248)
at R._settlePromise (https://mail.tutanota.com/libs.js:26:48048)
at R._settlePromise0 (https://mail.tutanota.com/libs.js:26:48747)
at R._settlePromises (https://mail.tutanota.com/libs.js:26:50099)
at c (https://mail.tutanota.com/libs.js:26:1413)
at a (https://mail.tutanota.com/libs.js:26:1352)
at s._drainQueues (https://mail.tutanota.com/libs.js:26:2474)
at https://mail.tutanota.com/libs.js:26:1286
```

restored stacktrace:

```
  at SearchView.value selectedValue (../../src/search/SearchView.js:497:3)
  at view (../../src/app.js:152:6)
  [original] at a (https://mail.tutanota.com/libs.js:26:74251)
  [original] at R._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:47248)
  [original] at R._settlePromise (https://mail.tutanota.com/libs.js:26:48048)
  [original] at R._settlePromise0 (https://mail.tutanota.com/libs.js:26:48747)
  [original] at R._settlePromises (https://mail.tutanota.com/libs.js:26:50099)
  [original] at c (https://mail.tutanota.com/libs.js:26:1413)
  [original] at a (https://mail.tutanota.com/libs.js:26:1352)
  [original] at s._drainQueues (https://mail.tutanota.com/libs.js:26:2474)
  [original] at https://mail.tutanota.com/libs.js:26:1286
```

**Comment by charlag** [comment]
This happens because `MailModel#mailboxDetails` doesn't have default (empty) value now and `map` on it will not be invoked until they are loaded and we won't assign `_mailFolderSelection` until that point.

**Comment by charlag** [comment]
To reproduce:
1. execute mail search
2. reload the page
3. observe the error
