### ISSUE TITLE
Desktop shortcuts are not displayed after reloading

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1828]
**To Reproduce**
1. Open the client
2. Press F1
3. See desktop shortcuts
4. Press F5
5. See no desktop shortcuts

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.47.4, 3.47.5

Follow up for #1061

**Comment by charlag** [comment]
Fails each time with
```
TypeError
Error message: shortcutsOfWindow is not iterable
Stacktrace:
TypeError: shortcutsOfWindow is not iterable
at Object.disableAll (node_modules/electron-localshortcut/index.js:55:25)
at BrowserWindow. (src/desktop/ApplicationWindow.js:120:51)
at BrowserWindow.emit (../../../../home/ivk/events.js:215:7)
```

**Comment by charlag** [comment]
This is an error because for dist builds blur comes focus comes before contents are loaded (probably bundle is bigger) and `electron-localshortcut` doesn't know about our window (and doesn't check if it knows)
