### ISSUE TITLE
KeyNotYetValidException

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1851]
Client: android
Tutanota version: 3.67.3
User agent:
Mozilla/5.0 (Linux; Android 9 ...)

```
de.tutao.tutanota.CryptoError
Error message: android.security.keystore.KeyNotYetValidException: Key not yet valid
Stacktrace:
de.tutao.tutanota.CryptoError: android.security.keystore.KeyNotYetValidException: Key not yet valid
at de.tutao.tutanota.Crypto.encryptKey(Crypto.java:314)
at de.tutao.tutanota.AndroidKeyStoreFacade.encryptKey(AndroidKeyStoreFacade.java:95)
at de.tutao.tutanota.push.SseStorage.storePushIdentifierSessionKey(SseStorage.java:122)
```

My first impulse was "we set invalid date when generating RSA key!" but it actually has nothing to do with asymmetric keypair, it's Android 9 and the stacktrace points to the retrieval of symmetric key.
I've found couple of issues but it doesn't give much:
https://github.com/iamMehedi/Secured-Preference-Store/issues/15
https://github.com/mozilla-mobile/fenix/issues/6813

**Comment by charlag** [comment]
Haven't been reported for a while
