### ISSUE TITLE
Provided date is not in valid range.

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1861]
Client: android
Tutanota version: 3.67.6

```
RangeError
Error message: Provided date is not in valid range.
Stacktrace:
RangeError: Provided date is not in valid range.
at DateTimeFormat.args (native)
at formatDate (file:///android_asset/tutanota/dist/main.js:1:1663608)
at DatePicker.value (file:///android_asset/tutanota/dist/main.js:1:1112179)
```

**Comment by charlag** [comment]
Still occurs on 3.68.1, only on Android, I suspect that this is time zone related.

**Comment by charlag** [comment]
There's a related report with 3.68.1

```
TypeError: value.getTime is not a function
  at convertJsToDbType  value (../../src/api/worker/crypto/InstanceMapper.js:187:9)
  at encryptValue  convertJsToDbType (../../src/api/worker/crypto/InstanceMapper.js:154:9)
  at encryptAndMapToLiteral  encryptValue (../../src/api/worker/crypto/InstanceMapper.js:102:31)
  at encryptAndMapToLiteral (../../src/api/worker/rest/EntityRestClient.js:64:17)
  [original] at a (https://mail.tutanota.com/libs.js:26:74251)
  [original] at R._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:47248)
  [original] at R._settlePromise (https://mail.tutanota.com/libs.js:26:48048)
  [original] at R._settlePromise0 (https://mail.tutanota.com/libs.js:26:48747)
  [original] at R._settlePromises (https://mail.tutanota.com/libs.js:26:50099)
  [original] at c (https://mail.tutanota.com/libs.js:26:1413)
  [original] at a (https://mail.tutanota.com/libs.js:26:1352)
  [original] at s._drainQueues (https://mail.tutanota.com/libs.js:26:2474)
  [original] at drainQueues (https://mail.tutanota.com/libs.js:26:1286)
```

It seems like we have something else instead of a `Date` somewhere, I looked for it but couldn't find it.

**Comment by charlag** [comment]
It seems like the issue with "valid range" is OS related. It only happens with Android 6 and 7. We tested it with one of the affected people and the issue only occurs on the phone with older OS which reports time zone differently from others.

**Comment by charlag** [comment]
> simply updating Android system webview actually did the trick, I can now see and edit the calendar.

It might be that DST database is not up-to-date on older WebViews.

**Comment by charlag** [comment]
Another user confirmed that updating WebView helps (was Chrome 55).
We should probably bump WebView requirements
