### ISSUE TITLE
Error: undefined dom element for virtual dom element 42, 0

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1862]
Yes, again

```
Tutanota version: 3.67.5
Error message: undefined dom element for virtual dom element 42, 0
Stacktrace:
Error: undefined dom element for virtual dom element 42, 0
at List.value (file:///C%3A/Program%20Files/Tutanota%20Desktop/resources/app.asar/main.js:1:922913)
at file:///C%3A/Program%20Files/Tutanota%20Desktop/resources/app.asar/main.js:1:917942
```

```
Tutanota version: 3.68.0
Error
Error message: undefined dom element for virtual dom element 40, 0
Stacktrace:
value@https://mail.tutanota.com/main.js:1:923764
value/<@https://mail.tutanota.com/main.js:1:918793

Stacktrace:
  at value  (../../src/gui/base/List.js:748:10)
  at value/< _reposition (../../src/gui/base/List.js:592:3)
```

**Comment by charlag** [comment]
Might happen during window resizing in some cases but it is really hard to reproduce.
