### ISSUE TITLE
IE11 login not shown

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2035]
Unhandled rejection Error: 'crypto' is undefined
  Evaluating https://mail.tutanota.com/src/misc/DeviceConfig.js
  Evaluating https://mail.tutanota.com/src/gui/theme.js
  Evaluating https://mail.tutanota.com/src/gui/base/Modal.js
  Evaluating https://mail.tutanota.com/src/RootView.js
  Evaluating https://mail.tutanota.com/src/app.js
  Loading src/app.js
   at value (https://mail.tutanota.com/theme.js:1:19133)
   at DeviceConfig (https://mail.tutanota.com/theme.js:1:18339)
   at execute (https://mail.tutanota.com/theme.js:1:21701)
   at C (https://mail.tutanota.com/libs.js:27:10903)
   at e (https://mail.tutanota.com/libs.js:27:7572)
   at e (https://mail.tutanota.com/libs.js:27:7320)
   at e (https://mail.tutanota.com/libs.js:27:7320)
   at e (https://mail.tutanota.com/libs.js:27:7320)
   at e (https://mail.tutanota.com/libs.js:27:7320)
   at M (https://mail.tutanota.com/libs.js:27:7217)
From previous event:
   at Anonymous function (https://mail.tutanota.com/libs.js:26:20819)
   at Y (https://mail.tutanota.c

**Comment by armhub** [comment]
Problem:
The login page is not shown if you open Tutanota in the browser for IE11.
Expected behavior:
The login page is shown for IE11 and you can login.

**Comment by mpfau** [comment]
other errors occur now. needs to be fixed from office

**Comment by mpfau** [comment]
LGTM
