### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by ajgraves** [tutao/tutanota#2050]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Describe the bug**
When attempting to build from source, getting an error that prevents the build from proceeding.

```
~/.../mytuta/tutanota >>> node dist prod           ±[●][wrap-headers-in-dialog]
started cleaning 0.005
started copying images 0.018
started tracing 0.24
started bundling 116.141
Build error in bundle build/dist/common.js
Build error in bundle build/dist/worker.js
Build error in bundle build/dist/main.js
Build error in bundle build/dist/theme.js
Build error in bundle build/dist/main-boot.js

Build error: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
    at writeFile (fs.js:1356:5)
    at tryCatcher (/home/ajgraves/Projects/mytuta/tutanota/node_modules/bluebird/js/release/util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (/home/ajgraves/Projects/mytuta/tutanota/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
    at /home/ajgraves/Projects/mytuta/tutanota/node_modules/systemjs-builder/lib/output.js:142:29
    at tryCatcher (/home/ajgraves/Projects/mytuta/tutanota/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ajgraves/Projects/mytuta/tutanota/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/ajgraves/Projects/mytuta/tutanota/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/ajgraves/Projects/mytuta/tutanota/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/ajgraves/Projects/mytuta/tutanota/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/ajgraves/Projects/mytuta/tutanota/node_modules/bluebird/js/release/promise.js:673:18)
    at /home/ajgraves/Projects/mytuta/tutanota/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/ajgraves/Projects/mytuta/tutanota/node_modules/mkdirp/index.js:48:26
    at FSReqCallback.oncomplete (fs.js:176:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**To Reproduce**
1. Run `npm install`
2. Run `node dist prod`
3. Observe failure

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Desktop Environment, if applicable (on Linux): xfce

**Additional context**
This is on a branch where I'm making two small changes, however the master branch fails to build as well as documented [here](https://github.com/tutao/tutanota/issues/1857#issuecomment-626868122).

**Comment by ajgraves** [comment]
Closing this as I noticed a comment from another thread that indicated the version of Node being used by me is "too new".
