### ISSUE TITLE
Use SystemKeysService for changing admin flag

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2078]
Currently we search through memberships in `UserManagementFacade._getAccountGroupMembership()` to get the right key when setting an admin flag. In rate cases Team group might not be consistent, we should use SystemKeysService to get the key reliably.

This will prevent following error:
```
TypeError
Error message: Cannot read property 'group' of null
Stacktrace:
TypeError: Cannot read property 'group' of null
  at group (../../src/api/worker/facades/UserManagementFacade.js:86:6)
  [original] at a (https://mail.tutanota.com/libs.js:26:74251)
  [original] at R._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:47248)
  [original] at R._settlePromise (https://mail.tutanota.com/libs.js:26:48048)
  [original] at R._settlePromise0 (https://mail.tutanota.com/libs.js:26:48747)
  [original] at R._settlePromises (https://mail.tutanota.com/libs.js:26:50099)
  [original] at c (https://mail.tutanota.com/libs.js:26:1413)
  [original] at a (https://mail.tutanota.com/libs.js:26:1352)
  [original] at s._drainQueues (https://mail.tutanota.com/libs.js:26:2474)
  [original] at drainQueues (https://mail.tutanota.com/libs.js:26:1286)
```

**Comment by charlag** [comment]
Test notes: makes someone admin/non-admin
