### ISSUE TITLE
Cannot read property 'webContents' of undefined

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2112]
```
Client: darwin
Tutanota version: 3.74.2
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.74.2 Chrome/80.0.3987.163 Electron/8.2.3 Safari/537.36
TypeError
Error message: Cannot read property 'webContents' of undefined
Stacktrace:
TypeError: Cannot read property 'webContents' of undefined
at click (src/desktop/DesktopContextMenu.js:20:165)
at MenuItem.click (../../../../../electron/js2c/browser_init.js:1501:9)
at Function.executeCommand (../../../../../electron/js2c/browser_init.js:1762:13)
```

**Comment by vaf-hub** [comment]
Test new context menu actions
[] paste, cut, copy, copy link action

**Comment by bedhub** [comment]
New actions were fine but could not reproduce a case were the web contents is unavailable so this is untested. We will just observe logs if the error occurs again.
