### ISSUE TITLE
Search result not updated when switching to contact results

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#212]
How to reproduce:
1. Search for an email, open results in search view
2. Select contact result button -> If no contacts are found for this search query, the result list is not updated

**Comment by mpfau** [comment]
Opening the search view from the quick search result triggers an error:

`error Error: undefined dom element for virtual dom element 30, 0
    at List._reposition (http://localhost:9000/client/build/src/gui/base/List.js:633:13)
    at eval (http://localhost:9000/client/build/src/gui/base/List.js:492:13)`
