### ISSUE TITLE
Downloading statistic logs for contact form is not possible

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2154]
Feedback v3.75.0 - MethodNotAllowedError - PREMIUM - linux
Client: linux
Type: PREMIUM
Tutanota version: 3.75.0
Timestamp (UTC): Wed, 15 Jul 2020 11:19:21 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.75.0 Chrome/80.0.3987.165 Electron/8.3.1 Safari/537.36
MethodNotAllowedError
Error message: 405: MCHBorm----2 | PUT /rest/tutanota/statisticlogentry/Lc1XolN----1/LyePOef--B-2
Stacktrace:
MethodNotAllowedError: 405: MCHBorm----2 | PUT /rest/tutanota/statisticlogentry/Lc1XolN----1/LyePOef--B-2
at file:///tmp/.mount_tutanoz2wA6k/resources/app.asar/common.js:1:242278
at XMLHttpRequest.xhr.onload (file:///tmp/.mount_tutanoz2wA6k/resources/app.asar/worker.js:1:748962)

**Comment by bedhub** [comment]
Issue was reported by a user again. We should fix it with the next release

**Comment by bedhub** [comment]
We decided to not support statistic logs in the future anymore so we will not fix this case. Instead we will remove the functionality.
