### ISSUE TITLE
Linux:  t disappears from my laptop after a shutdown/start.

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2283]
User comment:
"Every now and then, the file tutanota-desktop-linux.AppImage disappears from my laptop after a shutdown/start. I have not deleted the file and it does not appear in the Wastebin folder of the OS. Last time it happens was today but I have had the issue at least three times before.
I use latest version of Fedora with KDE and use the path /home/myuser/software/tutanota-desktop-linux.AppImage for the client and default path for the configuration."

**Comment by sofiageo** [comment]
This happened for me today, I think it's because the updater failed to update. Here are my logs from yesterday night.

	Oct 31 01:16:35 home tutanota-desktop.desktop[6585]: [2020-10-30T23:16:35.038Z] autoUpdater error:
	Oct 31 01:16:35 home tutanota-desktop.desktop[6585]:  Error: Error: spawnSync mv ENOTCONN
	Oct 31 01:16:35 home tutanota-desktop.desktop[6585]:     at Object.spawnSync (internal/child_process.js:1041:20)
	Oct 31 01:16:35 home tutanota-desktop.desktop[6585]:     at spawnSync (child_process.js:625:24)
	Oct 31 01:16:35 home tutanota-desktop.desktop[6585]:     at execFileSync (child_process.js:652:15)
	Oct 31 01:16:35 home tutanota-desktop.desktop[6585]:     at func (electron/js2c/asar.js:140:31)
	Oct 31 01:16:35 home tutanota-desktop.desktop[6585]:     at AppImageUpdater.doInstall (/tmp/.mount_tutanobQVz88/resources/app.asar/node_modules/electron-updater/out/AppImageUpdater.js:158:39)
	Oct 31 01:16:35 home tutanota-desktop.desktop[6585]:     at AppImageUpdater.install (/tmp/.mount_tutanobQVz88/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:71:19)
	Oct 31 01:16:35 home tutanota-desktop.desktop[6585]:     at AppImageUpdater.quitAndInstall (/tmp/.mount_tutanobQVz88/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:28:30)
	Oct 31 01:16:35 home tutanota-desktop.desktop[6585]:     at App.<anonymous> (/tmp/.mount_tutanobQVz88/resources/app.asar/src/desktop/ElectronUpdater.js:121:3834)
	Oct 31 01:16:35 home tutanota-desktop.desktop[6585]:     at Object.onceWrapper (events.js:417:26)
	Oct 31 01:16:35 home tutanota-desktop.desktop[6585]:     at App.emit (events.js:310:20)
	Oct 31 01:16:35 home tutanota-desktop.desktop[6585]: [2020-10-30T23:16:35.038Z] autoUpdater error:
	Oct 31 01:16:35 home tutanota-desktop.desktop[6585]:  Auto Update Error 1, continuing polling:
	Oct 31 01:16:35 home tutanota-desktop.desktop[6585]: spawnSync mv ENOTCONN

**Comment by CalliopeHummingbird** [comment]
Seeing the same problem with Linux Mint 20.1, two separate machines, one laptop, one desktop, same day.

**Comment by sofiageo** [comment]
I've migrated to [Flatpak](https://flathub.org/apps/details/com.tutanota.Tutanota) for the past year and never had another issue. Maybe it's an option for you.

**Comment by CalliopeHummingbird** [comment]
Happening to me again.. The flatpack available through the Mint Software Manager is still on version 3.85.3 and is apparently now out of support, forcing users to the appimage, which after two and a half years, is still uninstalling itself. Sofiageo's link does show v3.110.1 - but it's labelled Experimental and has known issues, a bit of a concern given Tuta's whole raison d'etre is email security.

**Comment by BradB58** [comment]
It is three years now and this extremely annoying bug has still not been fixed! What is the problem?
I am running latest appimage on Linux Mint 21.2 Cinnamon. I have auto updates always on.

**Comment by charlag** [comment]
We just managed to reproduce it today by closing the client.

**Comment by OzzDizz** [comment]
We're having the same issue over here. This has been an on-again off-again issue for years, across multiple systems running linux (mint, ubuntu) and has persisted after clean OS installs, leading me to suspect a wider issue not isolated to a single variable on one of those systems.

I was worried that our systems had malware, because on a stable system files don't typically disappear or delete themselves repeatedly.

After years of re-downloading the appimage and searching for an explanation, and a bit of questioning my sanity, I went hunting very thoroughly for malware and rootkits before I ended up setting up a cronjob to check for the existence of the appimage file. This proved that the appimage file does indeed disappear, and doesn't end up in the trash, but I couldn't find any explanation in the logs I checked e.g. .config/tutanota-desktop/logs.

Having verified my sanity and the fact that the appimage file does vanish periodically, I set the permissions for the appimage file as "readonly" for the non-root user account, hoping to see if it would make a difference (which remains to be seen, but seems to be holding for now). But this is really only a usability/reliability workaround, and likely diminishes security by almost certainly preventing auto-updates.

But from a usability perspective, having an email client disappear from multiple systems in our environment seemingly at random can be disruptive! I've absolutely been in the middle of a phone call with a client where I went to retrieve an email only to find the Tuta client software inexplicably gone (not to mention the repeated time-consuming investigations). 

I'm very glad I discovered this thread and that I'm not the only one experiencing this problem.

Is there a better place to check logs to help pin down the root cause of the issue?

**Comment by charlag** [comment]
> We're having the same issue over here. This has been an on-again off-again issue for years, across multiple systems running linux (mint, ubuntu) and has persisted after clean OS installs, leading me to suspect a wider issue not isolated to a single variable on one of those systems.
> 
> I was worried that our systems had malware, because on a stable system files don't typically disappear or delete themselves repeatedly.
> 
> After years of re-downloading the appimage and searching for an explanation, and a bit of questioning my sanity, I went hunting very thoroughly for malware and rootkits before I ended up setting up a cronjob to check for the existence of the appimage file. This proved that the appimage file does indeed disappear, and doesn't end up in the trash, but I couldn't find any explanation in the logs I checked e.g. .config/tutanota-desktop/logs.
> 
> Having verified my sanity and the fact that the appimage file does vanish periodically, I set the permissions for the appimage file as "readonly" for the non-root user account, hoping to see if it would make a difference (which remains to be seen, but seems to be holding for now). But this is really only a usability/reliability workaround, and likely diminishes security by almost certainly preventing auto-updates.
> 
> But from a usability perspective, having an email client disappear from multiple systems in our environment seemingly at random can be disruptive! I've absolutely been in the middle of a phone call with a client where I went to retrieve an email only to find the Tuta client software inexplicably gone (not to mention the repeated time-consuming investigations).
> 
> I'm very glad I discovered this thread and that I'm not the only one experiencing this problem.
> 
> Is there a better place to check logs to help pin down the root cause of the issue?

if you could start it with output attached (e.g. from terminal) and then reproduce it it might output something useful.

This randomness sounds like an odd race condition to me.

**Comment by helenvarley** [comment]
also happening to me. i think, but am not 100% certain, that it disappears every time it's updated. a bit annoying!
i'm on Ubuntu 22.04.4 LTS with Budgie desktop 10.6.1.

**Comment by CalliopeHummingbird** [comment]
> we are sorry to hear that but we are still unable to reproduce the issue. It would help us if somebody would grab an older release from Github, run it from the terminal and observe what happens on the update.

When this happens on my machine, it seems to be because I have NOT explicitly updated the app. I think auto-update is causing the problem, so I'm not sure how running from the terminal will help; but I'm happy to do it, if you could provide more detailed instructions.

Currently running Linux Mint 21.3 Cinnamon Desktop, Tuta v277.250414.1

**Comment by gea-1234** [comment]
We received a report on Tuta version 359.260904.0., so this issue is till occurring.
