### ISSUE TITLE
Alarm without trigger creates an unexpected error notification message.

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2313]
```
No AlarmTrigger for value java.lang.IllegalArgumentException:
No AlarmTrigger for value at de.tutao.tutanota.alarms.AlarmTrigger.get(AlarmTrigger.java:25) 
at de.tutao.tutanota.alarms.AlarmNotificationsManager.schedule(AlarmNotificationsManager.java:116) 
at de.tutao.tutanota.alarms.AlarmNotificationsManager.reScheduleAlarms(AlarmNotificationsManager.java:54) 
at de.tutao.tutanota.push.PushNotificationService.onCreate(PushNotificationService.java:55) 
at android.app.ActivityThread.handleCreateService(ActivityThread.java:4192) 
at android.app.ActivityThread.access$1500(ActivityThread.java:237) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932) 
at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:223) 
at android.app.ActivityThread.main(ActivityThread.java:7656) at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

![Tutanota app](https://user-images.githubusercontent.com/8296817/95177946-1c4eb400-07bf-11eb-977d-a5bbb15c846a.png)

**Comment by johnbotris** [comment]
To reproduce:
* Create an event with a guest and a reminder
* Have the guest accept the event
* The notification trigger in the organizers event has been overwritten with an empty string
