### ISSUE TITLE
Calendar export fails when event has invalid alarm trigger

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2325]
Trying to export a calendar with an invalid alarm trigger (presumably one which has been corrupted by the fixed bug from issue  #2265) fails with an error:

```
Feedback v3.76.11 - Error - PREMIUM - Browser
Client: Browser
Type: PREMIUM
Tutanota version: 3.76.11
Timestamp (UTC): Wed, 14 Oct 2020 11:20:05 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
Error
Error message: unknown alarm interval:
Stacktrace:
Error: unknown alarm interval:
at https://test.tutanota.com/main.js:1:1783575
at serializeAlarm (https://test.tutanota.com/main.js:1:1783628)
at https://test.tutanota.com/main.js:1:1785471
at Array.map (<anonymous>)
at serializeEvent (https://test.tutanota.com/main.js:1:1785444)
at https://test.tutanota.com/main.js:1:1782984
at Array.map (<anonymous>)
at serializeCalendar
...

```

**Comment by charlag** [comment]
I did not manage to import invalid alarm. Either parser refuses it or alarm is removed or alarm time defaults to 30min. However export works fine.
