### ISSUE TITLE
Error when logging in in Chrome on Windows

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#238]
error TypeError: Cannot read property 'indexTimestamp' of undefined
    at eval (http://192.168.178.27:9000/client/build/src/api/worker/search/ContactIndexer.js:94:21)
    at r (http://192.168.178.27:9000/client/build/libs/bluebird.min.js:31:9004)
    at i._settlePromiseFromHandler (http://192.168.178.27:9000/client/build/libs/bluebird.min.js:30:14217)
    at i._settlePromise (http://192.168.178.27:9000/client/build/libs/bluebird.min.js:30:15020)
    at i._settlePromise0 (http://192.168.178.27:9000/client/build/libs/bluebird.min.js:30:15721)
    at i._settlePromises (http://192.168.178.27:9000/client/build/libs/bluebird.min.js:30:17051)
    at i._fulfill (http://192.168.178.27:9000/client/build/libs/bluebird.min.js:30:16092)
    at http://192.168.178.27:9000/client/build/libs/bluebird.min.js:30:4676
    at IDBRequest.request.onsuccess (http://192.168.178.27:9000/client/build/src/api/worker/search/DbFacade.js:151:7)

**Comment by armhub** [comment]
Other stacktrace:
Error: GroupData not available for group <group_id>
at https://mail.tutanota.com/worker.js:1:296731
at https://mail.tutanota.com/worker.js:1:297241
at r (https://mail.tutanota.com/libs.js:32:9004)
at i._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:31:14217)
at i._settlePromise (https://mail.tutanota.com/libs.js:31:15020)
at i._settlePromise0 (https://mail.tutanota.com/libs.js:31:15721)
at i._settlePromises (https://mail.tutanota.com/libs.js:31:17051)
at i._fulfill (https://mail.tutanota.com/libs.js:31:16092)
at https://mail.tutanota.com/libs.js:31:4676
at IDBRequest.request.onsuccess (https://mail.tutanota.com/worker.js:1:379770)

**Comment by armhub** [comment]
Seems to occur only on systems with low memory.

**Comment by charlag** [comment]
Did not occur in a few months
