### ISSUE TITLE
Update Android SDK to 29

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2415]
Play requirement

Need to check disk access and TLS

**Comment by johnbotris** [comment]
- [x] Reading from contacts
- [x] Attaching files
- [ ] Downloading attachments
- [ ] Notifications
- [ ] Sharing

**Comment by johnbotris** [comment]
Notifications are working on android 10, they don't seem to be working on older android (6) but ill test with power saving mode turned off (the phone needs to charge)

Opening an attachment from the mail viewer works, selecting download gives an error:

```
"java.io.FileNotFoundException: /storage/emulated/0/Download/IMG_20191104_104622.jpg: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
	at de.tutao.tutanota.FileUtil.addFileToDownloads(FileUtil.java:179)
	at de.tutao.tutanota.FileUtil.lambda$null$2$FileUtil(FileUtil.java:157)
	at de.tutao.tutanota.-$$Lambda$FileUtil$CDv0_OITXgBUZ2InUFNGvTevWz4.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7296)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 8 more
"
```

**Comment by charlag** [comment]
Was the permission error on Android 10?

**Comment by johnbotris** [comment]
Android 10 yeah

**Comment by johnbotris** [comment]
`Environment.getExternalStoragePublicDirectory` has been deprecated and the path returned by it is no longer directly accessible.

so in `FileUtil.addFileToDownloads` it throws on the call to `copyLarge`
```
File downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);

...

File newFile = new File(downloadsDir, fileInfo.name);
IOUtils.copyLarge(activity.getContentResolver().openInputStream(file), new FileOutputStream(newFile),
		new byte[4096]);
```

 looks like we need to use `Environment.getExternalFilesDir`?

**Comment by johnbotris** [comment]
Download works on old Android however

**Comment by charlag** [comment]
Quick workaround for now is to do `android:requestLegacyExternalStorage="true"` in the Manifest
(https://medium.com/better-programming/all-you-need-to-know-about-scoped-storage-in-android-10-e621f40bc8b9)

Another option is to try DownloadManager with file URI:
https://stackoverflow.com/a/59464586/1923879

Another options is to implement file provider (we probably already do for opening files):
https://stackoverflow.com/a/57812480/1923879

**Comment by charlag** [comment]
Or perhaps we should add them to MediaStore.Downloads somehow https://developer.android.com/reference/android/provider/MediaStore.Downloads
