### ISSUE TITLE
Build for ARM64 using modified electron-package-json-template.js Errors out

### ISSUE THREAD

**Issue by rekab72** [tutao/tutanota#2435]
Building desktop app on Raspberry Pi 4 8GB Ubuntu Mate 20.10 for use on same device.
Modified package.json to update dependency keytar to version 7.1.0.

Building with "`node dist --custom-desktop-release`" generates desktop version for arch=x64 not arm64
```
`Building desktop client for v3.77.4 (linux)...
artifacts will be moved to /home/ubuntu/tmp/tutanota/build/desktop
Updating electron-builder config...
Tracing dependencies...
Starting installer build...
  • electron-builder  version=22.9.1 os=5.8.0-1007-raspi
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=build/dist/installers/builder-effective-config.yaml
  • installing production dependencies  platform=linux arch=x64 appDir=/home/ubuntu/tmp/tutanota/build/dist
  • packaging       platform=linux arch=x64 electron=10.1.5 appOutDir=build/dist/installers/linux-unpacked
Move artifacts to /home/ubuntu/tmp/tutanota/build/desktop

Build time: 614.859s (21:19)`
```
Attempted to build with `electron-builder -l tar.gz --arm64` Errors - What do I need to modify to build desktop for ARM64 on arch=arm64?
``` 
ubuntu@ubuntu-desktop:~/tmp/tutanota$ electron-builder -l tar.gz --arm64
  • electron-builder  version=22.9.1 os=5.8.0-1007-raspi
  • description is missed in the package.json  appPackageFile=/home/ubuntu/tmp/tutanota/package.json
  • author is missed in the package.json  appPackageFile=/home/ubuntu/tmp/tutanota/package.json
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=keytar@7.1.0 platform=linux arch=arm64
  • packaging       platform=linux arch=arm64 electron=10.1.5 appOutDir=dist/linux-arm64-unpacked
  ⨯ Application entry file "index.js" in the "/home/ubuntu/tmp/tutanota/dist/linux-arm64-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.  stackTrace=
           Error: Application entry file "index.js" in the "/home/ubuntu/tmp/tutanota/dist/linux-arm64-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/usr/local/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
    at checkFileInArchive (/usr/local/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:33:11)
    at LinuxPackager.checkFileInPackage (/usr/local/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:405:7)
    at LinuxPackager.sanityCheckPackage (/usr/local/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:456:5)
    at LinuxPackager.doPack (/usr/local/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:243:5)
    at LinuxPackager.pack (/usr/local/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:115:5)
    at Packager.doBuild (/usr/local/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/packager.ts:444:9)
    at executeFinally (/usr/local/lib/node_modules/electron-builder/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/usr/local/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/packager.ts:373:31)
    at Packager.build (/usr/local/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/packager.ts:337:12)
    at executeFinally (/usr/local/lib/node_modules/electron-builder/node_modules/builder-util/src/promise.ts:12:14)

```

**Comment by charlag** [comment]
Invoking `electron-builder` is not correct, we have a template package.json for desktop.

If you want to add architectures, try adding them here and do `node dist` again

https://github.com/tutao/tutanota/blob/c76ca300e0335807fb462ea578509b1e38cb97ac/buildSrc/electron-package-json-template.js#L163-L168

**Comment by rekab72** [comment]
Thanks for the pointer to that file. I made modifications and successfully built linux-arm64-unpacked.
Attempting to run I receive the following errors. Anymore insight? I built on Pi 4 8GB Ubuntu Mate 20.10 64 so ELFCLASS should be ELFCLASS64. Searching now where that parameter is noted to change.
```
`ubuntu@ubuntu-desktop:~/tmp/tutanota/build/desktop/linux-arm64-unpacked$ ./tutanota-desktop
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.juxhqP: wrong ELF class: ELFCLASS32
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/ubuntu/tmp/tutanota/build/desktop/linux-arm64-unpacked/resources/app.asar/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)


^Z
[1]+  Stopped                 ./tutanota-desktop`
```

**Comment by charlag** [comment]
I think node 10 doesn't support ARM. That's one thing.
Another thing is that we do rebuilding of dependencies on install and we do it with current architecture, not sure if it's done gone on building dist.
