### ISSUE TITLE
Cannot read property 'activeMatchOrdinal' of undefined

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2438]
>ctrl-f + "title"

```
Client: linux
Tutanota version: 3.77.4
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.77.4 Chrome/85.0.4183.121 Electron/10.1.5 Safari/537.36
TypeError
Error message: Cannot read property 'activeMatchOrdinal' of undefined
Stacktrace:
TypeError: Cannot read property 'activeMatchOrdinal' of undefined
at file:///tmp/.mount_tutanoImFKbE/resources/app.asar/main.js:1:130959
at a (file:///tmp/.mount_tutanoImFKbE/resources/app.asar/libs.js:26:74251)
at R._settlePromiseFromHandler (file:///tmp/.mount_tutanoImFKbE/resources/app.asar/libs.js:26:47248)
at R._settlePromise (file:///tmp/.mount_tutanoImFKbE/resources/app.asar/libs.js:26:48048)
at R._settlePromise0 (file:///tmp/.mount_tutanoImFKbE/resources/app.asar/libs.js:26:48747)
at R._settlePromises (file:///tmp/.mount_tutanoImFKbE/resources/app.asar/libs.js:26:50099)
at R._fulfill (file:///tmp/.mount_tutanoImFKbE/resources/app.asar/libs.js:26:49117)
at Object.main1638 (file:///tmp/.mount_tutanoImFKbE/resources/app.asar/libs.js:26:37402)
at Queue.value (file:///tmp/.mount_tutanoImFKbE/resources/app.asar/main-boot.js:1:357215)
at NativeWrapper.handleMessageObject (file:///tmp/.mount_tutanoImFKbE/resources/app.asar/main-boot.js:1:370115)
at EventEmitter. (:17:26)
at EventEmitter.emit (electron/js2c/sandbox_bundle.js:150:3752)
at Object.onMessage (electron/js2c/sandbox_bundle.js:131:1374)
```

Called from here:
https://github.com/tutao/tutanota/blob/c76ca300e0335807fb462ea578509b1e38cb97ac/src/gui/base/SearchInPageOverlay.js#L104-L113

and handled here:

https://github.com/tutao/tutanota/blob/c76ca300e0335807fb462ea578509b1e38cb97ac/src/desktop/IPC.js#L86-L97

`catch()` will return nothing and else branch is also incompatible.

**Comment by charlag** [comment]
This is already handled
