### ISSUE TITLE
Error when logging into an account

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#2490]
**Bug in mobile app**

**Describe the bug**
Error dialog opens when logging intp account on Android app
Login still works, though

**To Reproduce**
1. Open App
2. Log in to `armfortest`

**Bug report**
```
just logging in


Client: android
Type: PREMIUM
Tutanota version: 3.78.2
Timestamp (UTC): Tue, 15 Dec 2020 15:45:38 GMT
User agent:
Mozilla/5.0 (Linux; Android 10; Mi MIX 2 Build/QQ3A.200805.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/85.0.4183.101 Mobile Safari/537.36
TypeError
Error message: Cannot read property 'list' of null
Stacktrace:
TypeError: Cannot read property 'list' of null
at PushServiceApp.value (file:///android_asset/tutanota/dist/main.js:1:1034197)
at file:///android_asset/tutanota/dist/main.js:1:1031595
at a (file:///android_asset/tutanota/dist/libs.js:26:74251)
at R._settlePromiseFromHandler (file:///android_asset/tutanota/dist/libs.js:26:47248)
at R._settlePromise (file:///android_asset/tutanota/dist/libs.js:26:48048)
at R._settlePromise0 (file:///android_asset/tutanota/dist/libs.js:26:48747)
at R._settlePromises (file:///android_asset/tutanota/dist/libs.js:26:50099)
at R._fulfill (file:///android_asset/tutanota/dist/libs.js:26:49117)
at Object.main52 (file:///android_asset/tutanota/dist/libs.js:26:37402)
at Queue.value (file:///android_asset/tutanota/dist/main-boot.js:1:362085)
at Worker.Queue._transport._transport.onmessage (file:///android_asset/tutanota/dist/main-boot.js:1:361701)
```

**Comment by johnbotris** [comment]
related to #2459?

**Comment by charlag** [comment]
Something is wrong with this account. It doesn't happen with others. I suppose it's not migrated for some reason.

https://github.com/tutao/tutanota/blob/dff38f2f7ee16abb55cb65e62e93323d62f153ac/src/native/PushServiceApp.js#L112-L115
