### ISSUE TITLE
ProgrammingError when reconnecting web socket

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2601]
1. One client must be offline
1. Create event
2. Change date of event
3. Reconnect offline client -> Programming error

´´´
Feedback v3.80.3 - ProgrammingError - PREMIUM - Browser
Client: Browser
Type: PREMIUM
Tutanota version: 3.80.3
Timestamp (UTC): Fri, 08 Jan 2021 10:23:12 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
ProgrammingError
Error message: Impossible modification combination DELETE CREATE {"_type":{"app":"sys","type":"EntityUpdate"},"_id":"cPPlhw","application":"tutanota","instanceId":"YjS_JXka8tjYH7UniEpOpoEQQIiyD5n-jdofpYgIC_U","instanceListId":"MEMdAPQ----0","operation":"0","type":"CalendarEventUidIndex"}
Stacktrace:
ProgrammingError: Impossible modification combination DELETE CREATE {"_type":{"app":"sys","type":"EntityUpdate"},"_id":"cPPlhw","application":"tutanota","instanceId":"YjS_JXka8tjYH7UniEpOpoEQQIiyD5n-jdofpYgIC_U","instanceListId":"MEMdAPQ----0","operation":"0","type":"CalendarEventUidIndex"}
at _loop (https://test.tutanota.com/worker.js:1:617122)
at EventQueue.value (https://test.tutanota.com/worker.js:1:617890)
at EventQueue.value (https://test.tutanota.com/worker.js:1:614533)
at EventBusClient.value (https://test.tutanota.com/worker.js:1:637861)
at https://test.tutanota.com/worker.js:1:637153
at a (https://test.tutanota.com/libs.js:26:74251)
at R._settlePromiseFromHandler (https://test.tutanota.com/libs.js:26:47248)
at R._settlePromise (https://test.tutanota.com/libs.js:26:48048)
at R._settlePromise0 (https://test.tutanota.com/libs.js:26:48747)
at R._settlePromises (https://test.tutanota.com/libs.js:26:50099)
at R._fulfill (https://test.tutanota.com/libs.js:26:49117)
at R._resolveCallback (https://test.tutanota.com/libs.js:26:46296)
at R._settlePromiseFromHandler (https://test.tutanota.com/libs.js:26:47402)
at R._settlePromise (https://test.tutanota.com/libs.js:26:48048)
at R._settlePromise0 (https://test.tutanota.com/libs.js:26:48747)
at R._settlePromises (https://test.tutanota.com/libs.js:26:50099)
´´´

**Comment by charlag** [comment]
It's a problem for custom IDs and I imagine there being more issues. I didn't consider it really. E.g. currently we think that after DELETE nothing matters anymore but only until CREATE again I guess

**Comment by bedhub** [comment]
You are right it is related to custom ids. Same happens for contact forms. There it is possible to DELETE and CREATE with the same id again. Just wondering why it occurs with calendar events because id should change when changing start date.

**Comment by bedhub** [comment]
Ah, it is the CalendarEventUidIndex which creates the problem and not CalendarEvent. So delete and import again should lead to same error.
