### ISSUE TITLE
ProgrammingError: Impossible modification combination

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2647]
We still have a lot of ProgrammingError messages because of impossible modification combination. We need to check why this happens or decide that we can accept that these combinations.

Some examples: 

CREATE CREATE {"_type":{"app":"sys","type":"EntityUpdate"},"_id":"pjKs2Q","application":"tutanota","instanceId":"MRtHoTD--3-2","instanceListId":"M8x2iH6--B-2","operation":"0","type":"Contact"}

 CREATE CREATE {"_type":{"app":"sys","type":"EntityUpdate"},"_id":"KYGBfQ","application":"sys","instanceId":"MRrMk6W----2","instanceListId":"","operation":"0","type":"Group"}

UPDATE not allowed after DELETE

CREATE CREATE {"_type":{"app":"sys","type":"EntityUpdate"},"_id":"z20qCg","application":"tutanota","instanceId":"MRoY8ld--3-2","instanceListId":"MRoY8ld----2","operation":"0","type":"ConversationEntry"}

 UPDATE CREATE {"_type":{"app":"sys","type":"EntityUpdate"},"_id":"Z7sEAg","application":"tutanota","instanceId":"MRiUQzE----2","instanceListId":"LyUUfJd-0V-2","operation":"0","type":"Mail"}

**Comment by charlag** [comment]
I checked and seems like in all cases it happens in Indexer, probably because we get events from two places

**Comment by charlag** [comment]
I found more cases like below which are not from indexer:

```
{"app":"sys","type":"EntityUpdate"},"_id":"8GW_vw","application":"tutanota","instanceId":"MTYwNDExNTE1NTc2Mg","instanceListId":"MRkVhKY--B-2","operation":"0","type":"CalendarEvent"}
Stacktrace:
ProgrammingError. Impossible modification combination CREATE CREATE {"_type":{"app":"sys","type":"EntityUpdate"},"_id":"8GW_vw","application":"tutanota","instanceId":"MTYwNDExNTE1NTc2Mg","instanceListId":"MRkVhKY--B-2","operation":"0","type":"CalendarEvent"}
ProgrammingError@https://mail.tutanota.com/common.js:1:277497
_loop@https://mail.tutanota.com/worker.js:1:619156
value@https://mail.tutanota.com/worker.js:1:619461
value@https://mail.tutanota.com/worker.js:1:615807
value@https://mail.tutanota.com/worker.js:1:639489
value/a@https://mail.tutanota.com/libs.js:26:74251
[22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][23][18][22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][22][23][18][22][22][22][22][22][22][22][22][22][22][23][18][22][22][22]c@https://mail.tutanota.com/libs.js:26:1413
a@https://mail.tutanota.com/libs.js:26:1353
[2]s/this.drainQueues@https://mail.tutanota.com/libs.js:26:1286
```

**Comment by bedhub** [comment]
Still receiving this error with version 3.81.8.  In most cases for the WhitelistRequest but was also reported for Group

```
Error message: Impossible modification combination CREATE CREATE {"_type":{"app":"sys","type":"EntityUpdate"},"_id":"RLb9ww","application":"sys","instanceId":"MTYrEAX----2","instanceListId":"","operation":"0","type":"Group"}
```

WhitelistRequest

```
ProgrammingError
Error message: Impossible modification combination CREATE CREATE {"_type":{"app":"sys","type":"EntityUpdate"},"_id":"mWNQeg","application":"tutanota","instanceId":"4K0iPjx84TtjnJB1I7eNNnl1gKwxWKnbHPu3aS0kkCg","instanceListId":"Kip34x8--B-0","operation":"0","type":"Group"}
Stacktrace:
ProgrammingError: Impossible modification combination CREATE CREATE {"_type":{"app":"sys","type":"EntityUpdate"},"_id":"mWNQeg","application":"tutanota","instanceId":"4K0iPjx84TtjnJB1I7eNNnl1gKwxWKnbHPu3aS0kkCg","instanceListId":"Kip34x8--B-0","operation":"0","type":"WhitelistRequest"}
at e.value (file:///tmp/.mount_tutanoDnNNVo/resources/app.asar/worker.js:1:89655)
at e.value (file:///tmp/.mount_tutanoDnNNVo/resources/app.asar/worker.js:1:88086)
at e.value (file:///tmp/.mount_tutanoDnNNVo/resources/app.asar/worker.js:1:87908)
at e.value (file:///tmp/.mount_tutanoDnNNVo/resources/app.asar/worker.js:1:133905)
at file:///tmp/.mount_tutanoDnNNVo/resources/app.asar/worker.js:1:181767
at c (file:///tmp/.mount_tutanoDnNNVo/resources/app.asar/polyfill.js:1:112668)
at A._settlePromiseFromHandler (file:///tmp/.mount_tutanoDnNNVo/resources/app.asar/polyfill.js:1:85572)
at A._settlePromise (file:///tmp/.mount_tutanoDnNNVo/resources/app.asar/polyfill.js:1:86372)
at A._settlePromise0 (file:///tmp/.mount_tutanoDnNNVo/resources/app.asar/polyfill.js:1:87071)
at A._settlePromises (file:///tmp/.mount_tutanoDnNNVo/resources/app.asar/polyfill.js:1:88423)
at c (file:///tmp/.mount_tutanoDnNNVo/resources/app.asar/polyfill.js:1:39658)
at a (file:///tmp/.mount_tutanoDnNNVo/resources/app.asar/polyfill.js:1:39597)
at s._drainQueues (file:///tmp/.mount_tutanoDnNNVo/resources/app.asar/polyfill.js:1:40723)
at drainQueues (file:///tmp/.mount_tutanoDnNNVo/resources/app.asar/polyfill.js:1:39531)
```

**Comment by charlag** [comment]
It does seem to be a server problem (see 737)
