### ISSUE TITLE
ProgrammingError:  Batch does not have events for ...

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2648]
Client: Browser
Type: PREMIUM
Tutanota version: 3.80.5
Timestamp (UTC): Sun, 24 Jan 2021 10:22:15 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
ProgrammingError
Error message: Batch does not have events for fpGTE6Z6Bewv_TCSjNUBVYu0GtV6oW9vR9BXK_y9p9U
Stacktrace:
ProgrammingError. Batch does not have events for fpGTE6Z6Bewv_TCSjNUBVYu0GtV6oW9vR9BXK_y9p9U
ProgrammingError@https://mail.tutanota.com/common.js:1:277497
batchMod@https://mail.tutanota.com/worker.js:1:612930
_loop@https://mail.tutanota.com/worker.js:1:617167
value@https://mail.tutanota.com/worker.js:1:619461
value@https://mail.tutanota.com/worker.js:1:615807
value@https://mail.tutanota.com/worker.js:1:615413
value@https://mail.tutanota.com/worker.js:1:342488
value@https://mail.tutanota.com/worker.js:1:380173
value/value@https://mail.tutanota.com/worker.js:1:641222
value/a@https://mail.tutanota.com/libs.js:26:74251
[22][22][22][22][22][22][22][22][22][22][22][20]value@https://mail.tutanota.com/common.js:1:302666
Queue/this._transport.onmessage@https://mail.tutanota.com/common.js:1:302282

**Comment by charlag** [comment]
```
ProgrammingError. Batch does not have events for fpGTE6Z6Bewv_TCSjNUBVYu0GtV6oW9vR9BXK_y9p9U
  at ProgrammingError call (../../src/api/common/error/ProgrammingError.js:5:24)
  at batchMod  (../../src/api/worker/search/EventQueue.js:60:7)
  at _loop lastBatchForEntity (../../src/api/worker/search/EventQueue.js:128:44)
  at value _loop (../../src/api/worker/search/EventQueue.js:116:36)
  at value _optimizingAddEvents (../../src/api/worker/search/EventQueue.js:101:3)
  at value add (../../src/api/worker/search/EventQueue.js:89:3)
  at value addBatches (../../src/api/worker/search/IndexerCore.js:225:3)
  at value addBatchesToQueue (../../src/api/worker/search/Indexer.js:204:2)
  at value/value call (../../src/api/worker/EventBusClient.js:546:3)
  [original] value/a@https://mail.tutanota.com/libs.js:26:74251
  at [22][22][22][22][22][22][22][22][22][22][22][20]value  (../../src/api/common/WorkerProtocol.js:118:3)
  at Queue/this._transport.onmessage _handleMessage (../../src/api/common/WorkerProtocol.js:100:45)

```

**Comment by mpfau** [comment]
Howto reproduce:
* use two different browsers
* login with two different accounts (1,2) in A
* login with 1 in B
* enable search indexing in B
* log out in B
* enable out of office (A 1)
* send mail to account 1 (A 2)
* disable out of office notification (A 1)
* enable out of office notification (A 1)
* send mail to account 1 (A 2)
* disable out of office notification (A 1)
* enable out of office notification (A 1)
* send mail to account 1 (A 2)
* login with 1 in B
* error dialog should come up

test notes:
- [ ]  reproduce error with v3.82.4 and make sure that it can't be reproduced with current version
