### ISSUE TITLE
Alarm error on desktop

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2707]
Error on startup:
```
[2021-02-12T13:28:21.463Z] failed to schedule alarm! TypeError: Promise.map is not a function
    at Po (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain-ae1e34fb.js:1:409860)
    at Object.decryptAndMapToInstance (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain-ae1e34fb.js:1:412944)
    at Object.decryptAndMapToInstance (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain-ae1e34fb.js:13:175842)
    at /app/lib/tutanota/resources/app.asar/desktop/DesktopMain-ae1e34fb.js:13:195148
    at async Object.rescheduleAll (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain-ae1e34fb.js:13:197562)
```
we don't use bluebird in desktop side anymore but decryptAndMapToInstance is using Promise.map from it and it is used from desktop for alarms

**Comment by charlag** [comment]
Test notes:
 - [ ] Check that alarms are scheduled/cancelled now
 - [ ] Check sending encrypted emails
