### ISSUE TITLE
Exception when adding a deactivated user to mail group

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#272]
1. Deactivate user
2. try to add user to mail group from UserViewer
 -> Exception dialog

**Comment by asteintutao** [comment]
Deactivated user can not be added to a mail group anymore -> no exception fixed with #258

**Comment by asteintutao** [comment]
Still not fixed: Getting this after trying to add a deactivated user to a group

BadRequestError: 400: LPQhNm2----0 | POST /rest/sys/membershipservice
    at handleRestError (http://localhost:9000/src/api/common/error/RestError.js:139:11)
    at XMLHttpRequest.xhr.onload (http://localhost:9000/src/api/worker/rest/RestClient.js:101:1709)
