### ISSUE TITLE
Desktop Linux build fails since Rollup introduced

### ISSUE THREAD

**Issue by icjuego** [tutao/tutanota#2739]
Since Rollup was introduced in commit 79f3fff51a37fb60d71aaecd048499943f147e16, the desktop build instructions at https://github.com/tutao/tutanota/blob/master/doc/BUILDING.md do not work:
```
$ node dist -l --custom-desktop-release release
/home/user/tutanota/dist.js:12
import options from "commander"
       ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**To Reproduce**
1. Go to https://github.com/tutao/tutanota/blob/master/doc/BUILDING.md
2. Follow build instructions for desktop client
3. See error

**Desktop (please complete the following information):**
 - OS: Debian 10.8
 - Desktop Environment: XFCE
 - Version: any after 79f3fff51a37fb60d71aaecd048499943f147e16

 ```
$ node -v
v10.23.3
$ npm -v
7.5.3
```

**Comment by charlag** [comment]
You need newer node now like 14.15.5

**Comment by icjuego** [comment]
That fixed it, thanks! Maybe the build instructions need to be updated, then. They specifically mention Node 10.x, and I believe previously you couldn't use the newer ones.
