### ISSUE TITLE
Log in fails with Firefox 88.0 on Debian Buster

### ISSUE THREAD

**Issue by wodend** [tutao/tutanota#3014]
- [ x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ x] I've searched and did not find a similar issue.

**Bug in web app**
```
Feedback v3.83.3 - SyntaxError - UNKNOWN - Browser



 Client: Browser
 Type: UNKNOWN
 Tutanota version: 3.83.3
 Timestamp (UTC): Tue, 04 May 2021 05:24:43 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0
SyntaxError
 Error message: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Stacktrace: 
tc/</</</<@https://tutanota.com/worker.js:12:40409
u@https://tutanota.com/polyfill.js:1:114844
qr</e.exports<[22]</e.exports/M.prototype._settlePromiseFromHandler@https://tutanota.com/polyfill.js:1:87847
qr</e.exports<[22]</e.exports/M.prototype._settlePromise@https://tutanota.com/polyfill.js:1:88647
qr</e.exports<[22]</e.exports/M.prototype._settlePromise0@https://tutanota.com/polyfill.js:1:89346
qr</e.exports<[22]</e.exports/M.prototype._settlePromises@https://tutanota.com/polyfill.js:1:90698
f@https://tutanota.com/polyfill.js:1:42272
l@https://tutanota.com/polyfill.js:1:42212
qr</e.exports<[2]</s.prototype._drainQueues@https://tutanota.com/polyfill.js:1:43155
s/this.drainQueues@https://tutanota.com/polyfill.js:1:41953
```
**Describe the bug**
Fresh install of the `firefox` package from Debian buster unstable fails to load after accepting credentials. A popup appears stating informing the user of the error and providing the attached debug output.

**To Reproduce**
1. Go to tutanota.com/login
2. Click on the Email address field
3. Enter tutanota.com credentials
2. Click Log in
4. See popup window "An unexpected error occurred. Please try again later."

**Expected behavior**
Successful login and app loading.

**Screenshots**
![screen0](https://i.imgur.com/dduPkSQ.png)

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Browser Firefox
 - Version 88.0

**Comment by charlag** [comment]
Hi
I also tried with FF88.0 but could not reproduce it so far. Can you open devtools and copy error stacktrace from there? thanks!

**Comment by wodend** [comment]
I'm not a web developer so I couldn't figure out how to copy the error stacktrace I couldn't find any option to just display the plain text it's all these collapsable objects, here's the main error:
```
error 
Object { cause: SyntaxError, data: undefined, stack: "", … }
​
cause: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
​​
columnNumber: 8650
​​
data: undefined
​​
fileName: "https://tutanota.com/common-min-c32532d3.js"
​​
lineNumber: 1
​​
message: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"
​​
name: "SyntaxError"
​​
stack: "tc/</</</<@https://tutanota.com/worker.js:12:40409\nu@https://tutanota.com/polyfill.js:1:114844\nqr</e.exports<[22]</e.exports/M.prototype._settlePromiseFromHandler@https://tutanota.com/polyfill.js:1:87847\nqr</e.exports<[22]</e.exports/M.prototype._settlePromise@https://tutanota.com/polyfill.js:1:88647\nqr</e.exports<[22]</e.exports/M.prototype._settlePromise0@https://tutanota.com/polyfill.js:1:89346\nqr</e.exports<[22]</e.exports/M.prototype._settlePromises@https://tutanota.com/polyfill.js:1:90698\nf@https://tutanota.com/polyfill.js:1:42272\nl@https://tutanota.com/polyfill.js:1:42212\nqr</e.exports<[2]</s.prototype._drainQueues@https://tutanota.com/polyfill.js:1:43155\ns/this.drainQueues@https://tutanota.com/polyfill.js:1:41953\n"
​​
<prototype>: Error.prototype { stack: "", … }
​
data: undefined
​
isOperational: true
​
message: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"
​
name: "SyntaxError"
​
stack: "tc/</</</<@https://tutanota.com/worker.js:12:40409\nu@https://tutanota.com/polyfill.js:1:114844\nqr</e.exports<[22]</e.exports/M.prototype._settlePromiseFromHandler@https://tutanota.com/polyfill.js:1:87847\nqr</e.exports<[22]</e.exports/M.prototype._settlePromise@https://tutanota.com/polyfill.js:1:88647\nqr</e.exports<[22]</e.exports/M.prototype._settlePromise0@https://tutanota.com/polyfill.js:1:89346\nqr</e.exports<[22]</e.exports/M.prototype._settlePromises@https://tutanota.com/polyfill.js:1:90698\nf@https://tutanota.com/polyfill.js:1:42272\nl@https://tutanota.com/polyfill.js:1:42212\nqr</e.exports<[2]</s.prototype._drainQueues@https://tutanota.com/polyfill.js:1:43155\ns/this.drainQueues@https://tutanota.com/polyfill.js:1:41953\n"
​
<prototype>: Object { constructor: g(t)
, "constructor$": Error(), stack: "" }
Logger.js:89:18
Unknown error 
Object { cause: SyntaxError, data: undefined, stack: "", … }
​
cause: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
​
data: undefined
​
isOperational: true
​
message: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"
​
name: "SyntaxError"
​
stack: "tc/</</</<@https://tutanota.com/worker.js:12:40409\nu@https://tutanota.com/polyfill.js:1:114844\nqr</e.exports<[22]</e.exports/M.prototype._settlePromiseFromHandler@https://tutanota.com/polyfill.js:1:87847\nqr</e.exports<[22]</e.exports/M.prototype._settlePromise@https://tutanota.com/polyfill.js:1:88647\nqr</e.exports<[22]</e.exports/M.prototype._settlePromise0@https://tutanota.com/polyfill.js:1:89346\nqr</e.exports<[22]</e.exports/M.prototype._settlePromises@https://tutanota.com/polyfill.js:1:90698\nf@https://tutanota.com/polyfill.js:1:42272\nl@https://tutanota.com/polyfill.js:1:42212\nqr</e.exports<[2]</s.prototype._drainQueues@https://tutanota.com/polyfill.js:1:43155\ns/this.drainQueues@https://tutanota.com/polyfill.js:1:41953\n"
​
<prototype>: Object { constructor: g(t)
, "constructor$": Error(), stack: "" }
​​
constructor: function g(t)​​
"constructor$": function Error()
​​
stack: ""
​​
<prototype>: Error.prototype { stack: "", … }
​​​
constructor: function Error()
​​​
message: ""
​​​
name: "Error"
​​​
stack: ""
​​​
toString: function toString()
​​​
<get stack()>: function stack()
​​​
<set stack()>: function stack()
​​​
<prototype>: Object { … }
Logger.js:89:18
Source map error: Error: The operation was aborted. 
Resource URL: https://tutanota.com/date-a27c913c.js
Source Map URL: date-a27c913c.js.map
```

**Comment by charlag** [comment]
Thanks, it's fine the way it is. Do you have tracking protection enabled (blue shield left of URL bar)? It sometimes blocks random requests. Does it change anything if you disable it on the website?

**Comment by wodend** [comment]
I tried disabling tracking protection, but still getting the same error. This was also a fresh install with no third-party extensions such as ad or Javascript blockers.

**Comment by wodend** [comment]
Maybe this helps, I also get the same error on Chromium:
```
Feedback v3.83.3 - SyntaxError - UNKNOWN - Browser



 Client: Browser
 Type: UNKNOWN
 Tutanota version: 3.83.3
 Timestamp (UTC): Mon, 10 May 2021 22:27:56 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
SyntaxError
 Error message: Unexpected token < in JSON at position 0
Stacktrace: 
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at https://tutanota.com/worker.js:12:40409
    at u (https://tutanota.com/polyfill.js:1:114844)
    at M._settlePromiseFromHandler (https://tutanota.com/polyfill.js:1:87847)
    at M._settlePromise (https://tutanota.com/polyfill.js:1:88647)
    at M._settlePromise0 (https://tutanota.com/polyfill.js:1:89346)
    at M._settlePromises (https://tutanota.com/polyfill.js:1:90698)
    at f (https://tutanota.com/polyfill.js:1:42272)
    at l (https://tutanota.com/polyfill.js:1:42211)
    at s._drainQueues (https://tutanota.com/polyfill.js:1:43154)
    at drainQueues (https://tutanota.com/polyfill.js:1:41953)
```

From console:
 
 ```
Logger.js:89 error g
Logger.js:89 Unknown error g
sw.js:193 sw init 3.83.3
Logger.js:89 error g {cause: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at https:…, data: undefined, name: "SyntaxError", message: "Unexpected token < in JSON at position 0", isOperational: true, …}cause: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at https://tutanota.com/worker.js:12:40409
    at u (https://tutanota.com/polyfill.js:1:114844)
    at M._settlePromiseFromHandler (https://tutanota.com/polyfill.js:1:87847)
    at M._settlePromise (https://tutanota.com/polyfill.js:1:88647)
    at M._settlePromise0 (https://tutanota.com/polyfill.js:1:89346)
    at M._settlePromises (https://tutanota.com/polyfill.js:1:90698)
    at f (https://tutanota.com/polyfill.js:1:42272)
    at l (https://tutanota.com/polyfill.js:1:42211)
    at s._drainQueues (https://tutanota.com/polyfill.js:1:43154)
    at drainQueues (https://tutanota.com/polyfill.js:1:41953)data: undefinedname: "SyntaxError"message: "Unexpected token < in JSON at position 0"stack: "SyntaxError: Unexpected token < in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at https://tutanota.com/worker.js:12:40409\n    at u (https://tutanota.com/polyfill.js:1:114844)\n    at M._settlePromiseFromHandler (https://tutanota.com/polyfill.js:1:87847)\n    at M._settlePromise (https://tutanota.com/polyfill.js:1:88647)\n    at M._settlePromise0 (https://tutanota.com/polyfill.js:1:89346)\n    at M._settlePromises (https://tutanota.com/polyfill.js:1:90698)\n    at f (https://tutanota.com/polyfill.js:1:42272)\n    at l (https://tutanota.com/polyfill.js:1:42211)\n    at s._drainQueues (https://tutanota.com/polyfill.js:1:43154)\n    at drainQueues (https://tutanota.com/polyfill.js:1:41953)"__proto__: Objectconstructor: ƒ Error()message: ""name: "Error"toString: ƒ toString()__proto__: Objectdata: undefinedisOperational: truemessage: "Unexpected token < in JSON at position 0"name: "SyntaxError"stack: "SyntaxError: Unexpected token < in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at https://tutanota.com/worker.js:12:40409\n    at u (https://tutanota.com/polyfill.js:1:114844)\n    at M._settlePromiseFromHandler (https://tutanota.com/polyfill.js:1:87847)\n    at M._settlePromise (https://tutanota.com/polyfill.js:1:88647)\n    at M._settlePromise0 (https://tutanota.com/polyfill.js:1:89346)\n    at M._settlePromises (https://tutanota.com/polyfill.js:1:90698)\n    at f (https://tutanota.com/polyfill.js:1:42272)\n    at l (https://tutanota.com/polyfill.js:1:42211)\n    at s._drainQueues (https://tutanota.com/polyfill.js:1:43154)\n    at drainQueues (https://tutanota.com/polyfill.js:1:41953)"__proto__: Error
Logger.js:89 Unknown error g {cause: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at https:…, data: undefined, name: "SyntaxError", message: "Unexpected token < in JSON at position 0", isOperational: true, …}cause: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at https://tutanota.com/worker.js:12:40409
    at u (https://tutanota.com/polyfill.js:1:114844)
    at M._settlePromiseFromHandler (https://tutanota.com/polyfill.js:1:87847)
    at M._settlePromise (https://tutanota.com/polyfill.js:1:88647)
    at M._settlePromise0 (https://tutanota.com/polyfill.js:1:89346)
    at M._settlePromises (https://tutanota.com/polyfill.js:1:90698)
    at f (https://tutanota.com/polyfill.js:1:42272)
    at l (https://tutanota.com/polyfill.js:1:42211)
    at s._drainQueues (https://tutanota.com/polyfill.js:1:43154)
    at drainQueues (https://tutanota.com/polyfill.js:1:41953)data: undefinedisOperational: truemessage: "Unexpected token < in JSON at position 0"name: "SyntaxError"stack: "SyntaxError: Unexpected token < in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at https://tutanota.com/worker.js:12:40409\n    at u (https://tutanota.com/polyfill.js:1:114844)\n    at M._settlePromiseFromHandler (https://tutanota.com/polyfill.js:1:87847)\n    at M._settlePromise (https://tutanota.com/polyfill.js:1:88647)\n    at M._settlePromise0 (https://tutanota.com/polyfill.js:1:89346)\n    at M._settlePromises (https://tutanota.com/polyfill.js:1:90698)\n    at f (https://tutanota.com/polyfill.js:1:42272)\n    at l (https://tutanota.com/polyfill.js:1:42211)\n    at s._drainQueues (https://tutanota.com/polyfill.js:1:43154)\n    at drainQueues (https://tutanota.com/polyfill.js:1:41953)"__proto__: Error
```

**Comment by wodend** [comment]
Hello, bumping this up because I can't access my email which is critical for me. Can someone look into these errors, I see that the issue is that your code is trying to parse some string which is not a JSON string, and this string was not input from me I never set that anywhere
```
JSON.parse (<anonymous>)
```

Where is "<anonymous>" coming from? I assume it is something from the way Debian has packaged Firefox, do you not support Linux clients?

**Comment by wodend** [comment]
> I also tried with FF88.0 but could not reproduce it so far. Can you open devtools and copy error stacktrace from there? thanks!

Did you test on Debian Buster? I switched to unstable so that I could use FF 88 instead of the ESR, but I initially noticed this issue in FF ESR. Please try to reproduce this using the correct OS because all OS's have different builds for Firefox/Chromium

**Comment by charlag** [comment]
I assume JS couldn't be parsed. I will try to get Buster but I cannot promise I can do it soon

**Comment by johnbotris** [comment]
I tested this on Buster with both FF ESR and FF 88 from the unstable repo, I cannot reproduce it. 

@wodend Do you have this issue with other browsers (specifically chromium), the desktop client, or on other systems?

**Comment by Humam-Alhusaini** [comment]
I actually had a very similar issue to this while using Mozilla Firefox 146.0.1 on Arch Linux while running the tutamail locally. When I encounter this issue, switching my enhanced tracking protection (whether it is on or off) solves it for some reason.
