### ISSUE TITLE
Error on business account creation

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#3026]
When signing up as a private user and later realizing you would need a business account we appear to get into an inconsistent state. To preproduce:

 - start a signup
 - select a paid private account type
 - create your account 
 - don't enter payment details
 - use the wizard steps to go all the way back and select a business account
 - select payment type "purchase on account"
 - continue
 - see error
```
Feedback v3.83.3 - InternalServerError - FREE - Browser
Client: Browser
Type: FREE
Tutanota version: 3.83.3
Timestamp (UTC): Fri, 07 May 2021 08:58:05 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
InternalServerError
Error message: 500: M_524PO----2 | POST /rest/sys/switchaccounttypeservice
Stacktrace:
InternalServerError: 500: M_524PO----2 | POST /rest/sys/switchaccounttypeservice
at ac (https://mail.tutanota.com/common-min-c32532d3.js:1:2992)
at XMLHttpRequest._suspensionHandler.isSuspended.f.onload (https://mail.tutanota.com/worker.js:1:104169)
```

The account is a business one of type `FREE` and has approval `PAID_SUBSCRIPTION_NEEDED` state afterwards. Payment method is set to `Invoice`. `testsignupwithpromotion@tutanota.com` is a sample account on the production system.

**Comment by johnbotris** [comment]
I can't reproduce this, are the instructions missing a step?
