### ISSUE TITLE
Uncaught Error: TypeError - Cannot read property 'userGroup' of null

### ISSUE THREAD

**Issue by tovarian** [tutao/tutanota#3050]
Can anyone explain these errors?
I'm pretty sure someone in particular has injected code into my apps and I would like to stop it if possible.
Thanks

Feedback v3.82.18 - TypeError - UNKNOWN - android

 Client: android
 Type: UNKNOWN
 Tutanota version: 3.82.18
 Timestamp (UTC): Thu, 13 May 2021 20:32:02 GMT
 User agent:
Mozilla/5.0 (Linux; Android 10; moto e Build/QPG30.82-141; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.149 Mobile Safari/537.36
TypeError
 Error message: Cannot read property 'userGroup' of null
Stacktrace: 
TypeError: Cannot read property 'userGroup' of null
    at e.value (file:///android_asset/tutanota/dist/worker.js:1:112858)
    at e.value (file:///android_asset/tutanota/dist/worker.js:1:113117)
    at e.value (file:///android_asset/tutanota/dist/worker.js:1:111092)
    at file:///android_asset/tutanota/dist/worker.js:1:111536
    at u (file:///android_asset/tutanota/dist/polyfill.js:1:114844)
    at M._settlePromiseFromHandler (file:///android_asset/tutanota/dist/polyfill.js:1:87847)
    at M._settlePromise (file:///android_asset/tutanota/dist/polyfill.js:1:88647)
    at M._settlePromise0 (file:///android_asset/tutanota/dist/polyfill.js:1:89346)
    at M._settlePromises (file:///android_asset/tutanota/dist/polyfill.js:1:90698)
    at M._fulfill (file:///android_asset/tutanota/dist/polyfill.js:1:89716)
    at file:///android_asset/tutanota/dist/polyfill.js:1:110819

**Comment by charlag** [comment]
After manually looking at the error it seems like search index was accessed before the log in or loggging in was somehow unsuccessful. Can you email hello@tutao.de with link to this issue? Thank you!

**Comment by ProfessorCode212** [comment]
@charlag, I had the same issue. Should I send an email with a link to this issue as well?

**Comment by charlag** [comment]
@ProfessorCode212 I don't think it will help actually
