### ISSUE TITLE
Invalid mac on desktop

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3111]
A lot of reports still coming with invalid mac.

We should reset all stored data if this happens as key/data might get out of sync.

```
Tutanota version: 3.83.3
User agent:
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.83.3 Chrome/87.0.4280.141 Electron/11.4.4 Safari/537.36
CryptoError
Error message: invalid mac
Stacktrace:
CryptoError: invalid mac
at C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:1:415399
at Object.aes256Decrypt (C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:1:415739)
at Object.aesDecryptObject (C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:205269)
at Object._getEncryptedVar (C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:208726)
at async C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:246033
```

**Comment by charlag** [comment]
After discussing with @mpfau:
 - When we generate a new device key, clear all encrypted data (and probalby all SSE data)
 - We need to handle inconsistent data at least for now. We should write to log and possibly show it to the user
