### ISSUE TITLE
PreconditionFailed when accepting and then viewing and saving event invitation

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#3177]
I just accepted an invitation event via the banner, went on to look at it (while it was probably not refreshed yet), my attendence in the modal was still on "Pending". I changed it and saved the event and was given the following error:

```
Client: linux
Type: PREMIUM
Tutanota version: 3.84.4
Timestamp (UTC): Tue, 08 Jun 2021 15:03:26 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.84.4 Chrome/87.0.4280.141 Electron/11.4.6 Safari/537.36
PreconditionFailedError
Error message: 412: db.exists | POST /rest/tutanota/calendarevent/ML7HzUm--B-2
Stacktrace:
PreconditionFailedError: 412: db.exists | POST /rest/tutanota/calendarevent/ML7HzUm--B-2
at af (file:///tmp/.mount_tutanouPCVmo/resources/app.asar/common-min-9e5f97e2.js:1:2306)
at XMLHttpRequest.d.onload (file:///tmp/.mount_tutanouPCVmo/resources/app.asar/worker.js:1:100247)
```

I guess we just need to handle the error when saving/creating.

**Comment by jalhubb** [comment]
issue no longer reproduce-able
feel free to re-open if it happens again
