### ISSUE TITLE
Error when parsing calendar date

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3204]
Stacktrace:
TypeError: Cannot read property 'getUTCFullYear' of null
at ei (file:///android_asset/tutanota/dist/common-66ca0cd6.js:1:4747)
at HTMLInputElement.oninput (file:///android_asset/tutanota/dist/date-0c11838b.js:1:89934)
at D.handleEvent (file:///android_asset/tutanota/dist/app.js:1:27476)

**Comment by johnbotris** [comment]
message from the reporting user:

> Ich habe einen Termin per Email zugeschickt bekommen. Dann habe ich auf das Event geklickt und den Kalender geändert und es hinzugefügt. Anschließend habe ich auch nochmal auf Termin bestätigen geklickt. Jetzt kann ich nicht mehr auf den Kalendereintrag klicken und bekomme immer diese Fehlermeldung.
