### ISSUE TITLE
Desktop: Cannot read property 'getUTCHours' of undefined

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3295]
Some users are getting this error on desktop (reported so far from mac and windows):
```
TypeError
Error message: Cannot read property 'getUTCHours' of undefined
Stacktrace:
TypeError: Cannot read property 'getUTCHours' of undefined
at hu (C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:324631)
at Eu.scheduleAlarm (C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:328557)
at lc._scheduleAlarms (C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:91186)
at lc._decryptAndSchedule (C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:90337)
at async lc._handleCreateAlarm (C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:90924)
at async lc.handleAlarmNotification (C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:89827)
at async cc._invokeMethod (C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:96384)
```

users say:
> Give error report warning on adding events to calender. Calender seems to work OK, didn't notice anything wrong except the error report popup

> Termin geänder: Fehler

> Termin erstellt: Fehler

> Neuer Termin gemacht: Fehler

> sadsf

**Comment by bedhub** [comment]
error when creating appointment
We receive this error message from all Desktop clients. Seems to be a problem when scheduling alarms for an event because we receive them either when creating/updating an event and also after login (we also schedule alarms after login if there are new events or if it is the first time we log in on the device). 


Stacktrace after creating a calendar event:

```
Client: linux
Type: PREMIUM
Tutanota version: 3.85.10
Timestamp (UTC): Thu, 12 Aug 2021 09:01:44 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.85.10 Chrome/87.0.4280.141 Electron/11.4.11 Safari/537.36
TypeError
Error message: Cannot read property 'getUTCHours' of undefined
Stacktrace:
TypeError: Cannot read property 'getUTCHours' of undefined
at pu (desktop/DesktopMain.js:13:326214)
at bu.scheduleAlarm (desktop/DesktopMain.js:13:330140)
at lc._scheduleAlarms (desktop/DesktopMain.js:13:91127)
at lc._decryptAndSchedule (desktop/DesktopMain.js:13:90278)
at processTicksAndRejections (../../../../home/map/internal/process/task_queues.js:97:5)
at async lc._handleCreateAlarm (desktop/DesktopMain.js:13:90865)
at async lc.handleAlarmNotification (desktop/DesktopMain.js:13:89768)
```

Stacktrace after login:

```
Client: win32
Type: FREE
Tutanota version: 3.85.10
Timestamp (UTC): Thu, 12 Aug 2021 13:49:37 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.85.10 Chrome/87.0.4280.141 Electron/11.4.11 Safari/537.36
TypeError
Error message: Cannot read property 'getUTCHours' of undefined
Stacktrace:
TypeError: Cannot read property 'getUTCHours' of undefined
at pu (C:\Users\<Username>\AppData\Local\Programs\tutanota-desktop\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:326214)
at bu.scheduleAlarm (C:\Users\<Username>\AppData\Local\Programs\tutanota-desktop\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:330140)
at lc._scheduleAlarms (C:\Users\<Username>\AppData\Local\Programs\tutanota-desktop\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:91127)
at lc._decryptAndSchedule (C:\Users\<Username>\AppData\Local\Programs\tutanota-desktop\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:90278)
at async lc._handleCreateAlarm (C:\Users\<Username>\AppData\Local\Programs\tutanota-desktop\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:90865)
at async lc.handleAlarmNotification (C:\Users\<Username>\AppData\Local\Programs\tutanota-desktop\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:89768)
at async uc._invokeMethod (C:\Users\<Username>\AppData\Local\Programs\tutanota-desktop\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:96937)
```

**Comment by bedhub** [comment]
After checking the stacktrace it seems that DesktopMain.js:13:326214 resolves to this code in CommonCalendarUtils so either startDate or endDate of an event is not defined.

https://github.com/tutao/tutanota/blob/f944d5fe9edc49270969e2e8aac3ba20ae60149c/src/api/common/utils/CommonCalendarUtils.js#L13-L16

I don't know why this happens but maybe something goes wrong when decrypting the `AlarmNotification`. The function is called inside `AlarmScheduler.scheduleAlarm` called from `DesktopAlarmScheduler` after decrypting the `AlarmNotification`:

https://github.com/tutao/tutanota/blob/f944d5fe9edc49270969e2e8aac3ba20ae60149c/src/desktop/sse/DesktopAlarmScheduler.js#L107-L113

**Comment by ganthern** [comment]
## Testing:

* [ ] create some alarms and make sure they're saved in the conf.json. then close tutanota, delete the device key at `tutanota-vault/tuta` from the keychain (seahorse on linux). restart tutanota and check that the alarms get redownloaded and a new device key appears.

## Regressions:
* [ ] calendar alarms get rescheduled after a restart
* [ ] sse connects normally and gets heartbeats & notifications
