### ISSUE TITLE
Search in page error on quick keyboard input

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#3362]
When searching on a page with  <kbd>Ctrl</kbd>+<kbd>f</kbd> in the desktop client, an error is triggered when typing tooooo fast.

**To Reproduce**

**Note:** I can only reproduce on the production system, not locally

1. Open the desktop client
2. Hit <kbd>Ctrl</kbd>+<kbd>f</kbd> to get to the *Search in Page* overlay
3. Hit loads of buttons quickly, does not work when typing slowly (10 fast fingers anyone?)
```
TypeError
Error message: Cannot read property 'activeMatchOrdinal' of undefined
Stacktrace:
TypeError: Cannot read property 'activeMatchOrdinal' of undefined
at file:///tmp/.mount_tutanosAe8r9/resources/app.asar/native-main-9b277870.js:1:11513
at l (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/polyfill.js:1:81787)
at H._settlePromiseFromHandler (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/polyfill.js:1:54790)
at H._settlePromise (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/polyfill.js:1:55590)
at H._settlePromise0 (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/polyfill.js:1:56289)
at H._settlePromises (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/polyfill.js:1:57641)
at H._fulfill (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/polyfill.js:1:56659)
at Object.main486 (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/polyfill.js:1:44919)
at b._handleMessage (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/common-a3994593.js:1:6110)
at f.handleMessageObjectFromNative (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/native-common-0f760396.js:1:1461)
at Function.<anonymous> (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/native-common-0f760396.js:1:599)
```

**Expected behavior**
No error shown, other behavior is as intended/expected.

**Context**
Looks like it is triggered by a `r == undefined` here:
https://github.com/tutao/tutanota/blob/18d3181a3421fc7ca116cc8423546f8f7c6709d6/src/gui/SearchInPageOverlay.js#L106

**Comment by ganthern** [comment]
### Test Notes

* [ ] Ctrl + F opens the Search bar
* [ ] Esc closes the Search bar if it's focused
* [ ] Ctrl + F refocuses the Search bar if it's open
* [ ] Enter moves to next result
* [ ] Search Bar UI Elements work as expected

**Comment by jowlo** [comment]
### Test notes 
 * [ ] Hit lots of buttons real quick or alternatively hit as many buttons as you can at the same time while in the search field.

*And yes, i am being serious*, It seems to trigger a canceled event. :smiley:

**Comment by ganthern** [comment]
> ### Test notes
> 
>     * [ ]  Hit lots of buttons real quick or alternatively hit as many buttons as you can at the same time while in the search field.
> 
> 
> _And yes, i am being serious_, It seems to trigger a canceled event. smiley

Oof. Testing the actual bug fix is always a nice bonus ;)

**Comment by johnbotris** [comment]
>  Search Bar UI Elements work as expected

* The first press of enter does nothing, the search results only start cycling after the second press
* The query text in the search bar is detected as a result, and is highlighted and included when cycling
![Screenshot from 2021-08-25 12-03-24](https://user-images.githubusercontent.com/22109738/130771133-a9f5ca68-5f82-4426-956d-1021ad43d6c6.png)
* When the cycle reaches the text in the search bar, you have to hit enter twice to keep cycling

Not big problems, could be made into an issue and dealt with later
