### ISSUE TITLE
Critical error in "polyfill.js"

### ISSUE THREAD

**Issue by MasterInQuestion** [tutao/tutanota#3398]
```Wikitext
= Critical error in "polyfill.js" =

[
Seems like your browser is not supported or outdated. Please see FAQ entry for more information: [ https://tutanota.com/faq/#browser-support ].

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Safari/537.36
Error: Unsupported
Error: Unsupported
	at Object.execute (https://mail.tutanota.com/app.js:1:112279)
	at i (https://mail.tutanota.com/polyfill.js:1:4446)
	at k (https://mail.tutanota.com/polyfill.js:1:4415)
	at https://mail.tutanota.com/polyfill.js:1:3883
	at l (https://mail.tutanota.com/polyfill.js:1:81782)
	at H._settlePromiseFromHandler (https://mail.tutanota.com/polyfill.js:1:54785)
	at H._settlePromise (https://mail.tutanota.com/polyfill.js:1:55585)
	at H._settlePromise0 (https://mail.tutanota.com/polyfill.js:1:56284)
	at H._settlePromises (https://mail.tutanota.com/polyfill.js:1:57636)
	at H._fulfill (https://mail.tutanota.com/polyfill.js:1:56654)
	at H._settlePromise (https://mail.tutanota.com/polyfill.js:1:55783)
	at H._settlePromise0 (https://mail.tutanota.com/polyfill.js:1:56284)
	at H._settlePromises (https://mail.tutanota.com/polyfill.js:1:57636)
	at H._fulfill (https://mail.tutanota.com/polyfill.js:1:56654)
	at c._resolve (https://mail.tutanota.com/polyfill.js:1:61241)
	at c._promiseFulfilled (https://mail.tutanota.com/polyfill.js:1:61582)
]

Occurs at [ https://mail.tutanota.com/login?noAutoLogin=true ], effectively preventing the service from being accessed.


=== Related ===

[
|*| WebView Error with v.3.85.7 from F-Droid
|*| https://old.reddit.com/r/tutanota/comments/p3guyq/?sort=old ]
```

**Comment by charlag** [comment]
This comes from ClientDetector.prototype.isSupported and the last time we touched it and released was when we added a check for Object.fromEntries which should be supported since Chrome 73.

I guess you have something disabled e.g. Websocket?

**Comment by MasterInQuestion** [comment]
The last time it worked in the very environment was at version 3.84.5 (https://github.com/tutao/tutanota/releases/tag/tutanota-release-3.84.5).

**Comment by charlag** [comment]
You second stacktrace mentions Chrome 62 which is old, please update the WebView:https://tutanota.com/faq/#webview

**Comment by MasterInQuestion** [comment]
At version 3.87.1 (https://github.com/tutao/tutanota/releases/tag/tutanota-release-3.87.1):
```Text
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Safari/537.36
Error: Unsupported
Error: Unsupported
	at Object.execute (https://mail.tutanota.com/app.js:1:111805)
	at i (https://mail.tutanota.com/polyfill.js:1:4227)
	at j (https://mail.tutanota.com/polyfill.js:1:4196)
	at https://mail.tutanota.com/polyfill.js:1:3664
```

**Comment by charlag** [comment]
@MasterInQuestion this is not Android app, this is desktop stacktrace now, right?

**Comment by MasterInQuestion** [comment]
Yes. But they all originated from the very cause.

**Comment by charlag** [comment]
All of those are old Chrome versions (62 and 77)

**Comment by MasterInQuestion** [comment]
As things had worked without the problem in a not so remote version (3.84.5): the problem shouldn't be too hard to address. (merely a regression)

**Comment by MasterInQuestion** [comment]
Cause ascertained: support for "Object.fromEntries" appears to be missing in Chrome 77.
<br/>

Is there really significant necessity demanding it to be available, as the client appeared to be working alright [1] without it?

[1] Except some minor non-critical error pop-up (once, at each logon; but doesn't seem to affect any functionality) involving the function (if I recall correctly)?

**Comment by charlag** [comment]
@MasterInQuestion feel free to do any polyfills that you like, we do not support outdated and insecure browser versions

**Comment by MasterInQuestion** [comment]
I believe merely removing the "Object.fromEntries" function check in "tutanota/src/misc/ClientDetector.js" &#x5B; [https://github<b></b>.com/tutao/tutanota/blob/bb18f5b7e212876746e118ec840a3ad1cb1f183a/src/misc/ClientDetector.js#L98](https://github.com/tutao/tutanota/blob/bb18f5b7e212876746e118ec840a3ad1cb1f183a/src/misc/ClientDetector.js#L98) ] should fix the problem (largely).
