### ISSUE TITLE
Imports from tutanota-3 in admin client are not handled correctly by the IDE

### ISSUE THREAD

**Issue by rosso-ptg** [tutao/tutanota#3441]
When importing source files from tutanota-3 in admin client, the IDE is currently not able to construct the correct paths. The IDE for example will import tutanota-3/src/example/SomeFile. This path will then be rewritten by the build tools (and flow) and will result in tutanota-3/src/src/example/SomeFile. Currenlty the import would need to be tutanota-3/example/SomeFile in order to being correctly resolved during build.

It seems reasonable to get rid of all the rewrites and explicitly import tutanota-3/src/... rather than relying on rewrites which are not visible to the IDE.

IH:
- .flowconfig contains a name mapping for tutanota-3
- AdminBuilder.js uses resolveTutanota() to rewrite imports

**NOTE**
See PR 19 in tutanota-next for changes

**Comment by vaf-hub** [comment]
It seems that TypeRefs only defined in the admin client cannot be resolved anymore:


Feedback v3.88.0 - Error - SYSTEM - linux
Client: linux
Type: SYSTEM
Tutanota version: 3.88.0
Timestamp (UTC): Mon, 13 Sep 2021 11:54:59 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-admin-test/3.88.0 Chrome/91.0.4472.164 Electron/13.3.0 Safari/537.36
Error
Error message: Cannot find TypeRef: {"app":"sys","type":"System"}
Stacktrace:
Error: Cannot find TypeRef: {"app":"sys","type":"System"}
at resolveTypeReference (nollup-int:///node_modules/tutanota-3/src/api/common/EntityFunctions.js:54:27)
at _loadEntity (nollup-int:///node_modules/tutanota-3/src/api/common/EntityFunctions.js:96:10)
at load (nollup-int:///node_modules/tutanota-3/src/api/main/Entity.js:54:10)
at new CustomerDb (nollup-int:///src/customer/CustomerDb.js:170:27)
at eval (nollup-int:///src/customer/CustomerDb.js:875:20)
at Object.__impl (file:///home/vaf/dev/repositories/tutanota-next/admin/build/CustomerView-[hash].js:13050:21)
at executeModuleImpl (file:///home/vaf/dev/repositories/tutanota-next/admin/build/app.js:131:36)
at resolve_module (file:///home/vaf/dev/repositories/tutanota-next/admin/build/app.js:179:25)
at file:///home/vaf/dev/repositories/tutanota-next/admin/build/app.js:173:29
at Array.forEach (<anonymous>)
