### ISSUE TITLE
Error with onmousemove

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3586]
One of the example reports:

Client: Browser
Tutanota version: 3.89.5
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
TypeError

```
TypeError: Cannot read properties of undefined (reading '2')
  at currentSquareX (../../src/calendar/view/CalendarGuiUtils.js:78:30)
  at HTMLDivElement.onmousemove  posAndBoundsFromMouseEvent (../../src/calendar/view/CalendarMonthView.js:179:47)
  at D.handleEvent  call (../../libs/mithril.js:1142:56)
```

We probably need to check bounds for arrays.

**Comment by ganthern** [comment]
Some more:

```
clicked on calendar


Client: darwin
Type: PREMIUM
Tutanota version: 3.89.9
Timestamp (UTC): Thu, 04 Nov 2021 11:03:49 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.89.9 Chrome/91.0.4472.164 Electron/13.5.1 Safari/537.36
TypeError
Error message: Cannot read property '5' of undefined
Stacktrace:
TypeError: Cannot read property '5' of undefined
at file:///Applications/Tutanota%20Desktop.app/Contents/Resources/app.asar/calendar-view-8bda91b3.js:1:16681
at HTMLDivElement.onmousemove (file:///Applications/Tutanota%20Desktop.app/Contents/Resources/app.asar/calendar-view-8bda91b3.js:1:16685)
at D.handleEvent (file:///Applications/Tutanota%20Desktop.app/Contents/Resources/app.asar/app.js:1:26334)
```

This also looks related:
```
Client: Browser
Type: PREMIUM
Tutanota version: 3.89.9
Timestamp (UTC): Thu, 04 Nov 2021 10:36:08 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0
TypeError
Error message: r[Math.floor(...)] is undefined
Stacktrace:
onmousemove/this._dayUnderMouse<@https://mail.tutanota.com/calendar-view-8bda91b3.js:1:16670
onmousemove@https://mail.tutanota.com/calendar-view-8bda91b3.js:1:16685
execute/W
```
