### ISSUE TITLE
Uncaught UserNotAuthenticatedException: User not authenticated

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3645]
Bug which we cannot yet reproduce, looks like an issue in Android itself

```
Client: android
Tutanota version: 3.89.10
User agent:
Mozilla/5.0 (Linux; Android 9; Redmi 4X Build/PQ3A.190801.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/87.0.4280.101 Mobile Safari/537.36
java.security.KeyStoreException
Error message: android.security.keystore.UserNotAuthenticatedException: User not authenticated
Stacktrace:
java.security.KeyStoreException: android.security.keystore.UserNotAuthenticatedException: User not authenticated
at de.tutao.tutanota.AndroidKeyStoreFacade.getCipherForEncryptionMode(AndroidKeyStoreFacade.java:187)
at de.tutao.tutanota.credentials.CredentialsEncryptionBeforeAPI30.encryptUsingKeychain(CredentialsEncryptionBeforeAPI30.java:51)
at de.tutao.tutanota.Native.invokeMethod(Native.java:317)
at de.tutao.tutanota.Native.lambda$invoke$2(Native.java:98)
at de.tutao.tutanota.Native.$r8$lambda$f7qJ0eoqELxVifjuL5uWd7yLx-I(Unknown Source:0)
at de.tutao.tutanota.Native$$ExternalSyntheticLambda2.run(Unknown Source:4)
at java.lang.Thread.run(Thread.java:764)
Caused by: android.security.keystore.UserNotAuthenticatedException: User not authenticated
at android.security.KeyStore.getInvalidKeyException(KeyStore.java:895)
at android.security.KeyStore.getInvalidKeyException(KeyStore.java:937)
at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265)
at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:109)
at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2984)
at javax.crypto.Cipher.tryCombinations(Cipher.java:2877)
at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2796)
at javax.crypto.Cipher.chooseProvider(Cipher.java:773)
at javax.crypto.Cipher.init(Cipher.java:1143)
at javax.crypto.Cipher.init(Cipher.java:1084)
at de.tutao.tutanota.AndroidKeyStoreFacade.getCipherForEncryptionMode(AndroidKeyStoreFacade.java:182)
... 6 more
```

```
System Password or biometrics unlock doesn't work. Always shows this error.


Client: android
Tutanota version: 3.89.10
User agent:
Mozilla/5.0 (Linux; Android 10; Mi A1 Build/QQ3A.200805.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.158 Mobile Safari/537.36
java.security.KeyStoreException
Error message: android.security.keystore.UserNotAuthenticatedException: User not authenticated
Stacktrace:
java.security.KeyStoreException: android.security.keystore.UserNotAuthenticatedException: User not authenticated
at de.tutao.tutanota.AndroidKeyStoreFacade.getCipherForEncryptionMode(AndroidKeyStoreFacade.java:187)
at de.tutao.tutanota.credentials.CredentialsEncryptionBeforeAPI30.encryptUsingKeychain(CredentialsEncryptionBeforeAPI30.java:51)
at de.tutao.tutanota.Native.invokeMethod(Native.java:317)
at de.tutao.tutanota.Native.lambda$invoke$2(Native.java:98)
at de.tutao.tutanota.Native.$r8$lambda$f7qJ0eoqELxVifjuL5uWd7yLx-I(Unknown Source:0)
at de.tutao.tutanota.Native$$ExternalSyntheticLambda2.run(Unknown Source:4)
at java.lang.Thread.run(Thread.java:919)
Caused by: android.security.keystore.UserNotAuthenticatedException: User not authenticated
at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1348)
at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1413)
at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265)
at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:109)
at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2984)
at javax.crypto.Cipher.tryCombinations(Cipher.java:2877)
at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2796)
at javax.crypto.Cipher.chooseProvider(Cipher.java:773)
at javax.crypto.Cipher.init(Cipher.java:1143)
at javax.crypto.Cipher.init(Cipher.java:1084)
at de.tutao.tutanota.AndroidKeyStoreFacade.getCipherForEncryptionMode(AndroidKeyStoreFacade.java:182)
... 6 more
```

```
Can't login


Client: android
Tutanota version: 3.89.10
User agent:
Mozilla/5.0 (Linux; Android 11; SM-G781B Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/95.0.4638.74 Mobile Safari/537.36
de.tutao.tutanota.CryptoError
Error message: javax.crypto.IllegalBlockSizeException
Stacktrace:
de.tutao.tutanota.CryptoError: javax.crypto.IllegalBlockSizeException
at de.tutao.tutanota.AndroidKeyStoreFacade.encryptData(AndroidKeyStoreFacade.java:146)
at de.tutao.tutanota.credentials.CredentialsEncryptionFromAPI30.encryptUsingKeychain(CredentialsEncryptionFromAPI30.java:39)
at de.tutao.tutanota.Native.invokeMethod(Native.java:317)
at de.tutao.tutanota.Native.lambda$invoke$2(Native.java:98)
at de.tutao.tutanota.Native.$r8$lambda$f7qJ0eoqELxVifjuL5uWd7yLx-I(Unknown Source:0)
at de.tutao.tutanota.Native$$ExternalSyntheticLambda2.run(Unknown Source:4)
at java.lang.Thread.run(Thread.java:923)
Caused by: javax.crypto.IllegalBlockSizeException
at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
at javax.crypto.Cipher.doFinal(Cipher.java:2055)
at de.tutao.tutanota.AndroidKeyStoreFacade.encryptData(AndroidKeyStoreFacade.java:135)
... 6 more
Caused by: android.security.KeyStoreException: Key user not authenticated
at android.security.KeyStore.getKeyStoreException(KeyStore.java:1461)
at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunkedStreamer.java:140)
at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:169)
at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
... 8 more
```

E: Another one of the IllegalBlockSizeException:

> Trying to enable pin + biometrics unlock, but I get this error. Used to get it on my old phone (Galaxy S8) and on my new phone (Galaxy A54).

**Comment by charlag** [comment]
Does not occur anymore
