### ISSUE TITLE
Build error: Error: @rollup/plugin-typescript TS2307: Cannot find module '@tutao/tutanota-utils' or its corresponding type declarations.

### ISSUE THREAD

**Issue by yochananmarqos** [tutao/tutanota#3826]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
Building 3.91.2 fails with Node.js 17.3.0 or 16.13.1 and NPM 8.3.1 using `node dist -l --custom-desktop-release --unpacked`.

**To Reproduce**
1. Attempt to build 3.91.2 via the AUR package

**Expected behavior**
Successful build.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Desktop Environment: GNOME

**Additional context**

```

> tutanota@3.91.2 postinstall
> node ./buildSrc/compileKeytar

Compiling keytar from source using gyp ...
running  "node-gyp rebuild --build-from-source --arch=x64 --release" in /build/tutanota-desktop/src/tutanota-tutanota-release-3.91.2/node_modules/keytar
gyp info it worked if it ends with ok
gyp info using node-gyp@8.2.0
gyp info using node@17.3.0 | linux | x64
gyp info find Python using Python version 3.10.1 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v17.3.0/node-v17.3.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v17.3.0/node-v17.3.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v17.3.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v17.3.0/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/build/tutanota-desktop/src/tutanota-tutanota-release-3.91.2/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/build/tutanota-desktop/src/tutanota-tutanota-release-3.91.2/node_modules/keytar/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/build/tutanota-desktop/src/tutanota-tutanota-release-3.91.2/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/build/.cache/node-gyp/17.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/build/.cache/node-gyp/17.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/build/tutanota-desktop/src/tutanota-tutanota-release-3.91.2/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/build/.cache/node-gyp/17.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/build/tutanota-desktop/src/tutanota-tutanota-release-3.91.2/node_modules/keytar',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/build/tutanota-desktop/src/tutanota-tutanota-release-3.91.2/node_modules/keytar/build'
  CXX(target) Release/obj.target/keytar/src/async.o
  CXX(target) Release/obj.target/keytar/src/main.o
  CXX(target) Release/obj.target/keytar/src/keytar_posix.o
  SOLINK_MODULE(target) Release/obj.target/keytar.node
  COPY Release/keytar.node
make: Leaving directory '/build/tutanota-desktop/src/tutanota-tutanota-release-3.91.2/node_modules/keytar/build'
gyp info ok 
Compiled keytar successfully 


added 720 packages, and audited 725 packages in 20s

40 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (1 low, 4 moderate)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
started cleaning 0.002
bundling polyfill 0.003

Build error: Error: @rollup/plugin-typescript TS2307: Cannot find module '@tutao/tutanota-utils' or its corresponding type declarations.
    at error (file:///build/tutanota-desktop/src/tutanota-tutanota-release-3.91.2/node_modules/rollup/dist/es/shared/rollup.js:10361:30)
    at throwPluginError (file:///build/tutanota-desktop/src/tutanota-tutanota-release-3.91.2/node_modules/rollup/dist/es/shared/rollup.js:21700:12)
    at Object.error (file:///build/tutanota-desktop/src/tutanota-tutanota-release-3.91.2/node_modules/rollup/dist/es/shared/rollup.js:22405:20)
    at emitDiagnostic (/build/tutanota-desktop/src/tutanota-tutanota-release-3.91.2/node_modules/@rollup/plugin-typescript/dist/index.js:512:17)
    at reportDiagnostics (/build/tutanota-desktop/src/tutanota-tutanota-release-3.91.2/node_modules/@rollup/plugin-typescript/dist/index.js:520:9)
    at Array.forEach (<anonymous>)
    at emitFilesAndReportErrors (/build/tutanota-desktop/src/tutanota-tutanota-release-3.91.2/node_modules/typescript/lib/typescript.js:120043:21)
    at Object.result.afterProgramCreate (/build/tutanota-desktop/src/tutanota-tutanota-release-3.91.2/node_modules/typescript/lib/typescript.js:120221:13)
    at Object.afterProgramCreate (/build/tutanota-desktop/src/tutanota-tutanota-release-3.91.2/node_modules/@rollup/plugin-typescript/dist/index.js:675:29)
    at synchronizeProgram (/build/tutanota-desktop/src/tutanota-tutanota-release-3.91.2/node_modules/typescript/lib/typescript.js:120518:22) {
  pluginCode: 'TS2307',
  loc: {
    column: 29,
    line: 3,
    file: '/build/tutanota-desktop/src/tutanota-tutanota-release-3.91.2/src/api/common/DataFile.ts'
  },
  frame: '\n' +
    '\x1B[7m3\x1B[0m import {isSameTypeRef} from "@tutao/tutanota-utils"\n' +
    '\x1B[7m \x1B[0m \x1B[91m                            ~~~~~~~~~~~~~~~~~~~~~~~\x1B[0m\n',
  code: 'PLUGIN_ERROR',
  plugin: 'typescript',
  hook: 'buildStart'
}
```

**Comment by vitoreiji** [comment]
This is a but in the AUR package: the [`PKGBUILD`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tutanota-desktop) is missing the `npm run build-packages` mentioned in the [build instructions](https://github.com/tutao/tutanota/blob/master/doc/BUILDING.md).

**Comment by yochananmarqos** [comment]
That did the trick, thanks.
