### ISSUE TITLE
Error message: invalid mac

### ISSUE THREAD

**Issue by Ahmed-E-86** [tutao/tutanota#3885]
**Describe the bug**

Lately, I keep getting this error message during logging in

![Screenshot_20220209_123650](https://user-images.githubusercontent.com/29783425/153181066-ee541698-695d-4a49-98f1-39cf383b1ed5.png)

```
Feedback v3.91.9 - Error - UNKNOWN - linux

 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.91.9
 Timestamp (UTC): Wed, 09 Feb 2022 10:31:23 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.91.9 Chrome/96.0.4664.110 Electron/16.0.8 Safari/537.36
Error
 Error message: invalid mac
Stacktrace: 
Error: invalid mac
    at os (file:///app/lib/tutanota/resources/app.asar/worker.js:1:38652)
    at Wu.decrypt (file:///app/lib/tutanota/resources/app.asar/worker.js:12:130667)
    at file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:5590
    at C.handleMessage (file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:7598)
    at file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:6851
    at _worker.onmessage (file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:6431)
```
After I removed `~/.var/app/com.tutanota.Tutanota/`, I was able to log in, then after closing Tutanota and opening it again, I got the same error message.

**Desktop (please complete the following information):**
 - OS: Kubuntu 21.10
 - Desktop Environment: KDE Plasma 5.22.5
 - Version: 3.91.9 (Flatpak)

**Comment by charlag** [comment]
Duplcie of  #3875
