### ISSUE TITLE
App hangs before opening after clicking on notification

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3911]
Android 10 - 12

Clicking on email notification does nothing. System thinks that the app is opened but it is blocked even before UI thread has a chance to react. This is only happening on some devices but when it happens it is fairly constant.

I suspect that this is due to some of the blocking code in credential encryption (see AuthenticationPrompt.java). We should make sure that we don't block UI thread, especially that early.

## Test notes
 - [ ] Close app. Receive email notification. Click on email notification. Should log in into correct mailbox.
 - [ ] While the app is running and while being logged in put the app into background and also click on notification. Should open the app.

## Regression
 - [ ] Can still click on alarm notifications
 - [ ] Can share files with the app
   - [ ] When the app is running
   - [ ] When the app is not running yet
   - [ ] Back press still works (moves back in the app and then closes the app eventually)

**Comment by charlag** [comment]
I could reproduce it by developer settings "don't keep activities".

Not sure if that's the reason but I see this:

```
E/ActivityThread: Activity de.tutao.tutanota.MainActivity has leaked IntentReceiver de.tutao.tutanota.MainActivity$2@e42988d that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity de.tutao.tutanota.MainActivity has leaked IntentReceiver de.tutao.tutanota.MainActivity$2@e42988d that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1588)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1368)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1515)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1488)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1476)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:627)
        at de.tutao.tutanota.MainActivity.onCreate(MainActivity.java:165)
        at android.app.Activity.performCreate(Activity.java:7841)
        at android.app.Activity.performCreate(Activity.java:7830)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by charlag** [comment]
This is not the reason

**Comment by charlag** [comment]
This is:
```
Unable to resume activity {de.tutao.tutanota.debug/de.tutao.tutanota.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebMessagePort.postMessage(android.webkit.WebMessage)' on a null object reference
```
