### ISSUE TITLE
allow log out and log in on android 

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#394]

**Comment by armhub** [comment]
After login

Client: android app
Type: FREE
Tutanota version: 3.35.3
Timestamp (UTC): Wed, 04 Jul 2018 09:06:08 GMT
User agent: 
Mozilla/5.0 (Linux; Android 7.1.2; XT1635-02 Build/NJH47F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/63.0.3239.111 Mobile Safari/537.36

Stacktrace: 
TypeError: Cannot read property 'list' of null
at PushServiceApp._createPushIdentiferInstance (file:///android_asset/tutanota/src/native/PushServiceApp.js:88:57)
at eval (file:///android_asset/tutanota/src/native/PushServiceApp.js:37:48)
at r (file:///android_asset/tutanota/libs/bluebird.min.js:31:9004)
at i._settlePromiseFromHandler (file:///android_asset/tutanota/libs/bluebird.min.js:30:14217)
at i._settlePromise (file:///android_asset/tutanota/libs/bluebird.min.js:30:15020)
at i._settlePromise0 (file:///android_asset/tutanota/libs/bluebird.min.js:30:15721)
at i._settlePromises (file:///android_asset/tutanota/libs/bluebird.min.js:30:17051)
at i._fulfill (file:///android_asset/tutanota/libs/bluebird.min.js:30:16092)
at Object.main41 (file:///android_asset/tutanota/libs/bluebird.min.js:30:4676)
at Queue._handleMessage (file:///android_asset/tutanota/src/api/common/WorkerProtocol.js:168:2093)
at Worker.Queue._transport.onmessage (file:///android_asset/tutanota/src/api/common/WorkerProtocol.js:168:1653)
