### ISSUE TITLE
Wayland support broken in latest update

### ISSUE THREAD

**Issue by parasaito** [tutao/tutanota#3974]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
Native wayland support for the desktop client on Linux broke in the latest update (3.9.6). It worked just fine till update 3.9.5. Here's the log :

```
./tutanota-desktop-linux.AppImage --enable-features=UseOzonePlatform --ozone-platform=wayland             
the monkey has been patched
(node:54703) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `tutanota-desktop --trace-deprecation ...` to show where the warning was created)
version:   3.93.6
[54703:0318/222004.242960:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
resolving key... tutanota-vault
[2022-03-18T16:50:04.256Z] failed to read config! SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /tmp/.mount_tutanooeVZdp/resources/app.asar/desktop/DesktopMain.js:1:20721
    at async Re.init (/tmp/.mount_tutanooeVZdp/resources/app.asar/desktop/DesktopMain.js:1:21640)
[54751:0318/222004.299257:ERROR:gpu_init.cc(454)] Passthrough is not supported, GL is egl, ANGLE is 
[54751:0318/222004.327355:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
config up to date
sseInfo corrupted or not present, making sure pushEncSessionKeys and scheduled alarms are cleared
Resetting stored state
[ApplicationWindow] startFile:  file:///tmp/.mount_tutanooeVZdp/resources/app.asar/index-desktop.html
zsh: segmentation fault (core dumped)  ./tutanota-desktop-linux.AppImage --enable-features=UseOzonePlatform
```

**To Reproduce**
1. Make the official AppImage executable : `chmod +x tutanota-desktop-linux.AppImage`
2. Execute with the wayland flags : 
`./tutanota-desktop-linux.AppImage --enable-features=UseOzonePlatform --ozone-platform=wayland`

**Expected behavior**
As an electron app working on pretty up-to-date version of electron, app should work under Wayland natively.

**Desktop (please complete the following information):**
 - OS: Fedora Linux 35
 - Desktop Environment: GNOME 41.4 tk: GTK 3.24.31 wm: Mutter dm: GDM 41.3
 - Kernel: 5.16.14-200.fc35.x86_64

**Additional context**
Works under XWayland compatibility layer, however should work under Wayland directly, especially since the last version did support it.

**Comment by parasaito** [comment]
The issue now seems to be resolved in the new version 3.94.9 with electron 17.3
