### ISSUE TITLE
npm error - Invalid Version

### ISSUE THREAD

**Issue by mxnugget** [tutao/tutanota#3988]
I get this error while trying to build Tutanota:

```
$ sudo npm ci
npm ERR! Invalid Version: file:packages/tutanota-crypto

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-25T21_17_46_723Z-debug.log

```

**Comment by johnbotris** [comment]
you shouldn't be running `npm ci` as root, for starters

**Comment by jtrees** [comment]
I also get this and I'm not running as root.

Here's the log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/nix/store/s3c6813krvcxzd3fz1grlnjmgb5098vd-nodejs-14.19.1/bin/node',
1 verbose cli   '/nix/store/s3c6813krvcxzd3fz1grlnjmgb5098vd-nodejs-14.19.1/bin/npm',
1 verbose cli   'ci'
1 verbose cli ]
2 info using npm@6.14.16
3 info using node@v14.19.1
4 verbose npm-session 620eb7347653cc63
5 info prepare initializing installer
6 verbose prepare starting workers
7 verbose prepare installation prefix: /home/josh/resources/code/tutanota
8 verbose prepare using package-lock.json
9 verbose checkLock verifying package-lock data
10 verbose teardown shutting down workers.
11 info teardown Done in 0.001s
12 verbose stack TypeError: Invalid Version: file:packages/tutanota-crypto
12 verbose stack     at new SemVer (/nix/store/s3c6813krvcxzd3fz1grlnjmgb5098vd-nodejs-14.19.1/lib/node_modules/npm/node_modules/semver/semver.js:323:11)
12 verbose stack     at Range.test (/nix/store/s3c6813krvcxzd3fz1grlnjmgb5098vd-nodejs-14.19.1/lib/node_modules/npm/node_modules/semver/semver.js:1203:15)
12 verbose stack     at Function.satisfies (/nix/store/s3c6813krvcxzd3fz1grlnjmgb5098vd-nodejs-14.19.1/lib/node_modules/npm/node_modules/semver/semver.js:1257:16)
12 verbose stack     at /nix/store/s3c6813krvcxzd3fz1grlnjmgb5098vd-nodejs-14.19.1/lib/node_modules/npm/node_modules/lock-verify/index.js:46:25
12 verbose stack     at Array.forEach (<anonymous>)
12 verbose stack     at /nix/store/s3c6813krvcxzd3fz1grlnjmgb5098vd-nodejs-14.19.1/lib/node_modules/npm/node_modules/lock-verify/index.js:25:25
13 verbose cwd /home/josh/resources/code/tutanota
14 verbose Linux 5.15.41
15 verbose argv "/nix/store/s3c6813krvcxzd3fz1grlnjmgb5098vd-nodejs-14.19.1/bin/node" "/nix/store/s3c6813krvcxzd3fz1grlnjmgb5098vd-nodejs-14.19.1/bin/npm" "ci"
16 verbose node v14.19.1
17 verbose npm  v6.14.16
18 error Invalid Version: file:packages/tutanota-crypto
19 verbose exit [ 1, true ]
```

I suspect it may be related to the way node/npm is set up on NixOS. Any pointers on what the issue could be?
