### ISSUE TITLE
NotAuthenticatedError on logout

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3997]
I logged out in the desktop client and got this error:

```
Uncaught EventQueue error! 
NotAuthenticatedError: user must be authenticated for entity requests
    at Hr._validateAndPrepareRestRequest (file:///tmp/.mount_tutanoMluHPJ/resources/app.asar/worker.js:1:14585)
    at async Hr.loadRange (file:///tmp/.mount_tutanoMluHPJ/resources/app.asar/worker.js:1:11098)
    at async Object.loadAll (file:///tmp/.mount_tutanoMluHPJ/resources/app.asar/common-2a348d21.js:1:62653)
    at async Hr.load (file:///tmp/.mount_tutanoMluHPJ/resources/app.asar/worker.js:1:10743)
    at async qr.load (file:///tmp/.mount_tutanoMluHPJ/resources/app.asar/worker.js:1:3875)
```
Presumably it was processing entity events as I logged out

v3.94.2

**Comment by jalhubb** [comment]
no reproduction anymore
