### ISSUE TITLE
ProgrammingError related to AlarmInfo

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4071]
```
ProgrammingError
Error message: Undefined aggregation AlarmInfo:calendarRef
Stacktrace:
ProgrammingError: Undefined aggregation AlarmInfo:calendarRef
at eval (nollup-int:///src/api/worker/crypto/InstanceMapper.ts:59:31)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async eval (nollup-int:///packages/tutanota-utils/dist/PromiseMap.js:58:37)
```

## Test notes
 - [ ] Make sure there are alarms in calendar. Clear config. Log in on desktop. Should see no error but alarm should be scheduled.

**Comment by charlag** [comment]
We are unable to reproduce it anymore, might be related to a broken entity

**Comment by charlag** [comment]
The problem is that we pass the wrong type when decrypting alarms:

https://github.com/tutao/tutanota/blob/f3f1f0dca9200feb13a7999778283f6103c85a12/src/desktop/sse/DesktopAlarmScheduler.ts#L80-L85
