### ISSUE TITLE
[offline] Error on Startup with Offline Mode Enabled

### ISSUE THREAD

**Issue by jboucher614** [tutao/tutanota#4120]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**

Launching the program with Offline Mode enabled gives an error during the login process. 

The bug reads:
---
Feedback v3.96.3 - Error - UNKNOWN - linux

 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.96.3
 Timestamp (UTC): Tue, 10 May 2022 20:35:08 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.96.3 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36
Error
 Error message: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /app/lib/tutanota/resources/app.asar.unpacked/desktop/better_sqlite3.node)
Stacktrace: 
Error: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /app/lib/tutanota/resources/app.asar.unpacked/desktop/better_sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new bh (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:13:991056)
    at Ch.openDatabase (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:13:996817)
---

**To Reproduce**
1. Enable Offline Mode
2. Close Tutanota
3. Open Tutanota

**Expected behavior**
No error message

**Screenshots**
![image](https://user-images.githubusercontent.com/75694650/167718007-28335c8a-ce3e-4fcf-bdf9-173f0a5d5f5b.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Manjaro Linux
 - Desktop Environment, if applicable (on Linux) KDE
 - Version [e.g. 22] 3.96.3 Flathub Flatpak

**Additional context**

**Comment by charlag** [comment]
https://github.com/flathub/com.tutanota.Tutanota/issues/93
