### ISSUE TITLE
Offline feauture does not work on client installed from FlatHub (Linux)

### ISSUE THREAD

**Issue by DECHT** [tutao/tutanota#4138]
**Describe the bug**
The data can not be saved for offline using, while using Tutanota app on Linux installed from FlatHub. But it works well using the AppImage.

**To Reproduce**
1. Start the client with double-click or with `flatpak run com.tutanota.Tutanota`.
2. Here is the terminal output:
```
flatpak run com.tutanota.Tutanota
the monkey has been patched
(node:2) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `tutanota-desktop --trace-deprecation ...` to show where the warning was created)
version:   3.96.3

(tutanota-desktop:2): Gtk-WARNING **: 19:28:21.761: Whoever translated default:LTR did so wrongly. Defaulting to LTR.
Gtk-Message: 19:28:21.826: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:28:21.826: Failed to load module "canberra-gtk-module"
libGL error: MESA-LOADER: failed to retrieve device information
resolving key... tutanota-vault
config up to date
[46:0516/192821.936334:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:496 (GenerateTextureFormatCaps): glGetInternalformativ generated error 0x00000500 for format 0x00008D62. Skipping multisample checks.
[46:0516/192821.936587:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:496 (GenerateTextureFormatCaps): glGetInternalformativ generated error 0x00000500 for format 0x0000906F. Skipping multisample checks.
[46:0516/192821.936932:ERROR:angle_platform_impl.cc(44)] Display.cpp:940 (initialize): ANGLE Display::initialize error 12289: OpenGL ES 2.0 is not supportable.
[46:0516/192821.937171:ERROR:gl_surface_egl.cc(808)] EGL Driver message (Critical) eglInitialize: OpenGL ES 2.0 is not supportable.
[46:0516/192821.937440:ERROR:gl_surface_egl.cc(1430)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[46:0516/192821.939293:ERROR:angle_platform_impl.cc(44)] Display.cpp:940 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[ApplicationWindow] startFile:  file:///app/lib/tutanota/resources/app.asar/index-desktop.html
[46:0516/192821.939591:ERROR:gl_surface_egl.cc(808)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[46:0516/192821.939686:ERROR:gl_surface_egl.cc(1430)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[46:0516/192821.939773:ERROR:gl_ozone_egl.cc(20)] GLSurfaceEGL::InitializeOneOff failed.
[46:0516/192821.942155:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[DownloadManager] getting dictionaries from: https://mail.tutanota.com/desktop//dictionaries/
default mailto handler: false
scheduling to check sse in 1 seconds
libGL error: MESA-LOADER: failed to retrieve device information
[81:0516/192822.084592:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:496 (GenerateTextureFormatCaps): glGetInternalformativ generated error 0x00000500 for format 0x00008D62. Skipping multisample checks.
[81:0516/192822.084790:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:496 (GenerateTextureFormatCaps): glGetInternalformativ generated error 0x00000500 for format 0x0000906F. Skipping multisample checks.
[81:0516/192822.084992:ERROR:angle_platform_impl.cc(44)] Display.cpp:940 (initialize): ANGLE Display::initialize error 12289: OpenGL ES 2.0 is not supportable.
[81:0516/192822.085086:ERROR:gl_surface_egl.cc(808)] EGL Driver message (Critical) eglInitialize: OpenGL ES 2.0 is not supportable.
[81:0516/192822.085146:ERROR:gl_surface_egl.cc(1430)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[81:0516/192822.086067:ERROR:angle_platform_impl.cc(44)] Display.cpp:940 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[81:0516/192822.086186:ERROR:gl_surface_egl.cc(808)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[81:0516/192822.086253:ERROR:gl_surface_egl.cc(1430)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[81:0516/192822.086322:ERROR:gl_ozone_egl.cc(20)] GLSurfaceEGL::InitializeOneOff failed.
[81:0516/192822.088529:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[96:0516/192822.125482:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[2:0516/192822.169861:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:0516/192822.185148:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Webapp ready
no update info on disk, disabling updater.
[2:0516/192822.403348:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
desktop file exists, checking version...
resolving key... tutanota-credentials
last missed notification check: { lastMissedNotificationCheckTime: 1652721965687 }
scheduling to check sse in 26 seconds
starting sse connection
lookup sse request
established SSE connection
received new timeout: heartbeatTimeout:240
scheduling to check sse in 288 seconds
sse heartbeat 240
scheduling to check sse in 288 seconds
sse heartbeat 240
scheduling to check sse in 288 seconds
downloading missed notification
lookup
[2:0516/192823.336848:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
missed notification response 200
dl missed notification response closed
MissedNotification is empty
scheduling to check sse in 288 seconds
storing push identifier
```
3. This error message is shown in the client:
`An unexpected error occurred. Please try again later.`
```
Feedback v3.96.3 - Error - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.96.3
 Timestamp (UTC): Mon, 16 May 2022 17:28:22 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.96.3 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36
Error
 Error message: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /app/lib/tutanota/resources/app.asar.unpacked/desktop/better_sqlite3.node)
Stacktrace: 
Error: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /app/lib/tutanota/resources/app.asar.unpacked/desktop/better_sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new bh (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:13:991056)
    at Ch.openDatabase (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:13:996817)
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Ubuntu 22.04
 - 5.15.0-30-generic
 - 31-Ubuntu SMP Thu May 5 10:00:34 UTC 2022

**Comment by charlag** [comment]
https://github.com/flathub/com.tutanota.Tutanota/issues/93
