### ISSUE TITLE
Uncaught Error: trying to encrypt non-persistent credentials

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4193]
To reproduce:
 - log in without storing password
 - wait until session is expired (either wait for a day or test on local server with modified `SESSION_TIMEOUT_IN_SECONDS`)
 - See the error prompt
 - type in your password and press "Ok"
 - See the error

### One

```
Client: Browser
Type: PREMIUM
Tutanota version: 3.96.6
Timestamp (UTC): Mon, 23 May 2022 07:24:27 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
Error
Error message: Trying to encrypt non-persistent credentials
Stacktrace:
Error: Trying to encrypt non-persistent credentials
at Ds.encrypt (https://mail.tutanota.com/main-f48aa2d3.js:1:49607)
at [Cs.store](http://cs.store/) (https://mail.tutanota.com/main-f48aa2d3.js:1:45028)
at Object.action (https://mail.tutanota.com/main-f48aa2d3.js:1:93502)
at async o (https://mail.tutanota.com/gui-base-ef5812b8.js:1:111994)
```

```
Client: Browser
Type: PREMIUM
Tutanota version: 3.96.6
Timestamp (UTC): Fri, 20 May 2022 20:50:45 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.47
Error
Error message: Trying to encrypt non-persistent credentials
Stacktrace:
Error: Trying to encrypt non-persistent credentials
at Ds.encrypt (https://mail.tutanota.com/main-f48aa2d3.js:1:49607)
at [Cs.store](http://cs.store/) (https://mail.tutanota.com/main-f48aa2d3.js:1:45028)
at Object.action (https://mail.tutanota.com/main-f48aa2d3.js:1:93502)
at async o (https://mail.tutanota.com/gui-base-ef5812b8.js:1:111994)
```

```
Just trying to log in with pw only.


Client: Browser
Type: PREMIUM
Tutanota version: 3.96.6
Timestamp (UTC): Mon, 23 May 2022 05:49:36 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
Error
Error message: Trying to encrypt non-persistent credentials
Stacktrace:
Error: Trying to encrypt non-persistent credentials
at Ds.encrypt (https://mail.tutanota.com/main-f48aa2d3.js:1:49607)
at [Cs.store](http://cs.store/) (https://mail.tutanota.com/main-f48aa2d3.js:1:45028)
at Object.action (https://mail.tutanota.com/main-f48aa2d3.js:1:93502)
at async o (https://mail.tutanota.com/gui-base-ef5812b8.js:1:111994)
```

```
Client: Browser
Type: FREE
Tutanota version: 3.96.6
Timestamp (UTC): Mon, 23 May 2022 07:46:40 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
Error
Error message: Trying to encrypt non-persistent credentials
Stacktrace:
Error: Trying to encrypt non-persistent credentials
at Ds.encrypt (https://mail.tutanota.com/main-f48aa2d3.js:1:49607)
at [Cs.store](http://cs.store/) (https://mail.tutanota.com/main-f48aa2d3.js:1:45028)
at Object.action (https://mail.tutanota.com/main-f48aa2d3.js:1:93502)
at async o (https://mail.tutanota.com/gui-base-ef5812b8.js:1:111994)
```

https://github.com/tutao/tutanota/blob/40e94dee2bcec2b63f362da283123e9df1874cc1/src/misc/credentials/CredentialsProviderFactory.ts#L76-L83

### Two

```
Think I entered incorrect password. Crash.


Client: win32
Type: PREMIUM
Tutanota version: 3.96.6
Timestamp (UTC): Sat, 21 May 2022 00:35:33 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.96.6 Chrome/100.0.4896.143 Electron/18.2.3 Safari/537.36
Error
Error message: Trying to encrypt non-persistent credentials
Stacktrace:
Error: Trying to encrypt non-persistent credentials
at xs.encrypt (file:///C:/Users/5600/AppData/Local/Programs/Tutanota%20Desktop/resources/app.asar/main-f48aa2d3.js:1:47984)
at [Cs.store](http://cs.store/) (file:///C:/Users/5600/AppData/Local/Programs/Tutanota%20Desktop/resources/app.asar/main-f48aa2d3.js:1:45028)
at Object.action (file:///C:/Users/5600/AppData/Local/Programs/Tutanota%20Desktop/resources/app.asar/main-f48aa2d3.js:1:93502)
at async o (file:///C:/Users/5600/AppData/Local/Programs/Tutanota%20Desktop/resources/app.asar/gui-base-ef5812b8.js:1:111994)
```

https://github.com/tutao/tutanota/blob/40e94dee2bcec2b63f362da283123e9df1874cc1/src/misc/credentials/NativeCredentialsEncryption.ts#L25-L32

## Test notes
 - [ ] Try reproduce the issue with expired session
 - [ ] Regression for closed session & offline login

**Comment by charlag** [comment]
One of the stacktraces restored:
```
  at xs.encrypt   (../../../src/misc/credentials/NativeCredentialsEncryption.ts:29:9)
  at Cs.store  encrypt (../../../src/misc/credentials/CredentialsProvider.ts:180:64)
  at Object.action  store (../../../src/misc/ErrorHandlerImpl.ts:195:38)
  at async o  errorMessage (../../../src/gui/base/Dialog.ts:929:9)
```

**Comment by charlag** [comment]
Another one:

```
  at Ds.encrypt   (../../../src/misc/credentials/CredentialsProviderFactory.ts:81:9)
  at [Cs.store](http://cs.store/)  encrypt (../../../src/misc/credentials/CredentialsProvider.ts:180:64)
  at Object.action  store (../../../src/misc/ErrorHandlerImpl.ts:195:38)
  at async o  errorMessage (../../../src/gui/base/Dialog.ts:929:9)
```

what the hell is http://cs.store in the middle? Extension?

**Comment by charlag** [comment]
OMG we are calling `store` unconditionally! of course :facepalm:
