### ISSUE TITLE
AssertNotNull failed in drag handler

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4198]
>Cicked on notification about new mail, inbox opened, then error

```
Client: android
Tutanota version: 3.96.3
User agent:
[Android 12]

Error
Error message: AssertNotNull failed : null
Stacktrace:
Error: AssertNotNull failed : null
at p (file:///android_asset/tutanota/dist/common-min-bd0e3a79.js:1:11225)
at Qe.getVirtualElement (file:///android_asset/tutanota/dist/gui-base-1d58d190.js:1:179585)
at Qe.onHorizontalDrag (file:///android_asset/tutanota/dist/gui-base-1d58d190.js:1:177102)
at Qe.move (file:///android_asset/tutanota/dist/gui-base-1d58d190.js:1:156214)
at HTMLDivElement. (file:///android_asset/tutanota/dist/gui-base-1d58d190.js:1:155840)
```

**Comment by charlag** [comment]
Not sure how it happens but it would be very easy to fix: make `getVirtualElement()` return nullable value and check `null` in `onHorizontalDrag()`
