### ISSUE TITLE
Errors building Android apk

### ISSUE THREAD

**Issue by knightsg** [tutao/tutanota#421]
Following the Android build instructions, I get the following errors when I run 'gulp androidProdDistUnsigned'. I'm running this in a Windows Linux shell (Ubuntu 16.04.2 LTS):

root@comp:~/Work/tutanota/cordova# gulp androidProdDistUnsigned
[11:15:03] Using gulpfile /mnt/d/Work/tutanota/cordova/gulpfile.js
[11:15:03] Starting 'createWebRelease'...
[11:15:04] Starting 'updateAndroidPlatformAndTutanotaPlugin'...

You have been opted out of telemetry. To change this, run: cordova telemetry on.
(node:6675) UnhandledPromiseRejectionWarning: CordovaError: Current working directory is not a Cordova-based project.
    at Object.cdProjectRoot (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js:170:15)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/platform/index.js:55:40
    at _fulfilled (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:810:14
    at flush (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:6675) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6675) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/mnt/d/Work/tutanota/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/mnt/d/Work/tutanota/node_modules/socket.io/lib/store.js:35:42)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Work/tutanota/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:652:30)
[11:15:05] 'createWebRelease' errored after 1.44 s
[11:15:05] Error in plugin 'gulp-shell'
Message:
    Command failed: cd ../web; gulp distCordova
/mnt/d/Work/tutanota/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/mnt/d/Work/tutanota/node_modules/socket.io/lib/store.js:35:42)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Work/tutanota/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:652:30)

Details:
    killed: false
    code: 1
    signal: null
    cmd: cd ../web; gulp distCordova
    stdout:
    stderr: /mnt/d/Work/tutanota/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/mnt/d/Work/tutanota/node_modules/socket.io/lib/store.js:35:42)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Work/tutanota/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:652:30)

You have been opted out of telemetry. To change this, run: cordova telemetry on.
(node:6697) UnhandledPromiseRejectionWarning: CordovaError: Current working directory is not a Cordova-based project.
    at Object.cdProjectRoot (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js:170:15)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/platform/index.js:55:40
    at _fulfilled (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:810:14
    at flush (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:6697) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6697) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

You have been opted out of telemetry. To change this, run: cordova telemetry on.
(node:6714) UnhandledPromiseRejectionWarning: CordovaError: Current working directory is not a Cordova-based project.
    at Object.cdProjectRoot (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js:170:15)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/plugin/index.js:36:40
    at _fulfilled (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:810:14
    at flush (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:6714) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6714) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

You have been opted out of telemetry. To change this, run: cordova telemetry on.
(node:6731) UnhandledPromiseRejectionWarning: CordovaError: Current working directory is not a Cordova-based project.
    at Object.cdProjectRoot (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js:170:15)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/plugin/index.js:36:40
    at _fulfilled (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:810:14
    at flush (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:6731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6731) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[11:15:09] Finished 'updateAndroidPlatformAndTutanotaPlugin' after 5.65 s

I followed the steps as directed, what am I missing here?

Thanks,
Guy

**Comment by charlag** [comment]
Hi!
This is an old app, if you want to build an app I would recommend using the new app in the master branch. Using Cordova is really tricky. We will update instructions once it's done but for now please check #417

**Comment by knightsg** [comment]
Thanks, I'll take a look!
