### ISSUE TITLE
Can't login with system account on test.tutanota.com

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#4220]
I need to do this to add new users to the system customer.

```
Feedback v3.96.9 - NotFoundError - SYSTEM - Browser
Client: Browser
Type: SYSTEM
Tutanota version: 3.96.9
Timestamp (UTC): Fri, 27 May 2022 13:18:51 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
NotFoundError
Error message: 404: N34erBJ----0 | GET /rest/tutanota/mailboxgrouproot/KLKxJ5Z----0
Stacktrace:
NotFoundError: 404: N34erBJ----0 | GET /rest/tutanota/mailboxgrouproot/KLKxJ5Z----0
at cK (https://test.tutanota.com/common-min-64b806d8.js:1:7831)
at XMLHttpRequest.u.onload (https://test.tutanota.com/worker.js:12:95360)
```

**Comment by mpfau** [comment]
@charlag it happens all the time when I login with my system user.

**Comment by charlag** [comment]
old system admins are missing mailboxgrouproot, we either need to create one or ignore it
