### ISSUE TITLE
Temporary login not closed from signup form

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#4223]
* Go to signup form
* fill in email and password and then go to the next page
* then close the dialog by cancelling or finishing signing up
* login to another account
* get an error on login:

> NotAuthorizedError NotAuthorizedError: 403: N35-wTg----0 | GET /rest/tutanota/mail/N35-r0R--V-0
    at handleRestError (http://localhost:9000/client/build/worker.js:1173:14)
    at XMLHttpRequest.xhr.onload (http://localhost:9000/client/build/worker.js:62669:26)

**Comment by charlag** [comment]
Could not reproduce:
 - signup up, cancelled at some step, logged into another account without issues
 - finished signup, page was reloaded so I logged in without issues
