### ISSUE TITLE
Android notification service crashes

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4324]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.tutao.tutanota:pushprocess, PID: 18797
    java.lang.RuntimeException: Unable to create service de.tutao.tutanota.push.PushNotificationService: java.lang.NullPointerException
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4199)
        at android.app.ActivityThread.access$1500(ActivityThread.java:238)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1933)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7705)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
     Caused by: java.lang.NullPointerException
        at de.tutao.tutanota.alarms.EncryptedRepeatRuleKt.decrypt(EncryptedRepeatRule.kt:28)
        at de.tutao.tutanota.alarms.AlarmNotificationEntityKt.decrypt(AlarmNotificationEntity.kt:129)
        at de.tutao.tutanota.alarms.AlarmNotificationsManager.reScheduleAlarms(AlarmNotificationsManager.kt:27)
        at de.tutao.tutanota.push.PushNotificationService.onCreate(PushNotificationService.kt:33)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4187)
        at android.app.ActivityThread.access$1500(ActivityThread.java:238) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1933) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7705) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(R
```

This is line 28
https://github.com/tutao/tutanota/blob/727cefb30169a60f9f7a35d15f02015695d3623d/app-android/app/src/main/java/de/tutao/tutanota/alarms/EncryptedRepeatRule.kt#L28

endValue is not always there?

**Comment by charlag** [comment]
It is indeed not set when `EndType.Never`

https://github.com/tutao/tutanota/blob/727cefb30169a60f9f7a35d15f02015695d3623d/src/calendar/date/CalendarEventViewModel.ts#L1016-L1045

**Comment by ganthern** [comment]
### Test notes
create a repeating, never ending event with a reminder

* [ ] android schedules the notification and it is displayed at the correct time
