### ISSUE TITLE
Uncaught Error: Error UNKNOWN in desktop client

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4349]
We sometimes get reports of uncaught "unknown" errors that don't seem to break anything. We now have a report with logs from a lubuntu 16.04 install that's causing this error because of an incompatible glibc version:

> I just updated the mail app on my copy of Lubuntu 16.04 and am now getting an "unknown" error message each time I start the app. It doesn't cause the app to crash or effect anything but I thought I would give you the message details in case you want to look into it.

```
Feedback v3.98.4 - Error - UNKNOWN - linux

Client: linux
Type: UNKNOWN
Tutanota version: 3.98.4
Timestamp (UTC): Sat, 02 Jul 2022 01:02:36 GMT
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.98.4 Chrome/100.0.4896.160 Electron/18.3.0 Safari/537.36
Error
```

the (probably) relevant log entry of the root cause, printed to main_tutanota.log:

```
2022-07-02T01:02:36.209Z I "error",Error,"Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_tutanoao4Lpb/resources/app.asar.unpacked/desktop/better_sqlite3.node)
   at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
   at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
   at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
   at Module.load (node:internal/modules/cjs/loader:988:32)
   at Module._load (node:internal/modules/cjs/loader:829:12)
   at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
   at Module.require (node:internal/modules/cjs/loader:1012:19)
   at require (node:internal/modules/cjs/helpers:102:18)
   at new nf (/tmp/.mount_tutanoao4Lpb/resources/app.asar/desktop/DesktopMain.js:1:807404)
   at of.openDatabase (/tmp/.mount_tutanoao4Lpb/resources/app.asar/desktop/DesktopMain.js:1:813165)"

```

The actual uncaught error could be a knock-on effect because the error in the log doesn't seem to reach the uncaught error handler.

We could probably catch these and handle the incompatibility a little more gracefully by degrading offline functionality.

**Comment by v011** [comment]
Probably related to #4332, it's the same "UNKNOWN" error message (see the web console error too).

**Comment by 24788329** [comment]
I have the same error at every startup of the desktop client on Pop!_OS:

```
Feedback v3.98.4 - Error - UNKNOWN - linux

 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.98.4
 Timestamp (UTC): Wed, 13 Jul 2022 02:21:53 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.98.4 Chrome/100.0.4896.160 Electron/18.3.0 Safari/537.36
Error
```

**Comment by charlag** [comment]
This happened but only with Flatpak before, once we started compiling in env with older glibc is went away. Did something change now?

**Comment by v011** [comment]
I updated to the v3.98.12 (AppImage), but it still showing me the same error (at every startup too).

```
Feedback v3.98.12 - Error - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.98.12
 Timestamp (UTC): Sun, 17 Jul 2022 16:55:20 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.98.12 Chrome/102.0.5005.148 Electron/19.0.8 Safari/537.36
Error
```

But maybe the cause is not the same. As mentioned in #4332, the error message printed on the Console is :

```
Error while initializing offline cache storage Error: CBOR decode error: found map but not enough entries (got 5 [no key], expected 19)
```

**Comment by charlag** [comment]
Please try to delete the credentials and add them again

**Comment by v011** [comment]
I deleted the credentials and added again (v3.98.12). Now, it's worse, I've an error modal which is visible only for ~1 second, then the login page refreshes, so I can no longer enter in my mailbox on the desktop app (only when "Store password" is checked).

**Comment by charlag** [comment]
I asked few users and it's generally old distros

> UBUNTU 18.04.6 LTS
