### ISSUE TITLE
Fetching wordlibrary does not work on desktop client

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4390]
Try to open passphrase generator

get

```
PasswordGeneratorDialog.ts:21 Fetch API cannot load asset://app/wordlibrary.json. URL scheme "asset" is not supported.
aa @ PasswordGeneratorDialog.ts:21
Logger.ts:90 error TypeError: Failed to fetch
    at aa (PasswordGeneratorDialog.ts:21:22)
    at HTMLDivElement.onclick (PasswordForm.ts:251:39)
    at F.handleEvent (mithril.js:1143:57) TypeError: Failed to fetch
    at aa (asset://app/main-9b49c78c.js:1:7311)
    at HTMLDivElement.onclick (asset://app/settings-fe3df04b.js:1:33712)
    at F.handleEvent (asset://app/app.js:1:25437)
```

**Comment by ganthern** [comment]
closed by a06b12343598ee4810872a0e17b81710379e6f6d
