### ISSUE TITLE
Closing the window while logged in with run in background enabled results in an error

### ISSUE THREAD

**Issue by paw-hub** [tutao/tutanota#4398]
When testing #4337 (desktop app doesn't respect run in background setting), I got a crash on the Linux client when closing the window while logged in.

```
[2022-07-22T09:13:16.547Z] unexpected error: TypeError: Cannot read properties of undefined (reading 'length')
    at AsyncFunction.handler (/home/paw/a/tutanota/build/desktop/DesktopMain.js:48130:62)
(node:409717) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'length')
    at AsyncFunction.handler (/home/paw/a/tutanota/build/desktop/DesktopMain.js:48130:62)
(node:409717) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

Reproduction steps:
1. Log in on the desktop app (without storing credentials)
2. Ensure that running in background is enabled
3. Close the window (without quitting the desktop app)

**Comment by paw-hub** [comment]
It seems this does not occur if you store credentials.
