### ISSUE TITLE
Crash: Exception java.lang.IllegalStateException

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4503]
We're getting a fair amount of illegal state exceptions in android 3.98.19 and 3.98.20:

```
Exception java.lang.IllegalStateException:
  at de.tutao.tutanota.MainActivity.getMimeTypeForUrl (MainActivity.kt:260)
  at de.tutao.tutanota.MainActivity.access$getMimeTypeForUrl (MainActivity.kt:50)
  at de.tutao.tutanota.MainActivity$onCreate$2.shouldInterceptRequest (MainActivity.kt:183)
  at pa.a (chromium-TrichromeWebViewGoogle6432.aab-stable-<snipped>:223)
  at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative (chromium-TrichromeWebViewGoogle6432.aab-stable-<snipped>:34)
```

Only some of them contain our "Unknown extension" error message, but none of them actually contain an extension. We might just not handle empty extensions.

**Comment by charlag** [comment]
This is already fixed few versions ago

**Comment by Hacked4lyf** [comment]
Feedback v3.112.6 - java.lang.IllegalStateException - UNKNOWN - android



 Client: android
 Type: UNKNOWN
 Tutanota version: 3.112.6
 Timestamp (UTC): Sat, 22 Apr 2023 00:05:41 GMT
 User agent:
Mozilla/5.0 (Linux; Android 13; SM-A736B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.153 Mobile Safari/537.36
java.lang.IllegalStateException
 Error message: database not open
Stacktrace: 
java.lang.IllegalStateException: database not open
	at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1954)
	at net.sqlcipher.database.SQLiteDatabase.query(SQLiteDatabase.java:2943)
	at de.tutao.tutanota.offline.AndroidSqlCipherFacade.get(AndroidSqlCipherFacade.kt:90)
	at de.tutao.tutanota.ipc.SqlCipherFacadeReceiveDispatcher.dispatch(SqlCipherFacadeReceiveDispatcher.kt:50)
	at de.tutao.tutanota.ipc.AndroidGlobalDispatcher.dispatch(AndroidGlobalDispatcher.kt:41)
	at de.tutao.tutanota.RemoteBridge.invokeMethod(RemoteBridge.kt:153)
	at de.tutao.tutanota.RemoteBridge.handleMessageFromWeb(RemoteBridge.kt:90)
	at de.tutao.tutanota.RemoteBridge$initMessageChannel$1$onMessage$1.invokeSuspend(RemoteBridge.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Hacked4lyf** [comment]
OK so I'm being hacked for years and I'm trying to figure out how to catch these fraudsters 

This mailbox has a lot of bank fraud evidence 

How can I fox this
