### ISSUE TITLE
[android] Notification service crashing

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#453]
```
    java.lang.RuntimeException: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=de.tutao.tutanota/.push.PushNotificationService (has extras) }: app is in background uid UidRecord{6c86e2d u0a160 TRNB bg:+26m10s2ms idle change:uncached procs:2 seq(659,659,659)}
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=de.tutao.tutanota/.push.PushNotificationService (has extras) }: app is in background uid UidRecord{6c86e2d u0a160 TRNB bg:+26m10s2ms idle change:uncached procs:2 seq(659,659,659)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
        at android.app.ContextImpl.startService(ContextImpl.java:1477)
        at android.content.ContextWrapper.startService(ContextWrapper.java:650)
        at de.tutao.tutanota.push.PeriodicJobRestartService.onStartJob(PeriodicJobRestartService.java:19)
        at android.app.job.JobService$1.onStartJob(JobService.java:71)
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

> While an app is in the foreground, it can create and run both foreground and background services freely. When an app goes into the background, it has a window of several minutes in which it is still allowed to create and use services. At the end of that window, the app is considered to be idle. At this time, the system stops the app's background services, just as if the app had called the services' Service.stopSelf() methods.
> 
> Prior to Android 8.0, the usual way to create a foreground service was to create a background service, then promote that service to the foreground. With Android 8.0, there is a complication; the system doesn't allow a background app to create a background service. For this reason, Android 8.0 introduces the new method startForegroundService() to start a new service in the foreground. After the system has created the service, the app has five seconds to call the service's startForeground() method to show the new service's user-visible notification. If the app does not call startForeground() within the time limit, the system stops the service and declares the app to be ANR.

Thus, before O we can launch the service without foreground notification and restart it periodically.
Since O we can only either run all the time with foreground notification or check notifications once in 15 minutes (I am not sure how long this scheduled window is but I doubt that it's longer than 1-2 minutes).

**Comment by charlag** [comment]
Another hack would be promoting ourselves to the foreground every five minutes but this would annoy everyone I think because of the notification appearing and disappearing.
