### ISSUE TITLE
Switching from search to mail viewer produces a silent error

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4570]
1. Select any email
2. Search for anything and go to the search view
3. Go back to mail view

The line where it happens:

https://github.com/tutao/tutanota/blob/4b767be3c7daac31c0e143b5ab643d05b15a910e/src/mail/view/MailViewer.ts#L182-L185

```
mithril.js:1240 TypeError: Node is currently being rendered to and thus is locked.
    at mithril.js:1208:10
    at Function.sync (mithril.js:1239:10)
    at MailViewer.ts:185:14
    at Stream.stream71._map (stream.js:55:50)
    at Stream.stream71.map (stream.js:63:17)
    at MailViewer.setViewModel (MailViewer.ts:183:67)
    at new MailViewer (MailViewer.ts:138:8)
    at initComponent (mithril.js:418:103)
    at createComponent (mithril.js:427:3)
    at createNode (mithril.js:342:8)

mithril.js:1240 TypeError: Cannot read properties of undefined (reading 'view')
    at initComponent (mithril.js:408:25)
    at createComponent (mithril.js:427:3)
    at createNode (mithril.js:342:8)
    at createNodes (mithril.js:326:5)
    at updateNodes (mithril.js:538:45)
    at mithril.js:1221:4
    at sync (mithril.js:1239:10)
    at mithril.js:1249:5
```

## Test notes
 - [ ] Search
   - [ ] From mail view
   - [ ] From contacts view
   - [ ] From search
   - [ ] Switching between search parameters
   - [ ] Opening different items in search
   - [ ] From user list
   - [ ] From group list
   - [ ] On mobile: mail
   - [ ] On mobile: contacts
   - [ ] On mobile: switching between types

**Comment by charlag** [comment]
This might be a dev bug
