### ISSUE TITLE
Uncaught ProgrammingError: Trying to update MailViewerViewModel with unrelated email

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4613]
Repro steps unclear

```
Client: linux
Tutanota version: 3.100.2
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.100.2 Chrome/102.0.5005.167 Electron/19.0.17 Safari/537.36
ProgrammingError
Error message: Trying to update MailViewerViewModel with unrelated email ["Lnjtsoe--V-1","NCeRLpC----2"] ["Lnjtsoe--V-1","NCeKq87--J-2"] /mail/Lnjtsoe--V-1/NCeKq87--J-2
Stacktrace:
ProgrammingError: Trying to update MailViewerViewModel with unrelated email ["Lnjtsoe--V-1","NCeRLpC----2"] ["Lnjtsoe--V-1","NCeKq87--J-2"] /mail/Lnjtsoe--V-1/NCeKq87--J-2
at Gi.updateMail (asset://app/mail-view-0e1a4669.js:1:28857)
at MailView.entityEventReceived (asset://app/mail-view-0e1a4669.js:1:75984)
at async asset://app/common-min-2dc6ef26.js:1:17537
```

Also happens in firefox on windows 

## Test notes
- [ ] Try to reproduce
- Check test notes from #4896

**Comment by charlag** [comment]
Found the root cause
In `MailView` there is an `entityEventReceived()` which would try to load and insert the updated email into `MailViewer` but the loading is async and the mail viewer could be changed while the mail is being loaded.
It will be fixed with #4896
