### ISSUE TITLE
Migration doesn't work correctly

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4696]
```
SqliteError: table element_entities has no column named ownerGroup
    at hm.Bh [as prepare] (/tmp/.mount_tutanoRG11tX/resources/app.asar/desktop/DesktopMain.js:13:123317)
    at vm.run (/tmp/.mount_tutanoRG11tX/resources/app.asar/desktop/DesktopMain.js:13:136510)
    at Ih.run (/tmp/.mount_tutanoRG11tX/resources/app.asar/desktop/DesktopMain.js:13:118943)
    at Hy.dispatch (/tmp/.mount_tutanoRG11tX/resources/app.asar/desktop/DesktopMain.js:1:815169)
    at Zy.dispatch (/tmp/.mount_tutanoRG11tX/resources/app.asar/desktop/DesktopMain.js:1:817358)
    at ipc (/tmp/.mount_tutanoRG11tX/resources/app.asar/desktop/DesktopMain.js:1:808016)
    at an.handleMessage (/tmp/.mount_tutanoRG11tX/resources/app.asar/desktop/DesktopMain.js:1:44416)
    at /tmp/.mount_tutanoRG11tX/resources/app.asar/desktop/DesktopMain.js:1:43531
    at /tmp/.mount_tutanoRG11tX/resources/app.asar/desktop/DesktopMain.js:1:800553
    at node:electron/js2c/browser_init:189:579
```

#2874

**Comment by ganthern** [comment]
does this need test notes or a not-testable label?

**Comment by charlag** [comment]
it's okay to just test #4697
