### ISSUE TITLE
ProgrammingError: Already opened database!

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4866]
**Describe the bug**

It seems that we have some invalid state for the offline DB that leads to it being opened more than once in some cases:

>  Can't access my messages at all on Mac (iOS works ok), Tutanota always tells me I'm offline. My contacts, settings and calendar view works as intended. Tried downloading the app again, no help there.

```
Client: darwin
Type: PREMIUM
Tutanota version: 3.105.9
Timestamp (UTC): Mon, 19 Dec 2022 10:57:22 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.105.9 Chrome/108.0.5359.62 Electron/22.0.0 Safari/537.36
ProgrammingError
Error message: Already opened database!
Stacktrace:
ProgrammingError: Already opened database!
at Hh.openDb (/Applications/Tutanota [Desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:13:118654](http://desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:13:118654))
at sf.dispatch (/Applications/Tutanota [Desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:1:817470](http://desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:1:817470))
at df.dispatch (/Applications/Tutanota [Desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:1:819824](http://desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:1:819824))
at ipc (/Applications/Tutanota [Desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:1:810482](http://desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:1:810482))
at cn.handleMessage (/Applications/Tutanota [Desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:1:44668](http://desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:1:44668))
at /Applications/Tutanota [Desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:1:43783](http://desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:1:43783)
at /Applications/Tutanota [Desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:1:803019](http://desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:1:803019)
at node:electron/js2c/browser_init:2:97574
at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81087)
at EventEmitter.emit (node:events:513:28)
```

**Additional context**
The workaround for this seems to be to delete all stored credentials and logging back in.

**Comment by ganthern** [comment]
I was able to reproduce this by downgrading the desktop client across a offlineDb migration, in this case the systemFolders -> folders rename.

The client tries to log in, sees an invalid property name on the instance and seems to bail out without closing the database. if you try to log in again with the same credentials, above error will be thrown.

**Comment by charlag** [comment]
We probably don't need the complete downgrade but throwing away the db might not be too bad.
