### ISSUE TITLE
Uncaught InternalServerError in filedataservice: TimeoutException

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4878]
We're regularly receiving reports of internal server errors with an underlying TimeoutException:

```
Client: linux
Type: FREE
Tutanota version: 3.105.4
Timestamp (UTC): Sun, 04 Dec 2022 14:23:06 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.105.4 Chrome/102.0.5005.167 Electron/19.1.8 Safari/537.36
InternalServerError
Error message: 500: NISW9dv----9 | PUT /rest/tutanota/filedataservice
Stacktrace:
InternalServerError: 500: NISW9dv----9 | PUT /rest/tutanota/filedataservice
at cO (asset://app/common-min-29a182a8.js:1:7864)
at l.onload (asset://app/worker.js:12:100057)
```

```
E 15:22:49.979 sys [RootHandler.java](http://roothandler.java) MVFsFXJ----2 NISW9dv----9 ====> Uncaught exception: Idle timeout expired: 20000/20000 ms - PUT /rest/tutanota/filedataservice/fileDataId=NISW4_J----9 
java.util.concurrent.TimeoutException: Idle timeout expired: 20000/20000 ms
```

We generally don't catch InternalServerErrors but Infra would be open to changing this to a `408 Request Timeout` Http response or similar. We should discuss how to handle that, because at the moment, the client can't handle 408.

**Comment by mpfau** [comment]
FileDataService will not be used anymore in two to four weeks so we won't fix this anymore...
