### ISSUE TITLE
Uncaught Error: CBOR decode error: found map but not enough entries (got 5 [no key], expected 19)

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4947]
Reported since 3.100.2 on android, windows, linux. Got about a dozen reports from 4 users.

Older report:

> no calendar access. error from launch. 

Newer ones: 
> email fails to sync

Stack trace:

```
Client: win32
Type: PREMIUM
Tutanota version: 3.106.5
Timestamp (UTC): Fri, 06 Jan 2023 13:50:34 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.106.5 Chrome/108.0.5359.62 Electron/22.0.0 Safari/537.36
Error
Error message: CBOR decode error: found map but not enough entries (got 5 [no key], expected 19)
Stacktrace:
Error: CBOR decode error: found map but not enough entries (got 5 [no key], expected 19)
at asset://app/common-70d9c228.js:1:333626
at vr (asset://app/common-70d9c228.js:1:333982)
at T (asset://app/common-70d9c228.js:1:976)
at Zl.deserialize (asset://app/worker.js:17:6880)
at Zl.get (asset://app/worker.js:12:155816)
at async Ia._loadMultiple (asset://app/worker.js:1:18924)
at async asset://app/common-min-ad5cd377.js:1:17797
```

The error message itself is always exactly the same.

**Comment by ganthern** [comment]
may be related: 
https://github.com/tutao/tutanota/issues/4332

**Comment by charlag** [comment]
Is not reported anymore

**Comment by v011** [comment]
It seems related to #4332 .
