### ISSUE TITLE
Uncaught RangeError: The number NaN cannot be converted to a BigInt because it is not an integer

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4958]
Some few users have this problem which prevents them from using the app with saved credentials (it happens on any device for their account).

```
Client: android
Type: PREMIUM
Tutanota version: 3.106.4
Timestamp (UTC): Mon, 09 Jan 2023 17:39:51 GMT
User agent:
Mozilla/5.0 (Linux; Android 13; Pixel 4a Build/TQ1A.230105.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36
RangeError
Error message: The number NaN cannot be converted to a BigInt because it is not an integer
Stacktrace:
RangeError: The number NaN cannot be converted to a BigInt because it is not an integer
at BigInt (<anonymous>)
at ha (https://assets.tutanota.com/common-b391a7fd.js:1:320318)
at [Array.Ca](http://array.ca/) (https://assets.tutanota.com/common-b391a7fd.js:1:320024)
at Ar (https://assets.tutanota.com/common-b391a7fd.js:1:332046)
at Ar (https://assets.tutanota.com/common-b391a7fd.js:1:332014)
at Ar (https://assets.tutanota.com/common-b391a7fd.js:1:332014)
at Ar (https://assets.tutanota.com/common-b391a7fd.js:1:332014)
at Ar (https://assets.tutanota.com/common-b391a7fd.js:1:332014)
at _r (https://assets.tutanota.com/common-b391a7fd.js:1:332397)
at eK (https://assets.tutanota.com/common-b391a7fd.js:1:13524)
```
**Notes:**
* The function that fails is `cborg.encode()` which is called when setting metadata and when serializing instances/entities.
* It's not related to Blobs or Premium/Free

**Comment by bedhub** [comment]
Catch error and throw a new one with more information about the entity that is causing the problem.

**Comment by v011** [comment]
Related to #4332 .

**Comment by charlag** [comment]
Did not see it reported
