### ISSUE TITLE
Uncaught ImportError: Could not save events.

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4959]
On all clients since ~Dec 14: 

```
Client: win32
Type: PREMIUM
Tutanota version: 3.106.5
Timestamp (UTC): Mon, 09 Jan 2023 23:08:37 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.106.5 Chrome/108.0.5359.62 Electron/22.0.0 Safari/537.36
ImportError
Error message: Could not save events.
Number of failed imports: 1
Number of failed imports: undefined
Number of failed imports: undefined
Number of failed imports: undefined
Stacktrace:
ImportError: Could not save events.
Number of failed imports: 1
at ml._saveCalendarEvents (asset://app/worker.js:12:123638)
at async ml.saveCalendarEvent (asset://app/worker.js:12:123974)
```

```
Client: android
Type: FREE
Tutanota version: 3.106.4
Timestamp (UTC): Thu, 29 Dec 2022 15:04:44 GMT
User agent:
Mozilla/5.0 (Linux; Android 13; SM-A528B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36
ImportError
Error message: Could not save events.
Number of failed imports: 1
Number of failed imports: undefined
Stacktrace:
ImportError: Could not save events.
Number of failed imports: 1
at ml._saveCalendarEvents (https://assets.tutanota.com/worker.js:12:123638)
at async ml.saveCalendarEvent (https://assets.tutanota.com/worker.js:12:123974)
```

**Comment by ganthern** [comment]
Turns out this can happen when you open a shared calendar

bed:
> I justed opened the calendar

**Comment by charlag** [comment]
> Übernimmt keine Änderung im Kalender

```
Client: Browser
Type: PREMIUM
Tutanota version: 3.108.12
Timestamp (UTC): Mon, 06 Feb 2023 19:52:04 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 OPR/94.0.0.0
ImportError
Error message: Could not save events.
Number of failed imports: 1
Number of failed imports: undefined
Stacktrace:
ImportError: Could not save events.
Number of failed imports: 1
at kl._saveCalendarEvents (https://mail.tutanota.com/worker.js:12:128296)
at async kl.saveCalendarEvent (https://mail.tutanota.com/worker.js:12:128632)
```

**Comment by ganthern** [comment]
I have a reproduction: 
* create an account with a business feature for calendar invites
* create another account
* invite the second account with an event in the private calendar of the first account
* with the second account on android, click "yes" in the invite
* that takes a while for some reason, but the banner doesn't go away right away
* clicking "Yes" repeatedly will re-trigger the accept and lead to LockedErrors, PreconditionFailedErrors and an import error at the end.

**Comment by charlag** [comment]
Seems like what we get in all of those cases is `Number of failed imports: 1 First error: PreconditionFailedError: 412: db.exists`. Seems like we miss de-duplicating `UID` somewhere?

**Comment by ganthern** [comment]
This is still happening regularly:

> computer was off-line overnight. IIRC, the error message was already appearing when I looked this morning. Got online. Tried replying "Yes" to updated event notification a few times, with error appearing each time. (I might have already replied last night.)

```
Client: Browser
Type: PREMIUM
Tutanota version: 3.112.6
Timestamp (UTC): Sat, 15 Apr 2023 15:09:57 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
ImportError
Error message: undefined
Number of failed imports: undefined First error: Could not save events.
Number of failed imports: 1 First error: PreconditionFailedError: 412: db.exists | POST /rest/tutanota/calendarevent/MhV982y--B-2
Stacktrace:
ImportError: Could not save events.
Number of failed imports: 1 First error: PreconditionFailedError: 412: db.exists | POST /rest/tutanota/calendarevent/MhV982y--B-2
at CalendarFacade._saveCalendarEvents (https://mail.tutanota.com/worker-lazy-b8c3966a.js:1:39472)
at async CalendarFacade.saveCalendarEvent (https://mail.tutanota.com/worker-lazy-b8c3966a.js:1:39813)
```
