### ISSUE TITLE
Uncaught NotFoundError on CalendarEventUpdate DELETE

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4964]
About ~2 reports per day:

```
Client: android
Type: PREMIUM
Tutanota version: 3.106.5
Timestamp (UTC): Tue, 10 Jan 2023 16:47:31 GMT
User agent:
Mozilla/5.0 (Linux; Android 9; SM-G955F Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36
NotFoundError
Error message: 404: | DELETE /rest/tutanota/calendareventupdate/MnPp0sF--k-2/NLML9HI--3-9
Stacktrace:
NotFoundError: 404: | DELETE /rest/tutanota/calendareventupdate/MnPp0sF--k-2/NLML9HI--3-9
at cP (https://assets.tutanota.com/common-min-ad5cd377.js:1:7575)
at l.onload (https://assets.tutanota.com/worker.js:12:100956)
```

This one happened after clicking the notification, cancelling the biometric prompt on a login screen with two saved credentials and bringing the app back to foreground after a few hours to complete the login:

```
Clicked on a calendar Event push notification. Left the app when I was asked to login and returned a couple hours later to the app. Error was shown after logging in...

Client: android
Type: PREMIUM
Tutanota version: 3.106.5
Timestamp (UTC): Mon, 09 Jan 2023 21:12:46 GMT
User agent:
Mozilla/5.0 (Linux; Android 13; SM-A528B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36
NotFoundError
Error message: 404: | DELETE /rest/tutanota/calendareventupdate/ME_w8kp----2/NL6Kf6L--3-9
Stacktrace:
NotFoundError: 404: | DELETE /rest/tutanota/calendareventupdate/ME_w8kp----2/NL6Kf6L--3-9
at cP (https://assets.tutanota.com/common-min-ad5cd377.js:1:7575)
at l.onload (https://assets.tutanota.com/worker.js:12:100956)
```

and ios:

```
Client: ios
Type: PREMIUM
Tutanota version: 3.106.4
Timestamp (UTC): Thu, 05 Jan 2023 20:52:51 GMT
User agent:
Mozilla/5.0 (iPhone; CPU iPhone OS 16_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
NotFoundError
Error message: 404: | DELETE /rest/tutanota/calendareventupdate/MTpGaoV--g-2/NL1CTJA--3-9
Stacktrace:
o@asset://app/common-min-b40ebf9b.js:1:12207
Fe@asset://app/common-min-b40ebf9b.js:1:28486
cP@asset://app/common-min-b40ebf9b.js:1:7581
@asset://app/worker.js:12:100957
```

### Test Notes
test this on ios, android and linux

* [ ] syncing all calendar events after login still works (new credentials, login, go offline after sync, look at calendar)
* [ ] syncing them after offline login and going online still works
* [ ] alarms are scheduled after logging in
* [ ] calendar updates are still applied for other clients (create calendar, delete calendar, create event, move event, delete event, add alarm)
* [ ] accepting, cancelling and updating events from ICS files still works (for events where an internal recipient is invited, but doesn't have the calendar shared)

**Comment by charlag** [comment]
This is still reported fairly often.

Probably happens here:

https://github.com/tutao/tutanota/blob/03cb9e04ef50a3831ea21dac9272b95531e7ad21/src/calendar/model/CalendarModel.ts#L287

we should:

 * not process updates if we are not the leader client
 * simply catch not found errors

**Comment by charlag** [comment]
Probably happens when two clients try to process calendar updates in parallel.

Otherwise maybe happens when we try to synchronize after logging in but we are not sure why yet.

**Comment by ganthern** [comment]
we got a report from the linux client:

```
Client: linux
Type: PREMIUM
Tutanota version: 3.109.4
Timestamp (UTC): Wed, 22 Feb 2023 09:50:05 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.109.4 Chrome/108.0.5359.215 Electron/22.2.1 Safari/537.36
NotFoundError
Error message: 404: NOsWvNN--N-9 | DELETE /rest/tutanota/calendareventupdate/ME_Zc8H----2/NOsQiLg--3-9
Stacktrace:
NotFoundError: 404: NOsWvNN--N-9 | DELETE /rest/tutanota/calendareventupdate/ME_Zc8H----2/NOsQiLg--3-9
at cS (asset://app/common-min-3d2134e7.js:1:7350)
at l.onload (asset://app/worker.js:12:106152)
```
