### ISSUE TITLE
Uncaught ProgrammingError: Batch does not have events for entityId

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4987]
Reported on android, Browsers and windows since 3.105.9:

```
Received error while logging into Windows desktop client.


Client: win32
Type: FREE
Tutanota version: 3.106.5
Timestamp (UTC): Mon, 16 Jan 2023 05:27:56 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.106.5 Chrome/108.0.5359.62 Electron/22.0.0 Safari/537.36
ProgrammingError
Error message: Batch does not have events for W_lS774AAwADYW5BO6DAAYAK
Stacktrace:
ProgrammingError: Batch does not have events for W_lS774AAwADYW5BO6DAAYAK
at ya (asset://app/worker.js:1:4847)
at ma._optimizingAddEvents (asset://app/worker.js:1:5657)
at ma.add (asset://app/worker.js:1:5221)
at ma.addBatches (asset://app/worker.js:1:5102)
at Nc.addBatchesToQueue (asset://app/worker.js:12:52700)
at Yc._loadNewEntities (asset://app/worker.js:12:73131)
at async Yc.init (asset://app/worker.js:12:67647)
```

```
Client: android
Type: PREMIUM
Tutanota version: 3.106.5
Timestamp (UTC): Tue, 10 Jan 2023 18:56:07 GMT
User agent:
Mozilla/5.0 (Linux; Android 11; SM-A505FN Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36
ProgrammingError
Error message: Batch does not have events for YOPSkunAAAADYWb-shSAAAAK
Stacktrace:
ProgrammingError: Batch does not have events for YOPSkunAAAADYWb-shSAAAAK
at ya (https://assets.tutanota.com/worker.js:1:4847)
at ma._optimizingAddEvents (https://assets.tutanota.com/worker.js:1:5657)
at ma.add (https://assets.tutanota.com/worker.js:1:5221)
at ma.addBatches (https://assets.tutanota.com/worker.js:1:5102)
at Nc.addBatchesToQueue (https://assets.tutanota.com/worker.js:12:52700)
at Yc._loadNewEntities (https://assets.tutanota.com/worker.js:12:73131)
at async Yc.init (https://assets.tutanota.com/worker.js:12:67647)
```

**Comment by charlag** [comment]
We do not observe this for 3.108.12
