### ISSUE TITLE
Opening from external apps results in an immediate crash due to uncaught exception.

### ISSUE THREAD

**Issue by 4f77616973** [tutao/tutanota#5002]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
I tried implementing the ACRA library in an app I was writing recently. ACRA lets you generate a crash log when your app crashes, which you can file as a bug report by emailing it to an email address. This functionality was tested and works with the Gmail app, Protonmail and Yahoo Mail but it causes Tutanota to crash with the following exception:

```
Process: de.tutao.tutanota, PID: 9635
java.lang.NullPointerException: clipData.description.getMimeType(0) must not be null
at de.tutao.tutanota.MainActivity.share(MainActivity.kt:586)
at de.tutao.tutanota.MainActivity.access$share(MainActivity.kt:67)
at de.tutao.tutanota.MainActivity$handleIntent$1.invokeSuspend(MainActivity.kt:414)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:75)
at androidx.lifecycle.DispatchQueue.resume(DispatchQueue.kt:54)
at androidx.lifecycle.LifecycleController$observer$1.onStateChanged(LifecycleController.kt:40)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostCreated(ReportFragment.java:178)
at android.app.Activity.dispatchActivityPostCreated(Activity.java:1386)
at android.app.Activity.performCreate(Activity.java:8315)
at android.app.Activity.performCreate(Activity.java:8284)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7872)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**To Reproduce**
1. Make sure Tutanota is installed and is the default email client.
2. Use the ACRA example app [from here](https://github.com/ACRA/acra/tree/master/examples/acra-basic-kotlin-example).
3. Perform an action that causes the app to crash.
4. Observe the crash upon Tutanota's launch.

**Expected behavior**
There must be exception handling for situations like these that either:
1. Warns you that the clipboard is empty and that Tutanota didn't receive any data from the app that launched it and lets you compose a new email,
2. An empty new email screen is opened rather than the app quitting, or
3. Alert dialog stating that such an operation isn't supported by Tutanota.
4. Use similar methodologies that Protonmail or Gmail use to handle this issue.

**Screenshots**
_(None due to immediate crash)_

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6 (oriole)
 - OS: Android 13
 - Version 3.106.5

**Additional context**

**Comment by ganthern** [comment]
Thank you for this detailed report, we'll take a look at this.
