### ISSUE TITLE
Uncaught Error: Illegal key length: 0 (expected: 256)

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5006]
Happens to linux users that use kwallet for secret storage:

> yes, we had issues with kwallet not providing or incorrectly implementing the org.freedesktop.secrets DBus API that we require to store the key that encrypts the stored credentials. The client will generate the key, store it and then get a zero-length key back when asking for it on next startup.
> 
> The gnome-keyring package usually works out of the box for this purpose, but I understand that installing it is not always an option. We have some information about this in our FAQ at https://tutanota.com/de/faq/#secretstorage and in our issue tracker (You should find relevant discussions if you search for KDE or Kwallet in the closed and open issues).

```
Client: linux
Type: FREE
Tutanota version: 3.105.9
Timestamp (UTC): Mon, 19 Dec 2022 09:33:35 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.105.9 Chrome/108.0.5359.62 Electron/22.0.0 Safari/537.36
Error
Error message: Illegal key length: 0 (expected: 256)
Stacktrace:
Error: Illegal key length: 0 (expected: 256)
at ti (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:1:383863)
at Xn (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:1:382991)
at Object.aes256Encrypt (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:1:710037)
at Object.aesEncryptObject (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:13:141693)
at Be._setEncryptedVar (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:1:23244)
at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Be.setVar (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:1:23504)
at async Vy.storePushIdentifierLocally (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:1:808083)
at async ipc (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:1:810473
```

**Comment by charlag** [comment]
Another user reporting the same issue with KWallet version 23.08.2 (KDE 5.27.8), switching to KeepassXC helped
