### ISSUE TITLE
Uncaught SqliteError: duplicate column name: ownerGroup

### ISSUE THREAD

**Issue by nokhub** [tutao/tutanota#5027]
**To Reproduce**
1. Install current version (3.108.3)
2. store credentials and save some entities
3. close and delete app image
4. install client that is older than 3.105.9
5. error occurs will client tries to automatically login with stored credentials
6. when logging into the new client again, the error still occurs

```
2023-01-23T09:27:28.420Z I "error",SqliteError,"SqliteError: duplicate column name: ownerGroup
    at km.em [as prepare] (/tmp/.mount_desktolchqVj/resources/app.asar/desktop/DesktopMain.js:13:123364)
    at Km.run (/tmp/.mount_desktolchqVj/resources/app.asar/desktop/DesktopMain.js:13:136557)
    at Hh.run (/tmp/.mount_desktolchqVj/resources/app.asar/desktop/DesktopMain.js:13:118990)
    at sf.dispatch (/tmp/.mount_desktolchqVj/resources/app.asar/desktop/DesktopMain.js:1:817634)
    at df.dispatch (/tmp/.mount_desktolchqVj/resources/app.asar/desktop/DesktopMain.js:1:819823)
    at ipc (/tmp/.mount_desktolchqVj/resources/app.asar/desktop/DesktopMain.js:1:810481)
    at cn.handleMessage (/tmp/.mount_desktolchqVj/resources/app.asar/desktop/DesktopMain.js:1:44668)
    at /tmp/.mount_desktolchqVj/resources/app.asar/desktop/DesktopMain.js:1:43783
    at /tmp/.mount_desktolchqVj/resources/app.asar/desktop/DesktopMain.js:1:803018
    at node:electron/js2c/browser_init:2:97574"
2023-01-23T09:27:28.421Z I "Unknown error",SqliteError
2023-01-23T09:27:30.154Z I "Registering for push notifications"
2023-01-23T09:27:30.243Z I "error",InternalServerError
 Error message: 500: NMSx31Z----0 | GET /rest/tutanota/mail/NE03M7K-0k-0,"InternalServerError: 500: NMSx31Z----0 | GET /rest/tutanota/mail/NE03M7K-0k-0
    at cP (asset://app/common-min-021d8546.js:1:7953)
    at l.onload (asset://app/worker.js:12:100057)"
```

**Comment by ganthern** [comment]
I think this is not worth to fix until we get significant reports of the error
