### ISSUE TITLE
Uncaught TypeError: e is not iterable

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5066]
case [3] of https://github.com/tutao/tutanota/issues/5015 is back, though it seems to be rare:

> I clicked on an email after updating.
> 
> It actually did two updates in a row.

```
Client: win32
Type: PREMIUM
Tutanota version: 3.108.10
Timestamp (UTC): Mon, 30 Jan 2023 16:20:53 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.108.10 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36
TypeError
Error message: e is not iterable
Stacktrace:
TypeError: e is not iterable
at Pa (asset://app/worker.js:1:24525)
at Na.load (asset://app/worker.js:1:17359)
at asset://app/common-540ca3cd.js:1:13026
at Object.handleMessage (asset://app/common-540ca3cd.js:1:17560)
at asset://app/common-540ca3cd.js:1:16813
at _worker.onmessage (asset://app/common-540ca3cd.js:1:16382)
```

> the location where this is thrown is in expandId (the Id is not a string but also not an array, so the destructure fails): https://github.com/tutao/tutanota/blob/c327a9d82f20e2288cf45bb0de77b7c427b16127/src/api/worker/rest/DefaultEntityRestCache.ts#L756-L769

**Comment by charlag** [comment]
We should add more logging here, assert that id is an array and throw a message with type and string representation of id otherwise. id is probably undefined but we are unsure on why yet.
