### ISSUE TITLE
Uncaught Error: cannot delete mails in folder with type 0

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5072]
> error when deleting a folder in the trash

```
Client: linux
Type: PREMIUM
Tutanota version: 3.108.10
Timestamp (UTC): Wed, 01 Feb 2023 09:51:57 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.108.10 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36
Error
Error message: Cannot delete mails in folder MIRevG3--s-2,NJq4H5t----9 with type 0
Stacktrace:
Error: Cannot delete mails in folder MIRevG3--s-2,NJq4H5t----9 with type 0
at MailView.finallyDeleteAllMailsInSelectedFolder (asset://app/mail-view-c4d0a3b4.js:1:68914)
at [Object.click](http://object.click/) (asset://app/mail-view-c4d0a3b4.js:1:44166)
```

## Test Notes
- [ ] For the Trash and Spam folder, Selecting "Clear Folder" that appears at the top of the mail list clears all mails from the folder
- [ ] For subfolders of Trash or Spam, Selecting "Clear Folder" that appears at the top of the mail list clears all mails from and deletes the folder

**Comment by jernejp21** [comment]
If it helps, I got the same error on Windows. It happens if you try to Clear folder in a folder located in Trash. If you delete like on picture below, there is no error message.

![image](https://user-images.githubusercontent.com/61543115/216475385-5309fde6-6f03-4297-8744-39f9ab11148e.png)

```
Client: win32
Type: PREMIUM
Tutanota version: 3.108.10
Timestamp (UTC): Thu, 02 Feb 2023 23:30:56 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.108.10 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36
Error
Error message: Cannot delete mails in folder LWon_cN--N-1,NJpokCK----9 with type 0
Stacktrace:
Error: Cannot delete mails in folder LWon_cN--N-1,NJpokCK----9 with type 0
at MailView.finallyDeleteAllMailsInSelectedFolder (asset://app/mail-view-c4d0a3b4.js:1:68914)
at Object.click (asset://app/mail-view-c4d0a3b4.js:1:44166)
```

**Comment by charlag** [comment]
Ah, thank you!
