### ISSUE TITLE
LockedError is not handled when updating contacts

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5093]
```
Tried to update phone number


Client: android
Tutanota version: 3.106.4
LockedError
Error message: 423: | PUT /rest/tutanota/contact/NLuiuaE--B-9/NNV7_cb-2N-9
Stacktrace:
LockedError: 423: | PUT /rest/tutanota/contact/NLuiuaE--B-9/NNV7_cb-2N-9
at cP (https://assets.tutanota.com/common-min-b40ebf9b.js:1:7680)
at l.onload (https://assets.tutanota.com/worker.js:12:100956)
```

## Test Notes
* [ ] hitting ctrl + S twice in quick succession will not send two put/post requests with updated/new contacts
* [ ] clicking save twice won't either
* [ ] updating any of the fields still works
* [ ] the shared password field on contacts with external mail addresses is concealed in the editor
* [ ] the shared password can be updated from the contact editor and from the mail editor

**Comment by charlag** [comment]
Probably a double tap on save button, prevent parallel save
