### ISSUE TITLE
Uncaught TypeError:  Cannot set properties of undefined (setting 'mobileMultiSelectionActive')

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5154]
repro: On mobile any action on emails (delete, move, toggle read status) in multi-selection view leads to an error

```
Client: android
Type: PREMIUM
Tutanota version: 3.109.4
Timestamp (UTC): Tue, 21 Feb 2023 12:06:38 GMT
User agent:
Mozilla/5.0 (Linux; Android 12; GM1913 Build/SKQ1.211113.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.79 Mobile Safari/537.36
TypeError
Error message: Cannot set properties of undefined (setting 'mobileMultiSelectionActive')
Stacktrace:
TypeError: Cannot set properties of undefined (setting 'mobileMultiSelectionActive')
at selectNone (https://assets.tutanota.com/gui-base-c5e11ae2.js:1:148877)
at https://assets.tutanota.com/mail-view-a7ce8f7d.js:1:47009
at [Object.click](http://object.click/) (https://assets.tutanota.com/gui-base-c5e11ae2.js:1:104193)
at HTMLButtonElement.onclick (https://assets.tutanota.com/gui-base-c5e11ae2.js:1:107029)
at D.handleEvent (https://assets.tutanota.com/app.js:1:25731)
```

> Just wanted to delete a message

```
Client: android
Type: PREMIUM
Tutanota version: 3.109.4
Timestamp (UTC): Wed, 22 Feb 2023 07:51:16 GMT
User agent:
Mozilla/5.0 (Linux; Android 10; ELE-L29 Build/HUAWEIELE-L29; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/101.0.4951.61 Mobile Safari/537.36
TypeError
Error message: Cannot set properties of undefined (setting 'mobileMultiSelectionActive')
Stacktrace:
TypeError: Cannot set properties of undefined (setting 'mobileMultiSelectionActive')
at selectNone (https://assets.tutanota.com/gui-base-c5e11ae2.js:1:148877)
at https://assets.tutanota.com/mail-view-a7ce8f7d.js:1:47332
at https://assets.tutanota.com/mail-view-a7ce8f7d.js:1:3495
```

## Test Notes:
* [ ] on mobile go to search view
* [ ] type in some term which results in multiple search results
* [ ] select multiple results
  * [ ] delete them -> works
  * [ ] permanently delete mails that are already in the trash folder -> shows prompt and works
  * [ ] move folders to some other folder -> works
  * [ ] toggle read / unread status -> works
* [ ] check that the selection is removed after each operation

### Regressions:
* [ ] all of the above mentioned works on desktop and in browser as well
* [ ] all of the above mentioned works in normal mail list (not search) as well, on desktop, browser and mobile

**Comment by ganthern** [comment]
> Selected several emails matching the word “wishlist.” Attempted to delete the emails that I selected. Then I received this error after pressing the trash can icon.


```
Client: ios
Type: PREMIUM
Tutanota version: 3.109.4
Timestamp (UTC): Thu, 23 Feb 2023 04:11:44 GMT
User agent:
Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
TypeError
Error message: undefined is not an object (evaluating 'this.mobileMultiSelectionActive=!1')
Stacktrace:
selectNone@asset://app/gui-base-c5e11ae2.js:1:148850
@asset://app/mail-view-a7ce8f7d.js:1:3496
promiseReactionJob@[native code]
```
