### ISSUE TITLE
Uncaught Error: AssertNotNull failed : System folder of type does not exist!

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5155]
One report:

```
Client: win32
Type: PREMIUM
Tutanota version: 3.109.4
Timestamp (UTC): Tue, 21 Feb 2023 12:20:01 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.109.4 Chrome/108.0.5359.215 Electron/22.2.1 Safari/537.36
Error
Error message: AssertNotNull failed : System folder of type does not exist!
Stacktrace:
Error: AssertNotNull failed : System folder of type does not exist!
at l (asset://app/common-min-3d2134e7.js:1:11445)
at c (asset://app/common-16096e64.js:1:7281)
at asset://app/mail-view-a7ce8f7d.js:1:65381
```

This should only be possible for external / contact form mailboxes, but seems to have happened to a premium user.
Logs suggest this happened shortly after login.

main:
```
2023-02-21T12:20:00.446Z I "worker init time (ms):",159
2023-02-21T12:20:01.410Z I "removed topmost modal component"
2023-02-21T12:20:01.445Z I "Registering for push notifications"
2023-02-21T12:20:01.667Z I "error",?,"Error: AssertNotNull failed : System folder of type does not exist!\n    at l (asset://app/common-min-3d2134e7.js:1:11445)\n    at c (asset://app/common-16096e64.js:1:7281)\n    at asset://app/mail-view-a7ce8f7d.js:1:65381"
```

worker:
```
2023-02-21T12:20:01.235Z I "_initIndexer after log in"
2023-02-21T12:20:01.243Z I "ws connect reconnect:",false,"state:","terminated"
2023-02-21T12:20:01.273Z I "CalendarEvent list M5DD6G5--3-2 has 0 events"
2023-02-21T12:20:01.277Z I "CalendarEvent list M5DD6G5--7-2 has 3 events"
2023-02-21T12:20:01.347Z I "{\"indexingTime\":0,\"storageTime\":0,\"preparingTime\":0,\"mailcount\":0,\"storedBytes\":0,\"encryptionTime\":0,\"writeRequests\":0,\"largestColumn\":0,\"words\":0,\"indexedBytes\":0,\"downloadingTime\":0}","total time: ",0
2023-02-21T12:20:01.383Z I "ws open state:","automatic"
2023-02-21T12:20:01.384Z I "New leader status set:",true
```

desktop:
<details>
<summary> desktop log </summary>
<pre>
2023-02-21T12:19:47.871Z I "failed to detect locale"
2023-02-21T12:19:47.928Z I "the monkey has been patched"
2023-02-21T12:19:48.335Z I "version:  ","3.109.4"
2023-02-21T12:19:48.350Z I "config up to date"
2023-02-21T12:19:48.354Z I "resolving key...","tutanota-vault"
2023-02-21T12:19:48.386Z I "scheduling to check sse in",1,"seconds"
2023-02-21T12:19:48.387Z I "[ApplicationWindow]","webAssetsPath: ","C:\\Program Files\\Tutanota Desktop\\resources\\app.asar"
2023-02-21T12:19:48.445Z I "[ApplicationWindow]","getting dictionaries from:","https://mail.tutanota.com/desktop/dictionaries/"
2023-02-21T12:19:48.451Z I "default mailto handler:",false
2023-02-21T12:19:48.451Z I "Webapp ready"
2023-02-21T12:19:48.456Z I "[2023-02-21T12:19:48.456Z]","[ElectronUpdater]","INFO:","Checking for update"
2023-02-21T12:19:48.457Z I "[2023-02-21T12:19:48.457Z]","[ElectronUpdater]","INFO:","checking-for-update"
2023-02-21T12:19:48.551Z I "[ApplicationWindow]","spellcheck-dictionary-initialized","fr"
2023-02-21T12:19:48.847Z I "[2023-02-21T12:19:48.847Z]","[ElectronUpdater]","INFO:","Update for version 3.109.4 is not available (latest version: 3.109.4, downgrade is disallowed)."
2023-02-21T12:19:48.850Z I "[2023-02-21T12:19:48.847Z]","[ElectronUpdater]","INFO:","update not available:",{"version":"3.109.4","files":[{"url":"tutanota-desktop-win.exe","sha512":"37OY+SmidkROFBV4CgPRiZkL5BN8yqS5A5ijkeU4SiUO2fZwM1WJ2yV5z5TzDmW9KE+nsw50mcA6oYWaPtQdgw==","size":79431768}],"path":"tutanota-desktop-win.exe","sha512":"37OY+SmidkROFBV4CgPRiZkL5BN8yqS5A5ijkeU4SiUO2fZwM1WJ2yV5z5TzDmW9KE+nsw50mcA6oYWaPtQdgw==","releaseDate":"2023-02-16T11:08:00.394Z","signature":"SB50eGOLFhwu/52h/LSqxR+U55+BNGZyCl+I1TtE0OPAx4UWNbFvfHY5UM035oiLwX0jg/eM9MT3DcRS1Wg3N92gM8cCkBD812tNkaH0yxm688EOFF1uBeh40ssGnKZRh2jeS42IaZb7ES/SWyWc9WzlRbebFxPfYDEXfmTQ04KgfmuGOVs1tIj7UzXzHn4QtJRD2goZXamMmSFVBuuaZTH4K9vPFw7wMo9a0pYvEx4k7QQVCR2XCAleCCiqrwO8kmMWS8V4MyWRgGL5KEPQL49l26+uHPJaHho5leWWW+gwdSGdS8HKfpusavoVGKk0ACXyfhzU+bXeeQH+wByycg=="}
2023-02-21T12:19:49.294Z I "resolving key...","tutanota-credentials"
2023-02-21T12:19:49.954Z I "last missed notification check:",{"lastMissedNotificationCheckTime":1676981954918}
2023-02-21T12:19:49.954Z I "scheduling to check sse in",34,"seconds"
2023-02-21T12:19:49.954Z I "starting sse connection"
2023-02-21T12:19:49.991Z I "lookup sse request"
2023-02-21T12:19:50.156Z I "established SSE connection with code",200
2023-02-21T12:19:50.157Z I "received new timeout:","heartbeatTimeout:240"
2023-02-21T12:19:50.157Z I "scheduling to check sse in",288,"seconds"
2023-02-21T12:19:50.157Z I "sse heartbeat",240
2023-02-21T12:19:50.157Z I "scheduling to check sse in",288,"seconds"
2023-02-21T12:19:50.158Z I "sse heartbeat",240
2023-02-21T12:19:50.158Z I "scheduling to check sse in",288,"seconds"
2023-02-21T12:19:50.159Z I "downloading missed notification"
2023-02-21T12:19:50.161Z I "lookup"
2023-02-21T12:19:50.309Z I "missed notification response",200
2023-02-21T12:19:50.311Z I "dl missed notification response closed"
2023-02-21T12:19:50.311Z I "MissedNotification is empty"
2023-02-21T12:19:50.311Z I "scheduling to check sse in",288,"seconds"
2023-02-21T12:19:51.260Z I "storing push identifier"
2023-02-21T12:19:55.271Z I "[ApplicationWindow]","closing offline db for M5DBfjM----2"
2023-02-21T12:19:59.934Z I "[ApplicationWindow]","webAssetsPath: ","C:\\Program Files\\Tutanota Desktop\\resources\\app.asar"
2023-02-21T12:19:59.956Z I "[ApplicationWindow]","getting dictionaries from:","https://mail.tutanota.com/desktop/dictionaries/"
2023-02-21T12:20:00.445Z I "resolving key...","tutanota-credentials"
2023-02-21T12:20:01.474Z I "storing push identifier"
</pre>
<\details>

**Comment by ganthern** [comment]
still happens in 3.112.5:

```
tutanota geöffnet, passwort eignegeben...


Client: darwin
Type: PREMIUM
Tutanota version: 3.112.5
Timestamp (UTC): Mon, 03 Apr 2023 12:24:08 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.112.5 Chrome/110.0.5481.192 Electron/23.2.0 Safari/537.36
Error
Error message: AssertNotNull failed : System folder of type does not exist!
Stacktrace:
Error: AssertNotNull failed : System folder of type does not exist!
at q (asset://app/common-min-969d5d11.js:1:11549)
at an (asset://app/common-f0991525.js:1:4331)
at asset://app/mail-view-7b47bcdc.js:1:76061
```

**Comment by hrb-hub** [comment]
Still happening :(

```
Restored Stacktrace:
Error: AssertNotNull failed: System folder of type does not exist!
  at kt  (../../src/platform-kit/utils/Utils.ts:83:8)
  at Yc assertNotNull (../../src/applications/mail-app/mail/model/MailUtils.ts:149:8)
  at MailViewModel.getFolderForUserInbox assertSystemFolderOfType (../../src/applications/mail-app/mail/view/MailViewModel.ts:452:9)
  at async MailViewModel.selectFolderToUse _folder (../../src/applications/mail-app/mail/view/MailViewModel.ts:283:15)
  at async MailViewModel.showMail folderToUse (../../src/applications/mail-app/mail/view/MailViewModel.ts:249:8)
App version:
357.260824.1
Client type:
Android
Additional info:
Mozilla/5.0 (Linux; Android 17; Pixel 7 Pro Build/CP2A.260705.006; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/152.0.7977.87 Mobile Safari/537.36
```

```
Restored Stacktrace:
Error: AssertNotNull failed: System folder of type does not exist!
  at kt  (../../src/platform-kit/utils/Utils.ts:83:8)
  at Pc assertNotNull (../../src/applications/mail-app/mail/model/MailUtils.ts:149:8)
  at MailViewModel.getFolderForUserInbox assertSystemFolderOfType (../../src/applications/mail-app/mail/view/MailViewModel.ts:464:9)
  at async MailViewModel.selectFolderToUse _folder (../../src/applications/mail-app/mail/view/MailViewModel.ts:292:15)
  at async MailViewModel.showMail folderToUse (../../src/applications/mail-app/mail/view/MailViewModel.ts:258:8)
App version:
357.260901.0
Client type:
Windows
Additional info:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/357.260901.0 Chrome/152.0.7977.65 Electron/44.1.0 Safari/537.36
```
