### ISSUE TITLE
Uncaught Error: invalid type /calendar/month/2023-02-22

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5164]
Only happened once:

Looks like someone managed to get into the search from the calendar, this is thrown in `SearchUtils.getRestriction`

```
Client: Browser
Type: PREMIUM
Tutanota version: 3.109.5
Timestamp (UTC): Wed, 22 Feb 2023 22:51:59 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0
Error
Error message: invalid type /calendar/month/2023-02-22
Stacktrace:
aN@https://mail.tutanota.com/main-4c46812b.js:1:6948
_getCategory@https://mail.tutanota.com/search-8b9a48d7.js:1:20599
execute/_searchAgain/</<@https://mail.tutanota.com/search-8b9a48d7.js:1:17660
```

happened on android now:

```
Client: android
Type: PREMIUM
Tutanota version: 3.109.13
Timestamp (UTC): Thu, 02 Mar 2023 07:36:42 GMT
User agent:
Mozilla/5.0 (Linux; Android 13; Pixel 7 Pro Build/TQ1A.230205.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.154 Mobile Safari/537.36
Error
Error message: invalid type /calendar/month/2023-03-02
Stacktrace:
Error: invalid type /calendar/month/2023-03-02
at aP (https://assets.tutanota.com/main-991d0415.js:1:6961)
at SearchView._getCategory (https://assets.tutanota.com/search-2a78c4ad.js:1:20727)
at https://assets.tutanota.com/search-2a78c4ad.js:1:17789
```

and there's someone who did it in the settings:

```
Client: Browser
Type: PREMIUM
Tutanota version: 3.109.5
Timestamp (UTC): Tue, 07 Mar 2023 14:08:36 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Error
Error message: invalid type /settings/mail
Stacktrace:
Error: invalid type /settings/mail
at aN (https://mail.tutanota.com/main-4c46812b.js:1:6948)
at SearchView._getCategory (https://mail.tutanota.com/search-8b9a48d7.js:1:20598)
at https://mail.tutanota.com/search-8b9a48d7.js:1:17660
```

**Comment by wrdhub** [comment]
Have not seen in over a year.
