### ISSUE TITLE
We're refusing to open Links that don't have a scheme prefix

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5249]
~~from some logs sent to us:~~ These are treated as relative URLs by the browser, we should do the same (so nothing to do)

```
2023-02-25T09:53:35.939Z I "Relative/invalid URL",{},"www.linkedin.com/lumentechnologies"
2023-02-25T09:53:35.940Z I "Relative/invalid URL",{},"www.facebook.com/lumentechnologies"
2023-02-25T09:53:35.940Z I "Relative/invalid URL",{},"www.twitter.com/lumentechco"
2023-02-25T09:53:35.940Z I "Relative/invalid URL",{},"www.youtube.com/lumentechnologies"
2023-02-25T09:53:35.940Z I "Relative/invalid URL",{},"www.instagram.com/lumentechnologies"
```

while technically not valid URLs, maybe we can do something about this. The check was included because some mails have relative links to resources that would break the viewer.

---

Another similar thing:
`2023-03-13T07:48:38.839Z I "Relative/invalid URL",{},"#"`

this was attached to

```
Client: darwin
Type: PREMIUM
Tutanota version: 3.110.0
Timestamp (UTC): Mon, 13 Mar 2023 07:48:58 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.110.0 Chrome/108.0.5359.215 Electron/22.3.1 Safari/537.36
TypeError
Error message: Invalid URL
Stacktrace:
TypeError [ERR_INVALID_URL]: Invalid URL
at new NodeError (../../../../../node:internal/errors:387:5)
at URL.onParseError (../../../../../node:internal/url:564:9)
at new URL (../../../../../node:internal/url:640:5)
at new ClientRequest (../../../../../node:_http_client:130:30)
at Object.request (../../../../../node:http:96:10)
at AsyncFunction.<anonymous> (desktop/DesktopMain.js:1:48032)
```

and should have been caught by our catch blocks on the native side

**Comment by ganthern** [comment]
closing because it's somewhat expected and not a big problem.
