### ISSUE TITLE
Error: invalid type

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5267]
```
Client: win32
Type: PREMIUM
Tutanota version: 3.110.1
Timestamp (UTC): Thu, 16 Mar 2023 07:42:39 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.110.1 Chrome/110.0.5481.179 Electron/23.1.3 Safari/537.36
Error
Error message: invalid type /settings/desktop
Stacktrace:
Error: invalid type /settings/desktop
at aP (asset://app/main-3b3b2824.js:1:6961)
at SearchView._getCategory (asset://app/search-9dab2701.js:1:20727)
at asset://app/search-9dab2701.js:1:17789
```

The problem is here:
https://github.com/tutao/tutanota/blob/0283c38e8d35f544970668aa1988523caa2e2057/src/search/view/SearchView.ts#L407-L423

we are extending search index and then assuming that we are still in the search view. If we are not, we get an error

**Comment by charlag** [comment]
Duplicate of 5164
