### ISSUE TITLE
Unexpected error: module did not self-register

### ISSUE THREAD

**Issue by Zahrun** [tutao/tutanota#5273]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Describe the bug**
I get this error dialog every time I open a new tutanota window. Everything seems to work fine otherwise.

```
Feedback v3.110.0 - Error - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.110.0
 Timestamp (UTC): Fri, 17 Mar 2023 16:25:57 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.110.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
Error
 Error message: Module did not self-register: '/nix/store/68njn99b2axvxhlbaj3xvbdrxvi54ndb-tutanota-desktop-3.110.0/share/tutanota-desktop/resources/app.asar.unpacked/desktop/better_sqlite3.node'.
Stacktrace: 
Error: Module did not self-register: '/nix/store/68njn99b2axvxhlbaj3xvbdrxvi54ndb-tutanota-desktop-3.110.0/share/tutanota-desktop/resources/app.asar.unpacked/desktop/better_sqlite3.node'.
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at new Au (/nix/store/68njn99b2axvxhlbaj3xvbdrxvi54ndb-tutanota-desktop-3.110.0/share/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:13:131802)
    at Nu.openDb (/nix/store/68njn99b2axvxhlbaj3xvbdrxvi54ndb-tutanota-desktop-3.110.0/share/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:13:137406)
```

**To Reproduce**
1. Open new tutanota window
2. See error

**Expected behavior**
No error dialog

**Screenshots**
![image](https://user-images.githubusercontent.com/10415894/225963442-e3d6513a-c905-4644-a6d5-b0c000dae788.png)

**Desktop (please complete the following information):**
 - OS: NixOS 22.11
 - Desktop Environment: KDE Plasma 5.26.4
 - Version: 3.110.0

**Additional context**
Using the tutanota version from unstable nix repo https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=tutanota
Bug also declared at https://github.com/NixOS/nixpkgs/issues/221379

**Comment by charlag** [comment]
this is a problem with nix package (of which there are plenty and we don't want to track them here)
