### ISSUE TITLE
Invalid unit value NaN

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5330]
```
Client: win32
Tutanota version: 3.111.0
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.111.0 Chrome/110.0.5481.179 Electron/23.1.3 Safari/537.36
Error
Error message: Invalid unit value NaN
Stacktrace:
Error: Invalid unit value NaN
at Zn (asset://app/date-6dde548b.js:1:18910)
at jn (asset://app/date-6dde548b.js:1:19051)
at ci.fromObject (asset://app/date-6dde548b.js:1:56234)
at Ja (asset://app/date-6dde548b.js:1:96706)
at asset://app/date-6dde548b.js:1:92937
at [Array.map](http://array.map/) (<anonymous>)
at Ya (asset://app/date-6dde548b.js:1:92788)
at oo (asset://app/date-6dde548b.js:1:97937)
at ao (asset://app/date-6dde548b.js:1:97836)
at Hs.getCalendarDataForUpdate (asset://app/main-971900dc.js:1:42191)
```

**Comment by charlag** [comment]
It seems like the client gets stuck on invalid calendar update, we should skip those and not get stuck at the very least.

Additionally we should catch this earlier as parsing error

**Comment by ganthern** [comment]
This is happening to one single person, but it happens every single time it they log in.
