### ISSUE TITLE
Uncaught Error: net::ERR_NETWORK_CHANGED

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5336]
Observed on linux:

```
Tutanota crashes whenever I toggle my VPN connection on and off.


Client: linux
Type: PREMIUM
Tutanota version: 3.111.0
Timestamp (UTC): Mon, 03 Apr 2023 16:39:33 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.111.0 Chrome/110.0.5481.179 Electron/23.1.3 Safari/537.36
Error
Error message: net::ERR_NETWORK_CHANGED
Stacktrace:
Error: net::ERR_NETWORK_CHANGED
at SimpleURLLoaderWrapper.<anonymous> (../../../../home/adrian/node:electron/js2c/browser_init:2:49386)
at SimpleURLLoaderWrapper.emit (../../../../home/adrian/node:events:513:28)
```

It's probably safe to just have the request fail in this case and try again.

**Comment by ganthern** [comment]
probably a duplicate of https://github.com/tutao/tutanota/issues/5338
