### ISSUE TITLE
Uncaught IndexSizeError: Failed to execute 'setStart' on 'Range': The offset is larger than the node's length

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5339]
> I was typing a new message in my browser. I think I was pasting a URL.

```
Client: Browser
Type: PREMIUM
Tutanota version: 3.112.5
Timestamp (UTC): Tue, 04 Apr 2023 00:05:41 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
IndexSizeError
Error message: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (5).
Stacktrace:
Error: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (5).
at yn (https://mail.tutanota.com/mail-editor-bda46a73.js:1:20548)
at https://mail.tutanota.com/mail-editor-bda46a73.js:1:23668
```

I already encountered this when typing/pasting URLs, it seems to be related to the squire update in 3.112.5

Reproduction steps:
* have any text in the mail editor
* put the cursor in the middle of a word
* type space
* type a link that will be linkified
* type another space
* see the error pop up

It seems to require a block of text where the first part will be turned into a link once a space is added in the middle.

## Test Notes
* [ ] test that the bug does not occur when adding a space with a normal cursor and when multiple characters/lines are replaced with a space
* [ ] smoke test the other formatting functionality in the mail editor

**Comment by ganthern** [comment]
Blocked on squire merging the fix to https://github.com/fastmail/Squire/issues/430
