### ISSUE TITLE
Uncaught Error: no uid set on the event

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5367]
One single report:

> I tried to delete a single event in a series.

```
Client: Browser
Type: PREMIUM
Tutanota version: 3.112.6
Timestamp (UTC): Wed, 12 Apr 2023 15:45:49 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Error
Error message: no uid set on the event
Stacktrace:
Error: no uid set on the event
at CalendarFacade.saveCalendarEvent (https://mail.tutanota.com/worker-lazy-b8c3966a.js:1:39698)
at https://mail.tutanota.com/common-f0991525.js:1:2227
```

According to the user, the event was not imported, but "created in tutanota ages ago".

**Comment by charlag** [comment]
I don't think that happens anymore
