### ISSUE TITLE
Uncaught CryptoError: javax.crypto.BadPaddingException

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5374]
> I changed biometric unlock on my phone

```
Client: android
Type: PREMIUM
Tutanota version: 3.112.6
Timestamp (UTC): Fri, 14 Apr 2023 19:58:48 GMT
User agent:
Mozilla/5.0 (Linux; Android 12; M2007J20CG Build/SKQ1.211019.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.116 Mobile Safari/537.36
de.tutao.tutanota.CryptoError
Error message: javax.crypto.BadPaddingException
Stacktrace:
de.tutao.tutanota.CryptoError: javax.crypto.BadPaddingException
at de.tutao.tutanota.AndroidKeyStoreFacade.decryptData(AndroidKeyStoreFacade.kt:118)
at de.tutao.tutanota.credentials.CredentialsEncryptionFromAPI30.decryptUsingKeychain(CredentialsEncryptionFromAPI30.kt:53)
at de.tutao.tutanota.ipc.NativeCredentialsFacadeReceiveDispatcher.dispatch(NativeCredentialsFacadeReceiveDispatcher.kt:29)
at de.tutao.tutanota.ipc.AndroidGlobalDispatcher.dispatch(AndroidGlobalDispatcher.kt:38)
at de.tutao.tutanota.RemoteBridge.invokeMethod(RemoteBridge.kt:153)
at de.tutao.tutanota.RemoteBridge.handleMessageFromWeb(RemoteBridge.kt:90)
at de.tutao.tutanota.RemoteBridge$initMessageChannel$1$onMessage$1.invokeSuspend(RemoteBridge.kt:58)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at [kotlinx.coroutines.DispatchedTask.run](http://kotlinx.coroutines.dispatchedtask.run/)(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: javax.crypto.BadPaddingException
at [android.security](http://android.security/).keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal([AndroidKeyStoreCipherSpiBase.java:609](http://androidkeystorecipherspibase.java:609/))
at javax.crypto.Cipher.doFinal([Cipher.java:2056](http://cipher.java:2056/))
at de.tutao.tutanota.AndroidKeyStoreFacade.decryptData(AndroidKeyStoreFacade.kt:116)
... 12 more
Caused by: [android.security](http://android.security/).KeyStoreException: Invalid argument
at [android.security](http://android.security/).KeyStore2.getKeyStoreException([KeyStore2.java:356](http://keystore2.java:356/))
at [android.security](http://android.security/).KeyStoreOperation.handleExceptions([KeyStoreOperation.java:78](http://keystoreoperation.java:78/))
at [android.security](http://android.security/).KeyStoreOperation.finish([KeyStoreOperation.java:127](http://keystoreoperation.java:127/))
at [android.security](http://android.security/).keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish([KeyStoreCryptoOperationChunkedStreamer.java:228](http://keystorecryptooperationchunkedstreamer.java:228/))
at [android.security](http://android.security/).keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal([KeyStoreCryptoOperationChunkedStreamer.java:181](http://keystorecryptooperationchunkedstreamer.java:181/))
at [android.security](http://android.security/).keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal([AndroidKeyStoreCipherSpiBase.java:603](http://androidkeystorecipherspibase.java:603/))
```

**Comment by charlag** [comment]
We don't see it happening anymore, there are some other keychain errors but not this one
