### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'getUTCHours') in _loadMonthIfNeeded

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5419]
`_loadMonthIfNeeded` does not use `getUTCHours`, so this is kinda weird. I suspect it's in _loadEvents that's called from there.

```
Client: win32
Type: PREMIUM
Tutanota version: 3.112.6
Timestamp (UTC): Mon, 24 Apr 2023 07:26:37 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.112.6 Chrome/110.0.5481.192 Electron/23.2.0 Safari/537.36
TypeError
Error message: Cannot read properties of undefined (reading 'getUTCHours')
Stacktrace:
TypeError: Cannot read properties of undefined (reading 'getUTCHours')
at Ir (asset://app/common-f0991525.js:1:349795)
at Oi (asset://app/date-3aad3b59.js:1:69156)
at Bi (asset://app/date-3aad3b59.js:1:71892)
at asset://app/calendar-view-f9cbbcfe.js:1:13408
at Array.filter (<anonymous>)
at asset://app/calendar-view-f9cbbcfe.js:1:13388
at async CalendarViewModel._loadMonthIfNeeded (asset://app/calendar-view-f9cbbcfe.js:1:12882)
```

**Comment by wrdhub** [comment]
Have not seen in over a year.
