### ISSUE TITLE
Uncaught ProgrammingError Trying to resume the session for user xxx - while already logged in for xxx

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5537]
We receive this error 3 to 4 time per day in the error reports mailbox.

Happens on all devices, apps and web client.

```
Client: android
Type: PREMIUM
Tutanota version: 3.113.3
Timestamp (UTC): Mon, 12 Jun 2023 20:39:05 GMT
User agent:
Mozilla/5.0 (Linux; Android 13; SM-N980F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.162 Mobile Safari/537.36
ProgrammingError
Error message: Trying to resume the session for user xxx while already logged in for xxx
Stacktrace:
ProgrammingError: Trying to resume the session for user xxx while already logged in for xxx
at zi.resumeSession (https://assets.tutanota.com/worker.js:12:13478)
at https://assets.tutanota.com/common-adc646e7.js:1:1873
```

## Test notes
 - [ ] Fail offline login (might not be possible in your version). Try to log in again. Should not see unexpected error.
 - [ ] Log out and log in again
 - [ ] Log out and log in into another user again
 - [ ] Do sign up and then log in without reloading the window
 - [ ] See that ephemeral session is closed when closing the window
 - [ ] Have multiple windows in desktop app logged in into the same user. Delete credentials in one of those windows. All windows should log out
 - [ ] Sign up with gift card and then log in
 - [ ] Try termination form

**Comment by bedhub** [comment]
Some user comments:


"Tried to refresh session (reconnect) pressing Ctrl+F5 on Firefox",
"I was only trying to log in"
"Just opened the app"
"Login attempted on Android phone."
"Error happaned only when awaking form sleep mode"

**Comment by charlag** [comment]
This happens e.g. when offline login partially fails during init of the client side. Right now can be introduced by trying offline login (which fails) and logging in again.
