### ISSUE TITLE
Cannot open attachments popup

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#570]
Tutanota version: 3.36.1

Stacktrace: 
```
ReferenceError: DOMRect is not defined
at file:///android_asset/tutanota/dist/main.js:1:265964
at file:///android_asset/tutanota/dist/main-boot.js:1:212131
at r (file:///android_asset/tutanota/dist/libs.js:32:9004)
at i._settlePromiseFromHandler (file:///android_asset/tutanota/dist/libs.js:31:14217)
at i._settlePromise (file:///android_asset/tutanota/dist/libs.js:31:15020)
at i._settlePromiseCtx (file:///android_asset/tutanota/dist/libs.js:31:15528)
at r._drainQueue (file:///android_asset/tutanota/dist/libs.js:30:3039)
at r._drainQueues (file:///android_asset/tutanota/dist/libs.js:30:3117)
at drainQueues (file:///android_asset/tutanota/dist/libs.js:30:1238)
at
```

**Comment by charlag** [comment]
it seems like `DOMRect` is not supported in some browsers
