### ISSUE TITLE
Error message: can't access dead object on logout in FF

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5749]
```
Feedback v3.115.2 - TypeError
Closing down when error message appeared


Client: Browser
Tutanota version: 3.115.2
Timestamp (UTC): Mon, 07 Aug 2023 20:42:43 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0
TypeError
Error message: can't access dead object
Stacktrace:
A@https://mail.tutanota.com/app.js:1:28895
execute/T.set@https://mail.tutanota.com/app.js:1:30209
click@https://mail.tutanota.com/main-a45d81a5.js:1:162635
click@https://mail.tutanota.com/gui-base-ec6e3cbd.js:1:100008
onclick@https://mail.tutanota.com/gui-base-ec6e3cbd.js:1:97238
execute/D.prototype.handleEvent@https://mail.tutanota.com/app.js:1:23727
```

```
Error message: can't access dead object
Stacktrace:
  at A pushState (../../libs/mithril.js:1491:24)
  at execute/T.set setPath (../../libs/mithril.js:1532:2)
  at click set (../../../src/gui/nav/DrawerMenu.ts:132:26)
  at click call (../../../src/gui/base/Button.ts:325:9)
  at onclick click (../../../src/gui/base/Button.ts:125:41)
  at execute/D.prototype.handleEvent call (../../libs/mithril.js:1022:56)
```

> I'm just trying to logout. I don't know how to replicate the bug. Maybe yesterday I left my pc in hibernate and today I restart from hibernate state. Thanks for your help.

Maybe we could switch to not use mithril routing in that button (no need to put logout URL into history anyway) but so far it's completely mysterious for me why this could happen.

**Comment by jalhubb** [comment]
outdated - no repro until now. reopen if it resurfaces
