### ISSUE TITLE
Uncaught TypeError: Invalid state: Controller is already closed

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5763]
probably related to our move to using fetch in the main thread: 
https://github.com/nodejs/undici/issues/1564

some errors in node's new http implementation are not caught correctly.

```
Client: linux
Type: FREE
Tutanota version: 3.116.8
Timestamp (UTC): Thu, 10 Aug 2023 12:45:14 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.116.8 Chrome/114.0.5735.248 Electron/25.3.2 Safari/537.36
TypeError
Error message: Invalid state: Controller is already closed
Stacktrace:
TypeError [ERR_INVALID_STATE]: Invalid state: Controller is already closed
at new NodeError (../../../../home/steph/node:internal/errors:399:5)
at ReadableStreamDefaultController.enqueue (../../../../home/stephanie/node:internal/webstreams/readablestream:1036:13)
at fetchParams.controller.resume (../../../../home/steph/node:internal/deps/undici/undici:11261:45)
at process.processTicksAndRejections (../../../../home/steph/node:internal/process/task_queues:95:5)
```

```
the moment when i open tutanota 
```

**Comment by charlag** [comment]
Still reported regularly

> Tutanota is always informing that an error ocurred.

```
Client: linux
Tutanota version: 3.118.7
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.118.7 Chrome/116.0.5845.188 Electron/26.2.1 Safari/537.36
TypeError
Error message: Invalid state: Controller is already closed
Stacktrace:
TypeError [ERR_INVALID_STATE]: Invalid state: Controller is already closed
at new NodeError (../../../../../home/Henrique/node:internal/errors:399:5)
at ReadableStreamDefaultController.enqueue (../../../../../home/Henrique/node:internal/webstreams/readablestream:1036:13)
at Fetch.resume (../../../../../home/Henrique/node:internal/deps/undici/undici:11305:45)
at process.processTicksAndRejections (../../../../../home/Henrique/node:internal/process/task_queues:95:5)
```

**Comment by charlag** [comment]
I think this is it:
https://github.com/nodejs/undici/issues/1564

**Comment by aralroca** [comment]
I have the same problem with Node 20. Switching to Node 22 is working fine, however my cloud provider is using the LTS (20) and I can't move to 22 there. Any workaround to solve it?

**Comment by charlag** [comment]
Does not occur anymore
