### ISSUE TITLE
Uncaught BadRequestError: DELETE /rest/tutanota/mailservice

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5770]
```
Messages failing to be removed from trash after selecting all search results and confirming permanent deletion.


Client: win32
Type: PREMIUM
Tutanota version: 3.114.1
Timestamp (UTC): Sun, 13 Aug 2023 12:57:15 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.114.1 Chrome/112.0.5615.165 Electron/24.2.0 Safari/537.36
BadRequestError
Error message: 400: NbiyCz0----9 | DELETE /rest/tutanota/mailservice
Stacktrace:
BadRequestError: 400: NbiyCz0----9 | DELETE /rest/tutanota/mailservice
at d0 (asset://app/common-min-14a25bc9.js:1:8951)
at d.onload (asset://app/worker.js:12:23441)
```

> Re recent error reports... items that failed to be "permanently deleted from trash" were apparently in a sub-folder under trash...

**Comment by vitoreiji** [comment]
From another report, it seems the folders the mails were in had been deleted, but not the mails, i.e., the `MailFolder` instance was deleted, but not the `Mail` list.

**Comment by vitoreiji** [comment]
1. Enable search
2. Move (searchable) mail to custom folder
3. Delete folder
4. Search for mail, it will show up in results
5. Try to delete mail
6. See error

**Comment by ganthern** [comment]
This is now server issue #1582
