### ISSUE TITLE
Uncaught CancelledError:

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5774]
This started happening in 3.116.8 exclusively on darwin. We got a single report of this from each reporter, so it might only be on first startup after the update.

```
Client: darwin
Type: PAID
Tutanota version: 3.116.8
Timestamp (UTC): Mon, 14 Aug 2023 10:26:35 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.116.8 Chrome/114.0.5735.248 Electron/25.3.2 Safari/537.36
CancelledError
Error message: stop retry processing after service unavailable due to reconnect
Stacktrace:
CancelledError: stop retry processing after service unavailable due to reconnect
at asset://app/worker.js:1:15702
at async ms.eventQueueCallback (asset://app/worker.js:1:13832)
```

**Comment by charlag** [comment]
We get this on different platforms, it happens when the server reports timeouts. This should be caught and not propagated to the user.
