### ISSUE TITLE
Uncaught BadRequestError: GET /rest/sys/publickeyservice

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5789]
Looks like we're not making sure the mail address is properly normalized for this request:

```
when i receive an event invitation from the sender, i cannot reply "Yes" as an error occur


Client: linux
Type: FREE
Tutanota version: 3.116.8
Timestamp (UTC): Wed, 16 Aug 2023 22:50:46 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.116.8 Chrome/114.0.5735.248 Electron/25.3.2 Safari/537.36
BadRequestError
Error message: 400: Nc-XpY4----9 | GET /rest/sys/publickeyservice
Stacktrace:
BadRequestError: 400: Nc-XpY4----9 | GET /rest/sys/publickeyservice
at db (asset://app/common-min-905556a0.js:1:9811)
at p.onload (asset://app/worker.js:12:23418)
```

Server Log (somewhat censored):
`
I 00:50:46.853 sys RootHandler.java:537 Md4goDg----2 Nc-XpY4----9 de.tutao.tutadb.rest.exceptions.BadRequestException:Invalid mail address: some name <somename@homeoffice.gov.uk> [...] - GET /rest/sys/publickeyservice/_body=%7B%22_format%22%3A%220%22%2C%22mailAddress%22%3A%some+name+%3Csomename%40homeoffice.gov.uk%3E%22%7D`

**Comment by wrdhub** [comment]
We are not seeing this error anymore.
