### ISSUE TITLE
Error message: No group with groupId _____ found!

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5875]
To repro:

1. Go to contact view
2. Click add new contact list
3. Add a name **and** some recipients right away
4. Click save
5. See the error

```
Client: linux
Tutanota version: 3.118.5

Error
Error message: No group with groupId Ne7RVi8----0 found!
Stacktrace:
Error: No group with groupId Ne7RVi8----0 found!
at La.getMembership (asset://app/worker.js:12:46779)
at asset://app/worker.js:12:46655
at v (asset://app/common-min-400ee161.js:1:15371)
at La.getGroupKey (asset://app/worker.js:12:46599)
at ji.setNewOwnerEncSessionKey (asset://app/worker.js:12:7521)
at As.setup (asset://app/worker.js:1:27434)
```

## Context
It looks like a timing issue where we did not receive a new group and a new group key yet but we are already trying to use it.

There are also related messages: `could not find permission for instance of type tutanota/ContactListGroupRoot with id _____` which probably have the same reason.

## Test Notes
- [ ] Try to reproduce, see that the error does not occur
- [ ] Regression: Creating a new calendars works without error

**Comment by charlag** [comment]
More context: `CalendarFacade` has a hack specifically for this case:

https://github.com/tutao/tutanota/blob/c54f0a382c4f1e6cae20748ffb97a4ee4ad6fac9/src/api/worker/facades/lazy/CalendarFacade.ts#L247-L266
