### ISSUE TITLE
Error in search: Start index not found

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5880]
```
Client: win32
Tutanota version: 3.118.4
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.118.4 Chrome/116.0.5845.97 Electron/26.1.0 Safari/537.36
Error
Error message: start index not found
Stacktrace:
Error: start index not found
at SearchViewModel.loadSearchResults (asset://app/search-3f4c1aaa.js:1:21992)
at Object.fetch (asset://app/search-3f4c1aaa.js:1:21270)
at async asset://app/main-bfb7cb90.js:1:181687
at async Object.retryLoading (asset://app/main-bfb7cb90.js:1:181481)
```

> Just opened Tutanota, clicked on renew (new version), searched on an email address 'van gelder'and clicked on first mail found in the list. Than this error

**Comment by charlag** [comment]
Duplicate of #5340
