### ISSUE TITLE
Can't log in the desktop app in Tails.

### ISSUE THREAD

**Issue by iwnc** [tutao/tutanota#5889]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
The authentication fails with the message "_Currently the server is not available. Try later_" (translated) (see attachment).

**To Reproduce**
1. Download the app from https://github.com/tutao/tutanota/releases/tag/tutanota-desktop-release-3.118.7
2. Make it executable.
3. Open the app and insert the username and password.
4. Click on Authentication

**Expected behavior**
If the 2FA has been setup the app should ask for 2FA, otherwise I should be able to login straight into my account.

**Screenshots**
![Captură de ecran de la 2023-09-15 19-25-20](https://github.com/tutao/tutanota/assets/92922165/d85eca3d-1811-4df9-b0ec-88c1077f134d)

**Desktop**
 - OS: Tails 5.17.1
 - Desktop Environment GNOME
 - Version 3.118.7

**Additional context**
Logs:
```
sep 15 19:46:04 amnesia org.gnome.Nautilus[18254]: the monkey has been patched
sep 15 19:46:04 amnesia org.gnome.Nautilus[18254]: (node:18254) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or>
sep 15 19:46:04 amnesia org.gnome.Nautilus[18254]: (Use `tutanota-desktop --trace-deprecation ...` to show where the warning was created)
sep 15 19:46:04 amnesia org.gnome.Nautilus[18254]: [18254:0915/194604.636032:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop:>
sep 15 19:46:04 amnesia org.gnome.Nautilus[18254]: [18254:0915/194604.636070:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
sep 15 19:46:04 amnesia org.gnome.Nautilus[18254]: version:   3.118.7
sep 15 19:46:04 amnesia org.gnome.Nautilus[15357]: [ApplicationWindow] webAssetsPath:  /tmp/.mount_tutanoyEiDmp/resources/app.asar
sep 15 19:46:04 amnesia org.gnome.Nautilus[18254]: config up to date
sep 15 19:46:04 amnesia org.gnome.Nautilus[15357]: [ApplicationWindow] getting dictionaries from: https://mail.tutanota.com/desktop/dictionaries/
sep 15 19:46:04 amnesia org.gnome.Nautilus[15357]: [15357:0915/194604.853780:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
sep 15 19:46:04 amnesia org.gnome.Nautilus[15357]: [15357:0915/194604.859904:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
sep 15 19:46:04 amnesia org.gnome.Nautilus[18292]: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
sep 15 19:46:06 amnesia systemd[7660]: tmp-.mount_tutanonPGsfs.mount: Succeeded.
sep 15 19:46:09 amnesia org.gnome.Nautilus[15357]: scheduling to check sse in 10 seconds
sep 15 19:46:09 amnesia org.gnome.Nautilus[15357]: sse info not available, skip reconnect
sep 15 19:46:15 amnesia org.gnome.Nautilus[15357]: [ProtocolProxy] error for GET https://mail.tutanota.com/rest/sys/saltservice:
sep 15 19:46:15 amnesia org.gnome.Nautilus[15357]: [ProtocolProxy] TypeError: fetch failed
sep 15 19:46:15 amnesia org.gnome.Nautilus[15357]:     at Object.fetch (node:internal/deps/undici/undici:11457:11)
sep 15 19:46:15 amnesia org.gnome.Nautilus[15357]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
sep 15 19:46:15 amnesia org.gnome.Nautilus[15357]:     at async /tmp/.mount_tutanoyEiDmp/resources/app.asar/desktop/DesktopMain.js:1:49005
sep 15 19:46:15 amnesia org.gnome.Nautilus[15357]:     at async AsyncFunction.<anonymous> (node:electron/js2c/browser_init:2:57570) {
sep 15 19:46:15 amnesia org.gnome.Nautilus[15357]:   cause: Error: connect ECONNREFUSED 185.205.69.10:443
sep 15 19:46:15 amnesia org.gnome.Nautilus[15357]:       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
sep 15 19:46:15 amnesia org.gnome.Nautilus[15357]:     errno: -111,
sep 15 19:46:15 amnesia org.gnome.Nautilus[15357]:     code: 'ECONNREFUSED',
sep 15 19:46:15 amnesia org.gnome.Nautilus[15357]:     syscall: 'connect',
sep 15 19:46:15 amnesia org.gnome.Nautilus[15357]:     address: '185.205.69.10',
sep 15 19:46:15 amnesia org.gnome.Nautilus[15357]:     port: 443
sep 15 19:46:15 amnesia org.gnome.Nautilus[15357]:   }
sep 15 19:46:15 amnesia org.gnome.Nautilus[15357]: }
sep 15 19:46:15 amnesia org.gnome.Nautilus[15357]: [ProtocolProxy] {"name":"TypeError","message":"fetch failed","stack":"TypeError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:11457:11)\>
sep 15 19:46:15 amnesia org.gnome.Nautilus[15357]: [ProtocolProxy] failed after 378ms
sep 15 19:46:19 amnesia org.gnome.Nautilus[15357]: scheduling to check sse in 10 seconds
sep 15 19:46:19 amnesia org.gnome.Nautilus[15357]: sse info not available, skip reconnect
sep 15 19:46:29 amnesia org.gnome.Nautilus[15357]: scheduling to check sse in 10 seconds
sep 15 19:46:29 amnesia org.gnome.Nautilus[15357]: sse info not available, skip reconnect
sep 15 19:46:39 amnesia org.gnome.Nautilus[15357]: scheduling to check sse in 10 seconds
sep 15 19:46:39 amnesia org.gnome.Nautilus[15357]: sse info not available, skip reconnect
sep 15 19:46:49 amnesia org.gnome.Nautilus[15357]: scheduling to check sse in 10 seconds
sep 15 19:46:49 amnesia org.gnome.Nautilus[15357]: sse info not available, skip reconnect
sep 15 19:46:59 amnesia org.gnome.Nautilus[15357]: scheduling to check sse in 10 seconds
sep 15 19:46:59 amnesia org.gnome.Nautilus[15357]: sse info not available, skip reconnect
sep 15 19:47:00 amnesia sudo[18352]:  amnesia : PWD=/home/amnesia ; USER=root ; COMMAND=/usr/local/lib/tails-get-date
sep 15 19:47:00 amnesia sudo[18352]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
sep 15 19:47:00 amnesia sudo[18352]: pam_unix(sudo:session): session closed for user root
sep 15 19:47:00 amnesia sudo[18354]:  amnesia : PWD=/home/amnesia ; USER=root ; COMMAND=/usr/local/lib/tails-get-date
sep 15 19:47:00 amnesia sudo[18354]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
sep 15 19:47:00 amnesia sudo[18354]: pam_unix(sudo:session): session closed for user root
sep 15 19:47:09 amnesia org.gnome.Nautilus[15357]: scheduling to check sse in 10 seconds
sep 15 19:47:09 amnesia org.gnome.Nautilus[15357]: sse info not available, skip reconnect
sep 15 19:47:19 amnesia org.gnome.Nautilus[15357]: scheduling to check sse in 10 seconds
```

**Comment by iwnc** [comment]
Hi @wrdhub, yes it still occurs. Here are the logs:

v259.241213.0 - linux


 Client: linux
 Type: UNKNOWN
 Tutanota version: 259.241213.0
 Timestamp (UTC): Fri, 20 Dec 2024 18:43:46 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/259.241213.0 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36


== MAIN LOG ==
2024-12-20T18:33:37.785Z I "Migrating credentials to native"
2024-12-20T18:33:37.785Z I "Skipping migration as encryption data is not there"
2024-12-20T18:33:37.785Z I "Stored credentials in native"
2024-12-20T18:33:37.785Z I "Cleared credentials in deviceConfig"
2024-12-20T18:33:37.802Z I "\n\n........................................\n........................................\n........................................\n........@@@@@@@@@@@@@@@@@@@@@@@.........\n.....@....@@@@@@@@@@@@@@@@@@@@@@@.......\n.....@@@....@@@@@@@@@@@@@@@@@@@@@@@.....\n.....@@@@@..............................    Do you care about privacy?\n.....@@@@@...@@@@@@@@@@@@@@@@@@@@@@.....\n.....@@@@...@@@@@@@@@@@@@@@@@@@@@@@.....    Work at Tuta! Fight for our rights!\n.....@@@@...@@@@@@@@@@@@@@@@@@@@@@......\n.....@@@...@@@@@@@@@@@@@@@@@@@@@@.......    https://tuta.com/jobs\n.....@@@...@@@@@@@@@@@@@@@@@@@@@@.......\n.....@@...@@@@@@@@@@@@@@@@@@@@@@........\n.....@@...@@@@@@@@@@@@@@@@@@@@@@........\n.....@...@@@@@@@@@@@@@@@@@@@@@@.........\n.....@...@@@@@@@@@@@@@@@@@@@@@@.........\n........@@@@@@@@@@@@@@@@@@@@@@..........\n.......@@@@@@@@@@@@@@@@@@@@@@...........\n.......@@@@@@@@@@@@@@@@@@@@@@...........\n........................................\n........................................\n........................................\n\n"
2024-12-20T18:33:37.837Z I "worker init time (ms):",84
2024-12-20T18:37:13.010Z I "removed topmost modal component"
2024-12-20T18:43:44.263Z I "removed topmost modal component"

== WORKER LOG ==
2024-12-20T18:37:12.327Z I "[RestClient]","failed request","GET","https://app.tuta.com/rest/sys/saltservice?_body=%7B%22_format%22%3A%220%22%2C%22mailAddress%22%3A%22iwnc%40tutanota.com%22%7D",0,"",["v","cv","Content-Type","Accept"],"[49 characters]"
2024-12-20T18:37:12.327Z I "[RestClient]","failed request","GET","https://app.tuta.com/rest/sys/saltservice?_body=%7B%22_format%22%3A%220%22%2C%22mailAddress%22%3A%22iwnc%40tutanota.com%22%7D",0,"",["v","cv","Content-Type","Accept"],"[49 characters]"

== NATIVE LOG ==
2024-12-20T18:33:36.407Z I "the monkey has been patched pid:",13688
2024-12-20T18:33:36.958Z I "Creating tables..."
2024-12-20T18:33:36.967Z I "Current credentials version: undefined"
2024-12-20T18:33:36.967Z I "Migrating to v1"
2024-12-20T18:33:36.970Z I "Tables created successfully!"
2024-12-20T18:33:36.975Z I "version:  ","259.241213.0"
2024-12-20T18:33:37.069Z I "resolving key...","tutanota-vault"
2024-12-20T18:33:37.091Z I "[2024-12-20T18:33:37.086Z]","using safeStorage with backend","gnome_libsecret"
2024-12-20T18:33:37.091Z W "key tutanota-vault not found, generating a new one"
2024-12-20T18:33:37.157Z I "[DesktopMain]","getting dictionaries from:","https://app.tuta.com/desktop/dictionaries/"
2024-12-20T18:33:37.157Z I "config up to date"
2024-12-20T18:33:37.159Z I "[DesktopMain]","spellcheck-dictionary-download-begin","en-US"
2024-12-20T18:33:37.160Z I "[2024-12-20T18:33:37.160Z]","Create tray:true"
2024-12-20T18:33:37.161Z I "[SSEFacade]","last missed notification check:",{"lastMissedNotificationCheckTime":null}
2024-12-20T18:33:37.162Z I "[ApplicationWindow]","webAssetsPath: ","/tmp/.mount_tutanoIiFyvf/resources/app.asar"
2024-12-20T18:33:37.302Z I "default mailto handler:",false
2024-12-20T18:33:37.303Z I "Webapp ready"
2024-12-20T18:33:37.303Z I "[SSEFacade]","No SSE info"
2024-12-20T18:33:37.304Z I "[2024-12-20T18:33:37.304Z]","[ElectronUpdater]","INFO:","Checking for update"
2024-12-20T18:33:37.304Z I "[2024-12-20T18:33:37.304Z]","[ElectronUpdater]","INFO:","checking-for-update"
2024-12-20T18:33:37.333Z I "[DesktopMain]","spellcheck-dictionary-download-failure","en-US"
2024-12-20T18:33:37.334Z I "/home/amnesia/.local/share/applications/tutanota-desktop.desktop does not exist, checking for permission to ask for permission..."
2024-12-20T18:33:37.404Z I "[2024-12-20T18:33:37.404Z]","[ElectronUpdater]","INFO:","Generated new staging user ID: 9ab25e50-6c31-5c0b-8325-9f51717984a8"
2024-12-20T18:33:37.407Z I "[DesktopMain]","getting dictionaries from:","https://app.tuta.com/desktop/dictionaries/"
2024-12-20T18:33:37.411Z I "[DesktopMain]","spellcheck-dictionary-download-begin","en-US"
2024-12-20T18:33:37.479Z I "[DesktopMain]","spellcheck-dictionary-download-failure","en-US"
2024-12-20T18:33:37.479Z E "[2024-12-20T18:33:37.479Z]","[ElectronUpdater]","ERROR:","Error: Error: net::ERR_CONNECTION_REFUSED\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:117806)\n    at SimpleURLLoaderWrapper.emit (node:events:519:28)"
2024-12-20T18:33:37.479Z E "[2024-12-20T18:33:37.479Z]","[ElectronUpdater]","ERROR:","Auto Update Error 1, continuing polling:\nnet::ERR_CONNECTION_REFUSED"
2024-12-20T18:33:37.479Z E "[2024-12-20T18:33:37.479Z]","[ElectronUpdater]","ERROR:","Update check failed,","net::ERR_CONNECTION_REFUSED"
2024-12-20T18:33:47.478Z I "updating no_integration blacklist..."
2024-12-20T18:37:12.324Z I "[ProtocolProxy]","error for GET https://app.tuta.com/rest/sys/saltservice:"
2024-12-20T18:37:12.326Z I "[ProtocolProxy]",?
2024-12-20T18:37:12.326Z I "[ProtocolProxy]","{\"name\":\"TypeError\",\"message\":\"fetch failed\",\"stack\":\"TypeError: fetch failed\\n    at /tmp/.mount_tutanoIiFyvf/resources/app.asar/desktop/DesktopMain.js:10:31493\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async ah (/tmp/.mount_tutanoIiFyvf/resources/app.asar/desktop/DesktopMain.js:10:31398)\\n    at async /tmp/.mount_tutanoIiFyvf/resources/app.asar/desktop/DesktopMain.js:10:33186\\n    at async AsyncFunction.<anonymous> (node:electron/js2c/browser_init:2:52556)\"}"
2024-12-20T18:37:12.326Z I "[ProtocolProxy]","failed after 312ms"

**Comment by wrdhub** [comment]
I know that sometimes the IPs of exit nodes get blocked because of abuse, but I do find it odd that this is consistently happening for you. Usually those blocks get cleared out and you should be fine, but you may want to try changing the exit node and see if that helps.

**Comment by eabase** [comment]
Seem like IP blocking is a repeating issue. #10438
