### ISSUE TITLE
Unknown TypeError at Login screen

### ISSUE THREAD

**Issue by Nyabinary** [tutao/tutanota#5936]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**
Unknown Error.

Feedback v3.118.8 - TypeError - UNKNOWN - android

Client: android
 Type: UNKNOWN
 Tutanota version: 3.118.8
 Timestamp (UTC): Tue, 26 Sep 2023 16:29:05 GMT
 User agent:
Mozilla/5.0 (Linux; Android 14; SM-S908U1 Build/UP1A.230905.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.0.0 Mobile Safari/537.36
TypeError
 Error message: Cannot read properties of undefined (reading 'startWebMessageChannel')
Stacktrace: 
TypeError: Cannot read properties of undefined (reading 'startWebMessageChannel')
    at fe.start (https://assets.tutanota.com/native-main-121f45bf.js:1:7306)
    at ve.init (https://assets.tutanota.com/native-main-121f45bf.js:1:7617)
    at https://assets.tutanota.com/app.js:1:84911

**Describe the bug**

**To Reproduce**
1. Sign in without saving password
2. Wait for the session to expire
3. Open app

**Expected behavior**

**Screenshots**
![Screenshot_20230926_122748_Tutanota](https://github.com/tutao/tutanota/assets/97130632/dddf23ca-dbcf-4264-bdd4-06d870411455)

**Smartphone (please complete the following information):**
 - Device: S22 Ultra
 - OS: Android
 - Version 13 & 14

**Additional context**
Using Firefox Nightly as default browser

**Comment by charlag** [comment]
Is it still relevant? Looks like "old webview" kind of issue

**Comment by nyabinary** [comment]
> Is it still relevant? Looks like "old webview" kind of issue

Still relevant 
```
Feedback v3.122.4 - TypeError - UNKNOWN - android



 Client: android
 Type: UNKNOWN
 Tutanota version: 3.122.4
 Timestamp (UTC): Mon, 26 Feb 2024 17:25:35 GMT
 User agent:
Mozilla/5.0 (Linux; Android 14; SM-S908U1 Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6323.0 Mobile Safari/537.36
TypeError
 Error message: Cannot read properties of undefined (reading 'startWebMessageChannel')
Stacktrace: 
TypeError: Cannot read properties of undefined (reading 'startWebMessageChannel')
    at fe.start (https://assets.tutanota.com/native-main-TvFdhlyu.js:1:8256)
    at ve.init (https://assets.tutanota.com/native-main-TvFdhlyu.js:1:8567)
    at https://assets.tutanota.com/app.js:1:86611
```

**Comment by charlag** [comment]
Chrome is up-to-date, Android is not very old, this is really weird

**Comment by nyabinary** [comment]
> Chrome is up-to-date, Android is not very old, this is really weird

tutanota rewrite when ;3 jk, but how can I debug this further?

**Comment by charlag** [comment]
ideally we want to look at the logs (you can get them if you tap on version number below) but I think it will also fail since IPC does not work for you. You would need to build a debug version to see what happens

**Comment by jalhubb** [comment]
outdated/stale

if this still happens, please let us know
