### ISSUE TITLE
Crash on startup Xiaomi MIUI 14.0.2

### ISSUE THREAD

**Issue by macartigan** [tutao/tutanota#5937]
**Bug in mobile app**

**Describe the bug**
Crash on startup from the last update of Xiaomi MIUI 14.0.2

**To Reproduce**
1. Open the app with MIUI 14.0.2
2. App crash: see error below 

**Expected behavior**
The app should start

**Screenshots**
![Screenshot_2023-09-27-08-34-31-222_com google android permissioncontroller](https://github.com/tutao/tutanota/assets/61415619/218646bd-a171-4a1c-8d99-96a47af7633a)

**Smartphone (please complete the following information):**
 - Device: Xiaomi poco 2201116PG
 Client: android
- Tutanota version: 3.118.8
Timestamp (UTC): Wed, 27 Sep 2023 06:43:17 GMT
User agent:
Mozilla/5.0 (Linux; Android 13; 2201116PG Build/TKQ1.221114.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36

**Additional context**
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.tutao.tutanota/de.tutao.tutanota.MainActivity}: java.lang.SecurityException: Unable to start service Intent { cmp=de.tutao.tutanota/.push.PushNotificationService (has extras) }: Unable to launch app de.tutao.tutanota/10440 for service Intent { cmp=de.tutao.tutanota/.push.PushNotificationService }: process is bad
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3909)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4062)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8410)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.SecurityException: Unable to start service Intent { cmp=de.tutao.tutanota/.push.PushNotificationService (has extras) }: Unable to launch app de.tutao.tutanota/10440 for service Intent { cmp=de.tutao.tutanota/.push.PushNotificationService }: process is bad
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1916)
	at android.app.ContextImpl.startService(ContextImpl.java:1874)
	at android.content.ContextWrapper.startService(ContextWrapper.java:827)
	at de.tutao.tutanota.MainActivity.setupPushNotifications(MainActivity.kt:559)
	at de.tutao.tutanota.MainActivity.onCreate(MainActivity.kt:150)
	at android.app.Activity.performCreate(Activity.java:8540)
	at android.app.Activity.performCreate(Activity.java:8504)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1440)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3890)
	... 12 more

**Comment by charlag** [comment]
Is it still happening?

**Comment by macartigan** [comment]
Not anymore (tested on v3.122.4 from play store)
