### ISSUE TITLE
PayloadTooLargeError: request body is too large. Path: /rest/sys/customerproperties

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5948]
```
Client: win32
Tutanota version: 3.118.12
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.118.12 Chrome/116.0.5845.190 Electron/26.2.2 Safari/537.36
PayloadTooLargeError
Error message: request body is too large. Path: /rest/sys/customerproperties/Ku4ka7V--V-0, Method: PUT, Body length: 2327724
Stacktrace:
PayloadTooLargeError: request body is too large. Path: /rest/sys/customerproperties/Ku4ka7V--V-0, Method: PUT, Body length: 2327724
at Ji.checkRequestSizeLimit (asset://app/worker.js:12:25280)
at Ji.request (asset://app/worker.js:12:21476)
at ks.update (asset://app/worker.js:1:29167)
```

**Comment by wrdhub** [comment]
We are not seeing reports of this so much anymore, it looks like we don't need to address this for now.
