### ISSUE TITLE
iOS app crashes upon startup

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#5955]
The iOS App is crashing for some users directly at launch.

This has been reported on iOS versions 15,16 and 17 for Tutanota v3.118.12

**Note**:
some users report that they were able to log in after reinstalling the app, but the crash happens when loading emails for the first time. After that, the app crashes upon startup again. 

## Test
* [ ] try to provoke a network timeout and make sure the app does not crash
* [ ] index a mailbox

**Comment by charlag** [comment]
Might be related:

> every time I open the app it immediately closes. I am also not getting any notifications from my calendar at all.

```
Client: android
Tutanota version: 3.118.12
User agent:
Mozilla/5.0 (Linux; Android 13; Pixel 7 Pro Build/TQ3A.230901.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36
java.lang.IllegalArgumentException
Error message: Not a valid AlarmInterval
Stacktrace:
java.lang.IllegalArgumentException: Not a valid AlarmInterval
at de.tutao.tutanota.alarms.AlarmInterval$Companion.fromString(AlarmInterval.kt:38)
at de.tutao.tutanota.alarms.EncryptedAlarmInfoKt.decrypt(EncryptedAlarmInfo.kt:33)
at de.tutao.tutanota.alarms.AlarmNotificationEntityKt.decrypt(AlarmNotificationEntity.kt:128)
at de.tutao.tutanota.alarms.AlarmNotificationsManager.scheduleNewAlarms(AlarmNotificationsManager.kt:63)
at de.tutao.tutanota.push.AndroidNativePushFacade.scheduleAlarms(AndroidNativePushFacade.kt:52)
at de.tutao.tutanota.ipc.NativePushFacadeReceiveDispatcher.dispatch(NativePushFacadeReceiveDispatcher.kt:51)
at de.tutao.tutanota.ipc.AndroidGlobalDispatcher.dispatch(AndroidGlobalDispatcher.kt:40)
at de.tutao.tutanota.RemoteBridge.invokeMethod(RemoteBridge.kt:153)
at de.tutao.tutanota.RemoteBridge.handleMessageFromWeb(RemoteBridge.kt:90)
at de.tutao.tutanota.RemoteBridge$initMessageChannel$1$onMessage$1.invokeSuspend(RemoteBridge.kt:58)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at [kotlinx.coroutines.DispatchedTask.run](http://kotlinx.coroutines.dispatchedtask.run/)(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by charlag** [comment]
Please note that we should see what the value is in the error message but we don't

**Comment by charlag** [comment]
I checked and iOS must have another reason for crashes which seems to be some concurrency issues in `ApiSchemeHandler` so I extracted Android issue into #5964

**Comment by charlag** [comment]
I did once manage to crash it by putting it into a faraday cage of sorts so we should check that timeouts works again

**Comment by charlag** [comment]
I did reproduce the crash few more times but there's no logs or crash info anywhere, I think it might be another issue
