### ISSUE TITLE
[android] Decryption fails with WRONG_FINAL_BLOCK_LENGTH

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#600]
```
Stacktrace: 
java.lang.RuntimeException: javax.crypto.IllegalBlockSizeException: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
at de.tutao.tutanota.TutaoCipherInputStream.read(TutaoCipherInputStream.java:69)
at java.io.InputStream.read(InputStream.java:162)
at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
at de.tutao.tutanota.Crypto.aesDecrypt(Crypto.java:236)
at de.tutao.tutanota.Crypto.aesDecryptFile(Crypto.java:221)
at de.tutao.tutanota.Native.invokeMethod(Native.java:181)
at de.tutao.tutanota.Native.lambda$invoke$2$Native(Native.java:76)
at de.tutao.tutanota.Native$$Lambda$0.run(Unknown Source)
at java.lang.Thread.run(Thread.java:818)
Caused by: javax.crypto.IllegalBlockSizeException: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
at com.android.org.conscrypt.OpenSSLCipher.doFinalInternal(OpenSSLCipher.java:430)
at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:490)
at javax.crypto.Cipher.doFinal(Cipher.java:1314)
at de.tutao.tutanota.TutaoCipherInputStream.read(TutaoCipherInputStream.java:60)
... 10 more
```

```
Stacktrace: 
java.io.IOException: javax.crypto.IllegalBlockSizeException: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH
at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:133)
at javax.crypto.CipherInputStream.read(CipherInputStream.java:249)
at javax.crypto.CipherInputStream.read(CipherInputStream.java:225)
at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
at de.tutao.tutanota.Crypto.aesDecrypt(Crypto.java:236)
at de.tutao.tutanota.Crypto.aesDecryptFile(Crypto.java:221)
at de.tutao.tutanota.Native.invokeMethod(Native.java:181)
at de.tutao.tutanota.Native.lambda$invoke$2$Native(Native.java:76)
at de.tutao.tutanota.Native$$Lambda$0.run(Unknown Source:4)
at java.lang.Thread.run(Thread.java:764)
Caused by: javax.crypto.IllegalBlockSizeException: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH
at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:596)
at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:398)
at javax.crypto.Cipher.doFinal(Cipher.java:2002)
at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:130)
... 11 more
```

**Comment by mpfau** [comment]
We need to find out if this happens only on certain android versions.

**Comment by armhub** [comment]
Reported only up to version 3.35.4
Reported for Android 5.0, 5.0.1, 5.0.2, 5.1.1

**Comment by charlag** [comment]
Assume tested
