### ISSUE TITLE
TypeError: Cannot read properties of null Error when looking at plans

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#6106]
Seeing a lot of reports of this 

TypeError: Error message: Cannot read properties of null (reading 'Free')

Repro: 
Click the Plan pencil to see available plans. (Confirmed on android)

If we try just to fetch the feature list
```
Refused to connect to 'https://tuta.com/resources/data/features.json' because it violates the following Content Security Policy directive: "connect-src 'self' 'unsafe-inline' https://app.tuta.com wss://app.tuta.com https://*.api.app.tuta.com api://app.tuta.com https://tutanota.com".
```

## Stacktrace
```
error TypeError: Cannot read property 'Free' of null
    at /app.js:24626
    at async FeatureListProvider.init (/app.js:24622)
    at async Function.getInitializedInstance (/app.js:24649)
    at async Promise.all (index 0)
    at async showProgressDialog (/app.js:7417)
    at async showSwitchDialog (/app.js:88309) TypeError: Cannot read property 'Free' of null
    at https://assets.tutanota.com/app.js:24626:46
    at async FeatureListProvider.init (https://assets.tutanota.com/app.js:24622:28)
    at async Function.getInitializedInstance (https://assets.tutanota.com/app.js:24649:11)
    at async Promise.all (index 0)
    at async showProgressDialog (https://assets.tutanota.com/app.js:7417:12)
    at async showSwitchDialog (https://assets.tutanota.com/app.js:88309:57)
```

**Comment by wrdhub** [comment]
It seems that this only occurs on apps with an old version (older that 3.118.25). It's a csp issue trying to access the plans types which have been moved to the new domain.

**Comment by murilopereirame** [comment]
Only happens on old versions, we are not going to fix it
