### ISSUE TITLE
Error: Update failed 5 times

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#6140]
This happens when we try `manualUpdate`. We do not handle the error at all on the client side.

```
Client: darwin
Tutanota version: 3.118.13
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.118.13 Chrome/116.0.5845.190 Electron/26.2.2 Safari/537.36
Error
Error message: Update failed 5 times
Stacktrace:
Error: Update failed 5 times
at At.manualUpdate (/Applications/Tutanota [Desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:1:59066](http://desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:1:59066))
at vT.manualUpdate (/Applications/Tutanota [Desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:2:288426](http://desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:2:288426))
at MT.dispatch (/Applications/Tutanota [Desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:2:294892](http://desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:2:294892))
at BT.dispatch (/Applications/Tutanota [Desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:2:297624](http://desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:2:297624))
at ipc (/Applications/Tutanota [Desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:2:287919](http://desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:2:287919))
at exports.MessageDispatcher.handleMessage (/Applications/Tutanota [Desktop.app/Contents/Resources/app.asar/desktop/NodeWorkerTransport-7c28b2d6.js:1:55142](http://desktop.app/Contents/Resources/app.asar/desktop/NodeWorkerTransport-7c28b2d6.js:1:55142))
at /Applications/Tutanota [Desktop.app/Contents/Resources/app.asar/desktop/NodeWorkerTransport-7c28b2d6.js:1:54251](http://desktop.app/Contents/Resources/app.asar/desktop/NodeWorkerTransport-7c28b2d6.js:1:54251)
at /Applications/Tutanota [Desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:2:280396](http://desktop.app/Contents/Resources/app.asar/desktop/DesktopMain.js:2:280396)
at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89468)
at WebContents.emit (node:events:513:28)
```

## Test Notes
- [ ] The app still searching for updates when startup
- [ ] When a update is available the app can download and install it
- [ ] The user can check for updates
- [ ] If the update fails more than 4 times, every time the user checks for a update it's throttled by (500 * tries)ms
- [ ] If the update fails more than 4 times, it will show a notification

**Comment by ganthern** [comment]
So I downloaded the AppImage 3.119.3 and set the file + folder it is in to read-only.

I still get an  uncaught Update failed 5 times" if I click the "Install Update" button in the desktop settings multiple times (5-6)
