### ISSUE TITLE
TypeError in a worker

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#621]
It must an error in the indexer

```
Stacktrace: 
TypeError: Cannot read property 'indexTimestamp' of undefined
at https://mail.tutanota.com/worker.js:1:271769
at r (https://mail.tutanota.com/libs.js:32:9004)
at i._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:31:14217)
at i._settlePromise (https://mail.tutanota.com/libs.js:31:15020)
at i._settlePromise0 (https://mail.tutanota.com/libs.js:31:15721)
at i._settlePromises (https://mail.tutanota.com/libs.js:31:17051)
at i._fulfill (https://mail.tutanota.com/libs.js:31:16092)
at https://mail.tutanota.com/libs.js:31:4676
at IDBRequest.request.onsuccess (https://mail.tutanota.com/worker.js:1:394517)
```

**Comment by charlag** [comment]
We were not able to reproduce it, assume fixed
