### ISSUE TITLE
App Password stuck in logging in dialog

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#6213]
Desktop issue:
  - If I enable the App Password and try to add an account, cancel when the pin is requested and hit login again, the app stucks at "Logging in..." dialog and I've to restart the app. The same happens if I enter an invalid password.
  - The error in console is "Offline db is closed"
  - On Android we have the same error ```Offline db is close```, but we're able to try to login in again and be prompted for the password

## Steps to Reproduce
1. Enable App Password
2. Logout from the app
3. Try to add a new account
4. Insert the credentials and tap Log in
5. When prompted for the App Password, insert a wrong password or cancel
6. Try to login again

**Stacktrace**
```
OfflineDbClosedError: Offline db is closed
    at get db [as db] (/tmp/.mount_desktoLN1Q6T/resources/app.asar/desktop/sqlworker.js:1:22379)
    at H.get (/tmp/.mount_desktoLN1Q6T/resources/app.asar/desktop/sqlworker.js:1:23353)
    at get (/tmp/.mount_desktoLN1Q6T/resources/app.asar/desktop/sqlworker.js:1:24055)
    at exports.MessageDispatcher.handleMessage (/tmp/.mount_desktoLN1Q6T/resources/app.asar/desktop/NodeWorkerTransport-2612abc5.js:1:60353)
    at /tmp/.mount_desktoLN1Q6T/resources/app.asar/desktop/NodeWorkerTransport-2612abc5.js:1:59462
    at MessagePort.<anonymous> (/tmp/.mount_desktoLN1Q6T/resources/app.asar/desktop/NodeWorkerTransport-2612abc5.js:1:60885)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:737:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
```

Ref. https://github.com/tutao/tutanota/issues/3853

**Comment by murilopereirame** [comment]
During the investigation, we found that the user is logged in even if it cancels the App Password prompt;
Also, if the user returns to the saved credentials page and then try to insert the credentials again, it will be redirected as a logged user after a couple of seconds.
