### ISSUE TITLE
[Android] Could not delete some files on sending 

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#622]
Either encryption failed on the previous step and we don't have the file or there's another reason. We should at least suppress the error.

```
Stacktrace: 
java.lang.Exception: could not delete file file:///data/user/0/de.tutao.tutanota/files/temp/encrypted/clara1.jpg
at de.tutao.tutanota.FileUtil.delete(FileUtil.java:73)
at de.tutao.tutanota.Native.invokeMethod(Native.java:202)
at de.tutao.tutanota.Native.lambda$invoke$2$Native(Native.java:86)
at de.tutao.tutanota.Native$$Lambda$0.run(Unknown Source:4)
at java.lang.Thread.run(Thread.java:764)
```

**Comment by armhub** [comment]
Some more information in order to fix the root cause. This is how to reproduce it:

1. Select two images in Android Gallery
2. Select share via Tutanota
3. Save draft

The error does not occur if you only select one image. It also does not occur if you select the images from the attach button in Tutanota.
