### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'trim') when editing event

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#6230]
```
Client: darwin
Tutanota version: 3.118.30
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.118.30 Chrome/116.0.5845.228 Electron/26.5.0 Safari/537.36
TypeError
Error message: Cannot read properties of undefined (reading 'trim')
Stacktrace:
TypeError: Cannot read properties of undefined (reading 'trim')
at Er (asset://app/common-35eb61f9.js:1:354122)
at ol.setupAttendees (asset://app/date-1c8b0835.js:1:119066)
at new ol (asset://app/date-1c8b0835.js:1:116831)
at asset://app/date-1c8b0835.js:1:136789
at N.whenModel (asset://app/date-1c8b0835.js:1:136464)
at async makeCalendarEventModel (asset://app/date-1c8b0835.js:1:135723)
at async Object.calendarEventModel (asset://app/main-d5ef5d1d.js:1:89098)
at async vr.editAll (asset://app/calendar-view-70482445.js:1:48435)
```

**Comment by ganthern** [comment]
I assume that this is happening in `cleanMailAddress`
It's a missing mail address on an own `EncryptedMailAddress` (normally consisting of name / mail address), on the organizers `EncryptedMailAddress` or on one of the attendees.

did this happen during import, edit or responding to an event?

**Comment by charlag** [comment]
ah it's probably encryption error?

**Comment by fegabe** [comment]
The error is happening when editing or deleting the event. And it's because there is an attendee that is shown as empty, but not sure how I came up into that situation. 

Here is the log without obfuscation

```
error TypeError: Cannot read properties of undefined (reading 'trim')
    at Er (CommonCalendarUtils.ts:99:17)
    at ol.setupAttendees (CalendarEventWhoModel.ts:228:16)
    at new ol (CalendarEventWhoModel.ts:114:8)
    at CalendarEventModel.ts:209:13
    at N.whenModel (CalendarEventModel.ts:282:17)
    at async makeCalendarEventModel (CalendarEventModel.ts:235:8)
    at async Object.calendarEventModel (MainLocator.ts:345:3)
    at async vr.deleteSingle (CalendarEventPopupViewModel.ts:136:10)
    at async click (CalendarEventPopup.ts:59:15) TypeError: Cannot read properties of undefined (reading 'trim')
    at Er (asset://app/common-35eb61f9.js:1:354122)
    at ol.setupAttendees (asset://app/date-1c8b0835.js:1:119066)
    at new ol (asset://app/date-1c8b0835.js:1:116831)
    at asset://app/date-1c8b0835.js:1:136789
    at N.whenModel (asset://app/date-1c8b0835.js:1:136299)
    at async makeCalendarEventModel (asset://app/date-1c8b0835.js:1:135723)
    at async Object.calendarEventModel (asset://app/main-d5ef5d1d.js:1:89098)
    at async vr.deleteSingle (asset://app/calendar-view-70482445.js:1:47836)
    at async click (asset://app/calendar-view-70482445.js:1:43256)
```

Thanks for taking a look!

**Comment by kib42** [comment]
The issue is still happening. It causes weird behavior when editing events.
![image](https://github.com/tutao/tutanota/assets/104761667/44fe52a5-dff2-4b19-9fae-f69be0507a5d)
