### ISSUE TITLE
NotFoundError for Mail: ws error while processing event batches

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#6232]
Is reported multiple times a day, pretty much everywhere, not clear how it happens yet because cache is supposed to handle this.

```
Client: android
Tutanota version: 3.118.27
User agent:
Mozilla/5.0 (Linux; Android 13; CPH2399 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.67 Mobile Safari/537.36
NotFoundError
Error message: 404: | GET /rest/tutanota/mail/MiMcXqY--k-2/NkI4fAV--3-9
Stacktrace:
NotFoundError: 404: | GET /rest/tutanota/mail/MiMcXqY--k-2/NkI4fAV--3-9
at df (https://assets.tutanota.com/common-min-160da492.js:1:10250)
at p.onload (https://assets.tutanota.com/worker.js:12:23410)
```

**Comment by charlag** [comment]
Does not seem to occur anymore
