### ISSUE TITLE
DeviceStorageUnavailableError: safeStorage API is not available - 'Could not access secret storage' in Tuta Mail for linux

### ISSUE THREAD

**Issue by gonviegas** [tutao/tutanota#6265]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
"Could not access secret storage" error since latest Tutanota desktop update

```
Feedback v3.119.3 - DeviceStorageUnavailableError - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.119.3
 Timestamp (UTC): Wed, 06 Dec 2023 13:19:44 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.119.3 Chrome/116.0.5845.228 Electron/26.6.1 Safari/537.36
DeviceStorageUnavailableError
 Error message: failed to resolve/generate key> DeviceStorageUnavailableError: safeStorage API is not available
    at Cw.assertAvailable (/tmp/.mount_tutanowg10CA/resources/app.asar/desktop/DesktopMain.js:5:193395)
    at async Cw.getPassword (/tmp/.mount_tutanowg10CA/resources/app.asar/desktop/DesktopMain.js:5:192606)
    at async Z_.fetchKey (/tmp/.mount_tutanowg10CA/resources/app.asar/desktop/DesktopMain.js:5:210883)
    at async Z_.fetchOrGenerateKey (/tmp/.mount_tutanowg10CA/resources/app.asar/desktop/DesktopMain.js:5:210597)
    at async db.decryptUsingKeychain (/tmp/.mount_tutanowg10CA/resources/app.asar/desktop/DesktopMain.js:5:281703)
    at async ipc (/tmp/.mount_tutanowg10CA/resources/app.asar/desktop/DesktopMain.js:5:292047)
Stacktrace: 
DeviceStorageUnavailableError: failed to resolve/generate key> DeviceStorageUnavailableError: safeStorage API is not available
    at Cw.assertAvailable (/tmp/.mount_tutanowg10CA/resources/app.asar/desktop/DesktopMain.js:5:193395)
    at async Cw.getPassword (/tmp/.mount_tutanowg10CA/resources/app.asar/desktop/DesktopMain.js:5:192606)
    at async Z_.fetchKey (/tmp/.mount_tutanowg10CA/resources/app.asar/desktop/DesktopMain.js:5:210883)
    at async Z_.fetchOrGenerateKey (/tmp/.mount_tutanowg10CA/resources/app.asar/desktop/DesktopMain.js:5:210597)
    at async db.decryptUsingKeychain (/tmp/.mount_tutanowg10CA/resources/app.asar/desktop/DesktopMain.js:5:281703)
    at async ipc (/tmp/.mount_tutanowg10CA/resources/app.asar/desktop/DesktopMain.js:5:292047)
    at Z_.fetchOrGenerateKey (/tmp/.mount_tutanowg10CA/resources/app.asar/desktop/DesktopMain.js:5:210784)
    at async db.decryptUsingKeychain (/tmp/.mount_tutanowg10CA/resources/app.asar/desktop/DesktopMain.js:5:281703)
    at async ipc (/tmp/.mount_tutanowg10CA/resources/app.asar/desktop/DesktopMain.js:5:292047)
```

**To Reproduce**
Trying to login

**Expected behavior**
Being able to login

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 12 (bookworm) x86_64
 - Desktop Environment: dwm

**Additional context**
Only tutanota has problems with keychain and it only started after latest update

**Comment by ganthern** [comment]
Hello :wave: 

Thank you for your report!

If this worked for you before, please try the workaround of adding --password-store="gnome-libsecret" to the command line when starting the AppImage.

other options for this switch can be found here:
https://www.electronjs.org/docs/latest/api/safe-storage#safestoragegetselectedstoragebackend-linux

**Comment by gonviegas** [comment]
Thank you for the quick reply.

It works with ```--password-store="gnome-libsecret"```.

Thanks!

**Comment by ganthern** [comment]
Glad I could help! I'll keep this open for tracking purposes until we release a fix with the next version.

**Comment by galegooo** [comment]
Hello!
I've been having the same problem as OP, and adding `--password-store="gnome-libsecret"` does not work (same error appears).

I'm in Arch Linux, how can I verify what keystore my OS is using? I had no problems in Tutanota until this last update.

If the new update fixes this, when will it be out?

Thank you!

**Comment by charlag** [comment]
It should be either end of this week or beginning of next week

**Comment by kibhub** [comment]
> Hello! I've been having the same problem as OP, and adding `--password-store="gnome-libsecret"` does not work (same error appears).
> 
> I'm in Arch Linux, how can I verify what keystore my OS is using? I had no problems in Tutanota until this last update.
> 
> If the new update fixes this, when will it be out?
> 
> Thank you!

@galegooo if you were able to store credentials before this extra flag should also work. The fix in the next release is actually just defaulting to gnome-libsecret.

Since you are asking about the keyring and have not changed it intentionally, I would assume that you have Gnome's libsecret already installed as it is a dependency for a lot of packages.

**Comment by kibhub** [comment]
tested on dwm and in an kde environment. Works in both cases and on KDE kwallet is used. **Note however that libsecret is installed in both cases.**

**Comment by AaronStiff** [comment]
@kibhub Can confirm that the 3.119.8 Appimage breaks access to secret storage on KDE without libsecret. Got it to work once somehow using the libsecret flag, but even then it was not remembering my credentials.

Any advice? 3.119.3 still works, so I'm fine for now. `apt` can't seem to find a `libsecret` package on Debian...

**Comment by gonviegas** [comment]
On Debian the package is ```libsecret-1-0```

**Comment by AaronStiff** [comment]
@gonviegas Awesome, thanks! Should have taken the time to look at that link myself. Changing "gnome-libsecret" in the flag to "kwallet5" (for KDE 5) fixes this for the 3.119.8 Appimage.

**Comment by pgeyfman** [comment]
Hello, I have the same issue.  Adding the command line parameters does not work around the error.  I'm running Endeavour OS (Arch base) and KDE Plasma.  I tried to delete the Tuta folders from KDE Wallet hoping they would get re-created, but I still have the same issue.

**Comment by kibhub** [comment]
> @kibhub Can confirm that the 3.119.8 Appimage breaks access to secret storage on KDE without libsecret. Got it to work once somehow using the libsecret flag, but even then it was not remembering my credentials.
> 
> Any advice? 3.119.3 still works, so I'm fine for now. `apt` can't seem to find a `libsecret` package on Debian...

This is weird. I have tested this on Kubuntu 22.04 LTS and KDE Neon. Both fresh installs and both have libsecret and libsecret-common preinstalled. 

Version 3.119.8 works out of the box on KDE neon but not on Kubuntu.

**Comment by pgeyfman** [comment]
adding `--password-store=kwallet5` to the command worked for me on KDE Plasma running on  Endeavour OS.  YMMV though.

**Comment by kibhub** [comment]
For KDE issues, please see my comment [here](https://github.com/tutao/tutanota/issues/6312#issuecomment-1866658427)

**Comment by helpisdev** [comment]
I'm currently facing the same issue on Fedora 40, with `libsecret` installed. Tried both with the flag on/off. The app was working just fine for months up until a couple of days ago.

**LOGS:**

```console
v230.240603.0 - linux


 Client: linux
 Type: UNKNOWN
 Tutanota version: 230.240603.0
 Timestamp (UTC): Fri, 07 Jun 2024 09:51:00 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/230.240603.0 Chrome/124.0.6367.207 Electron/30.0.6 Safari/537.36


== MAIN LOG ==
2024-06-07T09:50:53.425Z I "\n\n........................................\n........................................\n........................................\n........@@@@@@@@@@@@@@@@@@@@@@@.........\n.....@....@@@@@@@@@@@@@@@@@@@@@@@.......\n.....@@@....@@@@@@@@@@@@@@@@@@@@@@@.....\n.....@@@@@..............................    Do you care about privacy?\n.....@@@@@...@@@@@@@@@@@@@@@@@@@@@@.....\n.....@@@@...@@@@@@@@@@@@@@@@@@@@@@@.....    Work at Tuta! Fight for our rights!\n.....@@@@...@@@@@@@@@@@@@@@@@@@@@@......\n.....@@@...@@@@@@@@@@@@@@@@@@@@@@.......    https://tuta.com/jobs\n.....@@@...@@@@@@@@@@@@@@@@@@@@@@.......\n.....@@...@@@@@@@@@@@@@@@@@@@@@@........\n.....@@...@@@@@@@@@@@@@@@@@@@@@@........\n.....@...@@@@@@@@@@@@@@@@@@@@@@.........\n.....@...@@@@@@@@@@@@@@@@@@@@@@.........\n........@@@@@@@@@@@@@@@@@@@@@@..........\n.......@@@@@@@@@@@@@@@@@@@@@@...........\n.......@@@@@@@@@@@@@@@@@@@@@@...........\n........................................\n........................................\n........................................\n\n"
2024-06-07T09:50:53.441Z I "error",DeviceStorageUnavailableError
 Error message: failed to resolve/generate key> Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at K_.getPassword (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:192352)
    at async mR.fetchKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:209968)
    at async mR.fetchOrGenerateKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:209695)
    at async _P.decryptUsingKeychain (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:25:16154)
    at async qO.getCredentialsEncryptionKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:286267)
    at async qO.loadByUserId (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:284099)
    at async ipc (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:294946),"DeviceStorageUnavailableError: failed to resolve/generate key> Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.\n    at K_.getPassword (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:192352)\n    at async mR.fetchKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:209968)\n    at async mR.fetchOrGenerateKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:209695)\n    at async _P.decryptUsingKeychain (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:25:16154)\n    at async qO.getCredentialsEncryptionKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:286267)\n    at async qO.loadByUserId (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:284099)\n    at async ipc (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:294946)\n    at mR.fetchOrGenerateKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:209869)\n    at async _P.decryptUsingKeychain (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:25:16154)\n    at async qO.getCredentialsEncryptionKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:286267)\n    at async qO.loadByUserId (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:284099)\n    at async ipc (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:294946)"
2024-06-07T09:50:53.441Z I "Unknown error",DeviceStorageUnavailableError
 Error message: failed to resolve/generate key> Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at K_.getPassword (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:192352)
    at async mR.fetchKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:209968)
    at async mR.fetchOrGenerateKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:209695)
    at async _P.decryptUsingKeychain (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:25:16154)
    at async qO.getCredentialsEncryptionKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:286267)
    at async qO.loadByUserId (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:284099)
    at async ipc (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:294946)
2024-06-07T09:50:53.457Z I "worker init time (ms):",40
2024-06-07T09:50:54.638Z I "error",DeviceStorageUnavailableError
 Error message: failed to resolve/generate key> Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at K_.getPassword (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:192352)
    at async mR.fetchKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:209968)
    at async mR.fetchOrGenerateKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:209695)
    at async _P.decryptUsingKeychain (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:25:16154)
    at async qO.getCredentialsEncryptionKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:286267)
    at async qO.loadByUserId (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:284099)
    at async ipc (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:294946),"DeviceStorageUnavailableError: failed to resolve/generate key> Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.\n    at K_.getPassword (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:192352)\n    at async mR.fetchKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:209968)\n    at async mR.fetchOrGenerateKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:209695)\n    at async _P.decryptUsingKeychain (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:25:16154)\n    at async qO.getCredentialsEncryptionKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:286267)\n    at async qO.loadByUserId (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:284099)\n    at async ipc (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:294946)\n    at mR.fetchOrGenerateKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:209869)\n    at async _P.decryptUsingKeychain (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:25:16154)\n    at async qO.getCredentialsEncryptionKey (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:286267)\n    at async qO.loadByUserId (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:284099)\n    at async ipc (/tmp/.mount_tutanoVcYyoI/resources/app.asar/desktop/DesktopMain.js:11:294946)"
2024-06-07T09:50:56.324Z I "removed topmost modal component"
2024-06-07T09:50:58.186Z I "removed topmost modal component"
2024-06-07T09:50:58.927Z I "removed topmost modal component"

== NATIVE LOG ==
2024-06-07T08:52:38.796Z I "the monkey has been patched pid:",3422
2024-06-07T08:52:40.021Z I "version:  ","230.240603.0"
2024-06-07T08:52:40.103Z I "resolving key...","tutanota-vault"
2024-06-07T08:52:40.106Z I "config up to date"
2024-06-07T08:52:40.128Z I "[2024-06-07T08:52:40.127Z]","using safeStorage with backend","gnome_libsecret"
2024-06-07T08:52:40.163Z I "[DesktopMain]","getting dictionaries from:","https://app.tuta.com/desktop/dictionaries/"
2024-06-07T08:52:40.163Z I "[2024-06-07T08:52:40.163Z]","Create tray:true"
2024-06-07T08:52:40.165Z I "[SSEFacade]","last missed notification check:",{"lastMissedNotificationCheckTime":null}
2024-06-07T08:52:40.165Z I "[ApplicationWindow]","webAssetsPath: ","/tmp/.mount_tutanoVcYyoI/resources/app.asar"
2024-06-07T08:52:40.290Z I "default mailto handler:",false
2024-06-07T08:52:40.291Z I "Webapp ready"
2024-06-07T08:52:40.292Z I "[SSEFacade]","No SSE info"
2024-06-07T08:52:40.294Z I "[2024-06-07T08:52:40.294Z]","[ElectronUpdater]","INFO:","Checking for update"
2024-06-07T08:52:40.294Z I "[2024-06-07T08:52:40.294Z]","[ElectronUpdater]","INFO:","checking-for-update"
2024-06-07T08:52:40.304Z W "Failed to resolve/generate key: ","tutanota-vault",?
2024-06-07T08:52:59.012Z I "[DesktopMain]","spellcheck-dictionary-initialized","en-US"
2024-06-07T08:52:59.019Z I "desktop file exists, checking version..."
2024-06-07T08:52:59.063Z I "[DesktopMain]","getting dictionaries from:","https://app.tuta.com/desktop/dictionaries/"
2024-06-07T08:52:59.066Z I "[DesktopMain]","spellcheck-dictionary-initialized","en-US"
2024-06-07T08:52:59.258Z I "resolving key...","tutanota-credentials"
2024-06-07T08:52:59.259Z W "Failed to resolve/generate key: ","tutanota-credentials",?
2024-06-07T08:52:59.430Z I "[2024-06-07T08:52:59.430Z]","[ElectronUpdater]","INFO:","Update for version 230.240603.0 is not available (latest version: 230.240603.0, downgrade is disallowed)."
2024-06-07T08:52:59.430Z I "[2024-06-07T08:52:59.430Z]","[ElectronUpdater]","INFO:","update not available:",{"version":"230.240603.0","files":[{"url":"tutanota-desktop-linux.AppImage","sha512":"58Bd0yWTxxDyGJ5PL9Fox4lXGjv24sGlaYfAyR/vWaRQsLUNDD1/LL+qqwjp91mpsaPvwu/NoM0J+I8dTmXozw==","size":129643987,"blockMapSize":136679}],"path":"tutanota-desktop-linux.AppImage","sha512":"58Bd0yWTxxDyGJ5PL9Fox4lXGjv24sGlaYfAyR/vWaRQsLUNDD1/LL+qqwjp91mpsaPvwu/NoM0J+I8dTmXozw==","releaseDate":"2024-06-03T16:00:01.195Z","signature":"CbNHmCUXUW587aCEjr9t7qsRFwGwKBbdWMRb2YkPy03Plqg1VIaEcJbiUKqZI93Ava4sDBVZKM0QSGabkYb94WCy/+ladGcDbY3Fr/4WA8tAlYErNyQ45TOGFSFyx39vGf5/8T2whRyjbDMUAHj1EQZ09pgs1Gi9+J/tq1ElgHUF0WxdyNe/TvZDy7U6Auvj2ExnHLHlNExqnsWLXbXNhamnQEgZh75D8sWGi31EEeqFz0l74fXLSSVTzMtNqCbTyZHfb0NZXrIIR/S/wrMbggtiASZGvGkccQRCANgyj8s0pQBe79nUB5elFcaePSNqCGCS9l3+mT/5CSRMCqDBzA=="}
2024-06-07T09:40:59.937Z I "[ApplicationWindow]","webAssetsPath: ","/tmp/.mount_tutanoVcYyoI/resources/app.asar"
2024-06-07T09:41:00.078Z I "resolving key...","tutanota-credentials"
2024-06-07T09:41:00.078Z W "Failed to resolve/generate key: ","tutanota-credentials",?
2024-06-07T09:43:13.393Z I "[ApplicationWindow]","webAssetsPath: ","/tmp/.mount_tutanoVcYyoI/resources/app.asar"
2024-06-07T09:43:13.534Z I "resolving key...","tutanota-credentials"
2024-06-07T09:43:13.535Z W "Failed to resolve/generate key: ","tutanota-credentials",?
2024-06-07T09:43:17.353Z I "resolving key...","tutanota-credentials"
2024-06-07T09:43:17.353Z W "Failed to resolve/generate key: ","tutanota-credentials",?
2024-06-07T09:44:04.966Z I "[ApplicationWindow]","webAssetsPath: ","/tmp/.mount_tutanoVcYyoI/resources/app.asar"
2024-06-07T09:44:05.100Z I "resolving key...","tutanota-credentials"
2024-06-07T09:44:05.101Z W "Failed to resolve/generate key: ","tutanota-credentials",?
2024-06-07T09:46:40.596Z I "[ApplicationWindow]","webAssetsPath: ","/tmp/.mount_tutanoVcYyoI/resources/app.asar"
2024-06-07T09:46:40.725Z I "resolving key...","tutanota-credentials"
2024-06-07T09:46:40.726Z W "Failed to resolve/generate key: ","tutanota-credentials",?
2024-06-07T09:50:53.314Z I "[ApplicationWindow]","webAssetsPath: ","/tmp/.mount_tutanoVcYyoI/resources/app.asar"
2024-06-07T09:50:53.439Z I "resolving key...","tutanota-credentials"
2024-06-07T09:50:53.440Z W "Failed to resolve/generate key: ","tutanota-credentials",?
```

**Comment by Binary-Ape** [comment]
I have been seeing the same type of issue on Fedora 40 @helpisdev .

Looking at this post

> For KDE issues, please see my comment [here](https://github.com/tutao/tutanota/issues/6312#issuecomment-1866658427)


The linked comment has this statement:
`On older version, please use the --password-store="kwallet5" for the time being until your distro ships the mentioned KDE frameworks version.

If you encounter any issues, please remove the ~/.config/tutanota-desktop folder, which removes all locally stored data for the client and try again, regardless of whether you need to use the cli flag or not.`


1.  I removed the `~/.config/tutanota-desktop` folder and all contents
2. I started up the AppImage with  the `--password-store="kwallet5`

**Comment by marcSoda** [comment]
This should not be closed. I am on arch linux. The issue persists on the AUR install and the appimage regardless of running with the --password-store flag.
