### ISSUE TITLE
Renaming a contact list is not possible

### ISSUE THREAD

**Issue by vaf-hub** [tutao/tutanota#6388]
Renaming a contact list is not possible: 403 NotAuthorized

**To Reproduce**
1. Create a new contact list.
2. Share it with someone else (manage permissions).
3. Edit the list and try renaming it.
4. See the uncaught error below. Also notice that the list was renamed in the UI.
5. Log out and login again. See that the list name is back to what it was originally.

``` 
I 10:44:06.578 sys RootHandler.java:573 GENERATED_ID GENERATED_ID  - PUT /rest/sys/groupinfo/GENERATED_ID/GENERATED_ID/ 
de.tutao.tutadb.rest.exceptions.NotAuthorizedException: 
	at de.tutao.tutadb.system.service.PermissionService.checkAuthorization(PermissionService.java:505)
	at de.tutao.tutadb.instance.resources.DefaultListElementResource.lambda$put$12(DefaultListElementResource.java:323)
	at de.tutao.tutadb.instance.Locker.doWithLock(Locker.java:53)
	at de.tutao.tutadb.instance.resources.DefaultListElementResource.lambda$put$13(DefaultListElementResource.java:314)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at de.tutao.tutadb.instance.resources.ResourceUtils$1.onAllDataRead(ResourceUtils.java:75)
	at org.eclipse.jetty.server.HttpInput.run(HttpInput.java:411)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:589)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:558)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:379)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Expected behavior**
Renaming works without errors and persists logouts. It will also be used for new shares.

Tested with the linux-desktop 3.120.6.

## Test notes
- [ ] Create a contact list with a user that is not an admin of the customer
- [ ] Edit the contact list name
- [ ] Verify that it edits successfully
- [ ] Create a calendar with this user
- [ ] Edit the calendar name
- [ ] Verify it still edits successfully

Fixed in tutadb#567

**Comment by mpfau** [comment]
Implemented with tutadb#935
