### ISSUE TITLE
Unable to store email and password locally in Kubuntu Linux

### ISSUE THREAD

**Issue by sang-shelton** [tutao/tutanota#6419]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

---

**Describe the bug**
When running `tutanota-desktop-linux.AppImage`, i enter the email and password, everything works fine except that email and password are not stored and i have to re-enter them everytime i reopen the window or the application.

<details><summary>Output of ./tutanota-desktop-linux.AppImage</summary>
<p>

```
the monkey has been patched pid: 104709
(node:104709) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `tutanota-desktop --trace-deprecation ...` to show where the warning was created)
version:   3.120.6
resolving key... tutanota-vault
config up to date
[2024-01-22T11:17:43.786Z] using safeStorage with backend gnome_libsecret
[2024-01-22T11:17:43.849Z] Create tray:true
sseInfo corrupted or not present, making sure pushEncSessionKeys and scheduled alarms are cleared
Resetting stored state
[ApplicationWindow] webAssetsPath:  /tmp/.mount_tutanoZSVmJb/resources/app.asar
[ApplicationWindow] getting dictionaries from: https://app.tuta.com/desktop/dictionaries/
default mailto handler: false
Webapp ready
[2024-01-22T11:17:43.932Z] [ElectronUpdater] INFO: Checking for update
[2024-01-22T11:17:43.933Z] [ElectronUpdater] INFO: checking-for-update
[ApplicationWindow] spellcheck-dictionary-initialized en-US
/home/user/.local/share/applications/tutanota-desktop.desktop does not exist, checking for permission to ask for permission...
[DesktopWindowManager] invalidating alarms for all windows
[DesktopWindowManager] invalidating alarms for window 1
[2024-01-22T11:17:44.398Z] [ElectronUpdater] INFO: Update for version 3.120.6 is not available (latest version: 3.120.6, downgrade is disallowed).
[2024-01-22T11:17:44.398Z] [ElectronUpdater] INFO: update not available: {
  version: '3.120.6',
  files: [
    {
      url: 'tutanota-desktop-linux.AppImage',
      sha512: 'mFOnXFGMPJm+aZX/WuTNnbE5wO3P+g1A0295lwPm0tV3hgc88u3rjOQI8YSlA==',
      size: 117543732,
      blockMapSize: 123720
    }
  ],
  path: 'tutanota-desktop-linux.AppImage',
  sha512: 'mFOnXFGMPJm+aZX/WuTNnyIkmLgPbJdMYs4xs0k+uSEVshgc88u3rjOQI8YSlA==',
  releaseDate: '2024-01-15T12:28:23.234Z',
  signature: 'HN9UKqbq7bq9H67k4b3Apa6RNKTVAlfH2pjkb4ERwIC4JA2+XqatiMTygDjukPamqocgCDOVZqqfHSIpRvr/QUwScSqM3/3zsVfH+lVLkX3q7A/I3BkmuzVWzBNXjJsm+stg+u+Is1fdtTGMqxvrqhtD1tItecfwwRDKXg0OVR0XdP/Y8YV5DiFrcTTpv9iluE3sZU36qrJaNQ5TieXLs1K+x8WMgcY5FJCK2Zp0/Veavjng/Felo2UYbr1+PORXTd7o8MKeEJnnFVWbxHeSQRGhc4H4mTR+8vcDoo1Q=='
}
scheduling to check sse in 1 seconds
scheduling to check sse in 1 seconds
scheduling to check sse in 10 seconds
sse info not available, skip reconnect
[2024-01-22T11:17:56.164Z] [WorkerSqlCipher] started sqlcipher-worker-1
[2024-01-22T11:17:56.196Z] [sqlcipher-worker-1] set up sql cipher done
scheduling to check sse in 10 seconds
sse info not available, skip reconnect
resolving key... tutanota-credentials
sseInfo corrupted or not present, making sure pushEncSessionKeys and scheduled alarms are cleared
Resetting stored state
[DesktopWindowManager] invalidating alarms for all windows
[DesktopWindowManager] invalidating alarms for window 1
storing push identifier
[DesktopWindowManager] couldn't invalidate alarms for window 1 y [CryptoError]: Illegal key length: 0 (expected: 128,256)
    at Dt (/tmp/.mount_tutanoZSVmJb/resources/app.asar/desktop/DesktopMain.js:1:43056)
    at St (/tmp/.mount_tutanoZSVmJb/resources/app.asar/desktop/DesktopMain.js:1:41615)
    at Object.aesEncrypt (/tmp/.mount_tutanoZSVmJb/resources/app.asar/desktop/DesktopMain.js:5:206318)
    at Object.aesEncryptObject (/tmp/.mount_tutanoZSVmJb/resources/app.asar/desktop/DesktopMain.js:17:128697)
    at me.setEncryptedVar (/tmp/.mount_tutanoZSVmJb/resources/app.asar/desktop/DesktopMain.js:1:24891)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async me.setVar (/tmp/.mount_tutanoZSVmJb/resources/app.asar/desktop/DesktopMain.js:1:25190)
    at async Hb.storePushIdentifierLocally (/tmp/.mount_tutanoZSVmJb/resources/app.asar/desktop/DesktopMain.js:5:294280)
    at async ipc (/tmp/.mount_tutanoZSVmJb/resources/app.asar/desktop/DesktopMain.js:5:297200) {
  data: undefined
}
scheduling to check sse in 1 seconds
storing push identifier
scheduling to check sse in 10 seconds
sse info not available, skip reconnect
scheduling to check sse in 10 seconds
sse info not available, skip reconnect
```

</p>
</details> 

<details><summary>The error shown in the report inside the app</summary>
<p>

```
Feedback v3.120.6 - CryptoError - FREE - linux
Client: linux
Type: FREE
Tutanota version: 3.120.6
Timestamp (UTC): Mon, 22 Jan 2024 11:17:59 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.120.6 Chrome/116.0.5845.228 Electron/26.6.5 Safari/537.36
CryptoError
Error message: Illegal key length: 0 (expected: 128,256)
Stacktrace:
CryptoError: Illegal key length: 0 (expected: 128,256)
at Dt (/tmp/.mount_tutanoZSVmJb/resources/app.asar/desktop/DesktopMain.js:1:43056)
at St (/tmp/.mount_tutanoZSVmJb/resources/app.asar/desktop/DesktopMain.js:1:41615)
at Object.aesEncrypt (/tmp/.mount_tutanoZSVmJb/resources/app.asar/desktop/DesktopMain.js:5:206318)
at Object.aesEncryptObject (/tmp/.mount_tutanoZSVmJb/resources/app.asar/desktop/DesktopMain.js:17:128697)
at me.setEncryptedVar (/tmp/.mount_tutanoZSVmJb/resources/app.asar/desktop/DesktopMain.js:1:24891)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async me.setVar (/tmp/.mount_tutanoZSVmJb/resources/app.asar/desktop/DesktopMain.js:1:25190)
at async Hb.storePushIdentifierLocally (/tmp/.mount_tutanoZSVmJb/resources/app.asar/desktop/DesktopMain.js:5:294280)
at async ipc (/tmp/.mount_tutanoZSVmJb/resources/app.asar/desktop/DesktopMain.js:5:297200)
```

</p>
</details> 

---

**Desktop (please complete the following information):**
<details><summary>System info (inxi -Faz)</summary>
<p>

```
System:
  Kernel: 6.7.1-060701-generic arch: x86_64 bits: 64 compiler: N/A
    clocksource: tsc available: acpi_pm
    parameters: BOOT_IMAGE=/vmlinuz-6.7.1-060701-generic
    root=/dev/mapper/vgkubuntu-root ro quiet splash vt.handoff=7
  Desktop: KDE Plasma v: 5.27.8 tk: Qt v: 5.15.10 wm: kwin_x11 vt: 2
    dm: SDDM Distro: Ubuntu 23.10 (Mantic Minotaur)
Machine:
  Type: Laptop System: ASUSTeK product: ROG Strix G614JU_G614JU v: 1.0
    serial: <superuser required>
  Mobo: ASUSTeK model: G614JU v: 1.0 serial: <superuser required>
    UEFI: American Megatrends LLC. v: G614JU.321 date: 10/24/2023
Battery:
  ID-1: BAT0 charge: 84.9 Wh (100.0%) condition: 84.9/90.0 Wh (94.3%)
    volts: 17.4 min: 16.0 model: AS3GYFG3KC R220358 type: Unknown
    serial: <filter> status: full
CPU:
  Info: model: 13th Gen Intel Core i9-13980HX bits: 64 type: MST AMCP
    arch: Raptor Lake gen: core 13 level: v3 note: check built: 2022+
    process: Intel 7 (10nm) family: 6 model-id: 0xB7 (183) stepping: 1
    microcode: 0x11D
  Topology: cpus: 1x cores: 24 mt: 8 tpc: 2 st: 16 threads: 32 smt: enabled
    cache: L1: 2.1 MiB desc: d-16x32 KiB, 8x48 KiB; i-8x32 KiB, 16x64 KiB
    L2: 32 MiB desc: 8x2 MiB, 4x4 MiB L3: 36 MiB desc: 1x36 MiB
  Speed (MHz): avg: 832 high: 1152 min/max: 800/5400:5600:4000 scaling:
    driver: intel_pstate governor: powersave cores: 1: 800 2: 800 3: 800 4: 800
    5: 800 6: 800 7: 927 8: 800 9: 800 10: 956 11: 899 12: 800 13: 882 14: 800
    15: 929 16: 800 17: 800 18: 891 19: 1152 20: 800 21: 800 22: 800 23: 800
    24: 800 25: 800 26: 800 27: 800 28: 800 29: 800 30: 800 31: 800 32: 800
    bogomips: 154828
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
  Vulnerabilities:
  Type: gather_data_sampling status: Not affected
  Type: itlb_multihit status: Not affected
  Type: l1tf status: Not affected
  Type: mds status: Not affected
  Type: meltdown status: Not affected
  Type: mmio_stale_data status: Not affected
  Type: retbleed status: Not affected
  Type: spec_rstack_overflow status: Not affected
  Type: spec_store_bypass mitigation: Speculative Store Bypass disabled via
    prctl
  Type: spectre_v1 mitigation: usercopy/swapgs barriers and __user pointer
    sanitization
  Type: spectre_v2 mitigation: Enhanced / Automatic IBRS, IBPB:
    conditional, RSB filling, PBRSB-eIBRS: SW sequence
  Type: srbds status: Not affected
  Type: tsx_async_abort status: Not affected
Graphics:
  Device-1: Intel Raptor Lake-S UHD Graphics vendor: ASUSTeK driver: i915
    v: kernel arch: Gen-13 process: Intel 7 (10nm) built: 2022+ ports:
    active: eDP-1 empty: DP-1, DP-2, HDMI-A-1, HDMI-A-2 bus-ID: 0000:00:02.0
    chip-ID: 8086:a788 class-ID: 0300
  Device-2: NVIDIA AD107M [GeForce RTX 4050 Max-Q / Mobile]
    vendor: ASUSTeK GN21-X2 driver: nvidia v: 535.146.02
    alternate: nvidiafb,nouveau,nvidia_drm non-free: 535.xx+
    status: current (as of 2023-08) arch: Lovelace code: AD1xx
    process: TSMC n4 (5nm) built: 2022-23+ ports: active: none
    empty: DP-3,HDMI-A-3,eDP-2 bus-ID: 0000:01:00.0 chip-ID: 10de:28e1
    class-ID: 0300
  Device-3: Sonix USB2.0 HD UVC WebCam driver: uvcvideo type: USB rev: 2.0
    speed: 480 Mb/s lanes: 1 mode: 2.0 bus-ID: 1-8:3 chip-ID: 322e:2122
    class-ID: 0e02
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 23.2.0
    compositor: kwin_x11 driver: X: loaded: modesetting,nvidia
    unloaded: fbdev,nouveau,vesa dri: iris gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1680x1050 s-dpi: 98 s-size: 436x273mm (17.17x10.75")
    s-diag: 514mm (20.25")
  Monitor-1: eDP-1 model: TL160ADMP03-0 built: 2022 res: 1680x1050 hz: 60
    dpi: 124 gamma: 1.2 size: 345x215mm (13.58x8.46") diag: 407mm (16")
    ratio: 16:10 modes: 2560x1600
  API: OpenGL v: 4.6 Mesa 23.2.1-1ubuntu3.1 renderer: Mesa Intel Graphics
    (RPL-S) direct-render: Yes
Audio:
  Device-1: Intel vendor: ASUSTeK driver: snd_hda_intel v: kernel
    alternate: snd_sof_pci_intel_tgl bus-ID: 0000:00:1f.3 chip-ID: 8086:7a50
    class-ID: 0403
  Device-2: NVIDIA vendor: ASUSTeK driver: snd_hda_intel v: kernel
    bus-ID: 0000:01:00.1 chip-ID: 10de:22be class-ID: 0403
  API: ALSA v: k6.7.1-060701-generic status: kernel-api
    tools: alsactl,alsamixer,amixer
  Server-1: PipeWire v: 0.3.79 status: active with: 1: pipewire-pulse
    status: active 2: wireplumber status: active 3: pipewire-alsa type: plugin
    tools: pactl,pw-cat,pw-cli,wpctl
Network:
  Device-1: Intel driver: iwlwifi v: kernel port: N/A bus-ID: 0000:00:14.3
    chip-ID: 8086:7a70 class-ID: 0280
  IF: wlo1 state: up mac: <filter>
  Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    vendor: ASUSTeK driver: r8169 v: kernel port: 4000 bus-ID: 0000:6c:00.0
    chip-ID: 10ec:8168 class-ID: 0200
  IF: enp108s0 state: down mac: <filter>
Bluetooth:
  Device-1: Intel driver: btusb v: 0.8 type: USB rev: 2.0 speed: 12 Mb/s
    lanes: 1 mode: 1.1 bus-ID: 1-14:4 chip-ID: 8087:0033 class-ID: e001
  Report: hciconfig ID: hci0 rfk-id: 0 state: down
    bt-service: enabled,running rfk-block: hardware: no software: yes
    address: <filter>
  Info: acl-mtu: 1021:4 sco-mtu: 96:6 link-policy: rswitch sniff
    link-mode: peripheral accept
RAID:
  Hardware-1: Intel Volume Management Device NVMe RAID Controller Intel
    driver: vmd v: 0.6 port: N/A bus-ID: 0000:00:0e.0 chip-ID: 8086:a77f rev:
    class-ID: 0104
Drives:
  Local Storage: total: 953.87 GiB used: 276 GiB (28.9%)
  SMART Message: Unable to run smartctl. Root privileges required.
  ID-1: /dev/nvme0n1 maj-min: 259:0 vendor: Micron model: 2400 MTFDKBA1T0QFM
    size: 953.87 GiB block-size: physical: 512 B logical: 512 B speed: 63.2 Gb/s
    lanes: 4 tech: SSD serial: <filter> fw-rev: V3MA003 temp: 44.9 C
    scheme: GPT
Partition:
  ID-1: / raw-size: 929.41 GiB size: 913.75 GiB (98.31%)
    used: 275.16 GiB (30.1%) fs: ext4 dev: /dev/dm-1 maj-min: 252:1
    mapped: vgkubuntu-root
  ID-2: /boot raw-size: 1.67 GiB size: 1.61 GiB (96.26%)
    used: 815.8 MiB (49.6%) fs: ext4 dev: /dev/nvme0n1p2 maj-min: 259:2
  ID-3: /boot/efi raw-size: 512 MiB size: 511 MiB (99.80%)
    used: 43.2 MiB (8.5%) fs: vfat dev: /dev/nvme0n1p1 maj-min: 259:1
Swap:
  Kernel: swappiness: 60 (default) cache-pressure: 100 (default) zswap: no
  ID-1: swap-1 type: partition size: 1.91 GiB used: 0 KiB (0.0%)
    priority: -2 dev: /dev/dm-2 maj-min: 252:2 mapped: vgkubuntu-swap_1
Sensors:
  System Temperatures: cpu: 42.0 C mobo: N/A
  Fan Speeds (rpm): cpu: 0
Info:
  Processes: 517 Uptime: 3h 37m wakeups: 3 Memory: total: 24 GiB note: est.
  available: 23.09 GiB used: 5.64 GiB (24.4%) Init: systemd v: 253
  target: graphical (5) default: graphical tool: systemctl Compilers:
  gcc: 13.2.0 alt: 12/13 clang: 16.0.6 Packages: 3323 pm: dpkg pkgs: 3297
  libs: 2074 tools: apt,apt-get,aptitude pm: flatpak pkgs: 20 pm: snap pkgs: 6
  Shell: Bash v: 5.2.15 running-in: konsole inxi: 3.3.29
```

</p>
</details>

---

**Additional context**
1. I have tried installing these `libsecret-1-0`, `libsecret-1-dev`, `libsecret-common`, `libsecret-tools`
2. Tried installing `gnome-keyring`
3. Tried `./tutanota-desktop-linux.AppImage --password-store="kwallet5"` and `./tutanota-desktop-linux.AppImage --password-store="gnome-libsecret"`
4. I DO NOT get this ⬇️
<details><summary>🖼️</summary>
<p>

![Screenshot_20240122_151942](https://github.com/tutao/tutanota/assets/154356073/d2317419-f9c0-4e73-a6eb-d1bb1e938922)

</p>
</details>

**Comment by sebastiansalo** [comment]
same here have had problems ever since they modified where they store keys

**Comment by ganthern** [comment]
hey there :wave:

It's probably not going to work in this case, but did you already try to completely delete your apps user data? it's stored in `~/.config/tutanota-desktop` by default.

**Comment by sang-shelton** [comment]
> hey there 👋
> 
> It's probably not going to work in this case, but did you already try to completely delete your apps user data? it's stored in `~/.config/tutanota-desktop` by default. And do any of the password manangers on the system (like seahorse) show any tuta-related keys?

Yes i tried doing so, found this idea in one of the issues. Still no fix.

**Comment by kibhub** [comment]
This does not look like a secret storage issue. Please contact us at Support with your Tuta address so we could check your account.

**Comment by charlag** [comment]
Deleting `~/.config/tutanota-desktop` should help unless it's a flatpak

**Comment by sang-shelton** [comment]
I switched to Ubuntu (Gnome) and it now works fine

**Comment by sang-shelton** [comment]
Also on [MX Linux 23.2](https://mxlinux.org/) the tutanota app works fine.

**Comment by astrodv** [comment]
Can confirm on Linux (kernel 6.10.5) , AppImage.  (Gnome)
Delete `~/.config/tutanota-desktop`
