### ISSUE TITLE
Errorneously caching index.html on custom domains in ServiceWorker

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#662]
```
TypeError: Module instantiation did not call an anonymous or correctly named System.register.
at https://mail.journalist.dk/libs.js:36:3638
at r (https://mail.journalist.dk/libs.js:32:9004)
at i.22.e.exports.i._settlePromiseFromHandler (https://mail.journalist.dk/libs.js:31:14217)
at i.22.e.exports.i._settlePromise (https://mail.journalist.dk/libs.js:31:15020)
at i.22.e.exports.i._settlePromise0 (https://mail.journalist.dk/libs.js:31:15721)
at i.22.e.exports.i._settlePromises (https://mail.journalist.dk/libs.js:31:17051)
at r.2.r._drainQueue (https://mail.journalist.dk/libs.js:30:3056)
at r.2.r._drainQueues (https://mail.journalist.dk/libs.js:30:3117)
at 2.drainQueues (https://mail.journalist.dk/libs.js:30:1238)
```

**Comment by mpfau** [comment]
Fixed on server side (switched cache-control header to "no-store")
