### ISSUE TITLE
TypeError for List

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#663]
```
TypeError: Cannot read property '_id' of undefined
at getLetId (https://mail.tutanota.com/common.js:1:140266)
at List.value (https://mail.tutanota.com/main.js:1:642727)
at List.value (https://mail.tutanota.com/main.js:1:648545)
at https://mail.tutanota.com/main.js:1:655867
at r (https://mail.tutanota.com/libs.js:32:9669)
at i.22.e.exports.i._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:31:14830)
at i.22.e.exports.i._settlePromise (https://mail.tutanota.com/libs.js:31:15633)
at i.22.e.exports.i._settlePromiseCtx (https://mail.tutanota.com/libs.js:31:16141)
at c (https://mail.tutanota.com/libs.js:30:1610)
at a (https://mail.tutanota.com/libs.js:30:1496)
at r.2.r._drainQueues (https://mail.tutanota.com/libs.js:30:3106)
at 2.drainQueues (https://mail.tutanota.com/libs.js:30:1238)
```

**Comment by armhub** [comment]
We were not able to reproduce it, assume fixed
