### ISSUE TITLE
"The connection to the server was lost, please try again" and "Your security key is not registered for this domain"

### ISSUE THREAD

**Issue by Opening-Button-8988** [tutao/tutanota#6669]
**Describe the bug**
Two problems.
1. In desktop appimage, latest version (218.240305.0 (Desktop)), I get the error when attempting to sign in, "The connection to the server was lost, please try again". I have provided the logs below.
2. In browser (both Desktop and Android), I get the following error.

> Please accept this login from another tab or via the app.
> Your security key is not registered for this domain. Please login in another tab at tutanota.com.
> Then login here again and accept the login from the other tab.

I followed the instructions but I got the same error. I don't understand the error "your security key is not registered for this domain". I had the security key that I use to secure my account inserted. My key isn't the problem. And my OS can't be the problem either, because I got the same error on Android. And it can't be any USB hub because I used different ones for both desktop and android. And there's nothing wrong with my key because I can use it elsewhere. I've also only just started to get this error, I was able to log in using the same key, on the same account, a few days ago. It also doesn't make sense because the client shouldn't be able to have that information about my key until I tap it.

**To Reproduce**
1. Go to go desktop appimage Linux app, or Android client, or browser
2. Enter credentials
5. Click on Add Account
7. See error

**Expected behavior**
A 2FA popup asking me for my hardware key second factor, and then sign in.

**Screenshots**
I can't provide a screenshot without revealing my account email, and it would just be an image of the error I've already provided above.

**Desktop (please complete the following information):**
 - OS: Linux (Fedora)
 - Gnome 45.4
 - Workstation 39

**Additional context**

Log below.

 ```
Client: linux
 Type: UNKNOWN
 Tutanota version: 218.240305.0
 Timestamp (UTC): Wed, 06 Mar 2024 04:51:17 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/218.240305.0 Chrome/122.0.6261.57 Electron/29.0.1 Safari/537.36


== MAIN LOG ==
2024-03-06T04:51:10.296Z I "\n\n''''''''''''''''''''''''''''''''''''''''\n''''''''''''''''''''''''''''''''''''''''\n''''''''''''''''''''''''''''''''''''''''\n''''''''''''''''''''''''''''''''''''''''\n''''''''''''''''''''''''''''''''''''''''\n''''''''''''''''''''''''''''''''''''''''\n''''''''''''''''''''''''',:,''''''''''''\n''''''''''''';:llllcccccccc,''''''''''''    Do you care about privacy?\n'''''''''''':kXWXkoc::;,,'''''''''''''''\n'''''''''''',cdk0KKK00kxdolc;,''''''''''    Work at Tuta! Fight for our rights!\n'''''''''''''''';coxOKNMMWWNK0kdl:,'''''\n'''''''''''''''''''',;oKMMMMMMMMWX0dc,''    https://tuta.com/jobs\n'''''''''''''''''''''';kWMMMMMMMMMMWXk:'\n'''''''''''''''''''',:xXMMMMMMMMMMMMMWKl\n''''''''''''''''';lk0KWMMMMMMMMMMMMMMMWK\n''''''''''''';cdOKWMMMMMMMMMMMMMMMMMMMMM\n'''''''',:ldOKNWMMMMMMMMMMMMMMMMMMMMMMMM\n''',:ldk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nldk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\n"
2024-03-06T04:51:10.310Z I "worker init time (ms):",69
2024-03-06T04:51:11.284Z I "removed topmost modal component"

== WORKER LOG ==
2024-03-06T04:51:10.707Z I "[RestClient]","failed request","GET","https://app.tuta.com/rest/sys/user/[redacted]",0,"",["accessToken","v","cv","Accept"],"no body"
2024-03-06T04:51:10.707Z I "ws close closeOption: ","terminate","state:","terminated"
2024-03-06T04:51:10.708Z I "[RestClient]","failed request","GET","https://app.tuta.com/rest/sys/user/[redacted]",0,"",["accessToken","v","cv","Accept"],"no body"

== NATIVE LOG ==
2024-03-06T04:51:09.197Z I "the monkey has been patched pid:",105833
2024-03-06T04:51:09.446Z I "version:  ","218.240305.0"
2024-03-06T04:51:09.565Z I "resolving key...","tutanota-vault"
2024-03-06T04:51:09.567Z I "config up to date"
2024-03-06T04:51:09.600Z I "[2024-03-06T04:51:09.599Z]","using safeStorage with backend","gnome_libsecret"
2024-03-06T04:51:09.682Z I "[2024-03-06T04:51:09.682Z]","Create tray:true"
2024-03-06T04:51:09.684Z I "[ApplicationWindow]","webAssetsPath: ","/tmp/.mount_tutano7BR03m/resources/app.asar"
2024-03-06T04:51:09.792Z I "[ApplicationWindow]","getting dictionaries from:","https://app.tuta.com/desktop/dictionaries/"
2024-03-06T04:51:09.796Z I "[DesktopSseClient]","scheduling to check sse in",1,"seconds"
2024-03-06T04:51:09.808Z I "default mailto handler:",false
2024-03-06T04:51:09.808Z I "Webapp ready"
2024-03-06T04:51:09.811Z I "[2024-03-06T04:51:09.811Z]","[ElectronUpdater]","INFO:","Checking for update"
2024-03-06T04:51:09.811Z I "[2024-03-06T04:51:09.811Z]","[ElectronUpdater]","INFO:","checking-for-update"
2024-03-06T04:51:09.829Z I "[ApplicationWindow]","spellcheck-dictionary-initialized","en-GB"
2024-03-06T04:51:09.841Z I "desktop file exists, checking version..."
2024-03-06T04:51:10.295Z I "resolving key...","tutanota-credentials"
2024-03-06T04:51:10.314Z I "[PerWindowSqlCipherFacade]","open db for","[redacted]"
2024-03-06T04:51:10.316Z I "[2024-03-06T04:51:10.316Z]","[WorkerSqlCipher]","started sqlcipher-worker-1"
2024-03-06T04:51:10.377Z I "[2024-03-06T04:51:10.377Z]","[sqlcipher-worker-1]","set up sql cipher done"
2024-03-06T04:51:10.698Z I "[ProtocolProxy]","error for GET https://app.tuta.com/rest/sys/user/[redacted]:"
2024-03-06T04:51:10.705Z I "[ProtocolProxy]",?
2024-03-06T04:51:10.705Z I "[ProtocolProxy]","{\"name\":\"TypeError\",\"message\":\"fetch failed\",\"stack\":\"TypeError: fetch failed\\n    at /tmp/.mount_tutano7BR03m/resources/app.asar/desktop/DesktopMain.js:10:29051\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async /tmp/.mount_tutano7BR03m/resources/app.asar/desktop/DesktopMain.js:10:29559\\n    at async AsyncFunction.<anonymous> (node:electron/js2c/browser_init:2:47442)\"}"
2024-03-06T04:51:10.705Z I "[ProtocolProxy]","failed after 279ms"
2024-03-06T04:51:10.708Z I "[PerWindowSqlCipherFacade]","close db for","[redacted]"
2024-03-06T04:51:10.709Z I "[2024-03-06T04:51:10.709Z]","[OfflineDbRefCounter]","closed db for","[redacted]"
2024-03-06T04:51:10.796Z I "[DesktopSseClient]","last missed notification check:",{"lastMissedNotificationCheckTime":1709265577726}
2024-03-06T04:51:10.796Z I "[DesktopSseClient]","scheduling to check sse in",107,"seconds"
2024-03-06T04:51:10.797Z I "[DesktopSseClient]","starting sse connection"
2024-03-06T04:51:10.811Z I "lookup sse request"
2024-03-06T04:51:10.811Z I "lookup sse request"
2024-03-06T04:51:11.063Z E "[2024-03-06T04:51:11.063Z]","sse error:",""
2024-03-06T04:51:11.181Z I "[2024-03-06T04:51:11.181Z]","[ElectronUpdater]","INFO:","Update for version 218.240305.0 is not available (latest version: 218.240305.0, downgrade is disallowed)."
2024-03-06T04:51:11.181Z I "[2024-03-06T04:51:11.181Z]","[ElectronUpdater]","INFO:","update not available:",{"version":"218.240305.0","files":[{"url":"tutanota-desktop-linux.AppImage","sha512":"LLTH0SPsho90vWFqrUweFTGii2Rdb/LhVA90c5XlrcwyGP9a2u5sRRPvIdTYop6A5HZru33Gx19lm8X4kfph5Q==","size":123432632,"blockMapSize":130764}],"path":"tutanota-desktop-linux.AppImage","sha512":"LLTH0SPsho90vWFqrUweFTGii2Rdb/LhVA90c5XlrcwyGP9a2u5sRRPvIdTYop6A5HZru33Gx19lm8X4kfph5Q==","releaseDate":"2024-03-05T09:15:03.086Z","signature":"OKMmDQsRBc9wzm6XqZbg45WEoP1rGZkwcvlIP7bHtfB1rRtRouahQd7FMZzSFt7V1X4/CJGHcRW9Ji8dr+d2y5/FsLM+w+pf4BAhUpWnuRaJ9z3cVWERsIzmknAWgZtdFmqPqjb5R8ghZUySRMI2sJkv5Tq5AcPgRB2IGjbM1S6edexXh0ruiATgd8a0MMui8rc/zo7wHj7nd+rS6ns5i9/oECisvfPG/kGO0aaArZXadqdfthT9NX7f1nJVl1SbjuFIXvuywKCKVjbC/QL+0dCw6L5PIwTegSo0VVSj8IoFZjPXdLowdtxNzfacwdBdMgePOP1OvlYKQvHQVB9+cA=="}

```

**Comment by shobeira** [comment]
I have the "The connection to the server was lost, please try again" error as well. As I reported earlier, I and a few othe fellow still have the connectiion lost error as stated on the related issue. It is not nice asking someone who spend time to report an error to email the matter as well! The troubleshooting process is cofusing and is not implemented systematically. It is cofusing for tech savvies even, not only for a user who paid to use the service.

**Comment by charlag** [comment]
> Day two since reporting the errors via email and on github, I still cannot log in due to:
> 
> ![Screenshot from 2024-03-07 19-44-42](https://private-user-images.githubusercontent.com/110072244/310809672-75f4dffc-0480-4412-a3ee-b9202e4200a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjAwNjksIm5iZiI6MTcwOTgxOTc2OSwicGF0aCI6Ii8xMTAwNzIyNDQvMzEwODA5NjcyLTc1ZjRkZmZjLTA0ODAtNDQxMi1hM2VlLWI5MjAyZTQyMDBhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxMzU2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzBlNjU2OTZjNjU0YWExMDlkMWE3N2U2NTg1MGY4ZWEyNjJmZDUwYmMwZTgxMWYxM2JlNTI3OTUyYzEwNWI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JlM_mrzh1N8ZSSU9vkocSjBiDoDVfyAEvmSgsiMYzqs)
> 
> I really need to access my emails now! What's going on??
> 
> In case I need to repeat myself: my hardware key is indeed registered with tutanota.

you did not add a key for tuta.com, please log in on the web client and a key there

**Comment by shobeira** [comment]
I resolved the issue by enabling the IPv6 (Make sure ping -6 google.com has
a valid outcome).

**Comment by charlag** [comment]
Does not seem to be happening anymore (although there are other connectivity issues in desktop client reported elsewhere)

**Comment by diana-404** [comment]
I'm on CachyOS using the given appimage but i still get "The connection to the server was lost, please try again"
