### ISSUE TITLE
DbError when extending index & disabling search

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#687]

**Comment by charlag** [comment]
Fixed by https://github.com/tutao/tutanota/commit/4b3b2b9121a82bf4cf8be68434710a07c500ed51

**Comment by mpfau** [comment]
Had tests with three different outcomes:
* It works as expected 
* The spinner stays open indefinitely
* The following error is thrown: `error CancelledError: cancelled indexing - index mail list JjsNgd8--R-0
    at MailIndexer.value (https://mail.tutanota.com/worker.js:1:332623)
    at https://mail.tutanota.com/worker.js:1:334344
    at r (https://mail.tutanota.com/libs.js:32:9669)
    at i._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:31:14830)
    at i._settlePromise (https://mail.tutanota.com/libs.js:31:15633)
    at i._settlePromise0 (https://mail.tutanota.com/libs.js:31:16334)
    at i._settlePromises (https://mail.tutanota.com/libs.js:31:17689)
    at i._fulfill (https://mail.tutanota.com/libs.js:31:16705)
    at i._resolveCallback (https://mail.tutanota.com/libs.js:31:13566)
    at i._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:31:14985)
    at i._settlePromise (https://mail.tutanota.com/libs.js:31:15633)
    at i._settlePromise0 (https://mail.tutanota.com/libs.js:31:16334)
    at i._settlePromises (https://mail.tutanota.com/libs.js:31:17689)
    at i._fulfill (https://mail.tutanota.com/libs.js:31:16705)
    at i._resolveCallback (https://mail.tutanota.com/libs.js:31:13566)
    at i._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:31:14985)`

**Comment by armhub** [comment]
seems to befixed already, just wasn't closed
