### ISSUE TITLE
TypeError: undefined is not a function because of the performance measure

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#703]
v3.38.6

<details>
<summary>
Stacktrace: 
</summary>

```
TypeError: undefined is not a function
at https://mail.tutanota.com/worker.js:1:317579
at r (https://mail.tutanota.com/libs.js:32:9669)
at i._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:31:14830)
at i._settlePromise (https://mail.tutanota.com/libs.js:31:15633)
at i._settlePromiseCtx (https://mail.tutanota.com/libs.js:31:16141)
at c (https://mail.tutanota.com/libs.js:30:1610)
at a (https://mail.tutanota.com/libs.js:30:1496)
at r._drainQueues (https://mail.tutanota.com/libs.js:30:3106)
at drainQueues (https://mail.tutanota.com/libs.js:30:1238)
```

</details>

Apparent location:
`performance.mark("processEntityEvents-start")`

**Comment by charlag** [comment]
Happens on Chrome.. 38?.

**Comment by bedhub** [comment]
Safari on iOS 10  throws error

> [Log] error – "CryptoError. could not setup worker> ReferenceError: Can't find variable: performanc…" (main-boot.js, line 1)
> [Log] Unknown error (main.js, line 1)
> CryptoError
> 
> 
> message: "could not setup worker> ReferenceError: Can't find variable: performance"
> 
> name: "CryptoError"
> 
> stack: "CryptoError. could not setup worker> ReferenceError: Can't find variable: performanc…"
> 
> CryptoError Prototype

**Comment by charlag** [comment]
`performance.mark` is still not polyfilled in some cases. Chrome/37 based WebView:

```
Error message: 
undefined is not a function

Stacktrace: 
TypeError: undefined is not a function
at IndexerCore._createClass.value (file:///android_asset/tutanota/dist/worker.js:1:284021)
at file:///android_asset/tutanota/dist/worker.js:1:281013
at a (file:///android_asset/tutanota/dist/libs.js:26:73165)
at F._settlePromiseFromHandler (file:///android_asset/tutanota/dist/libs.js:26:46542)
at F._settlePromise (file:///android_asset/tutanota/dist/libs.js:26:47342)
at F._settlePromise0 (file:///android_asset/tutanota/dist/libs.js:26:48041)
at F._settlePromises (file:///android_asset/tutanota/dist/libs.js:26:49393)
at h (file:///android_asset/tutanota/dist/libs.js:26:1646)
at p (file:///android_asset/tutanota/dist/libs.js:26:1585)
at a._drainQueues (file:///android_asset/tutanota/dist/libs.js:26:3078)
at drainQueues (file:///android_asset/tutanota/dist/libs.js:26:1327)
```

perhaps we need `typeof` check there or just not support such old versions altogether.

**Comment by charlag** [comment]
Still happening in v3.48.1/Chrome 38:

```
Error message: 
undefined is not a function

Stacktrace: 
TypeError: undefined is not a function
at https://mail.tutanota.com/worker.js:1:397529
at a (https://mail.tutanota.com/libs.js:26:73165)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46542)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromiseCtx (https://mail.tutanota.com/libs.js:26:47848)
at h (https://mail.tutanota.com/libs.js:26:1699)
at p (https://mail.tutanota.com/libs.js:26:1585)
at a._drainQueues (https://mail.tutanota.com/libs.js:26:3078)
at drainQueues (https://mail.tutanota.com/libs.js:26:1327)
```

**Comment by bedhub** [comment]
This does not reproduce every time, we should disable old Chrome versions
