### ISSUE TITLE
Eror: no group data for group XXX

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#707]
v3.38.6

**Comment by mpfau** [comment]
@charlag When does this happen? Is a stacktrace available?

**Comment by charlag** [comment]
<details>
<summary>
3.39.1 Mobile Safari
</summary>

```
Error: no group data for group LIbwicn--g-0
at https://mail.tutanota.com/worker.js:1:316470
at a (https://mail.tutanota.com/libs.js:26:73165)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46542)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromise0 (https://mail.tutanota.com/libs.js:26:48041)
at F._settlePromises (https://mail.tutanota.com/libs.js:26:49393)
at F._fulfill (https://mail.tutanota.com/libs.js:26:48411)
at https://mail.tutanota.com/libs.js:26:37178
at IDBRequest.request.onsuccess (https://mail.tutanota.com/worker.js:1:399080)
```

</details>

<details>
<summary>
3.39.1 Chrome 69
</summary>

```
Error: no group data for group KYiRJzt--g-0
at https://mail.tutanota.com/worker.js:1:316470
at a (https://mail.tutanota.com/libs.js:26:73165)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46542)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromise0 (https://mail.tutanota.com/libs.js:26:48041)
at F._settlePromises (https://mail.tutanota.com/libs.js:26:49393)
at F._fulfill (https://mail.tutanota.com/libs.js:26:48411)
at https://mail.tutanota.com/libs.js:26:37178
at IDBRequest.request.onsuccess (https://mail.tutanota.com/worker.js:1:399080)
```

</details>

**Comment by charlag** [comment]
I did not try to reproduce it yet but there are numerous reports each day

**Comment by mpfau** [comment]
This happens during initialization of the indexer (https://github.com/tutao/tutanota/blob/2692aeb1a7091352a678b5e3fd1ea08a920158dd/src/api/worker/search/Indexer.js#L401). 

I currently don't understand why this happens. During the initialization of the indexer, we either invoke `_createIndexTables()` or `_loadIndexTables()`. Both functions update the group table, so it should be up to date when `_loadPersistentGroupData()` tries to read group data from the table...

Needs further analyzation.

**Comment by armhub** [comment]
Users claimed that this happened directly after login. Waiting for feedback on how to reproduce.

**Comment by charlag** [comment]
Workaround https://github.com/tutao/tutanota/commit/c36f202684176f878e515a17a003ece6956710c4

**Comment by charlag** [comment]
> re booted comp after clearing cookies/browsinh history

**Comment by charlag** [comment]
One person with `GroupData not available for group` said that they didn't clear browser storage or history.

**Comment by charlag** [comment]
Other two people say that they cleared it at some point.

**Comment by charlag** [comment]
One person reported "no group ids in database" error with Chrome 66 WebView and they said that updating the WebView fixed the issue.

**Comment by charlag** [comment]
One user reports gives a hint on when it may be happening: their storage was low.
My guess is that when there's not enough space left the browser cleans IndexedDB and refuses to write new data.
We should probably disable indexing when we throw `InvalidDatabaseStateError`.
Maybe it's a good idea to wait for extended logging and check what is happening but this is my best guess for now.
(could also make "indexing not supported" message less annoying in the meantime)

**Comment by charlag** [comment]
This doesn't really show up anymore
