### ISSUE TITLE
Invalid state: not connecting

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#7097]
```
ProgrammingError: Invalid state: not connecting
    at gP.exponentialBackdownReconnect (..\..\C:\Users\MGrantham\AppData\Local\Programs\Tutanota Desktop\Tuta Mail Desktop\resources\app.asar\desktop\DesktopMain.js:25:6318)
    at ..\..\ClientRequest.<anonymous> (C:\Users\MGrantham\AppData\Local\Programs\Tutanota Desktop\Tuta Mail Desktop\resources\app.asar\desktop\DesktopMain.js:25:5689)
    at ClientRequest.emit (..\..\node:events:518:28)
    at TLSSocket.socketErrorListener (..\..\node:_http_client:495:9)
    at TLSSocket.emit (..\..\node:events:518:28)
    at emitErrorNT (..\..\node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (..\..\node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (..\..\node:internal/process/task_queues:82:21)

App version:
230.240603.0
Client type:
Windows
Additional info:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/230.240603.0 Chrome/124.0.6367.207 Electron/30.0.6 Safari/537.36
```

## Test notes
It is hard to reproduce the original issue (it is some kind of race between connection events and connect call from the outside) but we can test regressions:

 - [ ] Test that SSE disconnects when network/server cannot be reached and reconnects later
 - [ ] Test that when connect attempt fails it will retry with a bigger delay

**Comment by Alf-Melmac** [comment]
I was having this problem quite regularly and can confirm that this has solved the issue. Thanks!
