### ISSUE TITLE
/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found

### ISSUE THREAD

**Issue by softwaredevelop** [tutao/tutanota#7133]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
I updated the desktop application to version tutanota-desktop/232.240626.0. The application cannot be used as an error message appears. The previous versions of the application worked properly.

**To Reproduce**
1. Start tutanota-desktop
2. 2FA
3. See error

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Desktop Environment, if applicable (on Linux): Openbox 3.6.1

**Additional context**
Feedback v232.240626.0 - Error - UNKNOWN - linux

 Client: linux
 Type: UNKNOWN
 Tutanota version: 232.240626.0
 Timestamp (UTC): Wed, 26 Jun 2024 13:59:29 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/232.240626.0 Chrome/126.0.6478.61 Electron/31.0.2 Safari/537.36
Error
 Error message: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_tutanoLnsS9j/resources/app.asar.unpacked/desktop/better-sqlite3.node)
Stacktrace: 
Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_tutanoLnsS9j/resources/app.asar.unpacked/desktop/better-sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1470:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at new Fe (/tmp/.mount_tutanoLnsS9j/resources/app.asar/desktop/better-sqlite3-DG-e8Kc7.js:1:18481)
    at l.openDb (/tmp/.mount_tutanoLnsS9j/resources/app.asar/desktop/sqlworker.js:1:5985)

**Comment by PrivacyDragon** [comment]
I have a very similar issue, which I feel might be the same issue? The error message is only a tiny bit different.
I am on OpenSuse Leap 15.4, using KDE as my desktop environment.
The steps to reproduce are exactly the same.

The only difference in the error is to be found in the error message, which is for me:
``Error message: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_tutanoNquPIk/resources/app.asar.unpacked/desktop/better-sqlite3.node)``
(That difference is indeed also found in the first line of the 'Stacktrace', of course.)

**Comment by charlag** [comment]
Could you please share which libc version you have installed?

**Comment by DarthRaver** [comment]
I'm on ubuntu mate 20.04.6 LTS (Focal Fossa) 64-bit and after updating tutanota client i get the same error as  @PrivacyDragon .

`Error message: /lib/x86_64-linux-gnu/libstdc++.so.6: version "GLIBCXX_3.4.29" not found (required by /tmp/.mount_tutano****/resources/app.asar.unpacked/desktop/better-sqlite3.node)`

`Ubuntu GLIBC 2.31-0ubuntu9.16`

**Comment by softwaredevelop** [comment]
Did the Tuta client die on Linux? - `Debian GLIBC 2.36-6` ☠️

**Comment by malehwi** [comment]
I have the same problem on Debian 11.

**Comment by malehwi** [comment]
Feedback v232.240626.0 - Error - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 232.240626.0
 Timestamp (UTC): Wed, 03 Jul 2024 06:46:40 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/232.240626.0 Chrome/126.0.6478.61 Electron/31.0.2 Safari/537.36
Error
 Error message: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_tutanoz6VI1z/resources/app.asar.unpacked/desktop/better-sqlite3.node)
Stacktrace: 
Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_tutanoz6VI1z/resources/app.asar.unpacked/desktop/better-sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1470:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at new Fe (/tmp/.mount_tutanoz6VI1z/resources/app.asar/desktop/better-sqlite3-DG-e8Kc7.js:1:18481)
    at l.openDb (/tmp/.mount_tutanoz6VI1z/resources/app.asar/desktop/sqlworker.js:1:5985)

**Comment by softwaredevelop** [comment]
The guys from Tuta are not interested in desktop Linux users, I'm closing the issue. A big disappointment.


Feedback v234.240627.0 - Error - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 234.240627.0
 Timestamp (UTC): Sun, 07 Jul 2024 11:19:34 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/234.240627.0 Chrome/126.0.6478.61 Electron/31.0.2 Safari/537.36
Error
 Error message: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_tutanoBwjjVj/resources/app.asar.unpacked/desktop/better-sqlite3.node)
Stacktrace: 
Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_tutanoBwjjVj/resources/app.asar.unpacked/desktop/better-sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1470:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at new Fe (/tmp/.mount_tutanoBwjjVj/resources/app.asar/desktop/better-sqlite3-eYHqTfXD.js:1:18481)
    at l.openDb (/tmp/.mount_tutanoBwjjVj/resources/app.asar/desktop/sqlworker.js:1:5985)

**Comment by Chownx** [comment]
Hello, 
I have the same issue. Debian11 
uname -a                                     
Linux irix 5.10.0-8-amd64 #1 SMP Debian 5.10.46-5 (2021-09-23) x86_64 GNU/Linux

Paquete: glibc-source                            
Versión: 2.31-13+deb11u10
Nuevo: sí
Estado: sin instalar
Multi-Arch: foreign
Prioridad: opcional
Sección: devel
Desarrollador: GNU Libc Maintainers <debian-glibc@lists.debian.org>
Arquitectura: all
Tamaño sin comprimir: 25,1 M
Recomienda: xz-utils
Rompe: cross-toolchain-base (< 45~), cross-toolchain-base-mipsen (< 10), cross-toolchain-base-ports (< 37~)
Descripción: GNU C Library: sources
 This package contains the sources and patches which are needed to build glibc.
Página principal: https://www.gnu.org/software/libc/libc.html



Feedback v234.240627.0 - Error - UNKNOWN - linux


 Client: linux
 Type: UNKNOWN
 Tutanota version: 234.240627.0
 Timestamp (UTC): Wed, 10 Jul 2024 14:36:58 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/234.240627.0 Chrome/126.0.6478.61 Electron/31.0.2 Safari/537.36
Error
 Error message: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /run/user/1000/.mount_tutanojwwuj3/resources/app.asar.unpacked/desktop/better-sqlite3.node)
Stacktrace: 
Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /run/user/1000/.mount_tutanojwwuj3/resources/app.asar.unpacked/desktop/better-sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1470:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at new Fe (/run/user/1000/.mount_tutanojwwuj3/resources/app.asar/desktop/better-sqlite3-eYHqTfXD.js:1:18481)
    at l.openDb (/run/user/1000/.mount_tutanojwwuj3/resources/app.asar/desktop/sqlworker.js:1:5985)

Thanks in advance.

**Comment by softwaredevelop** [comment]
As long as they can't eliminate the `GLIBCXX_3.4.29' not found errors in the Linux desktop app, they shouldn't release new versions for Linux.

Supposedly, security is Tutanota's hallmark. However, the Linux desktop application crashes regularly. It's quite frustrating to use an email client that crashes frequently. It raises the question, why should one use the Tutanota email system if it crashes regularly?


Feedback v235.240712.0 - Error - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 235.240712.0
 Timestamp (UTC): Sat, 13 Jul 2024 06:23:07 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/235.240712.0 Chrome/126.0.6478.61 Electron/31.0.2 Safari/537.36
Error
 Error message: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_tutanoueDgH4/resources/app.asar.unpacked/desktop/better-sqlite3.node)
Stacktrace: 
Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_tutanoueDgH4/resources/app.asar.unpacked/desktop/better-sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1470:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at new Fe (/tmp/.mount_tutanoueDgH4/resources/app.asar/desktop/better-sqlite3-Dk2b9047.js:1:18578)
    at l.openDb (/tmp/.mount_tutanoueDgH4/resources/app.asar/desktop/sqlworker.js:1:5985)

**Comment by mgarrido** [comment]
Hello.

I'm having the same issue. My O.S. is Linux Mint 20 Ulyana.

 Client: linux
 Type: UNKNOWN
 Tutanota version: 235.240712.0
 Timestamp (UTC): Tue, 16 Jul 2024 05:29:56 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/235.240712.0 Chrome/126.0.6478.61 Electron/31.0.2 Safari/537.36
Error
 Error message: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_tutanoirPuLp/resources/app.asar.unpacked/desktop/better-sqlite3.node)
Stacktrace: 
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_tutanoirPuLp/resources/app.asar.unpacked/desktop/better-sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1470:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at new Fe (/tmp/.mount_tutanoirPuLp/resources/app.asar/desktop/better-sqlite3-Dk2b9047.js:1:18578)
    at l.openDb (/tmp/.mount_tutanoirPuLp/resources/app.asar/desktop/sqlworker.js:1:5985)
