### ISSUE TITLE
Miscellaneous / Mysterious Error Message Upon Opening of App

### ISSUE THREAD

**Issue by Gitchick57** [tutao/tutanota#7597]
I get an error message upon opening the app on my phone.  Then I am asked to either ignore it or report to Tuta with information about my phone / browser.  Shortly after that I see an ad asking me to upgrade my service to paid.🤔

**Comment by wrdhub** [comment]
@Gitchick57, is this still happening? 
If you could provide the error (when you get the pop-up, click on Send Report -> then "Details" and copy that), info about your device (type, operating system version), and the Tuta version number that would really help us figure out what is going on! Thank you.

**Comment by Gitchick57** [comment]
Yes, this is still happening.  I have sent a few email messages to reports with my device details and a few error messages I just selected ignore and close.

Should I send information from previous error reports or wait until I get a new error message?



Sep 23, 2024, 10:41 AM by ***@***.***:

**Comment by Gitchick57** [comment]
This is still happening


Client: android
Type: FREE
Tutanota version: 244.240913.0
Timestamp (UTC): Mon, 23 Sep 2024 17:04:48 GMT
User agent:
Mozilla/5.0 (Linux; Android 12; Studio Mini 2023 Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/128.0.6613.146 Mobile Safari/537.36
net.sqlcipher.database.SQLiteException
Error message: error code 5: database is locked
Stacktrace:
net.sqlcipher.database.SQLiteException: error code 5: database is locked
at net.sqlcipher.database.SQLiteStatement.native_execute(Native Method)
at net.sqlcipher.database.SQLiteStatement.execute(Unknown Source:19)
at net.sqlcipher.database.SQLiteDatabase.execSQL(SourceFile:0)
at de.tutao.tutanota.offline.AndroidSqlCipherFacade.run(Unknown Source:8)
at de.tutao.tutanota.ipc.SqlCipherFacadeReceiveDispatcher.dispatch(Unknown Source:339)
at de.tutao.tutanota.ipc.AndroidGlobalDispatcher.dispatch(Unknown Source:154)
at de.tutao.tutanota.RemoteBridge.invokeMethod(Unknown Source:62)
at de.tutao.tutanota.RemoteBridge.handleMessageFromWeb(Unknown Source:204)
at de.tutao.tutanota.RemoteBridge$initMessageChannel$1$onMessage$1.invokeSuspend(Unknown Source:41)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
at kotlinx.coroutines.DispatchedTask.run(Unknown Source:98)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)

**Comment by Gitchick57** [comment]
This is still happening even after the recent update.



Sep 23, 2024, 11:31 AM by ***@***.***:

**Comment by charlag** [comment]
@Gitchick57 thank you for the info. Does it happen to you all the time? I think it might be related to notification process somehow. Sorry to ask you but does restarting your phone help?

**Comment by Gitchick57** [comment]
It happened just now when I opened the app, saw your email and restarted my phone but I've restarted the phone before and it doesn't help.  The error messages don't happen every time I open the app but have been happening sporadically since I've put in the help request around 9/19.

I have Tuta set up for notifications.



Sep 30, 2024, 3:54 AM by ***@***.***:

**Comment by Gitchick57** [comment]
I DON'T have Tuta set up to receive notifications, apologies.



Sep 30, 2024, 5:42 AM by ***@***.***:

**Comment by charlag** [comment]
Thank you for your answers, I'm not sure how it comes to that yet
