### ISSUE TITLE
Can't access in Inbox due to CBOR decode error

### ISSUE THREAD

**Issue by wpanas** [tutao/tutanota#7662]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**
```
2024-10-04T05:47:02.343Z I "native visibility change",true
2024-10-04T05:47:02.347Z I "\n\n........................................\n........................................\n........................................\n........@@@@@@@@@@@@@@@@@@@@@@@.........\n.....@....@@@@@@@@@@@@@@@@@@@@@@@.......\n.....@@@....@@@@@@@@@@@@@@@@@@@@@@@.....\n.....@@@@@..............................    Do you care about privacy?\n.....@@@@@...@@@@@@@@@@@@@@@@@@@@@@.....\n.....@@@@...@@@@@@@@@@@@@@@@@@@@@@@.....    Work at Tuta! Fight for our rights!\n.....@@@@...@@@@@@@@@@@@@@@@@@@@@@......\n.....@@@...@@@@@@@@@@@@@@@@@@@@@@.......    https://tuta.com/jobs\n.....@@@...@@@@@@@@@@@@@@@@@@@@@@.......\n.....@@...@@@@@@@@@@@@@@@@@@@@@@........\n.....@@...@@@@@@@@@@@@@@@@@@@@@@........\n.....@...@@@@@@@@@@@@@@@@@@@@@@.........\n.....@...@@@@@@@@@@@@@@@@@@@@@@.........\n........@@@@@@@@@@@@@@@@@@@@@@..........\n.......@@@@@@@@@@@@@@@@@@@@@@...........\n.......@@@@@@@@@@@@@@@@@@@@@@...........\n........................................\n........................................\n........................................\n\n"
2024-10-04T05:47:02.358Z I "worker init time (ms):",114
2024-10-04T05:47:04.443Z I "removed topmost modal component"
2024-10-04T05:47:04.649Z I "MailVM","Loading sticky mail","MeJxi1y--s-2","O8L0uas--3-9"
2024-10-04T05:47:04.676Z I "error",Error,"Error: CBOR decode error: data to decode must be a Uint8Array\n    at https://assets.tutanota.com/common-DEqpHnyW.js:1:6216\n    at bH (https://assets.tutanota.com/common-DEqpHnyW.js:1:6495)\n    at Ds.decodeCborEntity (https://assets.tutanota.com/worker.js:6:9286)\n    at Ds.deserialize (https://assets.tutanota.com/worker.js:6:9188)\n    at Ds.get (https://assets.tutanota.com/worker.js:1:21882)"
```

**Describe the bug**

Inbox is not available on mobile. It doesn't show any emails. Everything works just fine on desktop.

**To Reproduce**
1. Open app
2. Immediately get notification about error

**Expected behavior**
I want to be able to read my email :)

**Screenshots**
Not applicable

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samsung S21+
 - OS: [e.g. iOS8.1] Android 14
 - Version [e.g. 22] 244.240912.0

**Additional context**

**Comment by wrdhub** [comment]
Hello, I'm sorry you ran into this issue. For now: if you log out, delete credentials (or just delete the app ) and log back in. It should fix the issue.

**Comment by charlag** [comment]
Duplicate of #7645
