### ISSUE TITLE
Inbox rules are processed too early

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#7698]
```
 error Error: AssertNotNull failed : null
    at assertNotNull (Utils.js:69:15)
    at LoginController.getUserController (LoginController.ts:207:10)
    at InboxRuleHandler.findAndApplyMatchingRule (InboxRuleHandler.ts:107:17)
    at MailViewModel.ts:552:53
    at promiseFilter (PromiseUtils.js:121:19)
    at async MailViewModel.loadMailSetMailRange (MailViewModel.ts:551:21)
    at async MailViewModel.loadMailRange (MailViewModel.ts:528:11)
    at async Object.fetch (MailViewModel.ts:365:33)
    at async ListModel.ts:154:43
    at async ListModel.loadInitial (ListModel.ts:123:3) Error: AssertNotNull failed : null
    at assertNotNull (http://localhost:9000/app.js:1867:11)
    at LoginController.getUserController (http://localhost:9000/app.js:70553:16)
    at InboxRuleHandler.findAndApplyMatchingRule (http://localhost:9000/app.js:72221:97)
    at http://localhost:9000/app.js:100440:62
    at promiseFilter (http://localhost:9000/app.js:2950:15)
    at async MailViewModel.loadMailSetMailRange (http://localhost:9000/app.js:100439:29)
    at async MailViewModel.loadMailRange (http://localhost:9000/app.js:100426:18)
    at async Object.fetch (http://localhost:9000/app.js:100127:54)
    at async http://localhost:9000/app.js:75378:62
    at async ListModel.loadInitial (http://localhost:9000/app.js:75352:9)
```

**Comment by hrb-hub** [comment]
Was not able to reproduce the issue locally
