### ISSUE TITLE
Unable to Log In to Tuta macOS App - "Connection to Server Lost"

### ISSUE THREAD

**Issue by emeritaacuity0u** [tutao/tutanota#7709]
**Summary:**
I'm unable to log in to the Tuta macOS app. The app attempts to log in but fails after displaying "organizing calendar events" and returns the error: "The connection to the server was lost. Please try again." I can successfully log in using the same credentials on the iOS app and web app.

**Steps to Reproduce:**
Launch the Tuta macOS app (Version: 246.241008.0).
Enter valid credentials (same credentials work on iOS and web).
Attempt to log in.
The app reaches "organizing calendar events" and then fails, returning the error.
Expected Behavior:
After entering credentials, the app should log in and display the inbox.

**Actual Behavior:**
The app fails to log in and returns the following error: "The connection to the server was lost. Please try again." This occurs after the app displays the message: "organizing calendar events."

**Environment:**
macOS Version: 15.0.1 (24A348)
Tuta App Version: 246.241008.0
Network: Wi-Fi
DNS Setup: Custom DNS (AdGuard DNS Personal), but app.tuta.com is not being blocked (NOERROR response in logs).
Firewall: macOS firewall enabled, but no blocking of the app in logs.

**Error Messages:**
"The connection to the server was lost. Please try again."
Troubleshooting Steps Already Taken:
Verified that login credentials are correct (successfully log in on iOS app and web app).
Checked that DNS and firewall settings are not blocking the app (logs show no errors).
Reinstalled the app, but the issue persists.
Verified there are no permission issues on macOS and no errors in the Console logs.
Confirmed that the issue only occurs on the macOS app, as I can log in without issue on iOS and the web.
Additional Context:
The app gets stuck at "organizing calendar events" before failing.
Network setup (AdGuard DNS, macOS firewall) has been confirmed not to be the issue through log analysis.

**Comment by MineGene** [comment]
Also experiencing this issue.
Tuta support on Reddit told me to contact an email that I specifically mentions not to contact it for support, and instead raise the issue here.

I have never been able to login on 3 machines with the app due to this issue.

**Comment by hrb-hub** [comment]
Thank you for the report,
Does this still happen on versions >= 259.241223.0 ?

@MineGene , Can you please check whether or not you're on the latest version? And if you are, could you please send us your logs? You can retrieve the logs even when not logged in by clicking the version number.
![image](https://github.com/user-attachments/assets/a36fad82-0c08-4811-97bf-0e85675aba4d)

Please send the logs to our support, if you're on a paid plan. Otherwise please send them to: hello[at]tutao.de

**Comment by MineGene** [comment]
> Thank you for the report,
> 
> Does this still happen on versions >= 259.241223.0 ?
> 
> 
> 
> @MineGene , Can you please check whether or not you're on the latest version? And if you are, could you please send us your logs? You can retrieve the logs even when not logged in by clicking the version number.
> 
> ![image](https://github.com/user-attachments/assets/a36fad82-0c08-4811-97bf-0e85675aba4d)
> 
> 
> 
> Please send the logs to our support, if you're on a paid plan. Otherwise please send them to: hello[at]tutao.de

Hi,

Yes, it still happens.

Here's the logs:
```

v259.241223.2 - darwin


 Client: darwin
 Type: UNKNOWN
 Tutanota version: 259.241223.2
 Timestamp (UTC): Mon, 30 Dec 2024 10:19:51 GMT
 User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/259.241223.2 Chrome/130.0.6723.152 Electron/33.3.0 Safari/537.36


== MAIN LOG ==
2024-12-30T10:19:20.552Z I "Migrating credentials to native"
2024-12-30T10:19:20.552Z I "Skipping migration as encryption data is not there"
2024-12-30T10:19:20.552Z I "Stored credentials in native"
2024-12-30T10:19:20.552Z I "Cleared credentials in deviceConfig"
2024-12-30T10:19:20.563Z I "\n\n........................................\n........................................\n........................................\n........@@@@@@@@@@@@@@@@@@@@@@@.........\n.....@....@@@@@@@@@@@@@@@@@@@@@@@.......\n.....@@@....@@@@@@@@@@@@@@@@@@@@@@@.....\n.....@@@@@..............................    Do you care about privacy?\n.....@@@@@...@@@@@@@@@@@@@@@@@@@@@@.....\n.....@@@@...@@@@@@@@@@@@@@@@@@@@@@@.....    Work at Tuta! Fight for our rights!\n.....@@@@...@@@@@@@@@@@@@@@@@@@@@@......\n.....@@@...@@@@@@@@@@@@@@@@@@@@@@.......    https://tuta.com/jobs\n.....@@@...@@@@@@@@@@@@@@@@@@@@@@.......\n.....@@...@@@@@@@@@@@@@@@@@@@@@@........\n.....@@...@@@@@@@@@@@@@@@@@@@@@@........\n.....@...@@@@@@@@@@@@@@@@@@@@@@.........\n.....@...@@@@@@@@@@@@@@@@@@@@@@.........\n........@@@@@@@@@@@@@@@@@@@@@@..........\n.......@@@@@@@@@@@@@@@@@@@@@@...........\n.......@@@@@@@@@@@@@@@@@@@@@@...........\n........................................\n........................................\n........................................\n\n"
2024-12-30T10:19:20.619Z I "worker init time (ms):",96
2024-12-30T10:19:44.251Z I "removed topmost modal component"
2024-12-30T10:19:48.334Z I "removed topmost modal component"
2024-12-30T10:19:48.846Z I "removed topmost modal component"

== WORKER LOG ==
2024-12-30T10:19:44.249Z I "[RestClient]","failed request","GET","https://app.tuta.com/rest/sys/saltservice?_body=%7B%22_format%22%3A%220%22%2C%22mailAddress%22%3A%22jslawler%40tuta.io%22%7D",0,"",["v","cv","Content-Type","Accept"],"[48 characters]"
2024-12-30T10:19:44.250Z I "[RestClient]","failed request","GET","https://app.tuta.com/rest/sys/saltservice?_body=%7B%22_format%22%3A%220%22%2C%22mailAddress%22%3A%22jslawler%40tuta.io%22%7D",0,"",["v","cv","Content-Type","Accept"],"[48 characters]"

== NATIVE LOG ==
2024-12-30T10:19:19.754Z I "the monkey has been patched pid:",24096
2024-12-30T10:19:19.848Z I "Creating tables..."
2024-12-30T10:19:19.857Z I "Current credentials version: undefined"
2024-12-30T10:19:19.857Z I "Migrating to v1"
2024-12-30T10:19:19.859Z I "Tables created successfully!"
2024-12-30T10:19:19.862Z I "version:  ","259.241223.2"
2024-12-30T10:19:19.973Z I "resolving key...","tutanota-vault"
2024-12-30T10:19:20.013Z W "key tutanota-vault not found, generating a new one"
2024-12-30T10:19:20.052Z I "[DesktopMain]","getting dictionaries from:","https://app.tuta.com/desktop/dictionaries/"
2024-12-30T10:19:20.053Z I "config up to date"
2024-12-30T10:19:20.057Z I "[DesktopMain]","spellcheck-dictionary-initialized","en-AU"
2024-12-30T10:19:20.093Z I "[2024-12-30T10:19:20.093Z]","Create tray:true"
2024-12-30T10:19:20.096Z I "[SSEFacade]","last missed notification check:",{"lastMissedNotificationCheckTime":null}
2024-12-30T10:19:20.097Z I "[ApplicationWindow]","webAssetsPath: ","/Applications/Tuta Mail.app/Contents/Resources/app.asar"
2024-12-30T10:19:20.159Z I "default mailto handler:",false
2024-12-30T10:19:20.160Z I "Webapp ready"
2024-12-30T10:19:20.162Z I "[SSEFacade]","No SSE info"
2024-12-30T10:19:20.163Z I "[2024-12-30T10:19:20.163Z]","[ElectronUpdater]","INFO:","Checking for update"
2024-12-30T10:19:20.163Z I "[2024-12-30T10:19:20.163Z]","[ElectronUpdater]","INFO:","checking-for-update"
2024-12-30T10:19:20.207Z I "[2024-12-30T10:19:20.207Z]","[I src/logging/console.rs] spawned logger"
2024-12-30T10:19:20.267Z I "[2024-12-30T10:19:20.266Z]","[ElectronUpdater]","INFO:","Generated new staging user ID: 8633ca07-f4a5-50e3-8b1b-b3410e0933f8"
2024-12-30T10:19:20.275Z I "[DesktopMain]","getting dictionaries from:","https://app.tuta.com/desktop/dictionaries/"
2024-12-30T10:19:20.280Z I "[DesktopMain]","spellcheck-dictionary-initialized","en-AU"
2024-12-30T10:19:21.753Z I "[2024-12-30T10:19:21.753Z]","[ElectronUpdater]","INFO:","Update for version 259.241223.2 is not available (latest version: 259.241223.2, downgrade is disallowed)."
2024-12-30T10:19:21.754Z I "[2024-12-30T10:19:21.753Z]","[ElectronUpdater]","INFO:","update not available:",{"version":"259.241223.2","files":[{"url":"tutanota-desktop-mac.zip","sha512":"kufJ/YKOAge9VTx+GNLIJOT95GCvtxXm/ToYvL9iEx37xEWLKSmgbTitWAph017LtwkwKomsp3jrIEw2xHl/3A==","size":212306277},{"url":"tutanota-desktop-mac.dmg","sha512":"oOg1makwjeEZaW8O0o0jY+uiVUAbdcwhiauSM5G9kcTn5H4kQkyyu6mYjNDsdmKARdgM1JrZ40gu+4xPsap6nA==","size":220310337}],"path":"tutanota-desktop-mac.zip","sha512":"kufJ/YKOAge9VTx+GNLIJOT95GCvtxXm/ToYvL9iEx37xEWLKSmgbTitWAph017LtwkwKomsp3jrIEw2xHl/3A==","releaseDate":"2024-12-23T18:22:45.729Z","signature":"NeRs8AFf/ItwubBbFwIx2wFAjIX1RCojTITsxVynQRqB2S6DnQe6n5rnnY7XenBpxnm1dhQYMmtw8NMr2OGCTu25znvwveEMZEAk1MlgmqFH4qK8gNStzvBuzgG83EVCH2Jc8TqylAa398xsInHWRR9pL2zhJvyQ28JbhGHlSufeDCK1PsYywM0KMkooOm3p77dLcHK2kpdKkU8ZiPn/ab/c9400G/3cjG1FtBD8ZLUByzd7D/Li41RzJoUsA0qgus65SG1ardJlMAxTCIXBbjyIwD2xdDsYfgA8X0eU78H9qOTzGy1IWCnzj7auevDD+7DlS2Bm/TlqecAZEiycaQ=="}
2024-12-30T10:19:44.245Z I "[ProtocolProxy]","error for GET https://app.tuta.com/rest/sys/saltservice:"
2024-12-30T10:19:44.248Z I "[ProtocolProxy]",?
2024-12-30T10:19:44.248Z I "[ProtocolProxy]","{\"name\":\"TypeError\",\"message\":\"fetch failed\",\"stack\":\"TypeError: fetch failed\\n    at /Applications/Tuta Mail.app/Contents/Resources/app.asar/desktop/DesktopMain.js:10:31493\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async ay (/Applications/Tuta Mail.app/Contents/Resources/app.asar/desktop/DesktopMain.js:10:31398)\\n    at async /Applications/Tuta Mail.app/Contents/Resources/app.asar/desktop/DesktopMain.js:10:33186\\n    at async AsyncFunction.<anonymous> (node:electron/js2c/browser_init:2:53035)\"}"
2024-12-30T10:19:44.248Z I "[ProtocolProxy]","failed after 4285ms"

```

**Comment by hrb-hub** [comment]
@MineGene , sorry you're still struggling to login.
Thank you for the logs, we'll look into it :)

**Comment by charlag** [comment]
Do you use Apple iCloud Private Relay?

**Comment by MineGene** [comment]
Yes, but I have tried it both with and without it enabled.
I am also able to use it on my 4 other devices with private relay that aren't on macOS, including web browsers.

It's just the macOS app that doesn't work.

**Comment by MineGene** [comment]
@hrb-hub @charlag 
Confirming I am still unable to login on Version 264.250130.1 (264.250130.1.908).

**Comment by charlag** [comment]
@MineGene thank you for the update

**Comment by wrdhub** [comment]
Got another report of this today, on macOS 26.3.1and Tuta version 340.260326.1

**Comment by faultables** [comment]
happened on v345.260421.2 too

logs:

```
v345.260421.2 - darwin


 Client: darwin
 Type: UNKNOWN
 Tutanota version: 345.260421.2
 Timestamp (UTC): Sat, 25 Apr 2026 10:57:48 GMT
 Time zone: Asia/Jakarta
 User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/345.260421.2 Chrome/146.0.7680.179 Electron/41.2.0 Safari/537.36


== MAIN LOG ==
2026-04-25T10:57:28.872Z I "\n\n........................................\n........................................\n........................................\n........@@@@@@@@@@@@@@@@@@@@@@@.........\n.....@....@@@@@@@@@@@@@@@@@@@@@@@.......\n.....@@@....@@@@@@@@@@@@@@@@@@@@@@@.....\n.....@@@@@..............................    Do you care about privacy?\n.....@@@@@...@@@@@@@@@@@@@@@@@@@@@@.....\n.....@@@@...@@@@@@@@@@@@@@@@@@@@@@@.....    Work at Tuta! Fight for our rights!\n.....@@@@...@@@@@@@@@@@@@@@@@@@@@@......\n.....@@@...@@@@@@@@@@@@@@@@@@@@@@.......    https://tuta.com/jobs\n.....@@@...@@@@@@@@@@@@@@@@@@@@@@.......\n.....@@...@@@@@@@@@@@@@@@@@@@@@@........\n.....@@...@@@@@@@@@@@@@@@@@@@@@@........\n.....@...@@@@@@@@@@@@@@@@@@@@@@.........\n.....@...@@@@@@@@@@@@@@@@@@@@@@.........\n........@@@@@@@@@@@@@@@@@@@@@@..........\n.......@@@@@@@@@@@@@@@@@@@@@@...........\n.......@@@@@@@@@@@@@@@@@@@@@@...........\n........................................\n........................................\n........................................\n\n"
2026-04-25T10:57:28.896Z I "worker init time (ms):",51
2026-04-25T10:57:44.077Z I "removed topmost modal component"

== WORKER LOG ==
2026-04-25T10:57:43.374Z I "[RestClient]","failed request","GET","https://app.tuta.com/rest/sys/saltservice?_body=%7B%22418%22%3A%220%22%2C%22419%22%3A%22xxxxxxredactedxxxxxx%40tuta.io%22%7D",0,"",["v","cv","cp","Content-Type","Accept"],"[38 characters]"
2026-04-25T10:57:43.375Z I "[RestClient]","failed request","GET","https://app.tuta.com/rest/sys/saltservice?_body=%7B%22418%22%3A%220%22%2C%22419%22%3A%xxxxxxredactedxxxxxx%40tuta.io%22%7D",0,"",["v","cv","cp","Content-Type","Accept"],"[38 characters]"

== NATIVE LOG ==
2026-04-25T10:57:28.154Z I "the monkey has been patched pid:",40665
2026-04-25T10:57:28.203Z I "[2026-04-25T10:57:28.203Z]","registering for tuta protocol","/Applications/Tuta Mail.app/Contents/MacOS/Tuta Mail","/Applications/Tuta Mail.app/Contents/Resources/app.asar"
2026-04-25T10:57:28.207Z I "Creating tables..."
2026-04-25T10:57:28.213Z I "Current credentials version: 1"
2026-04-25T10:57:28.213Z I "Tables created successfully!"
2026-04-25T10:57:28.219Z I "version:  ","345.260421.2"
2026-04-25T10:57:28.257Z I "[2026-04-25T10:57:28.257Z]","[I packages/node-mimimi/src/logging/console.rs] spawned logger"
2026-04-25T10:57:28.324Z I "resolving key...","tutanota-vault"
2026-04-25T10:57:28.325Z I "config up to date"
2026-04-25T10:57:28.362Z I "[2026-04-25T10:57:28.362Z]","Create tray:true"
2026-04-25T10:57:28.363Z I "[SSEFacade]","last missed notification check:",{"lastMissedNotificationCheckTime":null}
2026-04-25T10:57:28.364Z I "[SSEFacade]","No SSE info"
2026-04-25T10:57:28.365Z I "[ApplicationWindow]","webAssetsPath: ","/Applications/Tuta Mail.app/Contents/Resources/app.asar"
2026-04-25T10:57:28.493Z I "[DesktopMain]","getting dictionaries from:","https://app.tuta.com/desktop/dictionaries/"
2026-04-25T10:57:28.494Z I "default mailto handler:",false
2026-04-25T10:57:28.494Z I "Webapp ready"
2026-04-25T10:57:28.496Z I "[2026-04-25T10:57:28.496Z]","[ElectronUpdater]","INFO:","Checking for update"
2026-04-25T10:57:28.496Z I "[2026-04-25T10:57:28.496Z]","[ElectronUpdater]","INFO:","checking-for-update"
2026-04-25T10:57:28.519Z I "[DesktopMain]","spellcheck-dictionary-initialized","en-GB"
2026-04-25T10:57:28.531Z I "[DesktopMain]","getting dictionaries from:","https://app.tuta.com/desktop/dictionaries/"
2026-04-25T10:57:28.531Z I "[DesktopMain]","spellcheck-dictionary-initialized","en-GB"
2026-04-25T10:57:29.766Z I "[2026-04-25T10:57:29.766Z]","[ElectronUpdater]","INFO:","Update for version 345.260421.2 is not available (latest version: 345.260421.2, downgrade is disallowed)."
2026-04-25T10:57:29.767Z I "[2026-04-25T10:57:29.766Z]","[ElectronUpdater]","INFO:","update not available:",{"version":"345.260421.2","files":[{"url":"tutanota-desktop-mac.zip","sha512":"a4OWcQMe4lQdrxx0QJgjtHDC5+ZESNn2LI4JRAQIWokNGSCO1CC5BwR+d4iRsrTjgnNGO2AbEXIg3QnoC7LBJg==","size":241624581},{"url":"tutanota-desktop-mac.dmg","sha512":"+GQ3qjI42MuiFubOvy3BRc273virrv91X8lTWp9wHkJq/IUI71VM5bxdvn3cNufh1r1CbI7qqJrEEK8UhtKV2A==","size":250823165}],"path":"tutanota-desktop-mac.zip","sha512":"a4OWcQMe4lQdrxx0QJgjtHDC5+ZESNn2LI4JRAQIWokNGSCO1CC5BwR+d4iRsrTjgnNGO2AbEXIg3QnoC7LBJg==","releaseDate":"2026-04-21T13:29:48.455Z","signature":"E8SYFNFClhrWtEDs5+HzomFjwO/CNx0cMopBkdug+7lIY+2M75df/lf9x4r0NAMb4+r0CBryWOGvqOVG7mD/ru9i+aNxhOuK2XkDPi1g/1C3rJYULIrpyQI/QtgBMZ3FANoOU5TG5pVH1YjMrz5PHtNNRwVC2qrUE3kk4xVKXVsI7lwUMb2FpMu62ibqy082c5+jyOQmAzDygQeIdjKdCsqGccdAP8ZLoA6ReFE6ZSjAMQHs16GM4FSSvJSFIPU83CJIUF93EHnU75q5Oi999SQesBGNpj6t0sT85cWOJ2KWJ7H5PPn/xZEXmKD3Kytx2uVjX/+Ysoe6JxnfX9Bm4A=="}
2026-04-25T10:57:43.372Z I "[ProtocolProxy]","error for GET https://app.tuta.com/rest/sys/saltservice:"
2026-04-25T10:57:43.373Z I "[ProtocolProxy]",?
2026-04-25T10:57:43.373Z I "[ProtocolProxy]","{\"name\":\"TypeError\",\"message\":\"fetch failed\",\"stack\":\"TypeError: fetch failed\"}"
2026-04-25T10:57:43.373Z I "[ProtocolProxy]","failed after 290ms"
```

i don't use Apple iCloud Private Relay (turned off) or any other VPN that routes my traffic

and currently still on Tuta Free plan

web access and iOS app works

the ping thing:

```
~ ping -c3 app.tuta.com
PING app.tuta.com (185.205.69.10): 56 data bytes
64 bytes from 185.205.69.10: icmp_seq=0 ttl=49 time=255.717 ms
64 bytes from 185.205.69.10: icmp_seq=1 ttl=49 time=267.844 ms
64 bytes from 185.205.69.10: icmp_seq=2 ttl=49 time=363.276 ms

--- app.tuta.com ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 255.717/295.612/363.276/48.101 ms

~ ping6 -c3 app.tuta.com
ping6: UDP connect: No route to host
```

**Comment by eclecticpassions** [comment]
It's not working on Mac Sequoia 15.7.5, Tuta Desktop v348.260518.0. I don't use private iCloud relay or VPNs. Web access also works, but I need to export email which is only on Desktop client. I'm a paid user. My logs are the same as @faultables and ping test: 

```bash
❯ ping -c3 app.tuta.com
PING app.tuta.com (185.205.69.10): 56 data bytes
64 bytes from 185.205.69.10: icmp_seq=0 ttl=54 time=218.585 ms
64 bytes from 185.205.69.10: icmp_seq=1 ttl=54 time=208.338 ms
64 bytes from 185.205.69.10: icmp_seq=2 ttl=54 time=203.067 ms

--- app.tuta.com ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 203.067/209.997/218.585/6.443 ms
```

**Comment by faultables** [comment]
> It's not working on Mac Sequoia 15.7.5, Tuta Desktop v348.260518.0. I don't use private iCloud relay or VPNs. Web access also works, but I need to export email which is only on Desktop client. I'm a paid user. My logs are the same as [@faultables](https://github.com/faultables) and ping test:
> 
> ❯ ping -c3 app.tuta.com
> PING app.tuta.com (185.205.69.10): 56 data bytes
> 64 bytes from 185.205.69.10: icmp_seq=0 ttl=54 time=218.585 ms
> 64 bytes from 185.205.69.10: icmp_seq=1 ttl=54 time=208.338 ms
> 64 bytes from 185.205.69.10: icmp_seq=2 ttl=54 time=203.067 ms
> 
> --- app.tuta.com ping statistics ---
> 3 packets transmitted, 3 packets received, 0.0% packet loss
> round-trip min/avg/max/stddev = 203.067/209.997/218.585/6.443 ms

i believe this is a network issue. if you make your dns drop any aaaa queries while your network does not support IPv6 you can somehow access the Tuta Mail desktop app again. not sure why the dual-stack thingy doesn't work on the Tuta Mail desktop app

i no longer use the desktop app since Tuta Mail was the only electron app on my laptop (saves me ~500 MB too) and i don't think dealing with my dns every time i want to open the Tuta Mail desktop app is efficient

i upgraded to Revolutionary and i'm still subscribing to it tho

**Comment by ganthern** [comment]
Hey there! :wave:

> i believe this is a network issue. if you make your dns drop any aaaa queries while your network does not support IPv6 you can somehow access the Tuta Mail desktop app again. not sure why the dual-stack thingy doesn't work on the Tuta Mail desktop app

Just to clarify, this issue occurs on a network where IPv6 connectivity is not available?

> i no longer use the desktop app since Tuta Mail was the only electron app on my laptop (saves me ~500 MB too) and i don't think dealing with my dns every time i want to open the Tuta Mail desktop app is efficient

Fair!

> i upgraded to Revolutionary and i'm still subscribing to it tho

Thank you :)

**Comment by eclecticpassions** [comment]
> i believe this is a network issue. if you make your dns drop any aaaa queries while your network does not support IPv6 you can somehow access the Tuta Mail desktop app again. not sure why the dual-stack thingy doesn't work on the Tuta Mail desktop app

Thanks for your reply @faultables. I am not sure I know how to make DNS drop aaaa queries. Anyway, @ganthern from #10590 told me I can export folders in Tuta webmail so I'll rely on that instead. My account is expiring in June and I'm trying to migrate...

**Comment by hrb-hub** [comment]
Might be fixed by #11508 . Moving to blocked for now.
