### ISSUE TITLE
Can't connect my account on macOS 12.7.6

### ISSUE THREAD

**Issue by annard** [tutao/tutanota#7889]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
I cannot connect to your server. I keep getting an error message that the connection failed. I removed all data from the tuta desktop app and tried to add my account again. There it fails as well. On iOS and Windows I can still access my account from the same network

**To Reproduce**
1. Click Online
2. I get an error message

**Expected behavior**
An updated list of my emails.

**Desktop (please complete the following information):**
 - OS: macOS 12.7.6
 - Desktop Environment, if applicable (on Linux)
 - Version v250.241025.0 - darwin

**Additional context**
Here is the log after I tried to add a new account:

```
v250.241025.0 - darwin


 Client: darwin
 Type: UNKNOWN
 Tutanota version: 250.241025.0
 Timestamp (UTC): Wed, 06 Nov 2024 15:21:00 GMT
 User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/250.241025.0 Chrome/128.0.6613.186 Electron/32.2.2 Safari/537.36


== MAIN LOG ==
2024-11-06T15:18:18.706Z I "\n\n........................................\n........................................\n........................................\n........@@@@@@@@@@@@@@@@@@@@@@@.........\n.....@....@@@@@@@@@@@@@@@@@@@@@@@.......\n.....@@@....@@@@@@@@@@@@@@@@@@@@@@@.....\n.....@@@@@..............................    Do you care about privacy?\n.....@@@@@...@@@@@@@@@@@@@@@@@@@@@@.....\n.....@@@@...@@@@@@@@@@@@@@@@@@@@@@@.....    Work at Tuta! Fight for our rights!\n.....@@@@...@@@@@@@@@@@@@@@@@@@@@@......\n.....@@@...@@@@@@@@@@@@@@@@@@@@@@.......    https://tuta.com/jobs\n.....@@@...@@@@@@@@@@@@@@@@@@@@@@.......\n.....@@...@@@@@@@@@@@@@@@@@@@@@@........\n.....@@...@@@@@@@@@@@@@@@@@@@@@@........\n.....@...@@@@@@@@@@@@@@@@@@@@@@.........\n.....@...@@@@@@@@@@@@@@@@@@@@@@.........\n........@@@@@@@@@@@@@@@@@@@@@@..........\n.......@@@@@@@@@@@@@@@@@@@@@@...........\n.......@@@@@@@@@@@@@@@@@@@@@@...........\n........................................\n........................................\n........................................\n\n"
2024-11-06T15:18:18.768Z I "worker init time (ms):",103
2024-11-06T15:20:56.902Z I "removed topmost modal component"
2024-11-06T15:20:58.564Z I "removed topmost modal component"

== NATIVE LOG ==
2024-11-06T15:16:28.807Z I "the monkey has been patched pid:",13999
2024-11-06T15:16:28.910Z I "Creating tables..."
2024-11-06T15:16:28.919Z I "Current credentials version: undefined"
2024-11-06T15:16:28.919Z I "Migrating to v1"
2024-11-06T15:16:28.921Z I "Tables created successfully!"
2024-11-06T15:16:28.926Z I "version:  ","250.241025.0"
2024-11-06T15:16:28.967Z I "resolving key...","tutanota-vault"
2024-11-06T15:16:29.005Z W "key tutanota-vault not found, generating a new one"
2024-11-06T15:16:29.039Z I "[DesktopMain]","getting dictionaries from:","https://app.tuta.com/desktop/dictionaries/"
2024-11-06T15:16:29.039Z I "config up to date"
2024-11-06T15:16:29.042Z I "[DesktopMain]","spellcheck-dictionary-initialized","en-AU"
2024-11-06T15:16:29.050Z I "[2024-11-06T15:16:29.049Z]","Create tray:true"
2024-11-06T15:16:29.053Z I "[SSEFacade]","last missed notification check:",{"lastMissedNotificationCheckTime":null}
2024-11-06T15:16:29.054Z I "[ApplicationWindow]","webAssetsPath: ","/Users/annard/Applications/Tuta Mail.app/Contents/Resources/app.asar"
2024-11-06T15:16:29.088Z I "default mailto handler:",false
2024-11-06T15:16:29.088Z I "Webapp ready"
2024-11-06T15:16:29.089Z I "[2024-11-06T15:16:29.089Z]","[ElectronUpdater]","DEBUG:","no update info on disk, disabling updater."
2024-11-06T15:16:29.091Z I "[SSEFacade]","No SSE info"
2024-11-06T15:16:50.763Z I "[ProtocolProxy]","error for GET https://app.tuta.com/rest/sys/saltservice:"
2024-11-06T15:16:50.764Z I "[ProtocolProxy]",?
2024-11-06T15:16:50.764Z I "[ProtocolProxy]","{\"name\":\"TypeError\",\"message\":\"fetch failed\",\"stack\":\"TypeError: fetch failed\\n    at eh (/Users/annard/Applications/Tuta Mail.app/Contents/Resources/app.asar/desktop/DesktopMain.js:10:11383)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async /Users/annard/Applications/Tuta Mail.app/Contents/Resources/app.asar/desktop/DesktopMain.js:10:33049\\n    at async AsyncFunction.<anonymous> (node:electron/js2c/browser_init:2:52165)\"}"
2024-11-06T15:16:50.764Z I "[ProtocolProxy]","failed after 10033ms"
2024-11-06T15:17:07.061Z I "[ProtocolProxy]","error for GET https://app.tuta.com/rest/sys/saltservice:"
2024-11-06T15:17:07.061Z I "[ProtocolProxy]",?
2024-11-06T15:17:07.061Z I "[ProtocolProxy]","{\"name\":\"TypeError\",\"message\":\"fetch failed\",\"stack\":\"TypeError: fetch failed\\n    at eh (/Users/annard/Applications/Tuta Mail.app/Contents/Resources/app.asar/desktop/DesktopMain.js:10:11383)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async /Users/annard/Applications/Tuta Mail.app/Contents/Resources/app.asar/desktop/DesktopMain.js:10:33049\\n    at async AsyncFunction.<anonymous> (node:electron/js2c/browser_init:2:52165)\"}"
2024-11-06T15:17:07.061Z I "[ProtocolProxy]","failed after 10003ms"
2024-11-06T15:18:18.410Z I "[ApplicationWindow]","webAssetsPath: ","/Users/annard/Applications/Tuta Mail.app/Contents/Resources/app.asar"
```
[1730905704688_desktop_tutanota.log](https://github.com/user-attachments/files/17649185/1730905704688_desktop_tutanota.log)
[1730905704688_main_tutanota.log](https://github.com/user-attachments/files/17649187/1730905704688_main_tutanota.log)
[1730905704688_worker_tutanota.log](https://github.com/user-attachments/files/17649188/1730905704688_worker_tutanota.log)

**Comment by annard** [comment]
Web access works also fine.

**Comment by charlag** [comment]
Montorey is not maintained by Apple anymore, I think it might miss new root certificates. Browsers tend to ship their own.

**Comment by annard** [comment]
No worries, that was the hint I was looking for. Now with the aid of [this article](https://apple.stackexchange.com/questions/422332/how-do-i-update-my-root-certificates-on-an-older-version-of-mac-os-e-g-el-capi) I have updated my root certs and it is working again.

Thanks!
Annard
