### ISSUE TITLE
Array.prototype.includes should be polyfilled or avoided

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#800]
v3.41.0

Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537

```
Error message: 
Object doesn't support property or method 'includes'

Stacktrace: 
TypeError: Object doesn't support property or method 'includes'
at value (https://mail.tutanota.com/main-boot.js:1:257797)
at Anonymous function (https://mail.tutanota.com/main.js:1:499829)
at view (https://mail.tutanota.com/main-boot.js:1:131286)
at initComponent (https://mail.tutanota.com/main-boot.js:1:227943)
at createComponent (https://mail.tutanota.com/main-boot.js:1:228328)
at createNode (https://mail.tutanota.com/main-boot.js:1:225297)
at createNodes (https://mail.tutanota.com/main-boot.js:1:225153)
at createElement (https://mail.tutanota.com/main-boot.js:1:227356)
at createNode (https://mail.tutanota.com/main-boot.js:1:225617)
at createNodes (https://mail.tutanota.com/main-boot.js:1:225153)
```

**Comment by charlag** [comment]
It is supported well enough
