### ISSUE TITLE
HTMLElement.protype.focus is not supported in some browsers

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#801]
v3.41.0

Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537

```
Error message: 
Object doesn't support property or method 'focus'

Stacktrace: 
TypeError: Object doesn't support property or method 'focus'
at render (https://mail.tutanota.com/main-boot.js:1:242651)
at run1 (https://mail.tutanota.com/main-boot.js:1:248051)
at lastUpdate (https://mail.tutanota.com/main-boot.js:1:248617)
at Anonymous function (https://mail.tutanota.com/main-boot.js:1:248772)
at a (https://mail.tutanota.com/libs.js:26:73149)
at F.prototype._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46535)
at F.prototype._settlePromise (https://mail.tutanota.com/libs.js:26:47337)
at F.prototype._settlePromiseCtx (https://mail.tutanota.com/libs.js:26:47843)
at h (https://mail.tutanota.com/libs.js:26:1697)
at p (https://mail.tutanota.com/libs.js:26:1585)
```

**Comment by charlag** [comment]
We will add check for such browsers and disable them

**Comment by charlag** [comment]
@mathiascode it works quite weird without it I'd say, I'm not even sure how much.
We are sorry that we didn't announce it but it's hard to predict for all devices and it wasn't deteced during our (pretty long) beta phase.
We try to support all the browsers we could but with people who are stuck with unupdatable browsers it's always hard. I would say that you're at a pretty big security risk by this point.
