### ISSUE TITLE
CancelledError when entering the wrong app password after changing account password

### ISSUE THREAD

**Issue by paw-hub** [tutao/tutanota#8021]
To reproduce:
1. Log in and log out, saving credentials and using app password
2. Change your account password on a different client
3. Try to log in again. Enter the app password correctly the first time.
4. When prompted to enter the app password a second time, enter the wrong app password.
5. Error

```
Feedback v252.241122.0 - CancelledError - PAID - linux
Client: linux
Type: PAID
Tutanota version: 252.241122.0
Timestamp (UTC): Tue, 26 Nov 2024 13:26:31 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/252.241122.0 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
CancelledError
Error message: app Pass verification failed
Stacktrace:
CancelledError: app Pass verification failed
at _F.removeAppPassWrapper (/tmp/.mount_tutanogMQqwC/resources/app.asar/desktop/DesktopMain.js:25:2576)
at async kF.decryptUsingKeychain (/tmp/.mount_tutanogMQqwC/resources/app.asar/desktop/DesktopMain.js:25:16446)
at async aD.getCredentialsEncryptionKey (/tmp/.mount_tutanogMQqwC/resources/app.asar/desktop/DesktopMain.js:11:212973)
at async aD.loadByUserId (/tmp/.mount_tutanogMQqwC/resources/app.asar/desktop/DesktopMain.js:11:210709)
at async ipc (/tmp/.mount_tutanogMQqwC/resources/app.asar/desktop/DesktopMain.js:11:221985)
```

**Comment by wrdhub** [comment]
Issue no longer occurs, app password is not asked for a second time. It does result in a blank page after entering the account password, you have to click on a folder before anything shows up. A little annoying, but a different issue
