### ISSUE TITLE
[Android] Not allowed to start service Intent

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#804]
v3.40.3

```
Error message: 
Not allowed to start service Intent { cmp=de.tutao.tutanota/.push.PushNotificationService (has extras) }: app is in background uid UidRecord{ff011c1 u0a132 TRNB bg:+12m35s448ms idle change:uncached procs:2 seq(0,0,0)}

Stacktrace: 
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=de.tutao.tutanota/.push.PushNotificationService (has extras) }: app is in background uid UidRecord{ff011c1 u0a132 TRNB bg:+12m35s448ms idle change:uncached procs:2 seq(0,0,0)}
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1522)
at android.app.ContextImpl.startService(ContextImpl.java:1478)
at android.content.ContextWrapper.startService(ContextWrapper.java:651)
at de.tutao.tutanota.Native.cancelNotifications(Native.java:275)
at de.tutao.tutanota.Native.invokeMethod(Native.java:226)
at de.tutao.tutanota.Native.lambda$invoke$2(Native.java:78)
at de.tutao.tutanota.-$$Lambda$Native$8fBIKwro4kS4gvJJ99lRbXtVm5g.run(Unknown Source:4)
at java.lang.Thread.run(Thread.java:764)
```

we should at least silence the error

**Comment by ganthern** [comment]
another one: 
```
Client: android
Type: FREE
Tutanota version: 3.47.2
Timestamp (UTC): Wed, 20 Feb 2019 11:31:43 GMT
User agent:
Mozilla/5.0 (Linux; Android 9; LYA-L09 Build/HUAWEILYA-L09; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/72.0.3626.105 Mobile Safari/537.36

Error message:
Not allowed to start service Intent { cmp=de.tutao.tutanota/.push.PushNotificationService (has extras) }: app is in background uid UidRecord{7ac794f u0a193 TPSL bg:+11m45s541ms idle change:cached procs:2 seq(0,0,0)}

Stacktrace:
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=de.tutao.tutanota/.push.PushNotificationService (has extras) }: app is in background uid UidRecord{7ac794f u0a193 TPSL bg:+11m45s541ms idle change:cached procs:2 seq(0,0,0)}
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1842)
at android.app.ContextImpl.startService(ContextImpl.java:1797)
at android.content.ContextWrapper.startService(ContextWrapper.java:664)
at de.tutao.tutanota.h.a(Unknown Source:74)
at de.tutao.tutanota.h.a(Unknown Source:431)
at de.tutao.tutanota.h.f(Unknown Source:49)
at de.tutao.tutanota.h.lambda$7Tg1F3chrDWiS3SpgrklGpWY-4k(Unknown Source:0)
at de.tutao.tutanota.-$$Lambda$h$7Tg1F3chrDWiS3SpgrklGpWY-4k.run(Unknown Source:4)
at java.lang.Thread.run(Thread.java:784)
```

apparently starting services while in background is being phased out: https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten

**Comment by charlag** [comment]
We didn't get this error since 3.64.3
