### ISSUE TITLE
SQLiteException: Database is locked

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#8049]
v250.241025.0 and up

```
Error message:
error code 5: database is locked

Stacktrace:
net.sqlcipher.database.SQLiteException: error code 5: database is locked
	at net.sqlcipher.database.SQLiteStatement.native_execute(Native Method)
	at net.sqlcipher.database.SQLiteStatement.execute(Unknown Source:19)
	at net.sqlcipher.database.SQLiteDatabase.execSQL(SourceFile:0)
	at de.tutao.tutashared.offline.AndroidSqlCipherFacade.run(Unknown Source:8)
	at de.tutao.tutashared.ipc.SqlCipherFacadeReceiveDispatcher.dispatch(Unknown Source:339)
	at de.tutao.tutashared.ipc.AndroidGlobalDispatcher.dispatch(Unknown Source:154)
	at de.tutao.tutanota.RemoteBridge.invokeMethod(Unknown Source:62)
	at de.tutao.tutanota.RemoteBridge.handleMessageFromWeb(Unknown Source:204)
	at de.tutao.tutanota.RemoteBridge$initMessageChannel$1$onMessage$1.invokeSuspend(Unknown Source:41)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:98)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
```

**Estimated: 8h**
**Taken: 4h**

## Test notes:
- [ ] Test offline login, that you can see mails in offline mode

**Comment by charlag** [comment]
This can probably happen when we are writing from notification process and then at the same time try to write from the main process.

https://discuss.zetetic.net/t/database-locked-error-code-5/1763

Theoretically SQLite has WAL mode:
https://www.sqlite.org/wal.html

but I'm almost sure it won't work because we are using it across processes. 

We can try adding automatic retry on locked errors. We can also try to see how Android implements multiprocess Room.
