### ISSUE TITLE
ParsingError: Invalid birthday format

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#8051]
```
Error message:
Invalid birthday format: --00-07
Stacktrace:
ParsingError: Invalid birthday format: --00-07
    at O (https://assets.tutanota.com/common-C_spbC6L.js:1:2245)
    at https://assets.tutanota.com/date-CP3gbtxQ.js:1:85412
    at Array.sort (<anonymous>)
    at CalendarEventsRepository.loadContactsBirthdays (https://assets.tutanota.com/date-CP3gbtxQ.js:1:85390)
    at async https://assets.tutanota.com/calendar-view-Cpf_PvEY.js:1:61451
App version:
251.241112.0
Client type:
Android
Additional info:
Mozilla/5.0 (Linux; Android 12; SM-T865 Build/SP2A.220305.013; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/102.0.5005.125 Safari/537.36
```

**Comment by murilopereirame** [comment]
We don't support short dates with just ```year-month``` so this is an invalid date. If this happens again, the needs to be edited and the birthday should be a full date or ```MM-dd``` date. For now on, new dates can't be created using this invalid format

**Comment by andrehgdias** [comment]
We still get the error when opening the calendar in an account with invalid contacts birthdays(as reported before) or when receiving the entity update:

```
ParsingError: Invalid birthday format: --00-31
at dp (https://app.test.tuta.com/common-DXIfClp7.js:1:390784)
at https://app.test.tuta.com/date-DeYfRKXB.js:1:161149
at Array.sort (<anonymous>)
at CalendarEventsRepository.loadContactsBirthdays (https://app.test.tuta.com/date-DeYfRKXB.js:1:161127)
at async CalendarViewModel.entityEventReceived (https://app.test.tuta.com/calendar-view-DyZPzWZT.js:1:67220)
at async https://app.test.tuta.com/main-Dj0LnmLT.js:1:81547
```
Ideally we could catch these errors and show a prettier message to the user asking them to edit the contact, show a toast informing them of the issue or clear the birthday field from these contacts.
