### ISSUE TITLE
 Creating the search index was aborted due to an error

### ISSUE THREAD

**Issue by hommerko** [tutao/tutanota#8095]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
 while trying to type a word to search field a got this message "Creating the search index was aborted due to an error"
I'm experiencing this message as well on web app. 

- OS win 10
- browsers  tried - Firefox , Brave Egde  (all updated )
- I have Revolutionary plan  

![image](https://github.com/user-attachments/assets/0e26d121-482d-4c0c-820d-8341d1ee1c4a)

Any idea ?

**Comment by hrb-hub** [comment]
Thank you for reporting the issue. Unfortunately we were not able to reproduce it based solely on the information provided. Could you please have a look at the logs and see if you can maybe provide us with more details? Cheers :)

**Comment by hrb-hub** [comment]
You can send the logs to hello[at]tutao.de if you're on the free plan. Alternatively, please contact support via the help icon in the app if you are a paying customer.

Cheers again :)

**Comment by hrb-hub** [comment]
Please note that since you're a paying customer, you may also contact support via the help icon in the app.

**Comment by hommerko** [comment]
> Please note that since you're a paying customer, you may also contact support via the help icon in the app.

Thanks I did  sent you logs. 

and as well up here :) 
[2024-12-10-20h32m34s-attachments.zip](https://github.com/user-attachments/files/18084976/2024-12-10-20h32m34s-attachments.zip)

the problem still persist , even on my tablets.
thank for help.

**Comment by charlag** [comment]
@hommerko hey, thank you for the logs, it does help but we need to investigate more.

**Comment by timsueberkrueb** [comment]
Hey there, I have the same issue. This bug is critical to me as it prevents me from searching my emails, a feature I rely on.
It happens whenever I select an old enough date in the past in the "From" field which is sometimes required when looking for an old email, independent of device.

Error displayed in the UI:

```
Creating the search index was aborted due to an error
```

Errors from the developer console:

<details>

```
RestClient] failed request GET https://app.tuta.com/rest/tutanota/mail/<omitted>?start=<omitted>&count=100&reverse=true 
403 Forbidden 
Logger.ts:94 Mail indexing failed:  
{
    "name": "NotAuthorizedError",
    "message": "403: <omitted> | GET /rest/tutanota/mail/<omitted>",
    "stack": "NotAuthorizedError: 403: <omitted> | GET /rest/tutanota/mail/<omitted>\n    at dJ (asset://app/common-min-8tnWe91U.js:1:10681)\n    at l.onload (asset://app/mail-worker.js:23:17957)"
}
at warn @ Logger.ts:94
```

</details>

Client info:

<details>

```
Client: linux
Type: PAID
Tutanota version: 259.241213.0
Timestamp (UTC): Mon, 16 Dec 2024 20:03:03 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/259.241213.0 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
```

</details>

Client logs (excerpt):

<details>

```
2024-12-16T19:51:54.665Z I "[RestClient]","failed request","GET","https://app.tuta.com/rest/tutanota/mail/<omitted>?ids=<omitted>",0,"",["accessToken","v","cv","Accept"],"no body"
2024-12-16T19:51:54.666Z I "[RestClient]","failed request","GET","https://app.tuta.com/rest/tutanota/mail/<omitted>?ids=<omitted>",0,"",["accessToken","v","cv","Accept"],"no body"
2024-12-16T19:57:35.912Z I "finished loading, setting min id"
2024-12-16T19:57:36.633Z I "finished loading, setting min id"
2024-12-16T19:57:36.752Z I "finished loading, setting min id"
2024-12-16T19:57:37.310Z I "finished loading, setting min id"
2024-12-16T19:57:44.447Z I "finished loading, setting min id"
2024-12-16T19:57:58.445Z I "finished loading, setting min id"
2024-12-16T19:58:11.565Z I "[RestClient]","failed request","GET","https://app.tuta.com/rest/tutanota/mail/<omitted>?start=<omitted>&count=100&reverse=true",403,"Forbidden",["accessToken","v","cv","Accept"],"no body"
2024-12-16T19:58:11.566Z W "Mail indexing failed: ",NotAuthorizedError
 Error message: 403: <omitted> | GET /rest/tutanota/mail/<omitted>
```

</details>

I also sent the full logs to the support email.

**Comment by charlag** [comment]
@timsueberkrueb hi, sorry to hear that you have this issue! Could you please try disabling mailbox search, deleting credentials on one of your devices, and then logging in again? We suspect something about the indexer might be cached improperly.

**Comment by timsueberkrueb** [comment]
Thanks for the fast response. On the same machine as above, I

* disabled mailbox search in the settings
* deleted my credentials by removing the account from the app
* deleted local config/cache: 
    ```
    > rm -rf ~/.config/tutanota-desktop/
    > rm -rf ~/.cache/tutanota-desktop-updater/
    ```

then logged in again. Now the issue already occurs when I place my cursor in the search field as described in #8068.

```
Creating the search index was aborted due to an error
```

**Developer console:**

<details>

```
RestClient] failed request GET https://app.tuta.com/rest/tutanota/mail/OCZOyGg--7-9?start=OELqNL------&count=100&reverse=true 403 Forbidden Array(4) no body

Mail indexing failed: 
  at i:
    message: '403: OEJgPZL--B-9 | GET /rest/tutanota/mail/<omitted>'
    name: "NotAuthorizedError"
    stack: 'NotAuthorizedError: 403: <omitted> | GET /rest/tutanota/mail/<omitted>\n    at dJ (asset://app/common-min-8tnWe91U.js:1:10681)\n    at l.onload (asset://app/mail-worker.js:23:17957)'
```

</details>

I sent you the full logs via the support email.

**Comment by timsueberkrueb** [comment]
Hey, did you roll out a fix to the backend? I'm happy to report that since today, I can no longer reproduce the problem. Thanks!

**Comment by charlag** [comment]
Hey, we haven't really found the cause but it seems to have been fixed for most of those who we know had it
