### ISSUE TITLE
Android/iOS: BadRequestError when calling publickeyservice with invalid email address

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#816]
Error message: 
400: LRc5nlY----1 | GET /rest/sys/publickeyservice

Stacktrace: 
BadRequestError: 400: LRc5nlY----1 | GET /rest/sys/publickeyservice
at handleRestError (file:///android_asset/tutanota/dist/main-boot.js:1:259075)
at XMLHttpRequest.xhr.onload (file:///android_asset/tutanota/dist/worker.js:1:572771)

**Comment by armhub** [comment]
Solution: filter contacts coming from the native side.
