### ISSUE TITLE
 Service Worker Response Error

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#823]
Example of stacktrace.
Should have had error id before the `|` symbol

```
Error message: 
500: Service Worker Response Error | GET  /rest/sys/entityeventbatch/.../...

Stacktrace: 
InternalServerError: 500: Service Worker Response Error | GET /rest/sys/entityeventbatch/.../...
at handleRestError (https://mail.tutanota.com/main-boot.js:1:261746)
at XMLHttpRequest.xhr.onload (https://mail.tutanota.com/worker.js:1:573145)
```

**Comment by charlag** [comment]
Assumption was not true, this is an error in service worker

**Comment by charlag** [comment]
It's happening only in Chrome. We receive some other errors for other environments. I would assume that Chrome doesn't handle status codes correctly sometimes.

**Comment by charlag** [comment]
This hasn't been reported in a very long time
