### ISSUE TITLE
TypeError performance.mark undefined is not a function

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#836]
Client: Browser
Type: FREE
Tutanota version: 3.41.4
Timestamp (UTC): Fri, 23 Nov 2018 10:51:05 GMT
User agent: 
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) MxNitro/1.0.1.3000 Chrome/35.0.1849.0 Safari/537.36

Error message: 
undefined is not a function

Stacktrace: 
TypeError: undefined is not a function
at IndexerCore._createClass.value (https://mail.tutanota.com/worker.js:1:284021)
at https://mail.tutanota.com/worker.js:1:281013
at a (https://mail.tutanota.com/libs.js:26:73165)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46542)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromise0 (https://mail.tutanota.com/libs.js:26:48041)
at F._settlePromises (https://mail.tutanota.com/libs.js:26:49393)
at h (https://mail.tutanota.com/libs.js:26:1646)
at p (https://mail.tutanota.com/libs.js:26:1566)
at a._drainQueues (https://mail.tutanota.com/libs.js:26:3078)
at drainQueues (https://mail.tutanota.com/libs.js:26:1327)

**Comment by charlag** [comment]
Note that this is a Chrome 35, idk if we should support that

23 Nov 2018, 13:13 by notifications@github.com:
