### ISSUE TITLE
Error - Undefined dom element for virtual dom element

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#839]
```
Client: Browser
Tutanota version: 3.41.5
User agent: 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

Error message: 
undefined dom element for virtual dom element 40, 0

Stacktrace: 
Error: undefined dom element for virtual dom element 40, 0
at value (https://mail.tutanota.com/main.js:1:683760)
at Anonymous function (https://mail.tutanota.com/main.js:1:678086)
```

**Comment by charlag** [comment]
should be fixed by e82c1f4c07d3f19b83105cb4fcd45e66f10a33ac

**Comment by charlag** [comment]
<summary>
Reports
<details>

```
Client: Browser
Tutanota version: 3.44.9
User agent: 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

Error message: 
undefined dom element for virtual dom element 42, 0

Stacktrace: 
Error: undefined dom element for virtual dom element 42, 0
at List.value (https://mail.tutanota.com/main.js:1:555208)
at List.value (https://mail.tutanota.com/main.js:1:545697)
at List.value (https://mail.tutanota.com/main.js:1:558021)
at List.value (https://mail.tutanota.com/main.js:1:557014)
at MailView.value (https://mail.tutanota.com/main.js:1:182217)
at https://mail.tutanota.com/main-boot.js:1:329817
at a (https://mail.tutanota.com/libs.js:26:73165)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46542)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromiseCtx (https://mail.tutanota.com/libs.js:26:47848)
at h (https://mail.tutanota.com/libs.js:26:1699)
at p (https://mail.tutanota.com/libs.js:26:1585)
at a._drainQueues (https://mail.tutanota.com/libs.js:26:3078)
at https://mail.tutanota.com/libs.js:26:1327
```

```
Client: Browser
Tutanota version: 3.44.9
User agent: 
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 YaBrowser/18.11.1.805 Yowser/2.5 Safari/537.36

Error message: 
undefined dom element for virtual dom element 42, 0

Stacktrace: 
Error: undefined dom element for virtual dom element 42, 0
at List.value (https://mail.tutanota.com/main.js:1:555208)
at List.value (https://mail.tutanota.com/main.js:1:545697)
at List.value (https://mail.tutanota.com/main.js:1:558021)
at List.value (https://mail.tutanota.com/main.js:1:557014)
at MailView.value (https://mail.tutanota.com/main.js:1:182217)
at https://mail.tutanota.com/main-boot.js:1:329817
at a (https://mail.tutanota.com/libs.js:26:73165)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46542)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromiseCtx (https://mail.tutanota.com/libs.js:26:47848)
at h (https://mail.tutanota.com/libs.js:26:1699)
at p (https://mail.tutanota.com/libs.js:26:1585)
at a._drainQueues (https://mail.tutanota.com/libs.js:26:3078)
at drainQueues (https://mail.tutanota.com/libs.js:26:1327)
```
```
Client: Browser
Tutanota version: 3.45.2
User agent: 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

Error message: 
undefined dom element for virtual dom element 44, 0

Stacktrace: 
Error: undefined dom element for virtual dom element 44, 0
at List.value (https://mail.tutanota.com/main.js:1:556245)
at List.value (https://mail.tutanota.com/main.js:1:546734)
at List.value (https://mail.tutanota.com/main.js:1:559058)
at List.value (https://mail.tutanota.com/main.js:1:558051)
at MailView.value (https://mail.tutanota.com/main.js:1:182695)
at https://mail.tutanota.com/main-boot.js:1:331806
at a (https://mail.tutanota.com/libs.js:26:73165)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46542)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromiseCtx (https://mail.tutanota.com/libs.js:26:47848)
at h (https://mail.tutanota.com/libs.js:26:1699)
at p (https://mail.tutanota.com/libs.js:26:1585)
at a._drainQueues (https://mail.tutanota.com/libs.js:26:3078)
at https://mail.tutanota.com/libs.js:26:1327
```
</details>
</summary>

**Comment by charlag** [comment]
Didn't happen for a few months
