### ISSUE TITLE
[Android] Cannot get file info from MIUI gallery 

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#841]
Reported multiple times.

```
Client: android app
Tutanota version: 3.41.1
User agent: 
Mozilla/5.0 (Linux; Android 5.1.1; 2014819 Build/LMY47V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.80 Mobile Safari/537.36

Error message: 
could not resolve file name / size for uri content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2FDCIM%2FScreenshots%2FScreenshot_xxx-xx-xx-xx_com.google.android.gm.png

Stacktrace: 
java.lang.RuntimeException: could not resolve file name / size for uri content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2FDCIM%2FScreenshots%2FScreenshot_xxx-xx-xx-xx_com.google.android.gm.png
at de.tutao.tutanota.Utils.getFileInfo(Utils.java:76)
at de.tutao.tutanota.FileUtil.getName(FileUtil.java:187)
at de.tutao.tutanota.Native.invokeMethod(Native.java:194)
at de.tutao.tutanota.Native.lambda$invoke$2(Native.java:78)
at de.tutao.tutanota.-$$Lambda$Native$8fBIKwro4kS4gvJJ99lRbXtVm5g.run(lambda)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by charlag** [comment]
New report, this time for the Office, should be easier to reproduce

```
Client: android app
Tutanota version: 3.44.4
User agent: 
Mozilla/5.0 (Linux; Android 7.0; SM-G925F Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/72.0.3626.76 Mobile Safari/537.36

Error message: 
could not resolve file name / size for uri content://com.microsoft.office.word.fileprovider/ffaa9f80-3353-4342-afd7-c15246a8be95/XXXX%20XXXX%20XXX-XXXX.docx

Stacktrace: 
java.lang.RuntimeException: could not resolve file name / size for uri content://com.microsoft.office.word.fileprovider/ffaa9f80-3353-4342-afd7-c15246a8be95/XXXX%20XXXX%20XXX-XXXX.docx
at de.tutao.tutanota.Utils.getFileInfo(Utils.java:79)
at de.tutao.tutanota.Crypto.aesEncryptFile(Crypto.java:210)
at de.tutao.tutanota.Native.invokeMethod(Native.java:176)
at de.tutao.tutanota.Native.lambda$invoke$2(Native.java:78)
at de.tutao.tutanota.-$$Lambda$Native$8fBIKwro4kS4gvJJ99lRbXtVm5g.run(lambda)
at java.lang.Thread.run(Thread.java:762)
```

**Comment by charlag** [comment]
Could not reproduce with Office, local file, file in OneDrive, file with spaces or with a dash. Asked for more details

**Comment by ganthern** [comment]
still happening:

```
Client: android
Type: FREE
Tutanota version: 3.105.9
Timestamp (UTC): Mon, 19 Dec 2022 11:14:19 GMT
User agent:
Mozilla/5.0 (Linux; Android 11; Mi 9T Pro Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36
java.lang.RuntimeException
Error message: could not resolve file name / size for uri content://[com.microsoft](http://com.microsoft/).skydrive.content.external/Drive/ID/1/Item/RID/[numbers]%[numbers]/Stream/1/Property/[filename].pdf?externalUriType=GetContent
Stacktrace:
java.lang.RuntimeException: could not resolve file name / size for uri content://[com.microsoft](http://com.microsoft/).skydrive.content.external/Drive/ID/1/Item/RID/[numbers]%[numbers]/Stream/1/Property/[filename].pdf?externalUriType=GetContent
at de.tutao.tutanota.Utils.getFileInfo(Utils.kt:88)
at de.tutao.tutanota.AndroidFileFacade.getName(AndroidFileFacade.kt:219)
at de.tutao.tutanota.ipc.FileFacadeReceiveDispatcher.dispatch(FileFacadeReceiveDispatcher.kt:47)
at de.tutao.tutanota.ipc.AndroidGlobalDispatcher.dispatch(AndroidGlobalDispatcher.kt:36)
at de.tutao.tutanota.RemoteBridge.invokeMethod(RemoteBridge.kt:153)
at de.tutao.tutanota.RemoteBridge.handleMessageFromWeb(RemoteBridge.kt:90)
at de.tutao.tutanota.RemoteBridge$initMessageChannel$1$onMessage$1.invokeSuspend(RemoteBridge.kt:58)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at [kotlinx.coroutines.DispatchedTask.run](http://kotlinx.coroutines.dispatchedtask.run/)(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by charlag** [comment]
Did not see this, will reopen if needed
