### ISSUE TITLE
[Android] FileNotFoundException when adding to downloads

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#858]
```
Client: android app
Tutanota version: 3.41.6
User agent: 
Mozilla/5.0 (Linux; Android 6.0.1; 503KC Build/102.0.2c30; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.80 Mobile Safari/537.36

Stacktrace: 
java.io.FileNotFoundException: /storage/emulated/0/Download/*****.pdf: open failed: ENOENT (No such file or directory)
at libcore.io.IoBridge.open(IoBridge.java:452)
at java.io.FileOutputStream.(FileOutputStream.java:87)
at java.io.FileOutputStream.(FileOutputStream.java:72)
at de.tutao.tutanota.FileUtil.addFileToDownloads(FileUtil.java:171)
at de.tutao.tutanota.FileUtil.lambda$null$2(FileUtil.java:156)
at de.tutao.tutanota.-$$Lambda$FileUtil$CDv0_OITXgBUZ2InUFNGvTevWz4.run(lambda)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
at libcore.io.Posix.open(Native Method)
at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
at libcore.io.IoBridge.open(IoBridge.java:438)
... 8 more
```

**Comment by vitoreiji** [comment]
Can you add some details on how to reproduce, please?

**Comment by charlag** [comment]
I think this happens when Downloads folder doesn't exist but I think we fixed this already
