### ISSUE TITLE
Error: formatDateWithWeekday

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#859]
Reported few times

```
Client: Browser
Tutanota version: 3.41.5
User agent: 
Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

Stacktrace: 
Error
at formatDateWithWeekday (https://mail.tutanota.com/main.js:1:1207739)
at formatDateTimeFromYesterdayOn (https://mail.tutanota.com/main.js:1:1208026)
at value (https://mail.tutanota.com/main.js:1:270636)
at value (https://mail.tutanota.com/main.js:1:684501)
at value (https://mail.tutanota.com/main.js:1:683982)
at Anonymous function (https://mail.tutanota.com/main.js:1:677225)
at y (https://mail.tutanota.com/libs.js:26:27619)
at a (https://mail.tutanota.com/libs.js:26:73149)
at F.prototype._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46383)
at F.prototype._settlePromise (https://mail.tutanota.com/libs.js:26:47337)
```

**Comment by charlag** [comment]
Duplicate of #889
