### ISSUE TITLE
TypeError MailEditor

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#860]
```
Client: android app
Tutanota version: 3.41.1
User agent: 
Mozilla/5.0 (Linux; Android 8.0.0; SM-G955F Build/R16NW; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.80 Mobile Safari/537.36

Error message: 
Cannot read property 'name' of null

Stacktrace: 
TypeError: Cannot read property 'name' of null
at file:///android_asset/tutanota/dist/main.js:1:321098
at Array.map ()
at MailEditor.value (file:///android_asset/tutanota/dist/main.js:1:321053)
at MailEditor.value (file:///android_asset/tutanota/dist/main.js:1:318904)
at MailViewer.value (file:///android_asset/tutanota/dist/main.js:1:244490)
at HTMLDivElement.onclick (file:///android_asset/tutanota/dist/main.js:1:235777)
at HTMLDivElement.callback (file:///android_asset/tutanota/dist/main-boot.js:1:242011)
```

**Comment by charlag** [comment]
Duplicate of #821
