### ISSUE TITLE
TypeError null is not an object moreResultsEntries

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#870]
Seems to be a timing issue. We wanted to get more results but new search result (`null`) came before that.

```
Trying to search for the mail. The word I entered disappears and the window blinks.
I see no results.

Client: ios app
Tutanota version: 3.41.7
User agent: 
Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16A366

Error message: 
null is not an object (evaluating 'neverNull(_this3._searchResult).moreResultsEntries')

Stacktrace: 
file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/main.js:1:411700
a@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:73170
_settlePromiseFromHandler@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:46546
_settlePromise@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:47367
_settlePromise0@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:48055
_settlePromises@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:49408
_fulfill@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:48426
_settlePromiseFromHandler@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:46712
_settlePromise@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:47367
_settlePromise0@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:48055
_settlePromises@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:49408
_fulfill@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:48426
_resolve@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:52833
_promiseFulfilled@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:35039
_settlePromise@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:47460
_settlePromise0@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:48055
_settlePromises@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:49408
_fulfill@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:48426
_settlePromise@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:47548
_settlePromise0@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:48055
_settlePromises@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:49408
_fulfill@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:48426
_settlePromiseFromHandler@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:46712
_settlePromise@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:47367
_settlePromise0@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:48055
_settlePromises@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:49408
_fulfill@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:48426
file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/libs.js:26:37186
value@file:///var/containers/Bundle/Application/8AA2B367-DC21-426D-A54B-A2863E40DDEE/tutanota.app/build/dist/common.js:1:187105
```

**Comment by charlag** [comment]
> I was searching and deleting emails.

```
Client: linux
Tutanota version: 3.46.2
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.46.2 Chrome/69.0.3497.106 Electron/4.0.2 Safari/537.36

Error message: 
Cannot read property 'moreResultsEntries' of null

Stacktrace: 
TypeError: Cannot read property 'moreResultsEntries' of null
at file:///tmp/.mount_tutanoWe0HiA/resources/app.asar/main.js:1:336136
at a (file:///tmp/.mount_tutanoWe0HiA/resources/app.asar/libs.js:26:73165)
at F._settlePromiseFromHandler (file:///tmp/.mount_tutanoWe0HiA/resources/app.asar/libs.js:26:46542)
at F._settlePromise (file:///tmp/.mount_tutanoWe0HiA/resources/app.asar/libs.js:26:47342)
at F._settlePromise0 (file:///tmp/.mount_tutanoWe0HiA/resources/app.asar/libs.js:26:48041)
at F._settlePromises (file:///tmp/.mount_tutanoWe0HiA/resources/app.asar/libs.js:26:49393)
at F._fulfill (file:///tmp/.mount_tutanoWe0HiA/resources/app.asar/libs.js:26:48411)
at F._resolveCallback (file:///tmp/.mount_tutanoWe0HiA/resources/app.asar/libs.js:26:45290)
at F._settlePromiseFromHandler (file:///tmp/.mount_tutanoWe0HiA/resources/app.asar/libs.js:26:46696)
at F._settlePromise (file:///tmp/.mount_tutanoWe0HiA/resources/app.asar/libs.js:26:47342)
at F._settlePromise0 (file:///tmp/.mount_tutanoWe0HiA/resources/app.asar/libs.js:26:48041)
at F._settlePromises (file:///tmp/.mount_tutanoWe0HiA/resources/app.asar/libs.js:26:49393)
at F._fulfill (file:///tmp/.mount_tutanoWe0HiA/resources/app.asar/libs.js:26:48411)
at u.e._resolve (file:///tmp/.mount_tutanoWe0HiA/resources/app.asar/libs.js:26:52825)
at u._promiseFulfilled (file:///tmp/.mount_tutanoWe0HiA/resources/app.asar/libs.js:26:35031)
at F._settlePromise (file:///tmp/.mount_tutanoWe0HiA/resources/app.asar/libs.js:26:47443)
```

**Comment by charlag** [comment]
Is not reported anymore
