### ISSUE TITLE
TypeError Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#871]
`hideAnimation` is called before Dropdown is actually rendered.

```
Client: Browser
Tutanota version: 3.41.9
User agent: 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

Error message: 
Cannot read property 'style' of undefined

Stacktrace: 
TypeError: Cannot read property 'style' of undefined
at Dropdown.value (https://mail.tutanota.com/main-boot.js:1:160012)
at Object.onbeforeremove (https://mail.tutanota.com/main-boot.js:1:175679)
at removeNode (https://mail.tutanota.com/main-boot.js:1:240714)
at removeNodes (https://mail.tutanota.com/main-boot.js:1:240151)
at updateNodes (https://mail.tutanota.com/main-boot.js:1:235381)
at updateFragment (https://mail.tutanota.com/main-boot.js:1:236578)
at updateNode (https://mail.tutanota.com/main-boot.js:1:235923)
at updateNodes (https://mail.tutanota.com/main-boot.js:1:233223)
at updateElement (https://mail.tutanota.com/main-boot.js:1:237601)
at updateNode (https://mail.tutanota.com/main-boot.js:1:236001)
at updateComponent (https://mail.tutanota.com/main-boot.js:1:238162)
at updateNode (https://mail.tutanota.com/main-boot.js:1:236050)
at updateNodes (https://mail.tutanota.com/main-boot.js:1:233223)
at updateElement (https://mail.tutanota.com/main-boot.js:1:237601)
at updateNode (https://mail.tutanota.com/main-boot.js:1:236001)
at updateComponent (https://mail.tutanota.com/main-boot.js:1:238162)
```

**Comment by armhub** [comment]
Too hard to reproduce, therefore set to tested.
