### ISSUE TITLE
 Get crypto error if preshared passwords are changed for external users

### ISSUE THREAD

**Issue by asteintutao** [tutao/tutanota#885]
Reproduction: 

1. Write E-mail to external mail address use pre-shared password
2. Login as External user by clicking "Show encrypted email" in the mail the external user received in his mailbox
3. Save credentials as external user 
4. Send another Email with a different password
5. Again click "Show encrypted email" in the new received mail
6. -> error CryptoError: aes decryption failed> pkcs#5 padding corrupt

    at aes256Decrypt (https://test.tutanota.com/worker.js:1:504895)
    at https://test.tutanota.com/worker.js:1:310660
    at a (https://test.tutanota.com/libs.js:26:73165)
    at F._settlePromiseFromHandler (https://test.tutanota.com/libs.js:26:46542)
    at F._settlePromise (https://test.tutanota.com/libs.js:26:47342)
    at F._settlePromise0 (https://test.tutanota.com/libs.js:26:48041)
    at F._settlePromises (https://test.tutanota.com/libs.js:26:49393)
    at F._fulfill (https://test.tutanota.com/libs.js:26:48411)
    at https://test.tutanota.com/libs.js:26:37178
    at IDBRequest.request.onsuccess (https://test.tutanota.com/worker.js:1:416147)

**Comment by ganthern** [comment]
this is the reason for https://github.com/tutao/tutanota/issues/851
