### ISSUE TITLE
Error after changing a user to global admin and back to non admin 

### ISSUE THREAD

**Issue by asteintutao** [tutao/tutanota#923]
Refused to get unsafe header "Retry-After"
RestClient.js? [sm]:50 failed request DELETE https://test.tutanota.com/rest/sys/membershipservice 

error BadRequestError: 400: LTSFIbl----0 | DELETE /rest/sys/membershipservice
    at handleRestError (http://localhost:9000/src/api/common/error/RestError.js:139:11)
    at XMLHttpRequest.xhr.onload (http://localhost:9000/src/api/worker/rest/RestClient.js:109:2043)

if it does not happen try changing the admin flag a few times.

**Comment by asteintutao** [comment]
related to #365

**Comment by bedhub** [comment]
this error occured when trying to remove a non existing group membership. Should only occur when removing admin membership

**Comment by charlag** [comment]
On any change now:
```
TyperError: "Cannot read property 'group' of null"

"TypeError: Cannot read property 'group' of null
    at https://test.tutanota.com/worker.js:1:121477
    at a (https://test.tutanota.com/libs.js:26:73165)
    at F._settlePromiseFromHandler (https://test.tutanota.com/libs.js:26:46542)
    at F._settlePromise (https://test.tutanota.com/libs.js:26:47342)
    at F._settlePromise0 (https://test.tutanota.com/libs.js:26:48041)
    at F._settlePromises (https://test.tutanota.com/libs.js:26:49393)
    at h (https://test.tutanota.com/libs.js:26:1646)
    at p (https://test.tutanota.com/libs.js:26:1585)
    at a._drainQueues (https://test.tutanota.com/libs.js:26:3078)
    at drainQueues (https://test.tutanota.com/libs.js:26:1327)"
```
