### ISSUE TITLE
BadRequestError after upgrading

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#950]
```
I attempted to pay for on fo your business accounts and this is where It led me as soon as I checked out 

Client: Browser
Tutanota version: 3.43.1
User agent: 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

Error message: 
400: LTtltpR----1 | GET /rest/sys/permission/LTtjUnx--B-1

Stacktrace: 
BadRequestError. 400: LTtltpR----1 | GET /rest/sys/permission/LTtjUnx--B-1
at BadRequestError (https://mail.tutanota.com/main-boot.js:1:264839)
at handleRestError (https://mail.tutanota.com/main-boot.js:1:262692)
at xhr.onload (https://mail.tutanota.com/worker.js:1:572523)
```

**Comment by charlag** [comment]
According to multiple people, it happens during the initial signup. It must be that the state is messed up somewhere.
