### ISSUE TITLE
BadRequestError on draftservice

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#951]

**Comment by charlag** [comment]
Happening in 3.43.1

**Comment by ganthern** [comment]
and in 3.47.4

```
Client: Browser
Type: EXTERNAL
Tutanota version: 3.47.4
Timestamp (UTC): Wed, 20 Feb 2019 13:36:47 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

Error message:
400: LZA6rXi----1 | POST /rest/tutanota/draftservice

Stacktrace:
BadRequestError: 400: LZA6rXi----1 | POST /rest/tutanota/draftservice
at handleRestError (https://mail.tutanota.com/common.js:1:177857)
at XMLHttpRequest.xhr.onload (https://mail.tutanota.com/worker.js:1:652531)
```
