### ISSUE TITLE
Error: Sending a message with attachments previously saved as draft

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#952]
```
Sending a message with attachments previously saved as draft

Client: android app
Tutanota version: 3.42.2
User agent: 
Mozilla/5.0 (Linux; Android 9; ONEPLUS A6013 Build/PKQ1.180716.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.98 Mobile Safari/537.36

Error message: 
listId is not defined for [object Object]

Stacktrace: 
Error: listId is not defined for [object Object]
at getLetId (file:///android_asset/tutanota/dist/common.js:1:140350)
at file:///android_asset/tutanota/dist/worker.js:1:200197
at Array.find ()
at file:///android_asset/tutanota/dist/worker.js:1:200125
at Array.forEach ()
at MailFacade.value (file:///android_asset/tutanota/dist/worker.js:1:200088)
at file:///android_asset/tutanota/dist/worker.js:1:199369
at a (file:///android_asset/tutanota/dist/libs.js:26:73165)
at F._settlePromiseFromHandler (file:///android_asset/tutanota/dist/libs.js:26:46542)
at F._settlePromise (file:///android_asset/tutanota/dist/libs.js:26:47342)
at F._settlePromise0 (file:///android_asset/tutanota/dist/libs.js:26:48041)
at F._settlePromises (file:///android_asset/tutanota/dist/libs.js:26:49393)
at F._fulfill (file:///android_asset/tutanota/dist/libs.js:26:48411)
at F._resolveCallback (file:///android_asset/tutanota/dist/libs.js:26:45290)
at F._settlePromiseFromHandler (file:///android_asset/tutanota/dist/libs.js:26:46696)
at F._settlePromise (file:///android_asset/tutanota/dist/libs.js:26:47342)
```

**Comment by charlag** [comment]
> Hi
> 
> The error was as a result of my opening a saved draft email, which had an attachment, removing that attachment, adding another different file with an identical filename (a revised version of the previous) and trying to save the draft.
> I'm a programmer so guessed this might be the problem - I had made this change amongst others since reopening the draft email.
> I resolved it by removing the attached revised file, saving the draft (which the app now allowed me to do - before it was throwing an error) and then adding the revised file and saving and closing the draft again.

```
Client: android app
Tutanota version: 3.42.2
User agent: 
Mozilla/5.0 (Linux; Android 9; ONEPLUS A6003 Build/PKQ1.180716.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.98 Mobile Safari/537.36

Error message: 
listId is not defined for [object Object]

Stacktrace: 
Error: listId is not defined for [object Object]
at getLetId (file:///android_asset/tutanota/dist/common.js:1:140350)
at file:///android_asset/tutanota/dist/worker.js:1:200197
at Array.find ()
at file:///android_asset/tutanota/dist/worker.js:1:200125
at Array.forEach ()
at MailFacade.value (file:///android_asset/tutanota/dist/worker.js:1:200088)
at file:///android_asset/tutanota/dist/worker.js:1:199369
at a (file:///android_asset/tutanota/dist/libs.js:26:73165)
at F._settlePromiseFromHandler (file:///android_asset/tutanota/dist/libs.js:26:46542)
at F._settlePromise (file:///android_asset/tutanota/dist/libs.js:26:47342)
at F._settlePromise0 (file:///android_asset/tutanota/dist/libs.js:26:48041)
at F._settlePromises (file:///android_asset/tutanota/dist/libs.js:26:49393)
at F._fulfill (file:///android_asset/tutanota/dist/libs.js:26:48411)
at F._resolveCallback (file:///android_asset/tutanota/dist/libs.js:26:45290)
at F._settlePromiseFromHandler (file:///android_asset/tutanota/dist/libs.js:26:46696)
at F._settlePromise (file:///android_asset/tutanota/dist/libs.js:26:47342)
```

**Comment by charlag** [comment]
More recent stacktrace:

```
Client: android app
Tutanota version: 3.43.1
User agent: 
Mozilla/5.0 (Linux; Android 9; ONEPLUS A6003 Build/PKQ1.180716.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.98 Mobile Safari/537.36

Error message: 
listId is not defined for [object Object]

Stacktrace: 
Error: listId is not defined for [object Object]
at getLetId (file:///android_asset/tutanota/dist/common.js:1:145017)
at file:///android_asset/tutanota/dist/worker.js:1:200043
at Array.find ()
at file:///android_asset/tutanota/dist/worker.js:1:199971
at Array.forEach ()
at MailFacade.value (file:///android_asset/tutanota/dist/worker.js:1:199934)
at file:///android_asset/tutanota/dist/worker.js:1:199215
at a (file:///android_asset/tutanota/dist/libs.js:26:73165)
at F._settlePromiseFromHandler (file:///android_asset/tutanota/dist/libs.js:26:46542)
at F._settlePromise (file:///android_asset/tutanota/dist/libs.js:26:47342)
at F._settlePromise0 (file:///android_asset/tutanota/dist/libs.js:26:48041)
at F._settlePromises (file:///android_asset/tutanota/dist/libs.js:26:49393)
at F._fulfill (file:///android_asset/tutanota/dist/libs.js:26:48411)
at F._resolveCallback (file:///android_asset/tutanota/dist/libs.js:26:45290)
at F._settlePromiseFromHandler (file:///android_asset/tutanota/dist/libs.js:26:46696)
at F._settlePromise (file:///android_asset/tutanota/dist/libs.js:26:47342)
```

**Comment by armhub** [comment]
1. Add attachment to new email
2. save and close email
3. open again send
-> attachment is missing in sent and received email
